### ISSUE TITLE
Fastparquet write :AttributeError: 'Series' object has no attribute 'valid'

### ISSUE THREAD

**Issue by QuantScientist** [dask/fastparquet#100]
Hi,
I am using a Dask data-frame as follows: 
`fastparquet.write(parquet_dir, X_df, file_scheme='hive',compression="SNAPPY")`

Stack trace: 
AttributeError                            Traceback (most recent call last)
<ipython-input-10-36d049f4de6b> in <module>()
      2 parquet_dir=createNewDir()
      3 print parquet_dir
----> 4 fastparquet.write(parquet_dir, X_df, file_scheme='hive',compression="SNAPPY")
      5 
      6 # X_df.to_parquet(parquet_dir, compression='SNAPPY')

/usr/local/lib/python2.7/dist-packages/fastparquet/writer.pyc in write(filename, data, row_group_offsets, compression, file_scheme, open_with, mkdirs, has_nulls, write_index, partition_on, fixed_text, append, object_encoding, times)
    747     fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
    748                         fixed_text=fixed_text, object_encoding=object_encoding,
--> 749                         times=times)
    750 
    751     if file_scheme == 'simple':

/usr/local/lib/python2.7/dist-packages/fastparquet/writer.pyc in make_metadata(data, has_nulls, ignore_columns, fixed_text, object_encoding, times)
    614         else:
    615             se, type = find_type(data[column], fixed_text=fixed,
--> 616                                  object_encoding=oencoding, times=times)
    617         col_has_nulls = has_nulls
    618         if has_nulls is None:

/usr/local/lib/python2.7/dist-packages/fastparquet/writer.pyc in find_type(data, fixed_text, object_encoding, times)
     90     elif dtype == "O":
     91         if object_encoding == 'infer':
---> 92             object_encoding = infer_object_encoding(data)
     93 
     94         if object_encoding == 'utf8':

/usr/local/lib/python2.7/dist-packages/fastparquet/writer.pyc in infer_object_encoding(data)
    181 
    182 def infer_object_encoding(data):
--> 183     head = data[:10] if isinstance(data, pd.Index) else data.valid()[:10]
    184     if all(isinstance(i, STR_TYPE) for i in head) and not PY2:
    185         return "utf8"

AttributeError: 'Series' object has no attribute 'valid'

Is it not possible to write a dask data-frame directly form fastparquet?

**Comment by QuantScientist** [comment]
BTW, 
If i first coerce the DF to a pandas DF, it works:
`fastparquet.write(parquet_dir, X_df.compute(), file_scheme='hive',compression="SNAPPY")`

But i would like to use the distributed dask version.

**Comment by mrocklin** [comment]
No, fastparquet only supports pandas.  You should use the dask.dataframe `to_parquet` method if you want to do this in parallel.

**Comment by QuantScientist** [comment]
Welll .... dask.dataframe to_parquet does not work either as I reported earlier :) 
I shall wait for the fix on p2.7 since I can not upgrade to 3 now.

**Comment by martindurant** [comment]
The fix on the dask side is coming through in https://github.com/dask/dask/pull/2050 , so you should be rolling soon.
