### ISSUE TITLE
Installing without conda on Ubuntu 14.04 gives core dumped error

### ISSUE THREAD

**Issue by kayibal** [dask/fastparquet#103]
I'm getting a dumped core lately when trying to import fastparquet on Ubuntu14.04 I also tried different python3 versions.

```
Python 3.5.1 (default, Mar 13 2017, 15:09:52) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastparquet
*** Error in `python': free(): invalid pointer: 0x00007ff450f803c0 ***
Aborted (core dumped)
```

Here are the steps to reproduce the error on a fresh Ubuntu 14.04 installation.
```
export LLVM_CONFIG=/usr/lib/llvm-3.9/bin/llvm-config
export PATH="/home/ubuntu/.pyenv/bin:$PATH"

sudo apt-get install -y git build-essential libreadline6 libreadline6-dev
sudo apt-get install -y bzip2 libssl-dev libbz2-dev libsqlite3-dev make
wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
sudo apt-get update
sudo apt-get install -y clang-3.9 lldb-3.9 

curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv install 3.5.1

pyenv global 3.5.1
pip install numpy cython
pip install fastparquet
python -c "import fastparquet"
```
The same approach works when using Ubuntu Xenial. Also installing with conda works fine on Trusty.

**Comment by martindurant** [comment]
Are there any warnings during build time that might be useful? pip install for numba is relatively new, and I don't know what guarantees it gives - that would be my first suspicion.

**Comment by kayibal** [comment]
You are right numba seems to be the issue here. I cloned the repo on the same machine and all tests fail with core dumped.

**Comment by martindurant** [comment]
You should open an issue on the number repo, they may be able to help you.

**Comment by kayibal** [comment]
Thx a lot. I will this can be closed then I guess :)
