### ISSUE TITLE
Boolean columns promoted to object

### ISSUE THREAD

**Issue by Kieleth** [dask/fastparquet#105]
Hi, 

First and foremost, thanks for great work with fastparquet.

I've struggled a bit to get pandas' column type bool into parquet. The reason is the automatic promotion to 'object' whenever we have 'NaN's  in the df.
Tried to do a pull request about it, but I think the requests are just for allowed members of the repo?
Could you please take a look at my approach for handling this? 

Both in writer.py:
```200     # Adding "NaN" to a boolean column promotes to column to object:
201     if all(isinstance(i, bool) for i in head):
202         return 'bool'
```
and:
```106         elif object_encoding == 'bool':
107             type, converted_type, width = typemap[object_encoding]
108
109         else:
110             raise ValueError('Object encoding (%s) not one of '
111                              'infer|utf8|bytes|json|bson' % object_encoding)
```

Also, a bit more of verbose whenever we're writing a column and snaps:
```575                 comp = compression
576             try:
577                 chunk = write_column(f, data[column.name], column,
578                                      compression=comp)
579             except TypeError as type_exception:
580                 # in append mode, if the chunk of data that is already in parquet
581                 # has different type from the one we're writing, this will break
582                 # Giving extra info to user, which column failed.
583                 msg = str(type_exception)
584                 msg += "\n Failed column details: '%s'" % str(column)
585                 raise TypeError(msg)
```
This one has saved me some debugging time, maybe will also save others? ;)

Plus, something that would be good add to documentation is the case when you're creating the dataframes from other data, to better use `from numpy import nan` in order to flag the missing cells. I'm transforming MongoDB collections into parquet and this was biting me big time (I was naively using "NaN" strings...)

Mentioning also that `infer_object_encoding` function, even though is great, it has hiccups if the data batches for append are small ~10 rows, since the likelihood of 10 rows inferred in one type and the next 10 to be inferred of another, is big, specially with NaN's or None's, etc. Bit of documentation there I think would save some time to future users.

It would be great to have your opinion and comments.

Thanks!

Luis

**Comment by martindurant** [comment]
I can see that this is a bit tricky... One workaround I can immediately propose is to recode your column as 0 for False, 1 for True, 2 for NULL and save as uint8, which is fast but dirty. Unfortunately, if you categorize a bool column, it doesn't seem to be possible to have the category values be a bool array, which I think would solve this problem.

I have no principled problem with allowing encoding of bool objects as you suggest for columns that contain only bool and NULL, but this could be extended to ints too.

**Comment by Kieleth** [comment]
Hey Martin, thanks for quick response.
Problem with re-en-coding to ints, is that I'm breaking then the schema coming from data source. We wanted parquet to be data-engine agnostic, so then we would have to "remember" to decode that column in all places we need to use.

The main problem emanates, as hinted, whenever you're in append=True, then the infer might change over time, then you run into all sort of problems.

**Comment by martindurant** [comment]
Can you get by without using object 'infer'? If you can specify the encoding types for each object column beforehand, nothing bad should happen during append of merge.

**Comment by Kieleth** [comment]
Let's take a look.

For bools, no problem for first write, but then in your next write for append, the new df has a None, so it promotes to 'object' and breaks:
```
In [434]: bools_df = df([True, False, True], columns=['bool_col'])

In [435]: bools_df.dtypes
Out[435]:
bool_col    bool
dtype: object

In [436]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True)

In [437]: bools_df = df([True, False, None], columns=['bool_col'])

In [438]: bools_df.dtypes
Out[438]:
bool_col    object
dtype: object

In [439]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=True, has_nulls=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-439-c72a81cf2126> in <module>()
----> 1 fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=True, has_nulls=True)

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in write(filename, data, row_group_offsets, compression, file_scheme, open_with, mkdirs, has_nul
ls, write_index, partition_on, fixed_text, append, object_encoding, times)
    754     fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
    755                         fixed_text=fixed_text, object_encoding=object_encoding,
--> 756                         times=times)
    757
    758     if file_scheme == 'simple':

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in make_metadata(data, has_nulls, ignore_columns, fixed_text, object_encoding, times)
    621         else:
    622             se, type = find_type(data[column], fixed_text=fixed,
--> 623                                  object_encoding=oencoding, times=times)
    624         col_has_nulls = has_nulls
    625         if has_nulls is None:

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in find_type(data, fixed_text, object_encoding, times)
     90     elif dtype == "O":
     91         if object_encoding == 'infer':
---> 92             object_encoding = infer_object_encoding(data)
     93
     94         if object_encoding == 'utf8':

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in infer_object_encoding(data)
    193         return 'json'
    194     else:
--> 195         raise ValueError("Can't infer object conversion type: %s" % head)
    196
    197

ValueError: Can't infer object conversion type: 0     True
1    False
Name: bool_col, dtype: object
```
Right, that was kindda expected.

Lets say, ok, lets make the column with a None since the beginning:
```
In [440]: bools_df = df([True, False, None], columns=['bool_col'])

In [441]: bools_df.dtypes
Out[441]:
bool_col    object
dtype: object

In [442]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-442-7980fc74c830> in <module>()
----> 1 fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True)

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in write(filename, data, row_group_offsets, compression, file_scheme, open_with, mkdirs, has_nul
ls, write_index, partition_on, fixed_text, append, object_encoding, times)
    754     fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
    755                         fixed_text=fixed_text, object_encoding=object_encoding,
--> 756                         times=times)
    757
    758     if file_scheme == 'simple':

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in make_metadata(data, has_nulls, ignore_columns, fixed_text, object_encoding, times)
    621         else:
    622             se, type = find_type(data[column], fixed_text=fixed,
--> 623                                  object_encoding=oencoding, times=times)
    624         col_has_nulls = has_nulls
    625         if has_nulls is None:

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in find_type(data, fixed_text, object_encoding, times)
     90     elif dtype == "O":
     91         if object_encoding == 'infer':
---> 92             object_encoding = infer_object_encoding(data)
     93
     94         if object_encoding == 'utf8':

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in infer_object_encoding(data)
    193         return 'json'
    194     else:
--> 195         raise ValueError("Can't infer object conversion type: %s" % head)
    196
    197

ValueError: Can't infer object conversion type: 0     True
1    False
Name: bool_col, dtype: object
```

Now, trying your suggestion on object_enconding='infer'
```
In [443]: bools_df = df([True, False, None], columns=['bool_col'])

In [444]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True, object_encoding={'bool_col':'infer'})
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-444-85c573304843> in <module>()
----> 1 fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True, object_encoding={'bool_col':'infer'})

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in write(filename, data, row_group_offsets, compression, file_scheme, open_with, mkdirs, has_nul
ls, write_index, partition_on, fixed_text, append, object_encoding, times)
    754     fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
    755                         fixed_text=fixed_text, object_encoding=object_encoding,
--> 756                         times=times)
    757
    758     if file_scheme == 'simple':

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in make_metadata(data, has_nulls, ignore_columns, fixed_text, object_encoding, times)
    621         else:
    622             se, type = find_type(data[column], fixed_text=fixed,
--> 623                                  object_encoding=oencoding, times=times)
    624         col_has_nulls = has_nulls
    625         if has_nulls is None:

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in find_type(data, fixed_text, object_encoding, times)
     90     elif dtype == "O":
     91         if object_encoding == 'infer':
---> 92             object_encoding = infer_object_encoding(data)
     93
     94         if object_encoding == 'utf8':

/home/lguzman/miniconda2/envs/datawarehouse/lib/python3.6/site-packages/fastparquet/writer.py in infer_object_encoding(data)
    193         return 'json'
    194     else:
--> 195         raise ValueError("Can't infer object conversion type: %s" % head)
    196
    197

ValueError: Can't infer object conversion type: 0     True
1    False
Name: bool_col, dtype: object
```
(This also fails with has_nulls=False too)

Let's try with diferent object_encodings:
```
fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=False, object_encoding={'bool_col':'bytes'})
...
TypeError: expected list of bytes

```

Now trying with utf8
```
fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=False, object_encoding={'bool_col':'utf8'})
...
TypeError: bad argument type for built-in operation
```

Ok, if we force conversion to 'bool' whenever we have None, then we lose the None-information:
```
In [451]: bools_df = df([None, None, None], columns=['bool_col'])

In [452]: bools_df.dtypes
Out[452]:
bool_col    object
dtype: object

In [453]: bools_df['bool_col'] = bools_df['bool_col'].astype('bool')

In [454]: bools_df.dtypes
Out[454]:
bool_col    bool
dtype: object

In [455]: bools_df
Out[455]:
  bool_col
0    False
1    False
2    False
```
And since parquet allows for Nulls, I think fastparquet should honor that capability, and not follow pandas' principle here.


On the append issue, let's imagine we have a bunch of Nones in our bool_col in the first batch, and then we start to have bools for next baches:
```
In [487]: bools_df = df([None, None, None], columns=['bool_col'])

In [488]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True, object_encoding={'bool_col':'infer'})

In [489]: bools_df = df([None, None, True], columns=['bool_col'])

In [490]: bools_df.dtypes
Out[490]:
bool_col    object
dtype: object

In [491]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=True, has_nulls=True, object_encoding={'bool_col':'infer'})
...
ValueError: Can't infer object conversion type: 2    True
Name: bool_col, dtype: object

```

So, whenever we have some Nones in an object, and we try to do 'infer' in the object_encoding, then we might run into problems, specially for bools.

Now, while writing this, I think I've bumped into a workaround: json!!!.
```
In [495]: bools_df = df([None, None, None], columns=['bool_col'])

In [496]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True, object_encoding={'bool_col':'json'})

In [497]: bools_df = df([None, None, False], columns=['bool_col'])

In [498]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=True, has_nulls=True, object_encoding={'bool_col':'json'})

In [499]: pf = fastparquet.ParquetFile('test_append_1')

In [500]: out_df = pf.to_pandas()

In [501]: out_df
Out[501]:
  bool_col
0     None
1     None
2     None
3     None
4     None
5    False

In [502]: out_df.dtypes
Out[502]:
bool_col    object
dtype: object
```
So I think I'm going to do this in my actual code.

But, I still think fastparquet should support to write native pandas' 'object' types with combination of booleans and None. Or just document this stuff?

Hope it makes sense, and let me know if I'm making some horrible basic assumption or something.

**Comment by martindurant** [comment]
Your assessment is correct, thank you for taking the time. Using JSON may not be very efficient, but if it works for you, I'm glad.

Adding an object_encoding='bool' with has_nulls=True (or object_encoding={'mycol': 'bool'}, has_nulls=['mycol']) would be the right way to allow native storage of bools. The issue would be, that when encountering an int or bool column with NULLs, the code currently converts to float (which is what pandas does for a series of ints), so you would not get back what you put in.

**Comment by Kieleth** [comment]
Auch, yes, I saw that when I used the object_encoding='bool' mod to write an object column, at the moment of extracting back to pandas, it showed the None's as False. 
I assumed that it was correctly stored as 'bool' in parquet, and the .to_pandas() extracting logic needed to be changed for handling it. 
But if we're storing bool as floats, then, no clue, I've not dug into parquet internals yet.

**Comment by martindurant** [comment]
"Auch, yes, I saw that when I used the object_encoding='bool' mod to write an object column, at the moment of extracting back to pandas, it showed the None's as False."
That is probably an implementation detail we can get right.

I was talking about what would currently happen when presented with a parquet file containing int or bool columns with NULLs: they would become float in the pandas dataframe. They could have been objects, but that is horribly memory and processing inefficient; they could have been categorical, which is memory efficient, but very inefficient for arithmetic purposes.

**Comment by Kieleth** [comment]
Ahh, ok, you're right, something fishy is going on with the bool-mod:

```

In [515]: bools_df = df([True, None, False], columns=['bool_col'])

In [516]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True, object_encoding={'bool_col':'bool'})

In [517]: pf = fastparquet.ParquetFile('test_append_1')

In [518]: out_df = pf.to_pandas()

In [519]: out_df.dtypes
Out[519]:
bool_col    bool
dtype: object

In [520]: out_df
Out[520]:
  bool_col
0    False
1    False
2    False

```

**Comment by martindurant** [comment]
btw: you can submit a PR if you fork this repo and push to a branch on your fork.

**Comment by Kieleth** [comment]
Ahh, ok, you're right, something fishy is going on with the bool-mod:

```

In [515]: bools_df = df([True, None, False], columns=['bool_col'])

In [516]: fastparquet.write('test_append_1', bools_df, compression='SNAPPY', append=False, has_nulls=True, object_encoding={'bool_col':'bool'})

In [517]: pf = fastparquet.ParquetFile('test_append_1')

In [518]: out_df = pf.to_pandas()

In [519]: out_df.dtypes
Out[519]:
bool_col    bool
dtype: object

In [520]: out_df
Out[520]:
  bool_col
0    False
1    False
2    False

```

**Comment by Kieleth** [comment]
Hi Martin,  following up in this. Managed to write my stuff using the "json" workaround, without storing in parquet "proper" types like bools etc, now if I try to use the data in non-pandas environment, like Zeppelin what I've encountered is that we need to do multiple casting on columns to get the types right.

This also affects dates, which in pandas are float64, got like float64 into parquet, in spite that parquet supports date/timestamp natively.

I think fastparquet should extend the parquet types into you can store 'object' type and 'float64' (for nulls) types from panda. I was thinking a more configurable 'object_encoding', like 'parquet_types'. 

Do you guys agree in this feature? is something you had in mind? Am I talking nonsense? I'd not mind to give a try to this if you think is a good idea, with help of course :)

**Comment by martindurant** [comment]
I'm not sure what you mean by Zeppelin as an environment - it's a notebook front-end, no? I assume you mean spark, in which case fastparquet can already cope with outputting "incorrect" datetime formatting:
```
write(df, 'file.parq', ..., times='int96')
```
where you can specify whether to write NULLs or not (nulls in pandas look like NaT). Note that the parquet spec [says](https://github.com/Parquet/parquet-format/blob/master/LogicalTypes.md) that the int64 is indeed the right way to write datetimes

**Comment by Kieleth** [comment]
True, but only if we force the pandas' dtype to be 'datetime64', probably my fault here for having them as 'object' and then forcing them as 'float64' using 'object_encoding' at the moment of calling write. Pandas' column types keep biting me badly.

My point on  booleans stands, though.

Thanks for clarification!

**Comment by martindurant** [comment]
I think for the time being I'll continue to recommend using floats for bools-with-nulls rather than add another object encoding type. If you did manage to get something that works for you, feel free to submit a PR and I can consider it.

**Comment by jsignell** [comment]
Just ran into this and took me a while to track down this issue. Is there any way that the error message could be made more clear?

**Comment by martindurant** [comment]
`object_encoding='bool'` has been a valid option for over a year now. 
What do you think the message should say?

**Comment by jsignell** [comment]
Hmm. So I shouldn't be seeing the message when using a categorical with bools as labels?

**Comment by martindurant** [comment]
Er, I don't think you should use categorical at all, if the column is bool. 
It could well be that this possibility is not covered. 

You have values True, False, None? You cannot encode a None *label*, i.e., you cannot have a not-null object which happens to be None.

**Comment by jsignell** [comment]
I just have True and False. It might just be that that shouldn't be categorical because that doesn't add any meaning :)

**Comment by martindurant** [comment]
No you shouldn't have categorical, it only adds work.
I suggest not putting any effort into tracing down the error message and whether it can be clearer for this case.
