### ISSUE TITLE
(non?)serialization of categories with dask

### ISSUE THREAD

**Issue by makmanalp** [dask/fastparquet#106]
Hi,

```python
from dask import dataframe as ddf
df = ddf.read_csv(disagg.csv.gz, compression="gzip", blocksize=None,
        dtype={
            "medium": "category",
            "routeorstation": "category",
            "faretype": "category",
            "timeperiod": "category",
        },
        parse_dates=["t"]
)
df.to_hdf("../data/raw/disagg.h5b", complib="blosc", key="data")
df.to_parquet("../data/raw/disagg.parq", compression="snappy")
```

Now, the dataframe in df (from the CSV) looks like this:

<img width="894" alt="screen shot 2017-03-17 at 12 30 28 am" src="https://cloud.githubusercontent.com/assets/161965/24028900/1a3bfb26-0aa9-11e7-820e-7d5cb37df75d.png">

and the hdf file, after doing this:

```python
da.read_hdf("../data/raw/disagg.h5b", key="data")
```
looks very similar, but with the categories being `known`:

<img width="855" alt="screen shot 2017-03-17 at 12 34 41 am" src="https://cloud.githubusercontent.com/assets/161965/24028971/97efd4b6-0aa9-11e7-8cd8-e78b138577dc.png">

but with the fastparquet one:
```python
da.read_parquet("../data/raw/disagg.parq", index="t")
```
we get:

<img width="636" alt="screen shot 2017-03-17 at 12 37 02 am" src="https://cloud.githubusercontent.com/assets/161965/24029022/f24a491e-0aa9-11e7-9a9e-b32e56548e10.png">

Currently using:
```
fastparquet (0.0.5)
dask (0.14.0)
pandas (0.19.2)
```

x-ref https://github.com/dask/dask/issues/1040

**Comment by martindurant** [comment]
parquet allows data to be written in categories for some chunks and not others. You therefore need to tell the reader which columns you would like to read as categoricals:
```
da.read_parquet("../data/raw/disagg.parq", index="t",
    categories=["medium", "routeorstation", "faretype", "timeperiod"])
```

We are aware that when data was written by fastparquet, a given column is consistently categorical or not, so we could in principle store some extra information in the metadata to avoid having to specify categorical columns in this manner.

**Comment by makmanalp** [comment]
@martindurant I see - specifying categories did indeed fix my problem. So I leave it up to you - to me, part of the draw of storage formats like HDF or parquet is that unlike CSV, I don't have to worry about things like casting columns to the right type, which often causes issues when pandas tries to be "smart" about guessing types.

IIRC categories work for HDF but perhaps in HDF's case, categoricals get stored specially (perhaps some sort of compression / metadata storage?) so there is a natural mapping to the underlying format? I can also see pandas' / numpy's ecosystem of types being richer than that of any underlying format(s), so perhaps doing it this way does make sense.





Thanks for the help.
