### ISSUE TITLE
Release a Windows wheel?

### ISSUE THREAD

**Issue by ankostis** [dask/fastparquet#110]
Is it possible to build it also on Windows? 
Maybe even use Appveyor for automated builds? (but I have no experience in building native libraries on Windows).

**Comment by martindurant** [comment]
There is a windows conda package, is that any use to you?
Am I right in thinking that, in order to build a wheel for windows myself, I would need a windows system?

**Comment by mrocklin** [comment]
The limitation here might be Numba, which requires LLVM.  I recommend
asking @seibert if an LLVM Windows wheel is feasible.

Generally wheels weren't intended to package non-python dependencies super
well.

**Comment by ankostis** [comment]
> Am I right in thinking that, in order to build a wheel for windows myself, I would need a windows system?

Only at the beginning, to make it work - afterwards, probably Appveyor can [produce the wheels](https://www.appveyor.com/docs/packaging-artifacts/).

> There is a windows conda package, is that any use to you?

Nope.
I'm using vanilla python 3.6 (actually as packaged by [WinPython](http://winpython.github.io/) distribution).

> The limitation here might be Numba, which requires LLVM. 

Gohlke packages `numba` for Windows](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numba), 
which is included also in WinPython, so I suppose there shouldn't be any problem.

**Comment by martindurant** [comment]
I have installed a windows VM and can look into this when I have the time (not immediately); although I am certain there are people with more windows experience than myself that might help.

**Comment by stonebig** [comment]
to create a wheel, I would do:
- use a python distro with numpy already installed,
- unzip "fastparquet-master" from github and launch "python setup.py bdist_wheel"

**Comment by martindurant** [comment]
@stonebig , are you happy to try this, to see if you can build something pip-installable?

**Comment by stonebig** [comment]
I did, from April 15th tree. As I compiled from Python-3.6.1, the 3.6 wheels may not be convenient for python-3.6.0 (see https://bugs.python.org/issue29943).

result there:  https://github.com/stonebig/winpython_afterdoc/tree/master/various_wheels/fastparquet

**Comment by martindurant** [comment]
OK, I'll be sure to give it a go when next I do a release, which shouldn't be too far off.

**Comment by stonebig** [comment]
checking my own dog food, I fall directly on  this:
``````
from fastparquet import ParquetFile
pf = ParquetFile(r'C:\WinPython\a\fastparquet-master20170415\fastparquet-master\test-data\snappy-nation.impala.parquet')
df = pf.to_pandas()

Traceback (most recent call last):

  File "<ipython-input-1-f3f64ac893d5>", line 1, in <module>
    from fastparquet import ParquetFile

  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\fastparquet\__init__.py", line 14, in <module>
    from .thrift_structures import parquet_thrift

  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\fastparquet\thrift_structures.py", line 7, in <module>
    parquet_thrift = thriftpy.load(THRIFT_FILE, module_name="parquet_thrift")  # pylint: disable=invalid-name

  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\thriftpy\parser\__init__.py", line 30, in load
    include_dir=include_dir)

  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\thriftpy\parser\parser.py", line 496, in parse
    url_scheme))

ThriftParserError: ThriftPy does not support generating module with path in protocol 'c'


````

**Comment by stonebig** [comment]
same error the other way:

````
import pandas as pd
import numpy as np
df = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : pd.Categorical(["test","train","test","train"]),
                      'F' : 'foo' })
from fastparquet import write
write('outfile.parq', df)
write('outfile2.parq', df, row_group_offsets=[0, 10000, 20000],
      compression='GZIP', file_scheme='hive')
      
Traceback (most recent call last):

  File "<ipython-input-1-680fbbc82549>", line 10, in <module>
    from fastparquet import write

  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\fastparquet\__init__.py", line 14, in <module>
    from .thrift_structures import parquet_thrift

  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\fastparquet\thrift_structures.py", line 7, in <module>
    parquet_thrift = thriftpy.load(THRIFT_FILE, module_name="parquet_thrift")  # pylint: disable=invalid-name

  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\thriftpy\parser\__init__.py", line 30, in load
    include_dir=include_dir)

  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.1.amd64\lib\site-packages\thriftpy\parser\parser.py", line 496, in parse
    url_scheme))

ThriftParserError: ThriftPy does not support generating module with path in protocol 'c'
````

I can compile fasatpartquet, but I still have no exact clue how it must be used

**Comment by stonebig** [comment]
there is a workaround here : https://github.com/eleme/thriftpy/issues/234#issuecomment-249794576

**Comment by stonebig** [comment]
after applying this one-liner,this works::
````
import pandas as pd
import numpy as np
df = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : pd.Categorical(["test","train","test","train"]),
                      'F' : 'foo' })
from fastparquet import write
write('outfile.parq', df) 
      
````

**Comment by martindurant** [comment]
That's a *horrible* workaround! :) 
Actually thriftpy.parser.parser was partially rewritten recently - you could try downgrading it one or more minor versions.

**Comment by stonebig** [comment]
you mean I should redo a wheel  from Thriftpy github master tree ? I was using version Thriftpy-0.3.9

**Comment by martindurant** [comment]
It looks like the code in 0.3.8 was different. There are a couple of further commits on that part of the code since 0.3.9 too, so it maybe that your issue is fixed in master.

**Comment by stonebig** [comment]
apparently a better workaround, on Thriftpy-0.3.9,  is:
````
    # if url_scheme == '':
    if url_scheme == 'file':
        with open(urlparse(path).netloc + urlparse(path).path) as fh:
            data = fh.read()
    elif url_scheme == '' or os.path.exists(path):
````

**Comment by martindurant** [comment]
Is this your code, or is that the solution in latest thriftpy-master?

I have briefly looked into the thriftpy codebase, and feel there is substantial scope for improvement in structure and speed for our limited scope (binary blob-> python dict-like objects). It is doubtful that I'll have the time to make such changes, though, which would amount to a general rewrite.

**Comment by stonebig** [comment]
I cherry picked it from https://github.com/eleme/thriftpy/pull/285

**Comment by stonebig** [comment]
well... cgohlke just patched it differently... I'll trust him to have done it better

**Comment by mrocklin** [comment]
@martindurant it might be worth putting down your experience into an
issue.  People have come by this project before to offer work (I'm thinking
specifically of the Python 2 support work).  If you raise an informative
issue you might encourage another developer to handle it.

**Comment by stonebig** [comment]
apparently, cgohlke may have lost the cythonization when doing the Thriftpy wheel... I will remain cautiously on my tar.gz

**Comment by cgohlke** [comment]
Thriftpy's Cython extensions are not available on Windows. See https://github.com/eleme/thriftpy/blob/develop/setup.py#L48

**Comment by martindurant** [comment]
@cgohlke , have you any idea why that is?

**Comment by cgohlke** [comment]
Thriftpy uses `endian.h` not available on Windows. See https://github.com/eleme/thriftpy/blob/develop/thriftpy/protocol/cybin/endian_port.h#L15. Probably easy to fix.

**Comment by stonebig** [comment]
nota :  pyarrow companion project claims incompatibility with Windows 32 bit .... 

https://github.com/apache/arrow/blob/master/python/setup.py#L175..L176

**Comment by martindurant** [comment]
I am thinking (see #133) that we could consider a limited port of thriftpy optimized for our purposes, if anyone wants the job. fastparquet doesn't use the TBinaryProtocol, above, at all, only TCompactProtocol (which is not cython-optimized). I would love it to be cythonized too, since this impacts the metadata parsing time.

**Comment by cgohlke** [comment]
I compiled Thriftpy for Windows with Cython extensions (http://www.lfd.uci.edu/~gohlke/pythonlibs/#thriftpy) using this patch:
```diff
diff --git a/thriftpy/parser/parser.py b/thriftpy/parser/parser.py
index f65320a..73238ed 100644
--- a/thriftpy/parser/parser.py
+++ b/thriftpy/parser/parser.py
@@ -539,7 +539,7 @@ def parse(path, module_name=None, include_dirs=None, include_dir=None,
     if url_scheme == 'file':
         with open(urlparse(path).netloc + urlparse(path).path) as fh:
             data = fh.read()
-    elif url_scheme == '':
+    elif len(url_scheme) <= 1:
         with open(path) as fh:
             data = fh.read()
     elif url_scheme in ('http', 'https'):
diff --git a/thriftpy/protocol/cybin/endian_port.h b/thriftpy/protocol/cybin/endian_port.h
index be8299b..9df06f9 100644
--- a/thriftpy/protocol/cybin/endian_port.h
+++ b/thriftpy/protocol/cybin/endian_port.h
@@ -1,5 +1,15 @@
+#if defined(_MSC_VER)

-#if defined(__APPLE__)
+#include <stdlib.h>
+
+#define htobe16(x) _byteswap_ushort(x)
+#define be16toh(x) _byteswap_ushort(x)
+#define htobe32(x) _byteswap_ulong(x)
+#define be32toh(x) _byteswap_ulong(x)
+#define htobe64(x) _byteswap_uint64(x)
+#define be64toh(x) _byteswap_uint64(x)
+
+#elif defined(__APPLE__)

 #include <libkern/OSByteOrder.h>


```

**Comment by martindurant** [comment]
I am too unfamiliar with the pip build-chain to know how to reliably incorporate the patch above to build a wheel for general use.

By the way, this is an extreme prune of thriftpy to show that should actually be little work for someone to totally optimize it https://github.com/martindurant/thriftpy/commit/676f21444e443e5ee842b7c475d94dc4372286f1  (note that if we're dealing with files, we don't need to worry about endianness anyway, that's all network-specific stuff). I found that running cython over compact.py without any modification increases parquet footer parsing speed by a factor of 2.

**Comment by diegojancic** [comment]
Since this is the page that shows up when you Google for '`ThriftPy does not support generating module with path in protocol 'c'`'

I'm going to drop a note here. In order for fastparquet to work on Windows, you must install it by opening the Anaconda Prompt (as Admin) and run the following: 

`conda install -c conda-forge fastparquet`

Do not install using `pip`.

**Comment by dlasusa** [comment]
I see the last comment was a little over 3 years ago.  

Is this still an open issue?  Are we unable to

`pip install fastparquet`  

without conda

I just did a pip install of:
llvmlite
numba
Cython
(other requirements were already met: pandas, numpy, six)

But got a lot of red text/error when then trying to `pip install fastparquet`

**Comment by martindurant** [comment]
With the source distribution, you need a working compiler chain locally.

**Comment by yohplala** [comment]
With its own thrift, maybe this ticket can be closed?

**Comment by martindurant** [comment]
This likely works anyway. We should no longer support py36 in any case.
