### ISSUE TITLE
Specifying categorical columns in the metadata?

### ISSUE THREAD

**Issue by martindurant** [dask/fastparquet#111]
Currently the user has to specify which columns to load as categoricals, because a general parquet files can have columns that are categorical in some chunks and not in others. Files written by us, however, will always have columns that are all-categorical or all-not - we could record the columns that are in a special field of the metadata, and by default assume them as categorical on load, unless the user says otherwise.

**Comment by makmanalp** [comment]
I don't know if this is too far but this could have other benefits, like if you're using dask to do a query  on a collection and it's filtered by a categorical value, dask could know whether to hit a table or file at all based on simply the metadata of what categories the categorical includes.

**Comment by martindurant** [comment]
I don't think it's reasonable to store the category labels in the metadata, as that could greatly increase the size of the metadata - and the type of filtering you mention would be per-rowgroup whereas the metadata is global. Note that *statistics* are stored per column per row-group, and that you can already filter out row-groups by *partitions* (i.e., directory-based).
