### ISSUE TITLE
Parquet Write Error: TypeError: cannot do slice indexing on <class 'pandas.indexes.range.RangeIndex'> with these indexers [5] of <class 'str'>

### ISSUE THREAD

**Issue by JohnOmernik** [dask/fastparquet#113]
I am trying to write a Pandas dataframe to a file, and when I do that I get the cryptic error below. Any help in pointing where I can look to troubleshoot would be great!

TypeError: cannot do slice indexing on <class 'pandas.indexes.range.RangeIndex'> with these indexers [5] of <class 'str'>

My data (in this test case is small, I printed the df prior to writing, here is a snippet

Write Dataframe to 19a679aaceb0_1490376057.parq at 5 records - Size: 8219 - Seconds since last 
write: 1 - Partitions in this batch: ['2017-03-24']
Writing partition 2017-03-24 to /app/data/2017-03-24/.19a679aaceb0_1490376057.parq
  accept_encoding accept_language  connection         day           dst_ip  \
0            gzip            None       close  2017-03-24    123.123.123.123   
1            None            None  keep-alive  2017-03-24  123.123.123.123   
2            None            None  keep-alive  2017-03-24  123.123.123.123   
3            None            None  keep-alive  2017-03-24  123.123.123.123.  
4            None            None  keep-alive  2017-03-24  123.123.123.123  

[5 rows x 43 columns]
Traceback (most recent call last):
  File "./pyweblogs.py", line 110, in <module>
    main()
  File "./pyweblogs.py", line 71, in main
    parqwrite(out_file, partdf, compression=parq_compress, row_group_offsets=parq_offsets, has_nulls=True)
  File "/usr/local/lib/python3.5/dist-packages/fastparquet/writer.py", line 759, in write
    compression, open_with, has_nulls, append)
  File "/usr/local/lib/python3.5/dist-packages/fastparquet/writer.py", line 660, in write_simple
    rg = make_row_group(f, data[start:end], fmd.schema,
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2047, in __getitem__
    indexer = convert_to_index_sliceable(self, key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1774, in convert_to_index_sliceable
    return idx._convert_slice_indexer(key, kind='getitem')
  File "/usr/local/lib/python3.5/dist-packages/pandas/indexes/base.py", line 1213, in _convert_slice_indexer
    return slice(self._validate_indexer('slice', key.start, kind),
  File "/usr/local/lib/python3.5/dist-packages/pandas/indexes/base.py", line 3035, in _validate_indexer
    self._invalid_indexer(form, key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/indexes/base.py", line 1284, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.indexes.range.RangeIndex'> with these indexers [5] of <class 'str'>

**Comment by martindurant** [comment]
Could you please create a stand-alone code snippet that exposes this exception? It is fine if you include some literal values like `df = pd.DataFrame({...})`. In particular, I am interested to know what your dataframe's column names are and the index looks like.

**Comment by JohnOmernik** [comment]
Happy to do that, can you clarify what you mean though. Do you want me to show you the code that is causing it, or perhaps hard code some data that causes the issue?  I am reading from Kafka now, to produce this, but I could probably create the same issue with a standalone piece of code...

**Comment by martindurant** [comment]
Both :)  I would like to see the exact call to fastparquet that you used, and an example dataframe that fails. Since your data if coming from an internal source and perhaps is sensitive, I am suggesting that you hard-code a small dataframe. The idea is that I can execute the code here and find out what went wrong.

**Comment by JohnOmernik** [comment]
Yep,

Code:
`#!/usr/bin/python3
import json
import pandas as pd
import time
import shutil
from fastparquet import write as parqwrite
import os

parq_offsets="50000000"
parq_compress="SNAPPY"


def main():

    hname = os.environ['HOSTNAME']
    base_dir = "/app/data/test"
    out_file = "/app/data/test/.test.parq"
    final_file = "/app/data/test/test.parq"


    f = open("test.json", "r")
    parqdf = pd.DataFrame()

    for l in f:
        if l.strip() != "":
            if parqdf.empty:
                parqdf = pd.DataFrame.from_records([json.loads(l)])
            else:
                parqdf = pd.concat([parqdf, pd.DataFrame.from_records([json.loads(l)])], ignore_index=True)

    if not os.path.isdir(base_dir):
        os.makedirs(base_dir)
    print(parqdf)
    parqwrite(out_file, parqdf, compression=parq_compress, row_group_offsets=parq_offsets, has_nulls=True)
    shutil.move(out_file, final_file)


if __name__ == "__main__":
    main()
`

**Comment by JohnOmernik** [comment]
Json test data (in file called test.json)
`{"accept_encoding":null,"accept_language":null,"connection":"close","day":"2017-03-24","dst_ip":"123.123.123.123","dst_port":"80","http_host":"host1.somedomain.com","http_method":"GET","http_request":"GET / HTTP/1.1","http_response":"HTTP/1.1 200 OK","http_status_code":"200","http_status_message":"OK","http_version":"HTTP/1.1","if_modified_since":null,"if_none_match":null,"ip_ver":"4","orig_content_type":null,"proto":"6","raw_src_ip":"192.168.0.1","referer":null,"req_accept":"*/*","req_accept_charset":null,"req_content_length":null,"req_headers":"Host: host1.somedomain.com\r\nCookie: d=1\r\nAccept: */*\r\nUser-Agent: iTunes/12.5.5 (Macintosh; OS X 10.10.5) AppleWebKit/600.8.9\r\nConnection: close\r\n\r\n","request_body_length":0,"request_body_str":null,"request_cookies":"fsdfdsfds=fdsfdsfs","resp_cookies":null,"resp_headers":"dasdsasdds","resp_location":null,"response_body_length":70329,"server_software":"fdsa","src_ip":"192.168.0.191","src_port":"49211","true_client_ip":null,"ts":1490374461.684255,"tsutc":"2017-03-24 16:54:21","uri":"/","user_agent":"iTunes/12.5.5 (Macintosh; OS X 10.10.5) AppleWebKit/600.8.9","x_forwarded_for":null}
{"accept_encoding":null,"accept_language":null,"connection":"keep-alive","day":"2017-03-24","dst_ip":"123.123.123.123","dst_port":"80","http_host":"host.someother.com","http_method":"GET","http_request":"GET /make/paths/great/again.html","http_response":"HTTP/1.1 404 Not Found","http_status_code":"404","http_status_message":"Not Found","http_version":"HTTP/1.1","if_modified_since":null,"if_none_match":null,"ip_ver":"4","orig_content_type":null,"proto":"6","raw_src_ip":"192.168.0.1","referer":null,"req_accept":null,"req_accept_charset":null,"req_content_length":null,"req_headers":"Host: host.someother.com\r\nConnection: keep-alive\r\nUser-Agent: wwww/ CFNetwork/720.5.7 Darwin/14.5.0 (x86_64)\r\n\r\n","request_body_length":0,"request_body_str":null,"request_cookies":null,"resp_content_length":"135","resp_content_type":"text/html; charset=iso-8859-1","resp_cookies":null,"resp_headers":"Date: Fri, 24 Mar 2017 16:54:29 GMT\r\nServer: Apache\r\nVary: Accept-Encoding\r\nContent-Type: text/html; charset=iso-8859-1\r\nContent-Length: 135\r\nConnection: keep-alive\r\nCache-Control: s-maxage=60, max-age=60\r\n\r\n","resp_location":null,"response_body_length":135,"server_software":"Apache","src_ip":"192.168.0.1","src_port":"49213","true_client_ip":null,"ts":1490374469.697150,"tsutc":"2017-03-24 16:54:29","uri":"/osxhe/2/4e/24e408e3c7ad0c38099c63f185d801aa.dat","user_agent":"dfsafsdfsda/ CFNetwork/720.5.7 Darwin/14.5.0 (x86_64)","x_forwarded_for":null}`

**Comment by JohnOmernik** [comment]
I think that should work, let me know if you can reproduce... if not we can try another method. 

Thanks!

**Comment by martindurant** [comment]
With the following:

```
with open('temp.json') as f:
    # much better way to load the data without concat
     parqdf = pd.DataFrame.from_records([json.loads(l) for l in f])
fastparquet.write('another.parq', parqdf, has_nulls=True)
```

Ah, I see the problem: your index is integer, but `parq_offsets` is a string. It should either be a string, or, if you really want to index by strings, you should pass `parq_offsets` as an explicit list of strings where you want to slice (because you don't multiply strings).

**Comment by JohnOmernik** [comment]
So, my issue is this, I am batching reads from Kafka. So I get a json record, one at a time as I loop. If there are 10 messages, it loops through 10 times, one message at at time. I don't want to write to a new file for each record, so I set up some maxes. Max records, Max size, and max time since last write.  If any of those are exceeded, it triggers a write, so I need to be able to batch add one or more records at a time.  (Then I open a new file, I do need to explore your appending) That's why I choose the concat method. 

As to the parq offsets, yep, changing that to a int fixed that.  Thanks for helping existentially deal with my own ineptitude :)  (This is actually meant in a kind way, thanks for taking the time to help me troubleshoot this, I was lost at this point). 

Back to the loading method, I get a single message at a time from my kafka emitter.  So that's why I batch them.  would your method work for adding multiple single messages?

**Comment by martindurant** [comment]
Yes, if the `for l in f` waits on `f`, which in my example is a file, but in your example is coming from kafka, then you can use the simple version. If you want a stopping condition with a *break*, then you need at least some for loop.
Repeatedly calling concat will become very slow, you'd be better off putting the text or dicts into a list and calling DataFrame.from_records on that.

**Comment by JohnOmernik** [comment]
Thanks for the tip. I went to keeping a list of records and then making the dataframe right before I write it.  This makes sense for my application.
