### ISSUE TITLE
New Feature: Inspect Data Frame Option with output of something that can be taken by writer

### ISSUE THREAD

**Issue by JohnOmernik** [dask/fastparquet#120]
Right now, if I read the docs well, the parquet writer uses 10 records to determine types etc while writing.  It would be neat to have a feature that taking a panda data frame, could inspect the whole (or partial...configurable of course) data frame and create a json output.  That could show:

- All Columns, and their "type" guess based on what the dataframe had in it. 
- For Str/Binary columns with limited length where a "fixed_text" could provide better performance, show what was seen in the data frame. 
- For items with low cardinalality (perhaps a set able threshold) show those field where the categorical option may improve performance
- Show those columns where we would have to add the NULL handling that would decrease performance 
-  If other feathers get added, they would be added to this output. 
- This output could have settings as in "This is what optimal performance should/could look like, this is how it will be written by fast parquet by default"

The idea here, is this json output, (or dict?) could be reviewed and edited by a data administrator.  Perhaps some Notes as to why something show shown.  This output, or edited output could be used in a multiple ways.

1. Just a data description for the user. Let's them understand, based on the dataframe how fast parquet will (by default) and how it could (for optimal performance) be handled based on the sample in the current data frame. 
2. It could be used as an object (either as outputted or edited by the user) to be passed to parquet.write so that instead of hand creating all the of the variables, it is one big thing based on inspection. 
3. It could also be saved so the definition is created and usable for future things
4. It could be applied as a filter to other dataframes loaded in. Thus you could take the optional filter created by this output and apply to a bunch of dataframes to see how it would work... i.e. so you take say 1 million rows, load it into a data frame, and create this filter. You look at it, make some small edits, then save it.  Then you can look at other samples of data and apply it... if all of the "application" works as intended, then you can include it for optimized parquet writes. If you see failures on other data sets, you can adjust. (maybe a fixed_text limit was 1 byte off based on the first sample of data, but applying it others you notice and update your template). 

Obviously this would be a best guess/opinionated output.  It would be described to the user as a way to quickly assess the biggest performance impacting components of a data set, to help write parquet in the most efficient way possible. It would also just help people working with data learn about their data and how to store it efficiently.  

I would be interested in helping/working on this with others if there is interest. Once of my biggest frustrations for working with Parquet is often we are dealing with TB of data where small performance tweaks can make huge impacts... Having a way to help understand, improve, and educate users here would be outstanding, especially built into a tool itself.

**Comment by martindurant** [comment]
Interesting idea. Some of this is already implemented: you can pass your dataframe to `fastparquet.writer.make_metadata` with the various options, to see what schema it makes. This output may not be very easy to read, however. I'll think about whether it's possible/useful to have something like a "empty ParquetFile" where you could view the schema/dtypes as you would had you actually written the data.

On the separate question of performance tweaks, the trouble is of course that often there is no obvious best answer, and only careful analysis of the data will help. This is particularly true when looking at only a sample of the data (for merge-like scenarios, or dask, where the whole data-set is not available at all at schema creation time). The first step I would recommend is `df.info()` and `df.describe(include='all')` to get the nulls count, dtypes and cardinality.

Note that the encoding for object columns is only guessed with the default object_encoding='infer', and you could, for instance set it to 'utf8' if you know you have only (unicode) strings, or set it per-column. Similarly, the default is to write NULLs information only for columns that have no implicit no-value (nan for floats, nat for times, -1 for category codes); this can also be explicitly set per-column.

**Comment by martindurant** [comment]
This will probably be implemented by pandas, who are driving to create a consistent metadata description of dataframes appropriate for binary storage.
