### ISSUE TITLE
fastparquet on pandas before 16.0? (Ubuntu 14.04/16.04)

### ISSUE THREAD

**Issue by davidabarrett** [dask/fastparquet#121]
I've managed to install the listed prerequisites and fastparquet on stock
Ubuntu 14.04 and 16.04 with a combination of apt-get install and pip/pip3 install.

Unfortunately, the resulting "import fastparquet" failed.  
It required pandas 18.0 (for pandas.RangeIndex) 
and pandas 16.1 (for pandas.CategoricalIndex).

Ubuntu 14.04 has pandas 13.1 and 16.04 has 17.1 stock (via apt-get)

Is it reasonable to have parquet on anything other than the (almost)
newest releases?  Looks like a really cool opportunity.

Here were my installation commands for python2 and 
python3 on both Ubuntu 14.04 and 16.04:

sudo apt-get install zlib1g zlib1g-dev libedit2 libedit-dev 

sudo apt-get install python-numpy python-pandas
sudo apt-get install python3-numpy python3-pandas

sudo apt-get install libsnappy-dev python-snappy liblzo2-dev python-lzo 
sudo apt-get install llvm-3.8 llvm-dev 

sudo pip3 install enum34 funcsigs
sudo -H LLVM_CONFIG=/usr/bin/llvm-config-3.8 pip3 install llvmlite==0.15.0 numba fastparqet

sudo pip install enum34 funcsigs
sudo -H LLVM_CONFIG=/usr/bin/llvm-config-3.8 pip install llvmlite==0.15.0 numba fastparqet

**Comment by martindurant** [comment]
The usual advice is to just use conda...

Before RangeIndex, the appropriate class would have been Int64Index, which is no big deal in the usage in fastparquet.dataframe.empty, but it would take a little more work to replace the usage in fastparquet.util.index_like, where presumably we would need to assert that `index == np.arange(len(index))`. In either case, it would be somewhat less efficient.

Would you like to make a PR which replaces RangeIndex in the case that pandas doesn't support it?

**Comment by mrocklin** [comment]
Have you considered updating pandas to a newer version?  Version 0.16 is a couple of years old now.   Either conda or pip should work fine.

**Comment by davidabarrett** [comment]
As it turns out, upon further investigation, I probably want the features of Pandas 18.0 and
above, which speaks well of how much the contributers have advanced it recently.

pip install pandas 0.18.0 or 0.19.2 after pip installing numpy 1.11.0 (for ubuntu 14.04),
did allow me to import fastparquet without error, which does indeed solve my immediate
problem.   [p.s. I have it on my todo list to evaluate using conda for  production deployment]

I was caught off guard by how many dependencies were required for a file format.
But I guess that shouldn't have surprised me for a new format without a prior history.

How hard would it be to fix the RangeIndex dependency to allow stock Ubuntu 16.04?

**Comment by martindurant** [comment]
"How hard would it be to fix the RangeIndex" - pretty straight-forward for someone with the motivation. As I said above, it only appears in a handful of places, and of those, only really one where some extra logic would be required.
For me, it doesn't seem very high priority, though.

**Comment by martindurant** [comment]
@davidabarrett , I will close this issue now, as I don't intend to work on it, and the pandas versions will only get older with time. If you wish to have a go, I'd be happy to consider a PR.
