### ISSUE TITLE
Bump version in setup.py

### ISSUE THREAD

**Issue by gbrener** [dask/fastparquet#123]
There is a release of `fastparquet` called "1.1" (https://github.com/dask/fastparquet/releases/tag/1.1) but the `setup.py` file still reports a version of "0.0.5". I believe the `setup.py` file's version should be updated, but there may be a compelling reason that I'm not aware of for why it has been kept back.

**Comment by martindurant** [comment]
You are probably referring to a version of parquet-python, on which fastparquet was originally based, and which still shows up as "forked from" on github. We decided that fastparquet was sufficiently different from parquet-python to begin vesioning from zero.

**Comment by mrocklin** [comment]
The setup.py file still shows 0.0.5.  This would be important if, for example, we made PyPI packages.

**Comment by martindurant** [comment]
The best action should be simply to remove git tags associated with parquet-python but not fastparquet from the repo? 0.0.5 is the correct version of the latest release in pypi and conda-forge.

**Comment by mrocklin** [comment]
To be clear, I think that @gbrener is referring to this line in the source:

https://github.com/dask/fastparquet/blob/master/setup.py#L23

**Comment by martindurant** [comment]
Agreed, but I am saying that is the correct version. It will go to 0.0.6 at the next release. There is no fastparquet 1.1; even though the repo has a tag 1.1, this refers to parquet-python.

**Comment by mrocklin** [comment]
Ah, I see.  NM then

**Comment by gbrener** [comment]
Ok, thanks @martindurant @mrocklin . I'm closing this issue, with the understanding that someone who has push access should remove the 1.1 tag instead of us bumping the version in setup.py.
