### ISSUE TITLE
Cannot write a single partition at a time

### ISSUE THREAD

**Issue by rothnic** [dask/fastparquet#125]
I ran into this issue by trying to partition on some data by dates. I have a query that takes a little bit of time to run on a database that I wanted to try working with parquet on. I decided to run this for one month at a time and partition on the month, each time I get the data back. So, get data for month, write data partitioned by month, then repeat until complete.

So I have this date parameter that I'm using as part of a Luigi task, which I add to my df as a column like this `df['year_month'] = self.start_date.strftime('%Y-%m')`. Next, I try to write out the dataframe with fastparquet, partitioning on 'year_month' like this:

```python
write('path_to_output_folder', df, file_scheme='hive',
    compression='snappy', partition_on='year_month')
```

I ended up with this error:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<input>", line 2, in <module>
  File "/Users/nroth/anaconda/envs/luigi/lib/python2.7/site-packages/fastparquet-0.0.5-py2.7-macosx-10.5-x86_64.egg/fastparquet/writer.py", line 780, in write
    sep, compression, open_with, mkdirs
  File "/Users/nroth/anaconda/envs/luigi/lib/python2.7/site-packages/fastparquet-0.0.5-py2.7-macosx-10.5-x86_64.egg/fastparquet/writer.py", line 826, in partition_on_columns
    remaining.remove(column)
ValueError: list.remove(x): x not in list
```

I then proceeded to download fastparquet to see if I could fix the problem and demonstrate it with a test. Well, following the pattern used in the code I came up with this test:

```python
def test_single_partition(tempdir):
    fn = str(tempdir)

    df0 = pd.DataFrame({'a': [1, 2, 3, 0],
                        'b': ['a', 'a', 'a', 'a'],
                        'c': True})
    df1 = pd.DataFrame({'a': [1, 2, 3, 0],
                        'b': ['b', 'b', 'b', 'b'],
                        'c': True})

    write(fn, df0, partition_on='b', file_scheme='hive')
    r = ParquetFile(fn)
    assert r.schema[1].name == 'a'

    write(fn, df1, partition_on='b', file_scheme='hive', append=True)
    assert r.schema[2].name == 'b'
```

To my surprise, this test passed. So, after some more digging, I found that the issue is the test cases are too simple. Because the column names are a single character, then you can iterate over the single character and get the same value, which wouldn't be the case with more complex column names. So, I altered the test to be the following, which fails. I wanted to share the problem here first in case I don't get around to fixing the problem and submitting a PR as this was quite confusing to me and I think it is a common pattern for partitioning that people would follow. The partitioning logic needs to be more robust against assuming the iterable type that is provided.

```python
def test_single_partition(tempdir):
    fn = str(tempdir)

    df0 = pd.DataFrame({'my_ids': [1, 2, 3, 0],
                        'my_chars': ['ab', 'ab', 'ab', 'ab'],
                        'my_bools': True})
    df1 = pd.DataFrame({'my_ids': [1, 2, 3, 0],
                        'my_chars': ['bc', 'bc', 'bc', 'bc'],
                        'my_bools': True})

    write(fn, df0, partition_on='my_chars', file_scheme='hive')
    r = ParquetFile(fn)
    assert r.schema[1].name == 'a'

    write(fn, df1, partition_on='my_chars', file_scheme='hive', append=True)
    assert r.schema[2].name == 'b'
```

I think another case that will fail would be if you provided `partition_on=['column_with_one_paritition']`. In my case, the data is written out, but I end up with a partition labeled `year_month=2`, when I'd expect `year_month=2017-01`. In the above test case, called with `partition_on=['my_chars']`, then I'd get a partition of `my_chars=a`.

**Comment by martindurant** [comment]
Please change the command 

    write(fn, df0, partition_on='my_chars', file_scheme='hive')

to

    write(fn, df0, partition_on=['my_chars'], file_scheme='hive')

Notice that the parameter `partition_on` should be a list, even if it contains only one column name.

**Comment by rothnic** [comment]
@martindurant: see my last paragraph. Providing the input of columns as a list results in a separate issue when you only have a single value in the partition.

**Comment by rothnic** [comment]
Looking at the parquet file a bit more, I don't see a clear place to check the value of the partitions. There is a cats property that contains it, but not sure if that is only for partitions.

This test fails:

```python
def test_single_partition(tempdir):
    fn = str(tempdir)

    df0 = pd.DataFrame({'my_ids': [1, 2, 3, 0],
                        'my_chars': ['ab', 'ab', 'ab', 'ab'],
                        'my_bools': True})
    df1 = pd.DataFrame({'my_ids': [1, 2, 3, 0],
                        'my_chars': ['bc', 'bc', 'bc', 'bc'],
                        'my_bools': True})

    write(fn, df0, partition_on=['my_chars'], file_scheme='hive')
    r = ParquetFile(fn)
    assert os.path.exists(os.path.join(fn, 'my_chars=a'))  # incorrect and returns True
    assert os.path.exists(os.path.join(fn, 'my_chars=ab')) # correct and returns False
```
