### ISSUE TITLE
Error parsing metadata file?

### ISSUE THREAD

**Issue by DigitalPig** [dask/fastparquet#130]
Hi,

I have a s3 directory having parquet files generated by databrick's Spark. When I am trying to read the file into `dask` using `read_parquet` I got the following errors:

```python
ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

During handling of the above exception, another exception occurred:

FileNotFoundError: s3://s3_bucket/_metadata/_metadata

During handling of the above exception, another exception occurred:

TTransportException                       Traceback (most recent call last)

TTransportException: <class 'thriftpy.transport.TTransportException'>
ALREADY_OPEN: 2
END_OF_FILE: 4
NOT_OPEN: 1
TIMED_OUT: 3
UNKNOWN: 0
args: ()
message: End of file reading from transport
type: 4
with_traceback: <built-in method with_traceback of TTransportException object at 0x7ff77f07abe8>


During handling of the above exception, another exception occurred:
ParquetException: Metadata parse failed: s3://s3_bucket/_metadata
```

I can read the directory into Spark without any issue. I can read the individual file in the directory using:

```python
myopen = s3.open
pf = ParquetFile('s3://s3_bucket/part-r-00000-3fc7f79f-8199-4691-9a15-2a9f47713b52.gz.parquet', open_with=myopen)
```

and it works fine.

**Comment by martindurant** [comment]
The newest version of Spark (unfortunately) no longer creates metadata files when writing parquet. You have two options:

-  use `fastparquet.writer.merge` to create the metadata file (you will only need to do this once), and then load as you were doing
- open with a list of files directly (you will need to do this every time)

In both cases, you will need a list of files that you want to include in your dataset, e.g.,

    import s3fs
    s3 = s3fs.S3FileSystem(...)
    files = ['s3:/%s' %s for s in s3.glob('/s3_bucket/*.parquet')]  # dask expects "s3://"
    pf = read_parquet(files)

**Comment by DigitalPig** [comment]
Thanks for the quick comments. I will try out the latest dev version. But I want to point out that the parquet file is generated using Spark 1.6 and it does have a `_metadata` in its folder.

**Comment by martindurant** [comment]
My apologies; that suggests then that the metadata in _metadata and that in the file are not the same, which would be strange. It is hard to tell from the traceback what might have happened. Is _metadata zero-length by any chance?

**Comment by DigitalPig** [comment]
Thanks for comment. 

![capture](https://cloud.githubusercontent.com/assets/97392/24970807/b65814c4-1f83-11e7-868c-e388f316ff99.PNG)

Here is the snapshot of the `_metadata` file. The bucket is encrypted (server side encryption) not sure if that is the issue. But if the encryption was the issue, I wouldn't be able to read single parquet then...

**Comment by martindurant** [comment]
A metadata file of 2.5GB! I cannot conceive of what might be stored in there, but if this is real, you are very probably hitting some overflow. Are the data-files similarly enormous?

**Comment by DigitalPig** [comment]
I did some additional research and found the previous `_metadata` indeed is an issue. Not sure how Spark read the data correctly. 

However I am having another issue now reading parquet (kind of similar to dask/dask#2051 with latest git version of `dask` and `fastparquet`. I have a minimum data sample that I created to replicate the error. You can go there to grab the data file.

**Comment by DigitalPig** [comment]
Looks the latest `fastparquet` solve this issue. Thanks for the help! @martindurant
