### ISSUE TITLE
Reading from parquet files with many row-groups can take a while

### ISSUE THREAD

**Issue by mrocklin** [dask/fastparquet#133]
```python
In [1]: import fastparquet

In [2]: %time pf = fastparquet.ParquetFile('day-0.parquet/')
CPU times: user 5.59 s, sys: 20 ms, total: 5.61 s
Wall time: 5.61 s

In [3]: len(pf.row_groups)
Out[3]: 778
```

**Comment by mrocklin** [comment]
This dataset is only 1/24th of the full dataset, and it's on my local system.  I suspect that when reading the full dataset from a remote storage system like S3 or GCS that this 5s delay (which is definitely manageable) will become worse.

**Comment by martindurant** [comment]
Would you mind doing a profile on this? If the time is taken up by thrift parsing (which is likely), I'm not sure there's much we can do - thriftpy is apparently cythonized. The filemetadata is a single massive thrift structure, so doesn't offer the opportunity to part-load.

**Comment by mrocklin** [comment]
Is there a way to take advantage of the repetition within each row-group?

I am also primarily interested in accelerating this for Dask.dataframe.  Are there things we could give up like finding statistics or partitions-per-row-group rather than partitions-per-files that would allow us to speed things up?

**Comment by martindurant** [comment]
In the common case, there is exactly one row-group per file (even for spark), so not much to do there. Yes, we could decide not to decode statistics, but we can't not load them with the current thriftpy implementation. The chunks written by dask/fastparquet will indeed be very homogenous, but this cannot in general be guaranteed. I don't know of a way to instruct/patch thriftpy to not interpret parts of the record structure, and it may not be possible: the data is a set of "field begins-value-field ends" sets without offsets for skipping.

This must be why spark decided to do away with metadata files - but the cost is that you need to access each file in turn before knowing if you'll want to load it for any particular query. If you load parquet with dak/fastparquet now, it builds the metadata in memory by accessing each file, so worst of both worlds.

**Comment by martindurant** [comment]
Looking through thriftpy, it appears that only the "binary" protocol is [cythonized](https://github.com/eleme/thriftpy/blob/develop/thriftpy/protocol/cybin/cybin.pyx), but not the "compact" protocol we use.  I am not sure, but I don't think that "compact" uses "binary" underneath. "Compact" also looks eminently doable.

**Comment by martindurant** [comment]
Interestingly, taking the compact.py file from thrift and running cython on it with **no annotations** reduced the ParquetFile constructor time for a small trial from 16ms to 9ms. That's with calling struct python functions, no considerations at all.

I also have the following small optimization for load time in util.py, caching the regex (which don't even get used for this case):
```
# simple cache to avoid re compile every time
seps = {}


def ex_from_sep(sep):
    """Generate regex for category folder matching"""
    if sep not in seps:
        if sep in r'\^$.|?*+()[]':
            s = re.compile(r"([a-zA-Z_]+)=([^\{}]+)".format(sep))
        else:
            s = re.compile("([a-zA-Z_]+)=([^{}]+)".format(sep))
        seps[sep] = s
    return seps[sep]
```

**Comment by martindurant** [comment]
@mrocklin, can you try with https://github.com/dask/fastparquet/pull/135/commits/6517e2b32239c1d09375c66b298c4309ff4236dd ?
Note that this seemed to give a good improvement in combination with cythonizing, as above.

**Comment by mrocklin** [comment]
### Master

```python
In [1]: import dask.dataframe as dd

In [2]: %time df = dd.read_parquet('day-0.parquet', index=False, categories={'ca
   ...: tegory_%d' % i: 2**31 for i in range(26)})
CPU times: user 5.86 s, sys: 24 ms, total: 5.88 s
Wall time: 5.9 s
```

### 6517e2b

```python
In [1]: import dask.dataframe as dd

In [2]: %time df = dd.read_parquet('day-0.parquet', index=False, categories={'ca
   ...: tegory_%d' % i: 2**31 for i in range(26)})
CPU times: user 4.1 s, sys: 16 ms, total: 4.12 s
Wall time: 4.12 s
```

**Comment by martindurant** [comment]
https://github.com/martindurant/thriftpy/tree/cropping instead of stock thriftpy may well get you a factor of 2

**Comment by martindurant** [comment]
I believe this should be reasonably well solved now.
