### ISSUE TITLE
error when reading from single path vs list of paths

### ISSUE THREAD

**Issue by sritchie-stripe** [dask/fastparquet#146]
Hello! I ran into a small bug while converting a bunch of our internal csv parsing over to fastparquet. (Thank you!) The bug appears when I try to use filters with `to_pandas`, but only when I pass in a string path to my parquet file instead of a list of paths.

First, the setup. This is all on commit `1bfd45f458056c28f2242180d8839b69e13c9f22`, btw.

```python
import fastparquet as parquet
import pandas as pd

df = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6, 7],
    'letter': ['a', 'b', 'c', 'd', 'e', 'f', 'g']
})

parquet.write("./output.parq", df)
```

Then let's try and read wiht a filter on `'x'`. This fails:

```python
pf = parquet.ParquetFile("./output.parq")
pf.to_pandas(filters=[['x', '>', 3]])
```

with the following traceback:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-fe74337cec8c> in <module>()
      1 pf = parquet.ParquetFile("./output.parq")
----> 2 pf.to_pandas(filters=[['x', '>', 3]])

/pay/home/sritchie/dev-sritchie/stripe/zoolander/vendor/src/fastparquet/fastparquet/api.pyc in to_pandas(self, columns, categories, filters, index, timestamp96)
    318         """
    319         check_column_names(self.columns, columns, categories, timestamp96)
--> 320         rgs = self.filter_row_groups(filters)
    321         size = sum(rg.num_rows for rg in rgs)
    322         columns = columns or self.columns

/pay/home/sritchie/dev-sritchie/stripe/zoolander/vendor/src/fastparquet/fastparquet/api.pyc in filter_row_groups(self, filters)
    236         return [rg for rg in self.row_groups if
    237                 not(filter_out_stats(rg, filters, self.schema)) and
--> 238                 not(filter_out_cats(rg, filters))]
    239 
    240     def iter_row_groups(self, columns=None, categories=None, filters=[],

/pay/home/sritchie/dev-sritchie/stripe/zoolander/vendor/src/fastparquet/fastparquet/api.pyc in filter_out_cats(rg, filters, sep)
    606         return False
    607     s = ex_from_sep(sep)
--> 608     partitions = s.findall(rg.columns[0].file_path)
    609     pairs = [(p[0], val_to_num(p[1])) for p in partitions]
    610     for cat, v in pairs:

TypeError: expected string or buffer
```

The same code succeeds when I wrap `"./output.parq"` in a list before passing it in to `ParquetFile`:

```python
pf = parquet.ParquetFile(["./output.parq"])
pf.to_pandas(filters=[['x', '>', 3]])
```

Interestingly, round-tripping to `"output.parq"` without the `./` prefix works fine when the path is NOT in a list, but fails when I stick it into a list.

I don't know enough to fix this one myself but it looks like it might be fairly straightforward. Thanks so much for the excellent library!

**Comment by martindurant** [comment]
Thank you for the report. I'll get back to you as soon as I can.
A quick note on filters: in your example there will be only one row_group, which contains some values of x greater than 3, so in this case the filter would have no effect, only row_groups with no valid values are excluded. Of course, in your data this may not be the case.

**Comment by sritchie-stripe** [comment]
Yup, I realized that after thinking that the filters weren't working. We do have more row groups in the data I'm using this with, but I'm using the single-row-group thing for some naive caching I'm doing, and I'll need to optimize it.

I did put together some internal code that I use to run the filters again on the returned dataframe. It's been really useful to be able to lean on the effect always working, under the hood and on the returned dataframe.

Here's the code in case the idea's interesting. Might be nice to include something like this with a flag.

```python
def apply_filters(df, filters):
    """applies all filters to the actual dataframe. (The supplied
    filters above only work for row groups.)

    """
    if len(filters) == 0:
        return df
    else:
        condition = True
        for col_name, op, filter_value in filters:
            new_filter = _apply_filter(df, col_name, op, filter_value)
            condition = condition & new_filter
        return df[condition]


def _apply_filter(df, col_name, op, filter_value):
    """applies the specific filter to the column and returns a pandas
    series of booleans.

    """
    col = df[col_name]

    if op == '==':
        return col == filter_value
    elif op == '!=':
        return col != filter_value
    elif op == 'in':
        return col.isin(filter_value)
    elif op == 'not in':
        return ~col.isin(filter_value)
    elif op == '>':
        return col > filter_value
    elif op == '<':
        return col < filter_value
    elif op == '>=':
        return col >= filter_value
    elif op == '<=':
        return col <= filter_value
    else:
        raise(Exception('operation %s not supported!' % op))
```

I also implemented some craziness that lets me supply filters for `np.datetime64` columns that might be serialized as unix epoch seconds. The code knows how to convert the filters into the proper representation for the row group filters and the actual dataframe filters (these might be different) and handles the timestamp conversion of the relevant columns after deserialization.

That might be too specific to share, but thought I'd mention it.

**Comment by martindurant** [comment]
I don't think its too useful for fastparquet itself, because once you have the pandas dataframe, you can apply whatever normal filtering that people do.

However, you may be interested to read parquet files using dask's [`read_parquet`](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.read_parquet), which gives you a lazy analogue of a pandas dataframe where filtering operation, on the index only, translate to not loading some parquet partitions but you also get automatic filtering of rows in those partitions read. In addition, you can still pass filters= for partition-wise filtering (particularly useful if you have used directory name partitioning).

**Comment by sritchie-stripe** [comment]
I think that's where we're headed. I just want to test everything out heavily and make sure that `dask` works well with the models that we're training in scikit-learn. Thanks!
