### ISSUE TITLE
Writing large frame with partition_on= used adds timestamp of creation time to partitions, breaks filters=

### ISSUE THREAD

**Issue by canada4663** [dask/fastparquet#149]
Hello - 

Related to #148 , but different issue.  I'm trying to re-create without posting ~1GB of data to the issue, but haven't been able to.

I have a ~2.7GB dataframe which I am trying to write to a partitioned parquet hive repository.  Command used below:
```python
pq.write('pqPartitioned', df, partition_on=['UnderlyingSymbol'], file_scheme='hive')
```

After it is successfully written and I run ```pq.ParquetFile('pqPartitioned').cats```, there is a timestamp of the creation time as one of the cats or partition keys.

This then breaks the filter_on= capability of to_pandas() function.

Further, even if I try to read the whole frame with ```pq.ParquetFile('pqPartitioned').to_pandas``` I get the below error:
```python
ValueError: Timestamp('2017-05-14 12:47:10') is not in list
```

I checked:
* input dataframe doesn't include any timestamps in the 'UnderlyingSymbol' column before being written
* tried this with original dataframe index intact as well as with index reset
* using fastparquet 0.0.6

I will keep trying to recreating this with my test dataframe generator so this can be recreated in other environments, but I think these two facts may indicate something is going on internally to fastparquet: 
1) the input dataframe column is definitively clean without timestamps
2) the timestamp inserted is consistent with the time the parquet hive tree was created

Any ideas would be appreciated!

Thanks -

**Comment by martindurant** [comment]
This sounds interesting, I'd definitely like to see an example I can run for myself.

**Comment by canada4663** [comment]
If I can come up with something, I will let you know.  

I decided to use PySpark to generate the hive formatted parquet files from my csv, so no longer an issue for my use case - but if I can come up with a way of re-creating this without posting the exact data I used, I will post.

**Comment by canada4663** [comment]
@martindurant - OK.  I think I figured out what is causing this issue... and its actually now causing an issue on the read side in to_pandas() method.

When partition underlyingsymbol=NOW, val_to_num method is converting this to current timestamp.

```python
def filter_out_cats(rg, filters, sep='/'):
    """
    According to the filters, should this row-group be excluded
    Considers the partitioning category applicable to this row-group
    Parameters
    ----------
    rg: thrift RowGroup structure
    filters: list of 3-tuples
        Structure of each tuple: (column, op, value) where op is one of
        ['==', '!=', '<', '<=', '>', '>=', 'in', 'not in'] and value is
        appropriate for the column in question
    Returns
    -------
    True or False
    """
    if len(filters) == 0 or rg.columns[0].file_path is None:
        return False
    s = ex_from_sep(sep)
    partitions = s.findall(rg.columns[0].file_path)
    pairs = [(p[0], val_to_num(p[1])) for p in partitions]      ##### This converts symbol=NOW to Timestamp
    for cat, v in pairs:

        app_filters = [f[1:] for f in filters if f[0] == cat]
        for op, val in app_filters:
            out = filter_val(op, val, v, v)
            if out is True:
                return True
    return False
```

I haven't run through the write side code that initially caused me to file this issue, however, I imagine it is the same issue causing both write and read failures.

As it stands, partion key equal to string 'NOW' will not work.  Maybe this could be changed so that the 'NOW' sentinel used presumably for time comparisons is something like '%%NOW%%' - or alternately, there is a type check on the column type and the val_to_num method is only called for certain types?

**Comment by martindurant** [comment]
Hah, good detective work!

    In [14]: pd.to_datetime('NOW')
    Out[14]: Timestamp('2017-05-21 21:22:44')

since the directory names are actually strings, the only way the code knows whether to convert to some value is by seeing if various conversion functions work, in this case causing an unfortunate alias of string to timestamp.

**Comment by martindurant** [comment]
One possible solution I can think of, is to pass any user-supplied string in a filter to `val_to_num` too

**Comment by canada4663** [comment]
Hmm... not sure I understand what you mean.

One approach might be checking for conformance to various regex.  You are evaluating the string to see if it becomes a python object, it would either be in a timestamp format or have a function name with parentheses.  If one of these doesn't match, then pass through as a string.

I was having another issue where there was a symbol in the partition key and the eval of that string was throwing an exception - this solution would also solve that problem.

Alternately, you could pass the column types in with each filter, and determine the val_to_num operation based on the column type.  That is probably the cleanest, but would involve some refactoring. 

For now.... I simply did:
```python
if x == 'NOW':
      return x
```

I *think* this is working now in my local repo.  Still playing.

**Comment by martindurant** [comment]
Does #155 solve the issue for you?
