### ISSUE TITLE
Expected list of bytes

### ISSUE THREAD

**Issue by gleblanc1783** [dask/fastparquet#160]
I've been using FP for a while now and it's been working great. I am working on a side project locally and I am having some problems writing a df to a file.

```
...
  File "fastparquet/speedups.pyx", line 110, in fastparquet.speedups.pack_byte_array (fastparquet/speedups.c:2809)
TypeError: expected list of bytes
```

Here's the code is that is generating the df:
```
...
    for key, value in balance_data.iteritems():
        data = {
            "currency": key,
            "current_balance": value
        }
        return_list.append(data)
    
    df = pd.DataFrame.from_records(return_list)
    print df
    #fastparquet.write(os.path.join("cryptmon", "data.parq"), df)
    fastparquet.write("data.parq", df)
```

This is exactly how I do it in my Linux environment, only this is OSX. 

Any ideas?

fastparquet==0.0.6 (have also tried 0.0.5) and pandas 0.20.1

**Comment by martindurant** [comment]
What are the types for `key` and `value`? The exception suggests that the guessing of how to turn them into bytes type for writing is failing. Since this happens for you on one system and not another (presumably for the same data), maybe you have py2 in one place and py3 in another?

In any case, you can be explicit and define how to encode object columns:

    fastparquet.write("data.parq", df, object_encoding='utf8')

(all columns)

    fastparquet.write("data.parq", df, object_encoding={'key': 'json', 'value': 'bytes'})

(columns individually)

**Comment by gleblanc1783** [comment]
Thanks so much for the reply @martindurant. That was it - "key" was a string, and "value" was a float. 

1) I just converted the float to a string **and it works now**
2) Any idea why I cannot convert a float into bytes?

**Comment by martindurant** [comment]
Floats do in general work fine, but your column type must be Object to have got this error - perhaps there are some non-float values like strings "None" or "NaN" (as opposed to the float NaN) somewhere in there?

**Comment by gleblanc1783** [comment]
You're right @martindurant - close about the non-float values.... Try integer :)

I initially create the parquet file in another file - but this is the code I use:
```
df = pd.DataFrame([{'currency': '', 'current_balance': 0}])
fastparquet.write(os.path.join("cryptmon", "data.parq"), df, compression='GZIP')
```

current_balance is an integer.  I simply corrected that error and everything works now.

Going to close this issue - thanks for the awesome responses!

**Comment by martindurant** [comment]
Glad it worked!
