### ISSUE TITLE
API: Should .to_pandas(filters=...) include rows that don't match the filters?

### ISSUE THREAD

**Issue by jdanbrown** [dask/fastparquet#166]
This confused me for a while when I first started working with fastparquet, and I only understood what was going on after digging into the low-level behaviors of parquet row groups:

```py
>>> import fastparquet
>>> import os
>>> import pandas as pd
>>> import time

>>> def fresh_file():
...     return '/tmp/x-%s.parquet' % time.time()

>>> def fresh_dir():
...     path = fresh_file()
...     os.mkdir(path)
...     return path

>>> dir = fresh_dir()
>>> fastparquet.write(
...     dir,
...     pd.DataFrame(data={'values': ['a', 'b', 'c']}),
...     file_scheme='hive',
... )
>>> fastparquet.ParquetFile(dir).to_pandas(
...     filters=[('values', '==', 'a')],
... )
  values
0      a
1      b
2      c
```

`.to_pandas(filters=...)` returns all three rows, even those that don't match the filter `('values', '==', 'a')`. After digging into the code I figured out that this is because it's only filtering on input row groups, and not again on output rows, which I found surprising. I think the api would be less surprising and thus more usable if it did the second row filter automatically. Thoughts?

**Comment by martindurant** [comment]
Perhaps it could be cleared up to say that this is a **filter row groups** operation? To load and filter within row groups too, I would use dask and wouldn't want to push the logic down into fastparquet. The reason is, that the memory for each part is pre-assigned to avoid memory copying and expensive concat operations. To allow filtering, there would have to be a pre-run through the data (at least the filtering columns) to find out how much dataframe memory to assign.

**Comment by jdanbrown** [comment]
- Ah, yep, clarifying that this is a "filter row group" operation would have avoided my confusion.
- And pushing the higher-level predicate pushdown concern into dask also makes sense.

**Comment by martindurant** [comment]
I put a few words in https://github.com/dask/fastparquet/pull/168/commits/7c45f2396e7887fbbfba318dd637e4e17b1e4c65

**Comment by jdanbrown** [comment]
Lgtm. And here's a small addition that would make it one step clearer, if you want to fold it in:
```
        filters: list of tuples
            To filter out (i.e., not read) some of the row-groups. (This doesn't also filter rows.)
            Filter syntax: [(column, op, val), ...],
            where op is [==, >, >=, <, <=, !=, in, not in]
```
