### ISSUE TITLE
filters with ==, in, <=, >= does not seem to work

### ISSUE THREAD

**Issue by pduch** [dask/fastparquet#173]
Hi guys,
It looks like for some reason the filtering with any kind of "equal" is not working. Here is a simple example.

import pandas as pd
import fastparquet as pq

FILE = 'c:\\tmp\\my_file.parquet'
COMPRESSION = 'GZIP'

dates = pd.date_range('20151201', '20170601', freq='M')
df = pd.DataFrame({'date': dates,   'num': [1.11] * len(dates), 'year': [d.year for d in dates]})
pq.write(FILE, df, compression='GZIP', partition_on=['year'], file_scheme='hive')

pf = pq.ParquetFile(FILE)

filters = [('year', '>', '2014'), ('year', '<', '2016')]
df = pf.to_pandas(filters=filters)
assert len(df) == 1

filters = [('year', '<=', '2015')]
df = pf.to_pandas(filters=filters)
assert len(df) == 1  # equals does not work !!!

filters = [('year', '==', '2015')]
df = pf.to_pandas(filters=filters)
assert len(df) == 1  # equals does not work !!!

filters = [('year', 'in', ['2015'])]
df = pf.to_pandas(filters=filters)
assert len(df) == 1  # equals does not work !!!

**Comment by martindurant** [comment]
This is working for me (for >, <, ==, <=), which may be because of a recent change in the code. Can you update to the most recent master?

One thing you should be aware of, is that you are doing string comparisons, because you are passing values like `'2015'` instead of the number `2015`. In the latest version, this works, but this change was recent. I notice it does *not* work for `in`, where you must supply a value with matching type - I am fixing this right now.

**Comment by martindurant** [comment]
(btw, tip:  `[d.year for d in dates]`->`dates.year`)

**Comment by pduch** [comment]
Thanks Martin

I had to use strings because as a number (2015) it was crashing. I will use the latest master and give it a try.
Cheers,
P

**Comment by pduch** [comment]
When is your next release on conda-forge?

**Comment by martindurant** [comment]
There is no concrete release plan - releases come when there appears to be enough new functionality or fixes to warrant it, or when a release of something else (dask) depends on recent changes.

**Comment by martindurant** [comment]
It is puzzling that using numbers caused an error for you. Are you on python 2 by any chance? I wonder is on windows, file names are not the type I expect.

**Comment by pduch** [comment]
I am on windows using Python 3.5. I will try the test on my Linux box to see how it goes. 
I am a bit puzzled too, considering that I can run your test cases on your data (test_read.py). I will keep you posted
