### ISSUE TITLE
Datetime field being read in as binary data

### ISSUE THREAD

**Issue by erikcw** [dask/fastparquet#175]
I have a Parquet file generated by a Spark job (pyspark).  When I attempt to read the file with fastparquet, everything looks good except for the contents of the column named `timestamp` which contains binary data instead of the `datetime` object that I'm expecting.

```python
pf = ParquetFile('part-r-01061-92f8858d-d5ff-4c54-aeff-4423d863c466.snappy.parquet')
df = pf.to_pandas()
df.loc[2].timestamp == '\xc0\xcfj\x00\x00\x00\x00\x00F\x81%'
```

**Comment by martindurant** [comment]
spark uses a non-typical type to store times. fastparquet can read this, but it is optional. Include the column containing the data in the `timestamp96` parameter, e.g.,

    df = pf.to_pandas(timestamp96=['my_time_column'])

**Comment by erikcw** [comment]
Ahh -- that works!  Does `write` automatically convert a Python `datetime` object into `timestamp96` format so my writes will be compatible with Spark for future reads?

**Comment by martindurant** [comment]
You will want `times='int96'` when writing.
