### ISSUE TITLE
Unable to install on ubuntu 16.0.4 due to llvm version issues

### ISSUE THREAD

**Issue by javadba** [dask/fastparquet#176]
When installing  via 

    pip install --user fastparquet

An error comes : we are supposed to use a non-stable development version of llvm ??

    RuntimeError: Building llvmlite requires LLVM 4.0.x. Be sure to set LLVM_CONFIG to the right 
   executable path.

Ok well let's try ..

$ aptget clang-4.0 lldb-4.0 lld-4.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-4.0 : Depends: libclang1-4.0 (= 1:4.0~svn305187-1~exp1) but it is not going to be installed
             Depends: libjsoncpp1 but it is not installable
             Depends: libllvm4.0 (>= 1:4.0~) but it is not going to be installed
             Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
             Depends: libstdc++-5-dev but it is not installable
             Depends: libgcc-5-dev but it is not installable
             Depends: libobjc-5-dev but it is not installable
             Depends: libclang-common-4.0-dev (= 1:4.0~svn305187-1~exp1) but it is not going to be installed
             Recommends: llvm-4.0-dev but it is not going to be installed
 lld-4.0 : Depends: libllvm4.0 (= 1:4.0~svn305187-1~exp1) but it is not going to be installed
           Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
           Depends: llvm-4.0-dev but it is not going to be installed
 lldb-4.0 : Depends: liblldb-4.0 (>= 1:4.0~) but it is not going to be installed
            Depends: libllvm4.0 (= 1:4.0~svn305187-1~exp1) but it is not going to be installed
            Depends: libncurses5 (>= 6) but 5.9+20140118-1ubuntu1 is to be installed
            Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
            Depends: libtinfo5 (>= 6) but 5.9+20140118-1ubuntu1 is to be installed
            Depends: llvm-4.0-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Is there a more straightforward way to install on ubuntu?

**Comment by martindurant** [comment]
It seems you still cannot reliably expect numba to be built by pip (although I believe there has been some work in that direction). If you must install via pip, then I would say you must have numba and cython already installed by whatever means. For most users of fastparquet, that would be via `conda` (where compiling is not an issue), but you could try getting them directly from your package manager if using system python.

**Comment by mrocklin** [comment]
@sklam are there guidelines for how to install numba on ubuntu without
conda?

**Comment by sklam** [comment]
We have llvmlite wheels for 64-bit linux since llvmlite 0.17.1.
