### ISSUE TITLE
Writing map datatype

### ISSUE THREAD

**Issue by erikcw** [dask/fastparquet#180]
I'm trying to use fastparquet to integrate a Python service into an existing Spark (pySpark) application.  I need to be able to read/write parquet files from both fastparquet and Spark.

I'm having trouble writing a map-type column from fastparquet (I'm able to read them no problem).

```python
import fastparquet

# Read in parquet file generate by pySpark.
pf = fastparquet.ParquetFile("./subset_part-r-02572-bddb92a4-e16d-4e9b-b0fd-4454c0c28525.snappy.parquet")

df = pf.to_pandas(timestamp96=['timestamp'])
assert df.loc[3].verticals == {u'401': u'1.0', u'58': u'0.5027621388435364'}, "Sanity check"
assert df.loc[3].verticals['58'] == u'0.5027621388435364', "Sanity check"

# Attempt to round trip the dataframe back out to Parquet in the same format as the input file.
fastparquet.write('write.parquet', df, compression='SNAPPY', file_scheme='hive', has_nulls=True, times='int96')

```

Now using [parquet-tools](https://github.com/wesleypeck/parquet-tools) to inspect the output.

```bash
# Input file generated with pySpark

$ parquet-tools schema subset_part-r-02572-bddb92a4-e16d-4e9b-b0fd-4454c0c28525.snappy.parquet
message spark_schema {
  required binary activity_id (UTF8);
  required int96 timestamp;
  optional binary uid (UTF8);
  optional group verticals (MAP) {
    repeated group key_value {
      required binary key (UTF8);
      required binary value (UTF8);
    }
  }
  optional binary url (UTF8);
  optional binary domain (UTF8);
  optional binary sld (UTF8);
  optional binary zip_code (UTF8);
}
```

fastparquet is writing the `verticals` column as type `JSON` instead of type `MAP`.

```bash
# Output file generate by fastparquet

$ parquet-tools schema write.parquet
message schema {
  optional binary activity_id (UTF8);
  optional int96 timestamp;
  optional binary uid (UTF8);
  optional binary verticals (JSON);
  optional binary url (UTF8);
  optional binary domain (UTF8);
  optional binary sld (UTF8);
  optional binary zip_code (UTF8);
}
```

Here is the schema used by pySpark
```python
from pyspark.sql.types import *
schema = StructType([
        StructField("activity_id", StringType(), False),
        StructField("timestamp", TimestampType(), False),
        StructField("date", StringType(), False),
        StructField("uid", StringType(), True),
        StructField("verticals", MapType(StringType(), StringType(), False), True),
        StructField("url", StringType(), True),
        StructField("domain", StringType(), True),
        StructField("sld", StringType(), True),
        StructField("zip_code", StringType(), True),
])

```

Also, how do you make fastparquet mark a column as "required" instead of "optional" in the schema?

**Comment by martindurant** [comment]
fastparquet is not capable of writing MAP, LIST or any nested schemas. The ability to read these is new, and exists because there is a need to input such data. Is there a good reason for you to write using these structured types rather than JSON?

It is the `has_nulls=True` that results in all columns being optional. You could instead provide a list of columns that you wish to be optional (others are required), or False, in which all fields will be required, or 'infer', which will have float and int64 time columns as required, because they have inherent NaN and NaT bad-data markers.

Note that spark will generally have all columns as optional in the parquet schema even if you say that the field is not nullable.

**Comment by erikcw** [comment]
The reason I'm using a `MAP` instead of `JSON` is that I need to be able to read the data from AWS Athena.  Athena supports `MAP`, but it doesn't support `JSON` type columns.

Further, since fastparquet is being added into a fairly large existing service, I need the `MAP` datatype so that I don't have to update all the existing spark and athena applications to use the `JSON` type instead -- additionally I'd need to rebuild all the existing data to migrate to the new column type.

**Comment by martindurant** [comment]
I consider it, but my initial thought is that it would be a lot of effort to implement writing MAP/LIST types for what seems like a niche use-case. I am surprised that Athena can't make use of the columns as they are.

**Comment by daniel-severo** [comment]
We are migrating our analytics stack to parquet here at our organization, but our data source is big unstructured and nested JSON data. The `MAP` encoding for us would also be a huge plus!

**Comment by martindurant** [comment]
If a large fraction of the data is in nested structures, then parquet might not be the best choice for storage format. There are others around (avro, thrift...), but actually, ujson is very efficient at parsing JSON records.

I don't have a strong recommendation for you, keeping in mind the in-memory representation of such nested structures in python will be dictionaries, and operating on them will be much slower than vectorized access to columns of numbers, times etc.

**Comment by dan-blanchard** [comment]
We have looked at moving from Spark to Dask a few times now and the lack of `MAP` support by `fastparquet` is the main thing blocking us. Changing all of our data to use a different datatype at this stage is not feasible.

**Comment by martindurant** [comment]
Curiosity question for those who have expressed interest in this matter: how would you picture the python-to-parquet MAP or LIST transformation? Would you be starting with a pandas dataframe, in which the object columns have various types such as UTF8 strings, but some contain exclusively (python) lists or exclusively (python) dicts? Is that the kind of situation you have now?
In that case, the theoretical function would look like

    fastparquet.write(df, object_encoding={'text_col': 'utf8', 'arr_col': 'list', 'dict_col': 'map'})

but we would **also** need the dtype of the elements and, potentially, their encoding, and maybe even specify whether NULLs are allowed at various levels (note the difference between values None, [], [None] and None, {}, {key: None}).
Spark/hive et al. have an object-oriented type system for this, pandas/fastparquet does not. Arrow may, I'm not sure.

Perhaps you see the reason for my reticence. I'd be happy for anyone but me to do this work!

**Comment by yohplala** [comment]
Hi there,
In case anyone is interested, this [SO answer](https://stackoverflow.com/a/60231549/4442753) details an 'option2' that can be a workaround worth having a look into.

**Comment by martindurant** [comment]
@yohplala , this is mentioned in the (old) comment stream above too, but the OP did not want to resort to JSON encoding.
