### ISSUE TITLE
Missing schema example in documentation.

### ISSUE THREAD

**Issue by daniel-severo** [dask/fastparquet#187]
Hi guys, looks like some text went missing in the docs: http://fastparquet.readthedocs.io/en/latest/details.html?#reading-nested-schema

Notice that at the end of these two points in the text the example schemas are missing:

- For instance, if a schema looks like
- For instance, the schema may include

Although it looks like in the source code the text is present: https://github.com/dask/fastparquet/blob/master/docs/source/details.rst#reading-nested-schema

**Comment by martindurant** [comment]
Oops! Thanks for pointing this out.
I have fixed in 218011781585312a81af9d0fb7aa4af393f399d7 (RTD now rebuilding).
