### ISSUE TITLE
fastparquet.speedups.array_encode_utf8 cannot handle str pd.Series

### ISSUE THREAD

**Issue by xwang777** [dask/fastparquet#191]
It seems that dask.dataframe.to_parquet cannot handle str columns in ascii encoding. More specifically, it's fastparquet.speedups.array_encode_utf8 that throw TypeError when it tries to convert some str object arrays into unicode object arrays.

Here's an example to reproduce. It creates 10 random pd.DataFrame with MultiIndex, where two index levels are str. It use dask.dataframe.read_parquet to read them back and then write to parquet again. It failed in to_parquet because fastparquet.speedups.array_encode_utf8 throw TypeError on these two str columns. 

If I assign unicode('sess_abc_%d' % i) and unicode( 'ABC_%d' % i ), then the code works. 

```
import dask, time
import dask.dataframe as dd
import fastparquet as fpq
import pandas as pd
import numpy as np

tx = pd.timedelta_range('09:30:00', '16:00:00', freq='100ms', name='time')
dfs = []
n_row, n_col = len(tx), 10
for i in xrange(5):
    df = pd.DataFrame(np.random.randn(n_row, n_col), columns = ['c_%d' % k for k in xrange(n_col)])
    df.index = tx
    df['sess_key'] = 'sess_abc_%d' % i
    df['prod'] = 'ABC_%d' % i
    df.set_index(['prod','sess_key'], append=True, inplace=True)
    dfs.append(df)

for i, df in enumerate(dfs):
    fpq.write('/tmp/tmerge/test_%d.pq' % i, df, row_group_offsets=100000, compression='snappy', write_index=True)

ddf = dd.read_parquet('/tmp/tmerge/*.pq', filters=[('time', '<=', pd.Timedelta('09:40:00').asm8)], index=False)
ddf = ddf.sample(frac=0.1)
ddf.to_parquet('/tmp/tmerge1')
```

Here's the last stack trace:

> /home/PFTCTRADING/xwang/app/anaconda/lib/python2.7/site-packages/fastparquet/speedups.pyx in fastparquet.speedups.array_encode_utf8 (fastparquet/speedups.c:2297)()
>      58     for i in range(n):
>      59         # Fast utf-8 encoding, avoiding method call and codec lookup indirection
> ---> 60         result[i] = PyUnicode_AsUTF8String(arr[i])
>      61 
>      62     return result
> 
> TypeError: bad argument type for built-in operation
>

**Comment by martindurant** [comment]
In fact, the error I get is as follows:
"NotImplementedError: multi-index not yet supported, use index=False" - which is more informative for you.
The reason is, that the dtype of the index of `df` is generic object, actually a set of tuples (not str!), which do not encode to parquet in an obvious way, certainly not as UTF8. Furthermore, dask dataframes do not in general work well with multi-level indexes. Please consider how you might perform your problem with a single-column index, or none.

**Comment by xwang777** [comment]
I can change to not write index:
`fpq.write('/tmp/tmerge/test_%d.pq' % i, df.reset_index(), row_group_offsets=100000, compression='snappy', write_index=False)
`,
and get the same error.

If I step up the stack into fastparquet/writer.py, I can see data passed to fastparquet.speedups.array_encode_utf8 is a pd.Series of str.

> > /home/PFTCTRADING/xwang/app/anaconda/lib/python2.7/site-packages/fastparquet/writer.py(168)convert()
>     166     elif dtype == "O":
>     167         if converted_type == parquet_thrift.ConvertedType.UTF8:
> --> 168             out = array_encode_utf8(data)
>     169         elif converted_type is None:
>     170             if type in revmap:
> 
>   /tmp/fastparquet/speedups.pyx(60)fastparquet.speedups.array_encode_utf8 (fastparquet/speedups.c:2297)()
> 
> ipdb> data.head()
> 27425    ABC_2
> 44609    ABC_2
> 14058    ABC_2
> 22294    ABC_2
> 23421    ABC_2
> Name: prod, dtype: object
> 
> ipdb> data.dtype
> dtype('O')
> 
> ipdb> data.iat[0]
> 'ABC_2'
> 

My lib versions:

> fastparquet               0.1.0                    py27_2    conda-forge
> dask                      0.15.0                   py27_0    conda-forge
>

**Comment by martindurant** [comment]
In fact, UTF8 encoding is appropriate for `unicode` type, not `str` (which are known in python3 as `bytes`). If fastparquet is guessing the former when you have the latter, then either you have mixed types, or the guessing code is incorrect. In any case, you can always specify with the `object_encoding` parameter ("bytes" in this case).

**Comment by xwang777** [comment]
As you suggested, adding the object_encoding arg to to_parquet solved it:
`ddf.to_parquet('/tmp/tmerge1', object_encoding=dict(sess_key='bytes', prod='bytes'))`

This is much more convenient that my current workaround of wrapping around all str inside unicode(..) before inserting to DataFrame. Thanks.
