### ISSUE TITLE
write - object_encoding error

### ISSUE THREAD

**Issue by yiga2** [dask/fastparquet#192]
I have a perfectly normal df (input fwf is fine and to_csv looks ok too) that does not render well in parquet, at least when querying with Drill. The object fields show as byte-arrays, not string.

Tried the writer object_encoding arg='utf8' but it errors out:
`...\writer.py", line 275, in encode_plain
    out = convert(data, se)`
  `...\writer.py", line 168, in convert
    out = array_encode_utf8(data)`
  `File "fastparquet/speedups.pyx", line 60, in fastparquet.speedups.array_encode_utf8 (fastparquet/speedups.c:2297)
    result[i] = PyUnicode_AsUTF8String(arr[i])`
**`TypeError: bad argument type for built-in operation`**

No error when using the same on the read_csv generated df.
What are the condition(s) for the error & are these related to the issue ?

**Comment by martindurant** [comment]
I'm sorry, I do not understand.
You are showing an error, which seems to say that you are trying to encode a column which is bytes using utf8, i.e., as if it were (unicode) strings.
Also you say that, despite the error, you can query the output with Drill, but that you see byte-arrays. 
Is the dataframe column data in fact bytes or (unicode) strings? I can see some possibilities:
- your data is in fact bytes, so you may as well use `object_encoding='bytes'`, and cast in Drill, if you wish
- your data is in fact (unicode) strings, in which case you need `object_encoding='utf8'` and don't need to do anything in Drill
- your data is mixed, which is causing the object_encoding infer to get confused and results in an error; decide which you want, and use Pandas methods to ensure you get it
- your data is bytes, but you really wish it were strings; use `df[col] = df[col].str.decode('utf8')`. Note that the conversion takes time, and the storage is in bytes anyway, but the metadata changes to make sure Drill knows the data should be interpreted as encoded strings.

**Comment by yiga2** [comment]
Thanks @martindurant. I have turned writing the attached script to test several scenarios. It seems that if I specifying the right encoding arg in read_csv **and** always 'utf8' to fp writer, all is good.
Looking at the result, it makes all sense now ! (kinda)
Maybe the 'bad argument type for built-in operation' could be more explicit.

[encoding_test.zip](https://github.com/dask/fastparquet/files/1229349/encoding_test.zip)

**Comment by martindurant** [comment]
OK, I'll close this.
Note that the default for `object_encoding` is `'infer'` rather than `None`, which I think should have guessed the right thing to do in a number of your error cases.
