### ISSUE TITLE
Partitioning without subdir

### ISSUE THREAD

**Issue by yiga2** [dask/fastparquet#194]
fastparket writer creates a directory structure as Drill 1.0 and earlier - requiring views, file organization,..
Drill 1.1.0 creates separate files but not separate directories when partitioning. 
[https://drill.apache.org/docs/how-to-partition-data/](url)
The benefit of that new 'structure' is that all partitions reside in one place and one can use the partition columns in select/where directly.

Is there any plan to support such structure e.g. new file_scheme option ?
Is there a standard (multiple?) on Parquet partitioning ? Not explicit on Parquet's website

**Comment by martindurant** [comment]
That is quite a clever partitioning scheme, I had not heard of it before. It has advantages as you suggest, but there is a clear disadvantage that the partitioned column data must still reside in each file (although it will compress very efficiently if all the values are the same).
At the moment, the splitting into files part is implemented in fastparquet, e.g., 

    fastparquet.write('outdir.parq', df, file_scheme='hive')  # or 'drill' - without partitioning

will write multiple files to the directory, chunked by a certain number of rows per file.

So you could work around this currently by sorting your data on the desired column, finding the rows where the value breaks in that column are, and passing them to the `row_group_offsets` parameter. I am unsure if a groupby method would be more efficient, but that would need more code, I think.

If you find a satisfactory way to accomplish those steps, it can be folded into fastparquet pretty easily (PR welcome!).

**Comment by yiga2** [comment]
I like to keep the partitioned columns inside the file to keep dataset integrity (=same as source) and identity. There is indeed no way to tell using current partitioning (not Drill 1.1) what the groupby values were, just by looking at the file content. Including that info in the filename would be a workaround. (why not in parquet file itself, in the metadata section ?!)

At the other hand, I just tested Drill's partitioning and unless you review the metadata, you cannot tell easily what groupby's the file relate to as the files get a sequence number - say I want to move very old data to cold storage or copy specific year/month data files.

For getting where I like to be, that is, 
- files partitioned by year & month (for performance),
- named like table_YYMM (for easy identification and clustering).
- containing the partitioned columns (to leverage legacy queries),
I have 2 hands-on options:
1. use Drill: query dataset and add dir0 (year) and dir1 (month) values in CTAS to a new set of partitioned files --> a no go as it failed on memory error, despite 32G of direct memory... (a common problem it seems)
2. using fastparquet: fp created the files to start with, one for each yr/month so my plan is to read them back to dataframe, add year and month to each (same values per df) and write back to parquet with well-formatted filename

**That brings me to a feature request** in the writer (would have saved me from the above !), 
- new boolean arg to keep the partitioned columns
- change the behavior of file_scheme + groupby combination. groupby should **never** be ignored if explicitly passed, even if scheme is not hive. To me, groupby should still create separate files, either in flat or in subdir structure if hive is specified. For the former, files would be prepended with the groupby values (separated by underscore or custom format in new arg)
**What do you think ?**

Note: I don't like to repurpose row_groups. To your point, it requires more coding (to do what groupby is meant to do) but should best be used to match the underlying FS block size. On that note, the parameter should get the bytes size of chunks instead of row count.
