### ISSUE TITLE
read dataframe with known categories

### ISSUE THREAD

**Issue by sfragosorodrig** [dask/fastparquet#205]
Hey guys,

is there any way of reading a dataframe from parquet with known categories? 

So far I managed to pass a dict indicating the amount of different labels per category but even then, dask reads the parquet file and keeps the categories as unknown..

cheers!

**Comment by martindurant** [comment]
No, this is not currently implemented, see https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L94

**Comment by martindurant** [comment]
You are welcome to post the issue to dask or even propose a PR, but I'll close this here for now.

**Comment by paularmand** [comment]
The code referred to is currently at https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L330

for reference:
 ```
   for cat in categories:
        if cat in meta:
            meta[cat] = pd.Series(pd.Categorical([],
                                                 categories=[UNKNOWN_CATEGORIES]),
                                  index=meta.index)
```

As a workaround you can partition the file on writing:
```
ddf.to_parquet(path, engine = 'fastparquet', partition_on=["my_cat_col_name"])
```
see https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L333 for the relevant code.

test the reading using:
```
ddf2 = dask.dataframe.read_parquet(path, engine = 'fastparquet')
ddf2["my_cat_col_name"].cat.known  # should return True
```
