### ISSUE TITLE
Python2 support?

### ISSUE THREAD

**Issue by jbednar** [dask/fastparquet#21]
I didn't see any python2 package on conda, so I installed with pip, but that doesn't seem to work (with errors suggesting 2/3 issues; see below.)  Should python2 work?

```
$ pip install fastparquet
Collecting fastparquet
  Downloading fastparquet-0.0.1.post2-py2.py3-none-any.whl
Requirement already satisfied: numba in .../anaconda/lib/python2.7/site-packages (from fastparquet)
Requirement already satisfied: numpy in .../anaconda/lib/python2.7/site-packages (from fastparquet)
Requirement already satisfied: pandas in .../anaconda/lib/python2.7/site-packages (from fastparquet)
Collecting thriftpy>=0.3.6 (from fastparquet)
  Downloading thriftpy-0.3.9.tar.gz (208kB)
Requirement already satisfied: llvmlite in .../anaconda/lib/python2.7/site-packages (from numba->fastparquet)
Requirement already satisfied: enum34 in .../anaconda/lib/python2.7/site-packages (from numba->fastparquet)
Requirement already satisfied: singledispatch in .../anaconda/lib/python2.7/site-packages (from numba->fastparquet)
Requirement already satisfied: funcsigs in .../anaconda/lib/python2.7/site-packages (from numba->fastparquet)
Requirement already satisfied: python-dateutil in .../anaconda/lib/python2.7/site-packages (from pandas->fastparquet)
Requirement already satisfied: pytz>=2011k in .../anaconda/lib/python2.7/site-packages (from pandas->fastparquet)
Requirement already satisfied: ply<4.0,>=3.4 in .../anaconda/lib/python2.7/site-packages (from thriftpy>=0.3.6->fastparquet)
Requirement already satisfied: six in .../anaconda/lib/python2.7/site-packages (from singledispatch->numba->fastparquet)
Building wheels for collected packages: thriftpy
  Running setup.py bdist_wheel for thriftpy ... [?25ldone
Stored in directory: .../Library/Caches/pip/wheels/ae/3b/73/082d28b917d2886b1c0d3e0dc6f3ca3919b7e1df519580873b
Successfully built thriftpy
Installing collected packages: thriftpy, fastparquet
Successfully installed fastparquet-0.0.1.post2 thriftpy-0.3.9
$ python
Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import fastparquet as fp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda/lib/python2.7/site-packages/fastparquet/__init__.py", line 15, in <module>
    from .core import read_thrift
  File ".../anaconda/lib/python2.7/site-packages/fastparquet/core.py", line 8, in <module>
    from . import encoding
  File ".../anaconda/lib/python2.7/site-packages/fastparquet/encoding.py", line 205, in <module>
    Numpy8 = numba.jitclass(spec8)(NumpyIO)
  File ".../anaconda/lib/python2.7/site-packages/numba/jitclass/decorators.py", line 27, in wrap
    return register_class_type(cls, spec, types.ClassType, ClassBuilder)
  File ".../anaconda/lib/python2.7/site-packages/numba/jitclass/base.py", line 140, in register_class_type
    _validate_spec(spec)
  File ".../anaconda/lib/python2.7/site-packages/numba/jitclass/base.py", line 108, in _validate_spec
    raise TypeError("spec keys should be strings, got %r" % (k,))
TypeError: spec keys should be strings, got u'data'
>>> 
```

**Comment by martindurant** [comment]
There are a few changes required for py2 compatibility. If this is important to you, it can be the highest priority task.

**Comment by mrocklin** [comment]
@jbednar do you need Python 2 support?  We were hoping to start avoiding maintaining this by default unless someone showed up willing to pay the bill for it.  Maintaining Python2/3 support for data formats can be somewhat costly due to Python 2's management of bytes/str.

**Comment by martindurant** [comment]
I've had a look, and I can get some tests working for py2 in my branch https://github.com/martindurant/fastparquet/tree/py2 , but probably covering all the cases where strings crop up would be annoying.

**Comment by jbednar** [comment]
I do have a client project where we are using python2, but we could conceivably migrate it.  At the moment, I just need to benchmark the read times under different conditions, and if I'm going to make a fair comparison it's hard to be sure about the results if some of the tests have to use Python2 and some Python3.  Currently my castra tests have to use Python2 because the data file isn't portable to Python3, but again I could convert that by exporting to something portable and recreating it using Python3.  So I think for all my own use cases, I can work around it; it's just a pain rather than a showstopper.  But the most important is that I would guess that it might give people pause if they want to store their data in Parquet format, because they would worry that people using Python2 couldn't use it.

**Comment by jbednar** [comment]
In any case, pip should presumably not allow installation on Python2 if it's not supported, and the name of the installation file suggests that Python2 is supported.

**Comment by mrocklin** [comment]
The performance limiting pieces here are not strongly Python version specific.  You'll be much more bound by, say, LLVM version than Python version.  I think that you can probably make the comparison relatively faithfully even if crossing versions.

If you find that Parquet is a good solution then perhaps the client project could pay for some of the work to port `fastparquet` to Python 2?

**Comment by jbednar** [comment]
I'm old, and I don't care how to count how many times I've thought (or my students or collaborators have thought) that they had identified performance improvements or reductions, when in fact they were just being confused by seemingly irrelevant differences in setup that later turned out to be relevant. :-)  So I've learned not to make *any* claims about performance if I'm not sure the two cases really are comparable, which is quite difficult to do between Python2 and Python3 (who knows which library might come into play for each one?).  So while I too guess that Py2/3 doesn't matter in this case, I will always prefer to control it instead.

**Comment by mrocklin** [comment]
As you like.  I just don't think that Python 2 support is as high a priority as some other things.  I would prefer to see us build out a well fleshed out Python 3 solution and then think about Python 2 support, ideally with the financial backing of someone willing to pay for it.

**Comment by mrocklin** [comment]
Just my preference though.  I don't have a good cost metric on what it will take to migrate and maintain.  My guess is that it is non-trivial.

**Comment by jbednar** [comment]
Sure.

**Comment by freshforlife** [comment]
@martindurant  @mrocklin , Is fastparquet compatible with python 2.7.12 at this time or you guys are concentrating on Python 3 ?  I require it for reading parquet files using dask dataframes.

**Comment by martindurant** [comment]
@freshforlife , PR #66 seems to work well, just needs a little cleanup before merging. Feel free to use and comment.

**Comment by freshforlife** [comment]
@martindurant  Thanks !!  Where do I download it from ? pip install seems to work and this version is installed:  fastparquet==0.0.4.post1 , however it gives the above error.

**Comment by martindurant** [comment]
To use that, you would need to clone this repository, checkout the relevant branch and python-install. Pip should be able to install directly from that git branch if you can get the correct syntax. I will be releasing a new version of fastparquet shortly after the PR is merged.
