### ISSUE TITLE
Write Append + Hive Format

### ISSUE THREAD

**Issue by citibeth** [dask/fastparquet#210]
I have the following code:

> first = True
> for filename...
>     chunk = make_dataframe(filename...)
>     fastparquet.write(parquet_fname, chunk, file_scheme='hive', partition_on=['yp', 'idate'], append=not first)
>     first = False
>     

When I run it... the first call to fastparquet.write() produces the file `yp=17/idate=200601/part0.parquet`, as expected.  The next call (and all subsequent) just produces `part1.parquet` in the top-level directory.  Why are these new files not being written in a nested directory, like the first one was?

**Comment by citibeth** [comment]
There's also a problem that the local variable `cats` is unordered; so the partitions can (and do) come out in the wrong order.

**Comment by martindurant** [comment]
Thank you for working on this! If you would like the commit credit, you may submit a PR for merger.
Note that the ParquetFile object has a `sep` attribute, because for remote file-systems (e.g., S3), the separator is not necessarily the local OS one.

**Comment by citibeth** [comment]
So I should use `self.sep` instead of `os.sep`?

>  If you would like the commit credit, you may submit a PR for merger.

Can I pass on that one?  I'm not in an environment that's conducive to such submission.  (One problem is I'm not yet able to run out of my own git-cloned version.  I'm directly editing some version that came with some Conda build.  I've asked our Conda folks to help me out with that).

**Comment by martindurant** [comment]
Does https://github.com/dask/fastparquet/pull/209 repeat this work? In the [current version](https://github.com/dask/fastparquet/blob/master/fastparquet/api.py#L159) there is no absolute reference to `'/'`.

**Comment by citibeth** [comment]
OK... it's clear we need to be running the latest version.  I'll get our Conda folks on the task.
