### ISSUE TITLE
Parallel Writing of Hive Format?

### ISSUE THREAD

**Issue by citibeth** [dask/fastparquet#212]
I would like to:

1. Create a Hive-format Parquet directory
2. Have multiple processes append to it simultaneously.

Is this possible?  If not, can it be?

**Comment by martindurant** [comment]
Have you tried using `dask.dataframe`'s `to_parquet` method? It supports hive-style partitioning. You will get one file (or none) in each directory per dask division. 
Otherwise, it would be tricky to use fastparquet.write directly from multiple processes, because each would over-write the `'_metadata'` files from other processes.

**Comment by citibeth** [comment]
AFAIK, Dask doesn't scale beyond a single machine?  We want to write in parallel from multiple machines.

> Otherwise, it would be tricky to use fastparquet.write directly from multiple processes, because each would over-write the '_metadata' files from other processes.

Thanks for the tip.  It seems that consecutively numbering the `part.X.parquet` files might also be a problem?  (However... in this case, each partition directory would get only one `part.X.parquet` file, so maybe that could be worked around?)

If I can figure out what the _metadata and _common_metadata file need to contain, maybe I can solve this problem by writing the data first, then constructing the metadata at the end?  A kind of map-reduce operation?

[The purpose of this exercise is to get our data in a format that can be read directly, and in parallel, as an Apache Spark dataframe]

**Comment by martindurant** [comment]
You *could* write to totally separate directories, then shuffle the files around and run `merge()`, I suppose.
However dask [certainly can](https://distributed.readthedocs.io/en/latest/) be run distributed across a cluster, and it sounds like it should be your best bet.

**Comment by martindurant** [comment]
@citibeth , I propose to close this issue, I think you should be able to make progress with either `merge` or Dask. If you have trouble with either, feel free to reopen with further details.

**Comment by citibeth** [comment]
Yes, please close.  It looks like it's already resolved in master.  Thank
you for your help.
