### ISSUE TITLE
Docs are misleading re: open_with.

### ISSUE THREAD

**Issue by jperkelens** [dask/fastparquet#214]
The docs specify that the default value for `open_with` is the built in `open` function. This is true, however, if one explicitly passes in the `open` function, the library throws an exception when calling `to_pandas` and `iter_row_groups`. This is because of an inconsistent application of `mode='rb'` in those functions, leading it to try to open the file in `r` mode.

The docs should either make that clear or the code should be changed to consistently read files in `rb` mode. I'm happy to submit a PR fixing this, when you have determined the fix you prefer.

**Comment by martindurant** [comment]
You are quite right, thanks.
The invocation should be `open(fn, 'rb')` to be explicit. This is the assumed value for `default_open` and the `open` of various backends such as s3fs, but not, as you say, built-in `open`.
