### ISSUE TITLE
Does fastparquet need to depend on pytest?

### ISSUE THREAD

**Issue by ceball** [dask/fastparquet#219]
conda packages of fastparquet such as https://anaconda.org/anaconda/fastparquet/ and https://anaconda.org/conda-forge/fastparquet appear to depend on pytest.

I am trying to create an environment that includes fastparquet, but unfortunately I get this:

```
conda env create --file environment.yml python=3.6
Fetching package metadata .................
Solving package specifications: .
[...]
CondaVerificationError: The package for pytest located at C:\Miniconda36-x64\pkgs\pytest-3.0.5-py36_0 appears to be corrupted. The path 'bin/py.test' specified in the package manifest is not a file.
```

I am using windows. 

I'll be able to work around this (e.g. maybe a newer pytest package would not have this problem), and it doesn't seem like fastparquet's fault really, but I was surprised to find that fastparquet depends on pytest. Obviously please feel free to just close this issue because you are entitled to depend on whatever packages you want :)

Note: appears to be the same problem as reported by in https://github.com/conda/conda/issues/5878.

**Comment by martindurant** [comment]
The reason is, that many testing functions depend on fixtures that are defined in the main package for convenience. I suppose it could be otherwise; but, on the other hand, it seems reasonable that anyone installing fastparquet should be able to run the tests without also having to get the source repo.
To your error above, I'm afraid it doesn't mean much to me, sorry.

**Comment by mrocklin** [comment]
Runtime dependence on pytest is odd.  You can still ship tests and have
convenience fixtures within the codebase without adding pytest to your
dependencies.  This just requires that in the course of normal imports of
fastparquet one never imports the testing modules.

**Comment by martindurant** [comment]
I'll look into where this lives and shift it at some point.
