### ISSUE TITLE
Reading parquet file containing categories or fixed-length bytes fails

### ISSUE THREAD

**Issue by philippjfr** [dask/fastparquet#22]
While trying to use dask interface for fastparquet to write some census data to file I think I ran into an issue reading certain dtypes. The data consists of two float64 columns and a column of length one strings. When writing the data to a file there is no error but loading fails if the string column is encoded as either ``S1`` or ``category``:

```python
from dask.dataframe.io.parquet import read_parquet, to_parquet
df = dd.read_hdf('./census_sample.h5',  key='census')
to_parquet('./census.parq/', df)
df = read_parquet('./census.parq/') <- category dtype fails here
df.compute() <- S1 dtype fails here
```

``error: unpack requires a bytes object of length 4``

Using ``object`` as the dtype works fine but is ~6x slower. I've uploaded the data sample [here](http://assets.holoviews.org/census_sample.h5).

**Comment by martindurant** [comment]
Using fastparquet directly seems to work (at least, my local branch) for both category and 1-byte types. I'll investigate further...
```
fastparquet.write('census.parq', df2, file_scheme='hive')
pf = fastparquet.ParquetFile('census.parq')
pf.to_pandas(categories='race')
```

**Comment by philippjfr** [comment]
>Using fastparquet directly seems to work

Can confirm works here too, but reading that with ``dask.dataframe.io.parquet.read_parquet`` gives me the same error.
