### ISSUE TITLE
Does parquet accept pandas dataframe column names starting with underscore?

### ISSUE THREAD

**Issue by apiszcz** [dask/fastparquet#222]
The pandas data frame has 4 fields starting with underscore:
```
        df['_srcfile'] = os.path.basename(csvpath)
        df[['_year', '_month', '_day']] = df.date.str.extract(r'^(?P<_year>\d{4})[-](?P<_month>\d{2})[-](?P<_day>\d{2})',expand=True)
```

When reading the metadata those columns do not appear. All other columns (not starting with '_') are present.
```
        pfn=fastparquet.ParquetFile(parquetdata)
        print(pfn.columns)

```

Note: the _name columns  **show up** in the output of .dtypes

`print(pfn.dtypes)`

Note: I used the _columns as partitions so when I when print opfn.info the _names appear as partitions.

**Comment by martindurant** [comment]
This is as expected: the `columns` attribute gives you the columns contained in the data files themselves, but the `cats` attribute gives you the names and labels associated with directory partitioning. The output dataframe will contain columns from both origins.
