### ISSUE TITLE
Partition/category/filter question?

### ISSUE THREAD

**Issue by apiszcz** [dask/fastparquet#226]
The _ymd attribute is a string YYYY-MM-DD and is set as a partition. 
_ymd is converted to datetime64 in a pandas dataframe.

Is this the following a valid filter to keep 2017-07-28 rows?
`[('_ymd', '>=', '2017-07-27'), ('_ymd', '<=', '2017-07-29')]`

When applied with to_pandas(df,filters=filters) I was expecting 2017-07-28 to be filtered. 
Instead the full input dataframe is returned with no filtering. 

```
Name: _ymd, Length: 6701, dtype: category
Categories (3, datetime64[ns]): [2017-07-26, 2017-07-28, 2017-07-22]
```

**Comment by martindurant** [comment]
If you pass values as strings, then the comparison will be string/lexical, so the result might not be quite what you expected, but the filters are valid. If you want strict numerical/date comparison, you are better off passing datetime or pandas timestamp values for the third tuple element.

**Comment by apiszcz** [comment]
Pandas Timestamp
TypeError: Cannot compare type 'Timestamp' with type 'str'

**Comment by apiszcz** [comment]
Panas Timestamp

```
  File "pandas\_libs\tslib.pyx", line 1080, in pandas._libs.tslib._Timestamp.__richcmp__ (pandas\_libs\tslib.c:20281)
TypeError: Cannot compare type 'Timestamp' with type 'str'
```

**Comment by apiszcz** [comment]
I'm not seeing the behavior in the test/test_read.py

![image](https://user-images.githubusercontent.com/1430861/31054309-30ba258c-a67e-11e7-8518-cec52831d699.png)

**Comment by apiszcz** [comment]
It appears some partition attribute is required. This the correct output.

![image](https://user-images.githubusercontent.com/1430861/31054394-d086fdd2-a67f-11e7-9de4-8748d4bb423c.png)

**Comment by apiszcz** [comment]
This is not what I expect.

![image](https://user-images.githubusercontent.com/1430861/31054413-1395ff1a-a680-11e7-85b2-59b8462c8b88.png)

**Comment by martindurant** [comment]
Filtering seems to produce the right results for me:

```
In [21]: files
Out[21]:
['dates/d=2017-07-22/temp.parq',
 'dates/d=2017-07-26/temp.parq',
 'dates/d=2017-07-28/temp.parq']

In [22]: pf = fastparquet.ParquetFile(files)

In [23]: pf.to_pandas(filters=[('d', '<=', '2017-07-29'), ('d', '>=', '2017-07-27')]).d.unique()
Out[23]:
[2017-07-28]
Categories (1, datetime64[ns]): [2017-07-28]

In [24]: pf.to_pandas(filters=[('d', '<=', pd.to_datetime('2017-07-29')), ('d', '>=', pd.to_datetime('2017-07-27'))
    ...: ]).d.unique()
Out[24]:
[2017-07-28]
Categories (1, datetime64[ns]): [2017-07-28]
```
(I called my partitioning variable `'d'`)

Are you sure you are filtering on a partitioning column? You error to me suggests maybe not; in which case, you should be aware that filtering does not apply row-by-row, but only to exclude row-groups which have *no* data meeting the filters.

**Comment by apiszcz** [comment]
In one of the cases I did not. You example you are using file paths, can
the same filter work on an a string attribute.

Separate test.
If i specify an integer attribute to partition on when I perform the filter
I get the unorderable types error.

**Comment by martindurant** [comment]
I feel we may be miscommunicating - I'm not sure what you mean by "string attribute" in your last comment. There are certainly two types of partition filtering: on the values encoded in the names of directories (which can filter by string or by parsed value, if parsing succeeds), and filtering on column values within the row-groups. In the latter case, again, you only exclude a row group if its max/min metadata is such that *none* of the data within passes the filter.

In the example where you partition on `_srcfile`, you only get one partition, and this partition does contain *some* data which has `lat>2`, therefore that partition is indeed loaded, this appears correct.

**Comment by apiszcz** [comment]
Thank you, I think understand, I see the statistics option.

**Comment by martindurant** [comment]
OK to close this issue?

**Comment by apiszcz** [comment]
Yes,
