### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by apiszcz** [dask/fastparquet#227]
If I use an integer in the filter I get a stack trace about str and int. 
```
filters=[('loni','>',2),('loni','<',100)]
`TypeError: unorderable types: int() >= str()`
```

If i use strings, I get nothing. I think I understand what I am doing is not possible, The filters will not allow one to filter out a range of values since it is not a numeric range for the test, rather it is lexographic. Is that correct? I was hoping to limit the I/O and amount of records loaded with filters. The plan was to create special codes for the row groups (partitions) and range test those codes. It seems I need to perform the 'in' test on a list of matching strings for the code/records of interest.

Out[12] is blank I was hoping to see REC=1 REC=2

![image](https://user-images.githubusercontent.com/1430861/31093551-0f14eb44-a780-11e7-8fc7-ee89d9bf28c4.png)

If the filter ('loni','>',2) is used rows 2,3 are returned, but not 3 since loni starts with a 1.

**Comment by martindurant** [comment]
When you provide strings, the comparison is lexographic: e.g., `'45' > '100'`. This explains why you are seeing no results. 

The example below shows that passing integers does indeed do the right thing, I don't know how this is going wrong for you.

```
In [2]: df = pd.DataFrame({'rec': [1, 2, 3, 4], 'loni': [1, 45, 95, 120]})

In [4]: fastparquet.write('out.parq', df, file_scheme='hive', partition_on=['loni'])

In [5]: pf = fastparquet.ParquetFile('out.parq')

In [6]: pf.to_pandas()
Out[6]:
   rec loni
0    4  120
1    1    1
2    2   45
3    3   95

In [8]: pf.to_pandas(filters=[('loni', '>', 2), ('loni', '<', 100)])
Out[8]:
   rec loni
0    2   45
1    3   95

In [9]: pf.to_pandas(filters=[('loni', '>', '2'), ('loni', '<', '100')])
Out[9]:
Empty DataFrame
Columns: [rec, loni]
Index: []

In [11]: import dask.dataframe as dd

n [13]: dd.read_parquet('out.parq', filters=[('loni', '>', 2), ('loni', '<', 100)]).compute()
Out[13]:
   rec loni
0    2   45
0    3   95
```

**Comment by apiszcz** [comment]
Thank you for validating what I was hoping for, It 'must' be my environment, I will test on another system.

Your example replayed with stack trace.

```
df = pd.DataFrame({'rec': [1, 2, 3, 4], 'loni': [1, 45, 95, 120]})
fastparquet.write('out.parq', df, file_scheme='hive', partition_on=['loni'])
pf = fastparquet.ParquetFile('out.parq')
pf.to_pandas()



rec

loni

0
4 120 

1
1 1 

2
2 45 

3
3 95 




pf.to_pandas(filters=[('loni', '>', 2), ('loni', '<', 100)])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-109-9caec04dee0a> in <module>()
----> 1 pf.to_pandas(filters=[('loni', '>', 2), ('loni', '<', 100)])

C:\g\test\lib\fastparquet\api.py in to_pandas(self, columns, categories, filters, index)
    374         Pandas data-frame
    375         """
--> 376         rgs = self.filter_row_groups(filters)
    377         size = sum(rg.num_rows for rg in rgs)
    378         if index is None:

C:\g\test\lib\fastparquet\api.py in filter_row_groups(self, filters)
    268         Filtered list of row groups
    269         """
--> 270         return [rg for rg in self.row_groups if
    271                 not(filter_out_stats(rg, filters, self.schema)) and
    272                 not(filter_out_cats(rg, filters))]

C:\g\test\lib\fastparquet\api.py in <listcomp>(.0)
    270         return [rg for rg in self.row_groups if
    271                 not(filter_out_stats(rg, filters, self.schema)) and
--> 272                 not(filter_out_cats(rg, filters))]
    273 
    274     def iter_row_groups(self, columns=None, categories=None, filters=[],

C:\g\test\lib\fastparquet\api.py in filter_out_cats(rg, filters, sep)
    703             else:
    704                 v0 = val_to_num(v)
--> 705             out = filter_val(op, val, v0, v0)
    706             if out is True:


C:\g\test\lib\fastparquet\api.py in filter_val(op, val, vmin, vmax)
    730         if op in ['==', '>='] and val > vmax:
    731             return True
--> 732         if op == '>' and val >= vmax:
    733             return True
    734         if op == 'in' and min(val) > vmax:

TypeError: unorderable types: int() >= str()
```

**Comment by martindurant** [comment]
Can you try with the latest fastparquet from the master branch?

**Comment by apiszcz** [comment]
Test on a different system is correct, matches your output, the failing system has the latest numpy 1.13.3 and other very new libraries. Will keep testing now that that we know it should work. Thank you.

**Comment by apiszcz** [comment]
​do you have the conda install line for that ?
yes can try on linux and windows
​

**Comment by martindurant** [comment]
No, the master branch is generally ahead of conda releases. To install, you would conda install fastparquet as normal (from the conda-forge channel) and then execute the following

    pip install git+https://github.com/dask/fastparquet

(you will probably want to do this in a conda environment set up specially for the test)

**Comment by apiszcz** [comment]
Windows Anaconda still fails the test.

See bottom of the install / update, assuming this installed and compiled, I'm guessing the version is still 0.1.2? 
>>> fastparquet.__version__
'0.1.2'

```
(C:\a\a3) C:\Users\apiszcz>pip install git+https://github.com/dask/fastparquet --upgrade
Collecting git+https://github.com/dask/fastparquet
  Cloning https://github.com/dask/fastparquet to c:\users\apiszcz\appdata\local\temp\pip-06lykqub-build
Collecting pandas (from fastparquet==0.1.2)
  Downloading pandas-0.20.3-cp35-cp35m-win_amd64.whl (8.2MB)
    100% |################################| 8.2MB 152kB/s
Collecting numba>=0.28 (from fastparquet==0.1.2)
  Downloading numba-0.35.0-cp35-cp35m-win_amd64.whl (1.4MB)
    100% |################################| 1.5MB 213kB/s
Collecting numpy>=1.11 (from fastparquet==0.1.2)
  Downloading numpy-1.13.3-cp35-none-win_amd64.whl (13.1MB)
    100% |################################| 13.1MB 106kB/s
Requirement already up-to-date: thrift>=0.10.0 in c:\a\a3\lib\site-packages (from fastparquet==0.1.2)
Requirement already up-to-date: six in c:\a\a3\lib\site-packages (from fastparquet==0.1.2)
Collecting cython (from fastparquet==0.1.2)
  Downloading Cython-0.27.1-cp35-cp35m-win_amd64.whl (2.2MB)
    100% |################################| 2.3MB 504kB/s
Collecting python-dateutil>=2 (from pandas->fastparquet==0.1.2)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |################################| 194kB 1.5MB/s
Collecting pytz>=2011k (from pandas->fastparquet==0.1.2)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |################################| 491kB 1.1MB/s
Collecting llvmlite (from numba>=0.28->fastparquet==0.1.2)
  Downloading llvmlite-0.20.0-cp35-cp35m-win_amd64.whl (9.1MB)
    100% |################################| 9.1MB 153kB/s
Installing collected packages: numpy, python-dateutil, pytz, pandas, llvmlite, numba, cython, fastparquet
  Found existing installation: numpy 1.13.1
    Uninstalling numpy-1.13.1:
      Successfully uninstalled numpy-1.13.1
  Found existing installation: python-dateutil 2.5.3
    Uninstalling python-dateutil-2.5.3:
      Successfully uninstalled python-dateutil-2.5.3
  Found existing installation: pytz 2016.6.1
    DEPRECATION: Uninstalling a distutils installed project (pytz) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pytz-2016.6.1:
      Successfully uninstalled pytz-2016.6.1
  Found existing installation: pandas 0.18.1
    Uninstalling pandas-0.18.1:
      Successfully uninstalled pandas-0.18.1
  Found existing installation: llvmlite 0.13.0
    DEPRECATION: Uninstalling a distutils installed project (llvmlite) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling llvmlite-0.13.0:
      Successfully uninstalled llvmlite-0.13.0
  Found existing installation: numba 0.28.1
    Uninstalling numba-0.28.1:
      Successfully uninstalled numba-0.28.1
  Found existing installation: Cython 0.24.1
    Uninstalling Cython-0.24.1:
      Successfully uninstalled Cython-0.24.1
  Found existing installation: fastparquet 0.1.2
    Uninstalling fastparquet-0.1.2:
      Successfully uninstalled fastparquet-0.1.2
  Running setup.py install for fastparquet ... done
Successfully installed cython-0.27.1 fastparquet-0.1.2 llvmlite-0.20.0 numba-0.35.0 numpy-1.13.3 pandas-0.20.3 python-dateutil-2.6.1 pytz-2017.2

(C:\a\a3) C:\Users\apiszcz>python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastparquet
>>> import pandas as pd
>>> #import pdb; pdb.set_trace()
...
>>> df = pd.DataFrame({'rec': [1, 2, 3, 4], 'loni': [1, 45, 95, 120]})
>>> fastparquet.write('out.parq', df, file_scheme='hive', partition_on=['loni'])
>>> pf = fastparquet.ParquetFile('out.parq')
>>> pf.to_pandas()
   rec loni
0    4  120
1    1    1
2    2   45
3    3   95
>>> pf.to_pandas(filters=[('loni', '>', 2), ('loni', '<', 100)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\a\a3\lib\site-packages\fastparquet\api.py", line 381, in to_pandas
    rgs = self.filter_row_groups(filters)
  File "C:\a\a3\lib\site-packages\fastparquet\api.py", line 275, in filter_row_groups
    return [rg for rg in self.row_groups if
  File "C:\a\a3\lib\site-packages\fastparquet\api.py", line 277, in <listcomp>
    not(filter_out_cats(rg, filters))]
  File "C:\a\a3\lib\site-packages\fastparquet\api.py", line 710, in filter_out_cats
    out = filter_val(op, val, v0, v0)
  File "C:\a\a3\lib\site-packages\fastparquet\api.py", line 736, in filter_val
    if op == '>' and val >= vmax:
TypeError: unorderable types: int() >= str()
>>>
```

**Comment by apiszcz** [comment]
fastparquet/api.py:716
```
-> if (op == 'in' and vmax is not None and vmin is not None and
(Pdb) val
2
(Pdb) type(val)
<class 'int'>
(Pdb) op
'>'
(Pdb) type(vmin)
<class 'str'>
(Pdb) type(vmax)
<class 'str'>
```

**Comment by apiszcz** [comment]
POSSIBLE BUG?

I get different results on WINDOWS compared to LINUX!

WINDOWS is definitely NOT an integer!


WINDOWS CODE PATH PRODUCES:
```
> c:\g\test\lib\fastparquet\api.py(713)filter_out_cats()
-> out = filter_val(op, val, v0, v0)
(Pdb) print(v0)
120\part.0.parquet
```

LINUX CODE PATH:
> /home/ap/p/test/lib/a/a3/lib/python3.5/site-packages/fastparquet/api.py(706)filter_out_cats()
-> out = filter_val(op, val, v0, v0)
(Pdb) print(v0)
120

**Comment by martindurant** [comment]
OK, we are getting somewhere!
Can you print the value of `sep`, `s` and `rg.columns[0].file_path`?

**Comment by apiszcz** [comment]
I think i found an issue, a handy try except MASKS the real exception.

```
(Pdb) n
> c:\g\via\lib\fastparquet\util.py(55)val_to_num()
-> try:
(Pdb) ast.literal_eval(x.lstrip('0'))
*** SyntaxError: unexpected character after line continuation character
(Pdb) x
'120\\part.0.parquet'
```

**Comment by martindurant** [comment]
That is expected, for the common case that the label is not an integer. It seems that the wrong path and/or regex is being produced, could you please give the values of the variables I suggested above?

**Comment by apiszcz** [comment]
I did answer your request above

SUSPECT LINE: util.py\ex_from_sep

`s = re.compile(r"([a-zA-Z_0-9]+)=([^\{}]+)".format(sep))`
(Pdb) print(s)
re.compile('([a-zA-Z_0-9]+)=([^\\\\]+)')
UNIX:

(Pdb) print(sep)
/
(Pdb) rg.columns[0].file_path
'loni=120/part.0.parquet'

**Comment by martindurant** [comment]
You *might* be the only one using fastparquet on windows with partitioning on a local disc (this would not be an issue for s3/gcs/azure). :)
Can you try with [this line](https://github.com/dask/fastparquet/blob/master/fastparquet/api.py#L277) replaced by:

    not(filter_out_cats(rg, filters, sep=self.sep))]

**Comment by apiszcz** [comment]
That fixes the issue, thank you, expect this will be in a future release.
BTW: S3 is in the plan.

WINDOWS
```
> py parqtest.py
   rec loni
0    2   45
1    3   95
```

**Comment by martindurant** [comment]
Yes, certainly it will be in the next release. Sorry for all the back-and-forth to figure this out!

**Comment by martindurant** [comment]
Fixed in a60c2dc968a307bb527c7ab7cff2edac7193e2fa

**Comment by apiszcz** [comment]
I'll be providing more feedback as needed concerning windows local file system use.

**Comment by martindurant** [comment]
Perhaps there should be some tests marked for windows only - except we don't actually have any windows CI  right now.

**Comment by apiszcz** [comment]
So now maybe there are other issues:
This works
print(pf.to_pandas(filters=[('loni', '>', 2), ('loni', '<', 100)]))

This fails
ddf.read_parquet(pf, columns=columns, filters=fd['parquetfilter']).compute()
  File "C:\g\via\lib\fastparquet\api.py", line 737, in filter_val
    if op in ['==', '>='] and val > vmax:
TypeError: unorderable types: int() > str()

**Comment by martindurant** [comment]
Exactly the same change is required at https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L65 (here refereed to as `fs.sep`)

**Comment by apiszcz** [comment]
filter_out_cats needs to be replaced by?



    rgs = [rg for rg in pf.row_groups if
           not(fastparquet.api.filter_out_stats(rg, filters, pf.schema)) and
           not (filter_out_cats(rg, filters, sep=self.sep))]



Traceback (most recent call last):
  File "lib\_testdm\testdm.py", line 478, in <module>
    main()
  File "lib\_testdm\testdm.py", line 465, in main
    ovdm.filter(oc,ol,ou,src,modes)
  File "lib\_testdm\testdm.py", line 241, in filter
    df = ddf.read_parquet(pfp, columns=columns, filters=fd['parquetfilter']).compute()
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 291, in read_parquet
    categories=categories, index=index)
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 63, in _read_fastparquet
    rgs = [rg for rg in pf.row_groups if
  File "C:\g\test\lib\dask\dataframe\io\parquet.py", line 65, in <listcomp>
    not (filter_out_cats(rg, filters, sep=self.sep))]
NameError: name 'filter_out_cats' is not defined

**Comment by martindurant** [comment]
`not (fastparquet.api.filter_out_cats(rg, filters, sep=self.sep))]`

**Comment by apiszcz** [comment]
maybe this
not(fastparquet.api.filter_out_cats(rg, filters, sep=fs.sep))]

**Comment by apiszcz** [comment]
Will that change be in future DASK versions, Matt Rocklin aware?

**Comment by apiszcz** [comment]
Success! It works like the documentation !

**Comment by martindurant** [comment]
PR: https://github.com/dask/dask/pull/2739  The dask team reviews these and makes sure they pass tests. Changes will appear in a conda package at the time of the next release (normally within a month).

**Comment by apiszcz** [comment]
Great, I appreciate the help, and should test on LINUX when I run into a DASK/FASTPARQUET issue. I thought I was confused and spent a bit of time on this, as you were tracking. Thank you again.

**Comment by martindurant** [comment]
Well dask *is* tested on windows too, so at least there's a little extra protection there.

**Comment by apiszcz** [comment]
Perhaps a local file system test is needed for the Windows regime.
