### ISSUE TITLE
write append behavior failing on Windows, incorrectly detecting 'drill' when it is 'hive'

### ISSUE THREAD

**Issue by apiszcz** [dask/fastparquet#228]
The output folder is empty on start in this example. File1 is stored with APPEND set to FALSE, File 2 inserts with append set to True, the third file is stating file scheme is not set? Debugging writer.py indicates the scheme is 'drill'?  I have not changed the file scheme. I am now a bit wobbly with windows and the 'sep' value, see get_file_scheme at bottom, do we have an issue here?

        PFWrite(dstpath,
                df,
                file_scheme='hive',
                partition_on=['_lati','_loni','_ymd'],
                compression='SNAPPY',
                append=appendflag)

```
2017-10-04T05:11:45.803567> TASK_FT0001 EncodeParquet  0/81 INPUT: f1.csv
APPEND False

2017-10-04T05:11:46.470039> TASK_FT0001 EncodeParquet  1/81 INPUT: f2.csv
APPEND True

2017-10-04T05:11:46.732225> TASK_FT0001 EncodeParquet  2/81 INPUT: f3.csv
APPEND True
Traceback (most recent call last):
  File "lib\_testdm\testdm.py", line 495, in <module>
    main()
  File "lib\_testdm\testdm.py", line 474, in main
    ovdm.run(oc, ol, ou, modes, src)
  File "lib\_testdm\testdm.py", line 373, in run
    self.encode_parquet(oc,ol,ou,src,csvsrc,dstpath,appendflag)
  File "lib\_testdm\testdm.py", line 144, in encode_parquet
    append=appendflag)
  File "C:\g\test\lib\fastparquet\writer.py", line 808, in write
    'existing file scheme is not.' % file_scheme)
ValueError: Requested file scheme is hive, but existing file scheme is not.
```

```
(Pdb) pf.file_scheme
'hive'
(Pdb) c
2017-10-04T05:17:29.232713> TASK_FT0001 EncodeParquet: 31.00 seconds
2017-10-04T05:17:29.233705> TASK_FT0001 EncodeParquet  2/81 INPUT: f3.csv
APPEND True
> c:\g\test\lib\fastparquet\writer.py(807)write()
-> if pf.file_scheme not in ['hive', 'empty', 'flat']:
(Pdb) pf.file_scheme
'drill'
```

util.py:get_file_scheme
```
    s = ex_from_sep(sep)
    dirs = [p.rsplit(sep, 1)[0] for p in paths]
    matches = [s.findall(d) for d in dirs]
    if all(len(m) == (l - 1) for (m, l) in
           zip(matches, lens)):
        keys = (tuple(m[0] for m in parts) for parts in matches)
        if len(set(keys)) == 1:
            return 'hive'
    return 'drill'
```

**Comment by martindurant** [comment]
It seems like we may have more problems with windows paths. I am not certain what to do about it, since the paths written into the metafile ought to be portable between systems. Do you know what spark or drill produces on windows (when metadata creation is enabled)?

**Comment by apiszcz** [comment]
I am using the hive option, the zip of out.par is attached, does that help?

```
import sys
sys.path.append('lib')
import fastparquet
import pandas as pd

df = pd.DataFrame({'rec': [1, 2, 3, 4], 'loni': [1, 45, 95, 120]})
fastparquet.write('out.parq', df, file_scheme='hive', partition_on=['loni'])
pf = fastparquet.ParquetFile('out.parq')
pf.to_pandas()
print(pf.to_pandas(filters=[('loni', '>', 2), ('loni', '<', 100)]))
```


[out.parq.zip](https://github.com/dask/fastparquet/files/1356161/out.parq.zip)

**Comment by martindurant** [comment]
Does the data written so far read back OK?

**Comment by martindurant** [comment]
OK, OK - it seems that windows python is totally fine using posix-style paths (with separator `'/'`), so it is probably a mistake to use `os.sep` **at all**, and instead should stick to paths with `'/'` in all cases except the initial path(s) input. In that location *if* os.sep == '\\' and *if* that sep appears in what was passed, we should do a conversion`'/'.join(path.split('\\'))`. What do you think?

**Comment by apiszcz** [comment]
I'm willing to test, I'm not locating if os.sep=='\', do you have a file/line#?

These two items return nothing
```
$ grep -rn "os.sep ==" *.py
$ grep -rn "if os.sep" *.py
```

FYSA: os.path.abspath 'normalizes' the separator for the os.. probably not what we need, however it does set the '/' to '\' for windows.





```
api.py:41:    sep: string [`os.sep`]
api.py:81:                 sep=os.sep, root=False):
core.py:280:                        sep=os.sep, scheme='hive'):
core.py:327:                   sep=os.sep, scheme='hive'):
test/util.py:20:        path = os.sep.join([TEST_DATA, 'split', 'cat=' + cat,
util.py:29:        return os.sep
util.py:168:def analyse_paths(file_list, sep=os.sep, root=False):

```

**Comment by martindurant** [comment]
There is no such line yet, I am proposing it as a possible solution: not to store any windows-style paths in parquet, always convert user-inputted paths at earliest opportunity.

**Comment by apiszcz** [comment]
Ah, ok. explicit conversion to backslash options may be worth reviewing. 

Your suggestion seems reasonable, however will these be worth reviewing?

os.normpath and os.path.abspath 

https://stackoverflow.com/questions/16010992/how-to-use-directory-separator-in-both-linux-and-windows
This is IMO the best answer to the question as it was phrased, "how to use “/” (directory separator) in both Linux and Windows". And it's also eminently useful -- I'd much rather do os.path.normpath('a/b/c/d/file.ext') than os.path.join('a','b','c','d','file.ext') when I need to specify a long path. – ukrutt Aug 17 '16 at 15:26

**Comment by apiszcz** [comment]
MORE mystery, sometimes I can properly store 6 to 80 files other times I get that error. Not sure what may cause non-deterministic behavior when nothing changes on the code side.

**Comment by apiszcz** [comment]
Commenting out writer.py:806/7/8, I get another error from line 866, in partition_on_columns which ends up fairly out in pandas generic and then groupby.py.

**Comment by martindurant** [comment]
Bear with me, I'll make a PR with windows path evasion as described above. It might take me a couple of days to get to.

**Comment by apiszcz** [comment]
NP, please bear with me, there is  more to this story, I just ran tests on two different systems, and if I pause/wait between writes it updates fine. No issues. If i put the updates in a for loop to process a lot of files it always file on file 3. I will try some sleep delays and see what that shows.

```
df = pd.DataFrame({'rec': [1, 2, 3, 4], 'lati': [1, 45, 95, 120],'loni': [1, 45, 95, 120]})
fastparquet.write(r'C:\x\out_parq', df, file_scheme='hive',
                  compression='SNAPPY',partition_on=['lati','loni'],append=False)

df = pd.DataFrame({'rec': [5,6,7,8], 'lati': [1, 45, 95, 120],'loni': [22,33,44,55]})
fastparquet.write(r'C:\x\out_parq', df, file_scheme='hive',
                  compression='SNAPPY',partition_on=['lati','loni'],append=True)

df = pd.DataFrame({'rec': [9,10,11,12], 'lati': [1, 45, 95, 120],'loni': [88,77,66,55]})
fastparquet.write(r'C:\x\out_parq', df, file_scheme='hive',
                  compression='SNAPPY',partition_on=['lati','loni'],append=True)
```

**Comment by martindurant** [comment]
In that case, possibly you are having disc latency problems: append requires reading the metadata file that has just been written, perhaps in some instances it isn't flushed in time?

**Comment by apiszcz** [comment]
Perhaps.

System 1: SSD
System 2: SAN

both systems fail in the same way. I put a time.sleep(10.0) in and all is happy. I'll reduce delay and eventually find a sweet spot.

**Comment by apiszcz** [comment]
Another observation.
When creating the parquet data set with 'hive' no errors. Then when it is opened and read operations are submitted I get errors, and metadata is showing the partitions to be dir0,dir1,dir... which indicates 'drill' format. If I increase the delay between writes from 1 to 5 seconds on the SSD, Everything is correct, partition_on has correct 'hive' names and no errors on read.

**Comment by apiszcz** [comment]
Observation, I created a synthetic data generator, easier to test performance topics, looks like I'm seeing about 111,000 rows/sec for encoding 1 million rows with ~20 attributes, into the parquet hive format on a windows 10 local file system to an SSD.

**Comment by apiszcz** [comment]
Here is a sample  that should cause the error on Windows.

```
import pandas as pd
import fastparquet
import numpy as np

append=False
for idx,loop in enumerate(range(10)):
    if idx>0: append=True
    print(loop,append)
    df = pd.DataFrame({'rec': np.arange(0.0,10000.0,1), '_loni': np.arange(0,10000,1), '_lati': np.arange(0,10000,1)})
    fastparquet.write(r'C:\x\out_parq2',df,file_scheme='hive',compression='SNAPPY',partition_on=['_loni','_lati'],append=append)
```

**Comment by apiszcz** [comment]
Another test, using a RAMDISK, same failure.

**Comment by apiszcz** [comment]
util.py:get_file_scheme
FAILURE happens when we get a length other than 1, so the 'set here will produce length 2 causing it to fail the conditional test for hive and return 'drill'

(Pdb) set(keys) {('_lati', '_loni', '_ymd'), ('_loni', '_lati', '_ymd')}

**Comment by martindurant** [comment]
How does the directory structure look at the time when you snapshot, above? Seems like the labels have been reversed.

**Comment by apiszcz** [comment]
R:\__TEST\PARQUETDATA
├───_lati=0
│   ├───_loni=51
│   │   └───_ymd=19700101
│   └───_loni=94
│       └───_ymd=19700101
├───_lati=1
│   └───_loni=48
│       └───_ymd=19700101
├───_lati=11
│   ├───_loni=16
│   │   └───_ymd=19700101
│   └───_loni=41

**Comment by martindurant** [comment]
Yet sometimes apparently it sees ('_loni', '_lati', '_ymd'), i.e., the order is incorrect

**Comment by apiszcz** [comment]
Here it is correct and still fails,

```
(Pdb) set(keys)
{('_lati', '_loni', '_ymd')}
(Pdb) c
LENGTH OF SET KEYS: 0
Traceback (most recent call last):
  File "lib\_viadm\viadm.py", line 581, in <module>
    main()
  File "lib\_viadm\viadm.py", line 564, in main
    ovdm.run(oc, ol, ou, modes, src)
  File "lib\_viadm\viadm.py", line 457, in run
    self.encode_parquet(oc,ol,ou,src,csvsrc,dstpath,appendflag)
  File "lib\_viadm\viadm.py", line 201, in encode_parquet
    append=appendflag)
  File "C:\g\via\lib\fastparquet\writer.py", line 810, in write
    'existing file scheme is not.' % file_scheme)
ValueError: Requested file scheme is hive, but existing file scheme is not.
```

**Comment by apiszcz** [comment]
reversal observation

```
    s = ex_from_sep(sep)
    dirs = [p.rsplit(sep, 1)[0] for p in paths]
    matches = [s.findall(d) for d in dirs]
    from pprint import pprint as pp
    pp(matches) 

```
[('_lati', '20'), ('_loni', '57'), ('_ymd', '19700101')],
 [('_lati', '4'), ('_loni', '43'), ('_ymd', '19700101')],
 [('_lati', '12'), ('_loni', '60'), ('_ymd', '19700101')],
 [('_lati', '14'), ('_loni', '0'), ('_ymd', '19700101')],
 [('_ymd', '19700101'), ('_loni', '57'), ('_lati', '4')],
 [('_ymd', '19700101'), ('_loni', '12'), ('_lati', '90')],
 [('_ymd', '19700101'), ('_loni', '19'), ('_lati', '48')],
 [('_ymd', '19700101'), ('_loni', '82'), ('_lati', '14')],

**Comment by apiszcz** [comment]
This is at thrift_structures.py:write_thrift
the slash issue is interesting, however pout.__dict__ has the items reversed, 

File 0  correct, next is flipped
```
{'state': 0, '_TCompactProtocol__last_fid': 0, 'trans': <_io.BufferedWriter name='R:/__test/parquetdata\\_lati=6\\_loni=37\\_ymd=19700101\\part.0.parquet'>, '_fast_encode': <built-in function encode_compact>, '_fast_decode': <built-in function decode_compact>, '_TCompactProtocol__bool_value': None, '_TCompactProtocol__bool_fid': None, 'container_length_limit': None, '_TCompactProtocol__structs': [], '_TCompactProtocol__containers': [], 'string_length_limit': None}
```

File 1 reverse order
`{'state': 0, '_TCompactProtocol__last_fid': 0, 'trans': <_io.BufferedWriter name='R:/__test/parquetdata\\_ymd=19700101\\_loni=38\\_lati=25\\part.1.parquet'>, '_fast_encode': <built-in function encode_compact>, '_fast_decode': <built-in function decode_compact>, '_TCompactProtocol__bool_value': None, '_TCompactProtocol__bool_fid': None, 'container_length_limit': None, '_TCompactProtocol__structs': [], '_TCompactProtocol__containers': [], 'string_length_limit': None}`

**Comment by martindurant** [comment]
Aha! https://github.com/dask/fastparquet/blob/master/fastparquet/writer.py#L811
This resets `partition_on` to what is found for the existing data; but `cats` is a dictionary, and so fundamentally unordered. It *could* (and maybe should) be ordered, but actually there's no real reason to do this, instead it should just ensure that the `partition_on` passed is compatible with what exists:

```
if set(partition_on) != set(pf.cats):
    raise ValueError('When appending must partition with same fields as existing data')
```

**Comment by martindurant** [comment]
But even if that fixes things for you, I still need to work on the paths, since writing windows-style paths into the metadata will make the dataset non-portable.

**Comment by apiszcz** [comment]
I'm watching the behavior, it is definitely creating random level 0 partitions lati, then loni, and ymd.
Will review your recent comment.

**Comment by apiszcz** [comment]
That change works for this current use case. I ran 20 trials, no errors.

```
#partition_on = list(pf.cats)
if set(partition_on) != set(pf.cats):
    raise ValueError('When appending, partitioning columns must match existing data')
```

**Comment by apiszcz** [comment]
I'll need the command for the pip/conda pull compile. for the latest update when ready
