### ISSUE TITLE
date can not be serialized

### ISSUE THREAD

**Issue by shantanuo** [dask/fastparquet#230]
I am getting an error while trying to save the dataframe as a file.

from fastparquet import write 
write('profile_dtl.parq', df)

The error is related to "date" and the error message looks like this...

ValueError: Can't infer object conversion type: 0    1990-01-01
1    1954-01-01
2    1981-11-15
3    1993-01-21
4    1948-01-01
5    1977-01-01
6    1968-04-28
7    1969-01-01
8    1989-01-01
9    1985-01-01
Name: dob, dtype: object

I have checked that the column is "object" just like any other column that can be serialized without any problem. If I remove the "dob" column from the dataframe, then this line will work. This will also work if there is date+time.

Only dates are not accepted by fast-parquet?

**Comment by martindurant** [comment]
What type is each individual element of the column?
To successfully write, you should probably convert to a datetime column, e.g., `pd.to_datetime` or `.astype('datetime64')`.

**Comment by shantanuo** [comment]
Since this is "date of birth" I will prefer not to add time. Why doesn't it consider this as "text string" and save to disk?

**Comment by martindurant** [comment]
Is it, in fact a text string? You can do `.as_type(str)` or `.as_type(bytes)`.

There is a simple date-type in the parquet spec, but then your values would come back as datetimes anyway.

**Comment by shantanuo** [comment]
ok. I used .astype('datetime64') and it worked. 
fastparquet is awesome, by the way.

**Comment by martindurant** [comment]
Thank you!

**Comment by sephib** [comment]
Hi,
I had a similar problem - the solution that worked for me was to convert the column to str as follows:
`df[col].dt.date.astype(str)`
