### ISSUE TITLE
Can't infer object conversion type

### ISSUE THREAD

**Issue by ugjackal** [dask/fastparquet#238]
I ran into this problem with fastparquet 1.3.   It seems to recognize integer elements in a pandas dataframe as objects.

   pwrite(path, data, open_with=s3_open, compression='GZIP', append=False, has_nulls=True)
  File "E:\p4vw2\lyengine\branches\CloudCanvasDev\dev\Tools\Python\2.7.12\windows\lib\site-packages\fastparquet\writer.py", line 784, in write
    times=times, index_cols=index_cols)
  File "E:\p4vw2\lyengine\branches\CloudCanvasDev\dev\Tools\Python\2.7.12\windows\lib\site-packages\fastparquet\writer.py", line 645, in make_metadata
    object_encoding=oencoding, times=times)
  File "E:\p4vw2\lyengine\branches\CloudCanvasDev\dev\Tools\Python\2.7.12\windows\lib\site-packages\fastparquet\writer.py", line 91, in find_type
    object_encoding = infer_object_encoding(data)
  File "E:\p4vw2\lyengine\branches\CloudCanvasDev\dev\Tools\Python\2.7.12\windows\lib\site-packages\fastparquet\writer.py", line 224, in infer_object_encoding
    raise ValueError("Can't infer object conversion type: %s" % head)
ValueError: Can't infer object conversion type: 0     97
1    230
2    330
3    350
4    448
5     49
6    135
7    154
8    199
9    268
Name: seqno, dtype: object

Code:

write(path, data, open_with=s3_open, compression='GZIP', append=False, has_nulls=True)    

Dataset example:
                                    msgid pltf seqno     srv_tmutc  \
0    b21f734b-b04f-11e7-853f-80a589a029d3  OSX    51  1.507925e+09
1    b287f914-b04f-11e7-9dcf-80a589a029d3  OSX   148  1.507925e+09
2    b2ab117a-b04f-11e7-b1a0-80a589a029d3  OSX   184  1.507925e+09
3    b2ed4a92-b04f-11e7-af69-80a589a029d3  OSX   247  1.507925e+09
4    b2f8bc44-b04f-11e7-a3e6-80a589a029d3  OSX   258  1.507925e+09
5    b30120b9-b04f-11e7-a407-80a589a029d3  OSX   266  1.507925e+09
6    b321a107-b04f-11e7-86c9-80a589a029d3  OSX   297  1.507925e+09
7    b340c1c6-b04f-11e7-b839-80a589a029d3  OSX   322  1.507925e+09
8    b39c2836-b04f-11e7-b454-80a589a029d3  OSX   407  1.507925e+09
9    b3b6dc21-b04f-11e7-a6fd-80a589a029d3  OSX   431  1.507925e+09
10   b3eba7cc-b04f-11e7-ae06-80a589a029d3  OSX   452  1.507925e+09
11   b4008f5f-b04f-11e7-b807-80a589a029d3  OSX   463  1.507925e+09
12   b205d0c1-b04f-11e7-aa26-80a589a029d3  OSX    20  1.507925e+09
13   b2465c40-b04f-11e7-bfa6-80a589a029d3  OSX    80  1.507925e+09
14   b24f35d3-b04f-11e7-915b-80a589a029d3  OSX    89  1.507925e+09
15   b2749829-b04f-11e7-b322-80a589a029d3  OSX   124  1.507925e+09
16   b286245f-b04f-11e7-b9b1-80a589a029d3  OSX   143  1.507925e+09
17   b2ad5b6b-b04f-11e7-81ad-80a589a029d3  OSX   183  1.507925e+09
18   b2f4ebaf-b04f-11e7-8ca4-80a589a029d3  OSX   251  1.507925e+09
19   b3134925-b04f-11e7-80fc-80a589a029d3  OSX   280  1.507925e+09
20   b37bcef6-b04f-11e7-98dd-80a589a029d3  OSX   374  1.507925e+09
21   b394d540-b04f-11e7-aef3-80a589a029d3  OSX   397  1.507925e+09
22   b3ec1cf2-b04f-11e7-a853-80a589a029d3  OSX   449  1.507925e+09

**Comment by martindurant** [comment]
What is the actual dtype of the column seqno?

**Comment by ugjackal** [comment]
The dataframe has it labelled as a dtype: object.

csv_data = pd.read_csv(StringIO(body),sep=",", encoding="utf-8")
for row in csv_data.itertuples(index=True): 
   df= pd.DataFrame([row], columns=columns) 
   df.append([row],ignore_index=True)

**Comment by martindurant** [comment]
Building your dataframe iteratively like that might not be such a good idea, partly because of the strange dtypes you can get out of it. Also it will be much slower.
The integer types in pandas don't support NULL values, and generally columns are coerced to floats, which have NaN as a placeholder. You can have columns like [1, 2, None, 3] type object if you want. In that case you can have ANY kinds of objects in there, and that might well be what is confusing fastparquet.
I would first recommend to cast your column to int or float:

    data['seqno'] = data['seqno'].astype(int)
    or
    data['seqno'] = data['seqno'].astype(int)

or you can try to explicitly pass `object_encoding={'seqno': 'int'}` to the `write` function.
