### ISSUE TITLE
Not Implemented error

### ISSUE THREAD

**Issue by shantanuo** [dask/fastparquet#242]
When I try to read from a parquet file, I get an index because the original dataframe used multi-index.

df= ParquetFile('df.parq').to_pandas()

NotImplementedError: multi-index not yet supported, use index=False

**Comment by martindurant** [comment]
Have you tried

    df = ParquetFile('df.parq').to_pandas(index=False)

?

**Comment by shantanuo** [comment]
That worked. Thanks.
