### ISSUE TITLE
ImportError: No module named fastparquet

### ISSUE THREAD

**Issue by dreyco676** [dask/fastparquet#243]
Hey all,

I've tried all three options for installing fastparquet to no avail. I'm in a conda environment on a REHL machine and can see it installed under `conda list`
![capture](https://user-images.githubusercontent.com/7094791/31910592-955e6106-b803-11e7-88dc-e76c90f5efb3.PNG)

Did something in the documentation change? I'm only trying `from fastparquet import write`

**Comment by dreyco676** [comment]
I guess the nuclear option of blowing up my conda environment resolved it!

**Comment by jsrobin888** [comment]
still having the same issue...

how did you solve it

**Comment by martindurant** [comment]
@jsrobin888 , how did you install, what exact import command are you using, and what exact error do you see? The first thing to check is probably your paths.
