### ISSUE TITLE
Adding new column to existing parquet file.

### ISSUE THREAD

**Issue by Thomas-Z** [dask/fastparquet#244]
It's not really an issue but I could not find a better place to ask.

I read somewhere that the parquet format did allow to add new column to existing parquet files.
I'm not sure that's the only place I read it but a mention can be found on [wikipedia](https://en.wikipedia.org/wiki/Apache_Parquet).

> Apache Parquet supports limited schema evolution where the schema can be modified according to the changes in the data. It also provides the ability to add new columns at the end of the file structure

From what I can see the only way to add a new column with fastparquet (and, in fact, with any other api) is to load the full file, add the new column to the dataframe and write it back. A really expensive process.
I understand that parquet file are not really supposed to be updated but are there any schema evolution supported with fastparquet ?

The workflow I'm interested in something like this :

1. create an initial parquet file with some time indexed "input" columns
2. create additional column by applying algorithms on a selection of input (or previously created) columns (can happen many times and require a lot of computing power) using the same time index
3. read a selection of data using filters and plot them in many different ways (that's the most common use case)
4. rerun improved version of algorithms from time to time (requiring to delete an existing column and recalculate it)

Parquet, Fastparquet and Dask seemed like a good solution to me but I might be wrong.

Steps 2 and 4 requires to write data and I'm not sure how I should do this.

The sample I'm using for my tests are 40Hz data with 275 columns (essentially float but some lists too).
I divided my data by day (directory), each day by hour (144.000 values by parquet file) and each hour is divided in 10 row groups in order to have an efficient filtering when using metadata.
This division is probably not optimal but I'm good with it for now.

My first thought was to use separated files for newly created variable and consolidate in one file later.
Have something like :
 - file_123_hour0.parquet
 - file_123_hour0_newColumns.parquet
 - file_123_hour1.parquet
 - file_123_hour1_newColumns.parquet
 - file_123_hour2.parquet
 - file_123_hour2_newColumns.parquet
 - ...

I could manage to do this manually but fastparquet can't handle parquet files with different schema and I would lose the filtering possibilities and easy to use features offered by fastparquet.
I cannot create metadata for my directories using fp.writer.merge(*.parquet) or read the full data for 1 hour using fp.ParquetFile(['file_123_hour0.parquet', 'file_123_hour0_newColumns.parquet'])

So, my main questions are :
 - is parquet the solution I'm looking for ?
 - could I expect writer.merge() and ParquetFile() functions to be able to handle such partitioned data in a near future ?
 - Any ideas ?

On another topic :
 - what are the limitation of writer.merge() ?

It seems to be memory limited when merging a large number of files.
I can create metadata for each day sub-directory but once I reach 15 or 20 days and try to merge together every parquet files in every sub-directory it will consume my limited 8 GB of RAM and never end.

Thanks and regards,
Thomas

**Comment by martindurant** [comment]
Schema evolution does not mean adding columns into existing parquet files, but adding whole new files to a parquet data collection, where the later files can contain new columns. Fastparquet does **not** support this. You can, of course, create data files however you like, if you intend them to be read by some third party framework that supports evolution.

I can't really think of a data storage mechanism that supports what you are after, but does not involve at some point reading and rewriting all of the data you have so far.

**Comment by Thomas-Z** [comment]
Would it make sense for Fastparquet to support the addition of new files to a parquet data collection (with different but compatible/complementary schema) ?
If yes, do you think it could be easily done (I'm not asking you to do it, just wondering) ?

You did not answer my question about the limitation of writer.merge().
As I see it, "global" metadata are useful when there is a huge quantity of files but it seems like writer.merge() can't handle this amount of files.

Thanks for your feedback. and regards,
Thomas

**Comment by martindurant** [comment]
It might make sense to support files with compatible but different schema. I imagine it would be a reasonably challenging task, as every reading method needs to care about not just the storage format but the required in-memory output format too.

You may just be the best person to evaluate the limits on merge() - the produced file-size and memory usage should grow linearly as Ncolumns*Nrow-groups. The implementation of thrift that fastparquet uses does not allow for streaming of thrift objects, it is always encoded/decoded in one step.

**Comment by fl2o** [comment]
@Thomas-Z Did you find a solution to your problem ? i am looking for the same functionnality (ie: add columns to existing parquet file(s) without rewriting all while still being able to use the filter / partitions)

**Comment by martindurant** [comment]
In retrospect, I do suppose it is technically feasible to append columns to an existing parquet file, but that would require development, and I don't believe there is much appetite for it, as it does not match typical parquet usage.

**Comment by fl2o** [comment]
A typical use case for "adding columns" is feature engineering workflows.
That would have been very convenient!

**Comment by martindurant** [comment]
I understand your purpose, but I don't think it's very common. Parquet has become both intermediary store and archive, but not mutable storage.
Have you tried simply saving new parquet datasets for the new columns?

**Comment by fl2o** [comment]
Yes, this is what I end up doing.
I posted an issue in dask about it ^^
Anyway, thank you for the good library!

**Comment by xhochy** [comment]
The normal workflow for this is to read a Parquet file, apply all necessary transformations and store the result in a new file. You could extend the writer to do magic things for in-place modifications but normally the benefits of having immutable file and storage being cheap outweighs the benefit of not duplicating the file.

**Comment by fl2o** [comment]
Thank you @xhochy @martindurant 
I will work this way then :)

But it raises a new issue, I posted it on dask "dask groupby apply give weird indexes
#3361" but it might be because of fastparquet indexing?

**Comment by skanskan** [comment]
Is it still not possible to append new columns with Parquet?
What other alternative file formats do we have able to do it?

**Comment by martindurant** [comment]
The format itself does not allow for this kind of operation in any obvious way beyond the discussion above. I am not aware of any columnar data format that would allow for efficient appendage of columns.

**Comment by skanskan** [comment]
> The format itself does not allow for this kind of operation in any obvious way beyond the discussion above. I am not aware of any columnar data format that would allow for efficient appendage of columns.

Maybe hdf5 but I need to try.
Another option could be SciDB but the connector for Julia is 4 years old.

**Comment by martindurant** [comment]
Maybe read up on TileDB?

**Comment by skanskan** [comment]
> Maybe read up on TileDB?

I can't see how to use it from Julia.

**Comment by skanskan** [comment]
> Maybe read up on TileDB?

I can't see how to use it from Julia.
At least there is something for R.

**Comment by yeskarthik** [comment]
The spec only says that schema in every row group must contain columns in the same order as that of the FileMetadata but it doesn't really say that it should contain all the columns. In that case, can we have more columns in subsequent row groups?

row group 1 -> col1, col2
row group 2 -> col1, col2, col3
row group 3 -> col1, col2, col3, col4
file metadata -> col1, col2, col3, col4

This seems to be conforming to whats mentioned in the spec here - https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L796
