### ISSUE TITLE
Question regarding snappy vs pyarrow snappy

### ISSUE THREAD

**Issue by asafcombo** [dask/fastparquet#246]
Hi,
For the same dataset, comparing the 2 libs I get totally different parquet file sizes. 
The file size from `fastparquet` is x4 times larger than the one given by `pyarrow`.

I tried changing the values of `row_group_offsets` and the x4 figure was the best I got.
The `pyarrow` default is `128 MB`.

For what can I attribute this vastly different file size ? How can I reduce it ?

**Comment by xhochy** [comment]
@asafcombo Can you check if the file size of both files are equal when you turn dictionary encoding off in `pyarrow`?  (i.e. set `use_dictionary=False` in https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html#pyarrow.parquet.write_table)

**Comment by asafcombo** [comment]
@xhochy , you are correct. Although I'm not sure what `use_dictionary=False` controls exactly.

Can I replicate this with `fastparquet` ? and if so what are the implications ?

**Comment by xhochy** [comment]
DictionaryEncoding is a way to save data in Parquet. It is simply a more efficient approach if your data not unique in each row. As far as I understand, `fastparquet` currently does not support writing it or does not have it enabled by default ( @martindurant  correct me if I'm wrong). The implications should simply be different file sizes. Reading Parquet files with dictionary encoding is supported by all standard-compliant Parquet readers and should give you the same performance (often it does even get you a significantly better performance as file size is much smaller and this is the read speed limitation if you read e.g. over network).

**Comment by martindurant** [comment]
Fastparquet uses dictionary encoding when your data type is categorical, which is a well known way to save space for pandas dataframes in memory. This generally makes the biggest impact for string-like columns, and you can choose to categorize your data before passing it to fastparquet.
For non-categoricals, it will not attempt to create dictionaries on a per-chunk basis. 
Attempting to use dictionary encoding for data that does not suit it (e.g., random float numbers) would result in some performance degradation on writing with the try-and-fallback method, and result in a column stored without dictionaries, so as fast to read as if the writer had not considered dictionaries in the first place. It is plausible in some circumstances (semi-random numbers) that dictionary encoding is slower.

**Comment by martindurant** [comment]
btw: your issue title is about snappy - is there something regarding this you wanted to ask? pyarrow defaults to compressing with snappy, fastparquet defaults to no compression.

**Comment by asafcombo** [comment]
My initial thought was that the size difference was due to a different SNAPPY lib being used, or a different compression ratio.

**Comment by martindurant** [comment]
OK. The snappy implementations should be near identical.

It would be a reasonable requests for fastparquet to consider dictionary encoding for stringy columns, e.g., by looking at the nunique/count of the column, but I won't have the time to implement that in the near future, so I'm closing this for now.

**Comment by wesm** [comment]
Note that other Parquet implementations: parquet-cpp, parquet-mr, Impala, etc. always dictionary encode all column types by default.
