### ISSUE TITLE
Missing import sys ?

### ISSUE THREAD

**Issue by brahmbhattspandan** [dask/fastparquet#247]
https://github.com/dask/fastparquet/blob/dc9f389bd99e85bee2af9a9bd35fa12f9deaae26/fastparquet/thrift_structures.py#L52

In case of an exception thrown , an `NameError` occurs.

`NameError: name 'sys' is not defined`

Should the module contain an `import sys` at the top ?

**Comment by martindurant** [comment]
Good idea!

**Comment by martindurant** [comment]
Fixed in current master
