### ISSUE TITLE
Writer mutates FileMetaData leading to non-threadsafe behavior

### ISSUE THREAD

**Issue by jcrist** [dask/fastparquet#248]
There are many locations with the following pattern:

```python
rgs = fmd.row_groups
fmd.row_groups = [...]
...
fmd.row_groups = rgs
```
Example: https://github.com/dask/fastparquet/blob/master/fastparquet/writer.py#L918-L921.

This leads to non-threadsafe behavior, as the mutations can be interleaved. Either `copy` (slow because the `__getstate__` for `FileMetaData` writes to bytes) or recreating with the constructor should be used.

**Comment by martindurant** [comment]
In the pure-fastparquet case, as opposed to dask, this should also be fixed, but it is very unlikely that anyone would be hit by it, the use case is typically single-threaded.
