### ISSUE TITLE
Encoding possible performance gains

### ISSUE THREAD

**Issue by alimanfoo** [dask/fastparquet#254]
I spent some time today developing a UTF8 codec for numcodecs, using the parquet byte array encoding, and starting from the code here in speedups.pyx. FWIW I think there is a possibility to accelerate encoding by up to 4X, and decoding by a more modest 1.5-2X. Some [benchmarks here](https://github.com/alimanfoo/numcodecs/blob/469215620615a38dbb8328a330e9c7d937c5c187/notebooks/benchmark_strings.ipynb) - compare results for fp_codec versus vlen_codec, both use the same encoding. I don't know enough about fastparquet codebase to submit a PR, but if it's of any use the [numcodecs implementation is here](https://github.com/alimanfoo/numcodecs/blob/469215620615a38dbb8328a330e9c7d937c5c187/numcodecs/vlen.pyx), feel free to steal code.

**Comment by alimanfoo** [comment]
On further inspection I think the encoding speedup is an effect of data being cached during benchmarking. On the first run, performance of the numcodecs and fastparquet codecs is very similar. I think the UTF8 encoded bytes are being cached on the str objects, so numcodecs goes much faster second time onwards. So I'm not sure there's much to be gained beyond where fastparquet codec currently is.

**Comment by martindurant** [comment]
I'll look into it when I have the time. I didn't write this code, and hadn't looked at it beyond to see that it worked and was certainly faster than the pure-python version used previously. Your version certainly looks simpler, so  wouldn't be surprised if there was performance to be gained.

**Comment by alimanfoo** [comment]
FWIW I've [updated the implementation](https://github.com/alimanfoo/numcodecs/blob/d7c18ed7f2fa5c7cf34b7b378b29736bbf9f0094/numcodecs/vlen.pyx#L58) to get PY2/PY3 compatibility, and also to remove the optimisation that relies on caching encoded values (which is only available in PY3 and isn't a real optimisation because it only improves performance when encoding the same data more than once, which isn't going to happen often in practice). The performance gains are modest relative to fastparquet, maybe 1.5X speedup on encode and decode, so not sure it's worth investing effort in. [Benchmarks here](https://github.com/alimanfoo/numcodecs/blob/d7c18ed7f2fa5c7cf34b7b378b29736bbf9f0094/notebooks/benchmark_vlen.ipynb).
