### ISSUE TITLE
Does cython need to be a runtime dependency?

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/fastparquet#255]
The install_requires list cython as a dependency (from requirements.txt), and also the conda-forge package has it listed in its runtime dependencies.

However, is it actually needed for this? Or is it only needed for development / installing from source ? (eg in the docs cython is not mentioned: https://fastparquet.readthedocs.io/en/latest/install.html#requirements) 
In that case, I think it would be nice to remove this hard dependency on cython.

**Comment by martindurant** [comment]
I guess, if you install normally and force-remove cython, but the test-suite runs without issue, then the requirement can be removed.
