### ISSUE TITLE
Parquet files with uint data written by fastparquet cannot be read by pyarrow

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/fastparquet#256]
Not sure where I should report this (here, arrow or parquet-cpp), but the example in the pandas docs (http://pandas.pydata.org/pandas-docs/stable/io.html#io-parquet) is not fully cross compatible: when written by fastparquet, it cannot be read by pyarrow. 

This seems to be due to the presence of uint column, so smaller example with just uint data to showcase:

```
# with normal ints works fine
In [83]: df = pd.DataFrame({'a': [1, 2, 3]})

In [84]: df.dtypes
Out[84]: 
a    int64
dtype: object

In [85]: df.to_parquet("__test_uint.parquet", engine='fastparquet')

In [86]: pd.read_parquet("__test_uint.parquet", engine='pyarrow')
Out[86]: 
   a
0  1
1  2
2  3

# with unsigned ints gives error
In [88]: df = df.astype('uint8')

In [89]: df.dtypes
Out[89]: 
a    uint8
dtype: object

In [90]: df.to_parquet("__test_uint.parquet", engine='fastparquet')

In [91]: pd.read_parquet("__test_uint.parquet", engine='pyarrow')
...
ArrowIOError: Unknown encoding type.
```

(the other way around (written by pyarrow, reading by fastparquet) works fine).

I tested it with both latest released as latest dev versions of both packages.

**Comment by mrocklin** [comment]
cc @martindurant @wesm @xhochy

**Comment by xhochy** [comment]
@jorisvandenbossche This is probably a `parquet-cpp` problem: https://issues.apache.org/jira/projects/PARQUET 

Seems like `fastparquet` writes the file with an encoding that is not supported in reading from `parquet-cpp`. Can you paste the output of `parquet meta <filename>` (see https://github.com/apache/parquet-mr/tree/master/parquet-cli) here?

**Comment by jorisvandenbossche** [comment]
It is not possible to get the same information you need with fastparquet / pyarrow? (I don't have the parquet cli installed at the moment)

```
In [144]: f = pq.ParquetFile("__test_uint.parquet")

In [145]: f.schema
Out[145]: 
<pyarrow._parquet.ParquetSchema object at 0x7f8e46e7bf48>
a: INT32 UINT_8
 

In [146]: f.metadata
Out[146]: 
<pyarrow._parquet.FileMetaData object at 0x7f8e46d86a48>
  created_by: fastparquet-python version 1.0.0 (build 111)
  num_columns: 1
  num_rows: 3
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 312
```

(but if needed can install parquet-cli later today)

**Comment by jorisvandenbossche** [comment]
Not sure if this is informative, but I find the following with fastparquet:

```
In [155]: f = fastparquet.ParquetFile("__test_uint.parquet")

In [158]: f.fmd
Out[158]: 
<class 'fastparquet.parquet_thrift.parquet.ttypes.FileMetaData'>
created_by: fastparquet-python version 1.0.0 (build 111)
key_value_metadata: [<class 'fastparquet.parquet_thrift.parquet.ttypes.KeyValue'>
key: pandas
value: {"columns": [{"metadata": null, "name": "a", "numpy_type": "uint8", "pandas_type": "uint8"}], "index_columns": [], "pandas_version": "0.22.0.dev0+260.g5da3759"}
]
num_rows: 3
row_groups: [<class 'fastparquet.parquet_thrift.parquet.ttypes.RowGroup'>
columns: [<class 'fastparquet.parquet_thrift.parquet.ttypes.ColumnChunk'>
file_offset: 41
file_path: None
meta_data: <class 'fastparquet.parquet_thrift.parquet.ttypes.ColumnMetaData'>
  codec: 1
  data_page_offset: 4
  dictionary_page_offset: None
  encoding_stats: [<class 'fastparquet.parquet_thrift.parquet.ttypes.PageEncodingStats'>
count: 1
encoding: 0
page_type: 0
]
  encodings: [3, 4, 0]
  index_page_offset: None
  key_value_metadata: []
  num_values: 3
  path_in_schema: ['a']
  statistics: <class 'fastparquet.parquet_thrift.parquet.ttypes.Statistics'>
    distinct_count: None
    max: b'\x03\x00\x00\x00'
    min: b'\x01\x00\x00\x00'
    null_count: 0

  total_compressed_size: 37
  total_uncompressed_size: 35
  type: 1

]
num_rows: 3
sorting_columns: None
total_byte_size: 35
]
schema: [<class 'fastparquet.parquet_thrift.parquet.ttypes.SchemaElement'>
children: OrderedDict([('a', <class 'fastparquet.parquet_thrift.parquet.ttypes.SchemaElement'>
converted_type: 11
field_id: None
name: a
num_children: None
precision: None
repetition_type: 1
scale: None
type: 1
type_length: 8
)])
converted_type: None
field_id: None
name: schema
num_children: 1
precision: None
repetition_type: None
scale: None
type: None
type_length: None
, <class 'fastparquet.parquet_thrift.parquet.ttypes.SchemaElement'>
converted_type: 11
field_id: None
name: a
num_children: None
precision: None
repetition_type: 1
scale: None
type: 1
type_length: 8
]
version: 1
```

**Comment by xhochy** [comment]
Yes this helps a bit but not totally. I will try to reproduce locally. This should give me also the necessary data to pin this further down.

**Comment by martindurant** [comment]
Short ints and unsigned ints are very handy and efficient, but it is known not to be compatible with spark (https://fastparquet.readthedocs.io/en/latest/details.html#short-type-integers), so it doesn't surprise me if this was down the list of priorities for arrow-cpp.

**Comment by xhochy** [comment]
`are stored using bitpacking`

Yes, we don't support the bitpacked-encoding for data yet in `parquet-cpp`. Not sure if this actually used by anything else yet. From reading `parquet-mr` code it seems that BITPACKED and RLE are only used for the levels but not the data.

**Comment by xhochy** [comment]
Nevertheless, I made an `parquet-cpp` issue to implement this: https://issues.apache.org/jira/browse/PARQUET-1171

**Comment by wesm** [comment]
I wasn't aware that bit-packing was a supported encoding for data pages (either PLAIN or dictionary-RLE are the ones used). I don't think Impala supports this either:

https://github.com/apache/impala/blob/master/be/src/exec/parquet-column-readers.cc#L495

If this is what's happening (encoding other than PLAIN or PLAIN_DICTIONARY / RLE), it's probably not a good idea for fastparquet to use anything other than these two encoding schemes by default since it won't be readable other Parquet readers in general

**Comment by martindurant** [comment]
I am not keen to remove a feature as useful as this. I wonder why parquet would have encodings that some frameworks do not implement? In any case, if you know you want uint16s, say, and go to effort of transforming your pandas columns appropriately, I'm inclined to provide less-used encodings to store them efficiently.

**Comment by mrocklin** [comment]
> I am not keen to remove a feature as useful as this. I wonder why parquet would have encodings that some frameworks do not implement? In any case, if you know you want uint16s, say, and go to effort of transforming your pandas columns appropriately, I'm inclined to provide less-used encodings to store them efficiently.

I have to say I agree with this.  "Other people didn't implement this part of the spec" doesn't seem like a sufficient reason not to implement part of the spec.  If we're going to decide that part of Parquet is no longer valid then that decision probably needs to be made higher up.

**Comment by wesm** [comment]
I am not actually sure if this is part of the spec. We should discuss the matter on dev@parquet.apache.org to make sure we know for certain

**Comment by wesm** [comment]
I am looking at https://github.com/apache/parquet-format/blob/master/Encodings.md

It is my understanding that BIT_PACKED and RLE are only to be used for encoding the repetition and definition levels. The only types supported for integers in Parquet V1 is PLAIN encoding.

**Comment by martindurant** [comment]
It does not say that on that page, it list a set of allowed encodings. Note that I am using the bit-packing branch of RLE, not BIT_PACKED. Why in any implementation it should be possible to load the dictionary codes from RLE but not integers directly (which are the exact same type) is beyond me, the algorithm is already there.

In fact, I would love to have delta and delta-strings as options, as they should perform much better, but I was unable to get any test data.

**Comment by wesm** [comment]
It looks like RLE is only supported for Booleans in parquet-mr, it doesn't appear to be supported in any other readers. 

See https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/Encoding.java#L115

and https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/Encoding.java#L232

If you try to decode INT32 from RLE (no dictionary), I believe it will drop into `getMaxLevel` and throw an exception.

I think this is a deficiency of the format specification. Either way we should start a mailing list thread to propose an improvement to the spec to make more clear what is expected. For the moment, I do not think it is a good idea to _by default_ produce files that no other Parquet implementations can read, even if the consensus it that the other implementations have not fully implemented the spec.

**Comment by wesm** [comment]
Mailing list thread: https://lists.apache.org/thread.html/9346d2d6101f72b99a084c5af725cc74d6ca68f43f5f2ba6ac379e1b@%3Cdev.parquet.apache.org%3E

**Comment by wesm** [comment]
To follow up on this:

Because UINT_8 is an annotation for INT32 (https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L125), the only valid physical storage in data pages for UINT_8 are the supported encodings for INT32. The RLE encoding scheme cannot represent negative integers, and so cannot be used for encoding INT32 when it is not dictionary-encoded. Let me know if this does not make sense. 

I still think it would be a good idea to clarify in the specification precisely what the RLE encoding is to be used for (repetition/definition levels, dictionary indices, and boolean values).

**Comment by wesm** [comment]
I just opened https://github.com/apache/parquet-format/pull/79 to clarify the uses for these encodings
