### ISSUE TITLE
Support for restoring timezone on reading parquet files?

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/fastparquet#257]
When writing a dataframe with tz-aware datetimes, you get a warning that the datetimes are coerced to UTC (the warning is not visible when using pandas `to_parquet` because it is catched for some reason, but that is another issue). 
However, the timezone information is still stored in the pandas metadata, so in principle it could be restored on reading a parquet file with such pandas metadata.

This is actually what `pyarrow` does, as it detects the timezone correctly for a file written by `fastparquet` (as opposed to `fastparquet` itself):

```
In [127]: df = pd.DataFrame({'a': pd.date_range('20130101', periods=3, tz='US/Eastern')})
     ...: df
     ...: 
Out[127]: 
                          a
0 2013-01-01 00:00:00-05:00
1 2013-01-02 00:00:00-05:00
2 2013-01-03 00:00:00-05:00

In [128]: df.to_parquet('__test_tz.parquet', engine='fastparquet')

In [129]: pd.read_parquet('__test_tz.parquet', engine='fastparquet')
Out[129]: 
                    a
0 2013-01-01 05:00:00
1 2013-01-02 05:00:00
2 2013-01-03 05:00:00

In [130]: pd.read_parquet('__test_tz.parquet', engine='pyarrow')
Out[130]: 
                          a
0 2013-01-01 00:00:00-05:00
1 2013-01-02 00:00:00-05:00
2 2013-01-03 00:00:00-05:00
```

Of course this can also be a choice to have the same behaviour for parquet files that do not have such a pandas metadata or than parquet readers that are not aware of such pandas metadata. But in that case maybe an option could be added?

**Comment by martindurant** [comment]
This sounds simple enough to implement. I don't have much time right now for coding for fastparquet, perhaps you are interested in submitting a PR?

**Comment by jorisvandenbossche** [comment]
Thanks for fixing this! 
Once there is a new release of fastparquet we should make sure to update the pandas tests and docs
