### ISSUE TITLE
Read directly from row group

### ISSUE THREAD

**Issue by mrocklin** [dask/fastparquet#26]
OK, so as we have it now any system that has to serialize a dask graph with ParquetFile objects can get very expensive.  Each task has megabytes of metadata in it.

```python
In [69]: from fastparquet import ParquetFile

In [70]: %time pf = ParquetFile('/home/mrocklin/data/nyc/indexed-full/')
CPU times: user 1.11 s, sys: 8 ms, total: 1.12 s
Wall time: 1.11 s

In [71]: %time len(cloudpickle.dumps(pf))
CPU times: user 1.56 s, sys: 20 ms, total: 1.58 s
Wall time: 1.58 s
Out[71]: 2082175
```

Currently we have the parquet file in *each task*, so everyone gets this cost, which is unfortunate when reads are in the 10ms range.  My guess is that this cost increases the more RowGroups we have, and presumably these can become quite large.

So we can't have these in each task of the graph.  There are a few options:

1.  We can put it in the graph once, and depend on the system to move it around between workers
2.  We can add opening the parquet file to each reading task.  This adds 1s of overhead per task
3.  We can make a new function that skips making the ParquetFile, and instead knows to go to a particular row group on disk.  This would be ideal if we can make it fast.

Any thoughts on how to do option 3 @martindurant ?

**Comment by martindurant** [comment]
Correct, each reader only needs the schema and the one row-group - a ParquetFile where row_groups is replaced with [row_group], i.e., just the one of interest, would be enough to specify everything. 
In fact, read_row_group_file is passed the row_group anyway, and doesn't access that list at all, just a few small attributes: opener function, filesystem separator, set of partitions, schema/helper

**Comment by martindurant** [comment]
In dask.dataframe.io.parquet before L68 (line with delayed) `del pf.row_groups` might solve it very easily.
