### ISSUE TITLE
ENH: support for reading MultiIndex

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/fastparquet#262]
From discussion in https://github.com/pandas-dev/pandas/pull/18629 (writing and reading indexes in `to_parquet` / `read_parquet` the default behaviour).

`fastparquet` supports writing multiple index levels and the pandas metadata are written correctly (and `pyarrow` can also read them in correctly), but raises an NotImplementedError on reading them in:

```
In [1]: import fastparquet

In [2]: fastparquet.__version__
Out[2]: '0.1.3'

In [3]: df = pd.DataFrame(np.random.randn(10, 3), columns=list('abc'), index=pd.MultiIndex.from_product([['A', 'B'], range(5)]))

In [5]: fastparquet.write("__test_mi.parquet", df)

In [6]: f = fastparquet.ParquetFile("__test_mi.parquet")

In [8]: f.key_value_metadata['pandas']
Out[8]: '{"columns": [{"metadata": null, "name": "level_0", "numpy_type": "object", "pandas_type": "unicode"}, {"metadata": null, "name": "level_1", "numpy_type": "int64", "pandas_type": "int64"}, {"metadata": null, "name": "a", "numpy_type": "float64", "pandas_type": "float64"}, {"metadata": null, "name": "b", "numpy_type": "float64", "pandas_type": "float64"}, {"metadata": null, "name": "c", "numpy_type": "float64", "pandas_type": "float64"}], "index_columns": ["level_0", "level_1"], "pandas_version": "0.21.0"}'

In [9]: f.to_pandas()
...
NotImplementedError: multi-index not yet supported, use index=False
```

(if you don't like opening issues for known limitations, it's fine to close)

**Comment by TomAugspurger** [comment]
It'd be nice to support. I'll look into how difficult it'd be to support them next week.

**Comment by martindurant** [comment]
Feeding index as a tuple everywhere it is now a string, and having an `if isinstance(index, str)` is easy enough. The tricky part will be in the preassignment dataframe.empty.
