### ISSUE TITLE
Tests do not pass on windows

### ISSUE THREAD

**Issue by klahnakoski** [dask/fastparquet#270]
There is many tests that do not pass, but let's focus on one: `fastparquet/test/test_api.test_attributes()`.

Windows uses backslash (`\`) as a separator, which is escaped when quoted. For example in `fastparquet/api`

    def __str__(self):
        return "<Parquet File: %s>" % self.info

this makes asserts, like 

        assert fn in str(pf)

fail

**Comment by martindurant** [comment]
Can you please check is #232 fixes this?
