### ISSUE TITLE
Does not handle nested object arrays

### ISSUE THREAD

**Issue by klahnakoski** [dask/fastparquet#272]
As per the docs, this lib does not handle nested object arrays well.  I would like to take a stab at it.

I believe the first step is to alter the code so that `write_column` can accept multidimensional arrays (of uniform type, of course) and calculate the repetition level so they can be reconstructed upon read.

If you have any wise words, please say.

**Comment by martindurant** [comment]
fastparquet does not handle writing nested data-structures *at all* :) The best it can do is to JSON-encode objects, which is not even supported by all parquet frameworks.

I would say that this is a pretty hard task. You need to be able to travers the objects in the column to figure out the the deep schema, including repeatable fields where there are lists. You would calculate the definition/repetition levels from that schema. Perhaps there could be a way to specify the schema for an objects column...
The encoders for specific types in fastparquet are all column-based, so you would need a way to iterate through the sequence of objects to create a set of temporary columns/arrays for encoding; or to call the encoder item-by-item and store the set of definition/repetition levels elsewhere.

As you say, the case for uniform type and lists only (i.e., each element of the column is None, or a list of the values of the primitive type and None) is much easier. Now you can construct a single column for encoding easily by concatenating all the lists. You should note, though, that there is still complexity, since the following entries are all different: `None`, `[]`, `[None]`. You could concentrate on non-null only columns (which are rarer), in which case only the middle one of the three is relevant.

**Comment by klahnakoski** [comment]
So, I made a prototype to ensure I get the repetition and definition levels out of arbitrarily nested object arrays, including arrays of arrays.

https://github.com/klahnakoski/mo-parquet

The README is just my random notes, so you may find them misleading. The interesting parts are the code, and the tests.  My next step is to build the reverse, and add many more test cases.  

If you happen to know where I can find a suite of test cases for complicated JSON, please post a link to this issue.  Maybe the test cases in this repo have some deep nested JSON?

**Comment by martindurant** [comment]
Supersedes #180

**Comment by klahnakoski** [comment]
My work is proceeding here https://github.com/klahnakoski/fastparquet/blob/nested/fastparquet/json_writer.py  There is no need to look at it, unless you want to see half-baked code.  The first step is to get the encoding to work, then I will optimize, and remove the plethora of dependencies I added.

@martindurant I have a question about this line https://github.com/dask/fastparquet/blob/ddea5b7ebbfab044c4235164162dea85314d9d15/fastparquet/writer.py#L403 What is it doing!?

     encode_unsigned_varint(len(out) << 1 | 1, temp)

What it appears to be zigzag encoding the number of records (as opposed to the number of rep-levels).  But I am probably wrong.  I need to know this so I can encode the real repetition and definition levels.

Thank you

**Comment by martindurant** [comment]
Explanation of the line of code:
the number of definition levels for the column is associated with the column's place in the schema, it does not get written into the definition levels block at all (see what happens when [reading](https://github.com/dask/fastparquet/blob/master/fastparquet/core.py#L57)). The maximum value for anything written by fastparquet at the moment is 1, and there is no repetition at all.

In the [bitpack branch](https://github.com/apache/parquet-format/blob/master/Encodings.md#run-length-encoding--bit-packing-hybrid-rle--3) of encoding 3, the "bitpack header" is made from the number of bytes, the data itself is boolean (null/not-null), and the boolean encode-plane is already done using bitpacking.

**Comment by martindurant** [comment]
To write bit-packed with a width greater than 1, you would have to reverse what happens in the [reading function](https://github.com/dask/fastparquet/blob/ddea5b7ebbfab044c4235164162dea85314d9d15/fastparquet/encoding.py#L100) or perhaps you can find some numpy trick similar to what is done for the boolean case.

**Comment by klahnakoski** [comment]
@martindurant  Yea!  Thanks! I got it now, the encoding has the following production:

    run := <bit-packed-run> | <rle-run>

Which is using the lsb to determine if it is `bit-packed-run` vs `rle-run`, and explains the `len(out) << 1 | 1` bit twiddling.

**Comment by klahnakoski** [comment]
@martindurant 

I would like to get your guidance on a problem:

I copied the `writer.py` and named it `json_writer.py` and then made some changes to get it to encode the additional definition and repetition levels.  Rather than putting a pandas dataframe in `data`, I wrapped the dataframe in a [`Table`](https://github.com/klahnakoski/fastparquet/commit/93c0315fba59eb70bcf11f482ab5fa1aa872c8f9#diff-3c6af483ccd308487e6287235f702c56R1107); which holds the dataframe, along with some other attributes to keep track of def levels and rep levels, etc.  I think this is a good strategy because only the `write_column()` method needs these extra properties and all the other functions need not change.  Well except in one important way:

https://github.com/klahnakoski/fastparquet/commit/93c0315fba59eb70bcf11f482ab5fa1aa872c8f9#diff-3c6af483ccd308487e6287235f702c56R464

I am pointing to the superficial replacement of `data` with `data.values`; which is the only change I am making to the other functions.  I would like to avoid doing so here is less code duplication.  I have 2 possible solutions:

1. Continue altering the `Table` to react like a pandas DataFrame; to trick these funtions to behave as expected
2. Alter the original `writer.py` to handle wrapped pandas DataFrames.

I *believe* the best solution is #2:  Pandas Dataframes can not describe deep repeated properties, so it is not good to let the writer accept them.

**Comment by martindurant** [comment]
You have already put a decent amount of work into this, I can only wish you the best with what is a large undertaking!
I don't think we talked about what the inputs would be when talking about nested lists/dicts. I was thinking something along the lines of (shown as pandas columns)

Single-level array values (all int)
```
    a
0  [0, 1]
1   None
2  [4, None, 5]
```

Single-level key/values (all int values, keys must be str, cannot be None)
```
    a
0  {'a': 0, 'b': 1}
1   None
2  {'c': 4, 'd': None, 'a': 5}
```

Deeper nested combinations
Two-level repeated values (all int) within key/value
```
    a
0  {'a': [0, 1], 'b': [1, None]}
1   None
2  {'c': [], 'd': None, 'a': [5]}
Schema
- a key/value
  - keys (str, required)
  - values (array, optional)
    - int (optional)
```
In the last case, the max repetition level for a.values.int is 2 (can repeat dict keys, can repeat elements of list) and max definition level is 3 (whole row is None, dict value is None, or int itself is None). How in this scheme do you represent `[]`? 

In every case, the pandas type is Object, and in general we expect to see Nones at any level. This is why I wanted JSON to be sufficient encoding for every case - but of course not all parquet readers support it.

I would use `encoding._assemble_objects` to test that single-level dicts and lists are successfully recreated before venturing deeper.

**Comment by klahnakoski** [comment]
I have not even considered how pandas/numpy store objects yet! I have only been considering JSON permutations. Still, thank you for pointing it out, I most-certainly will be encountering this complexity soon.
   
> How in this scheme do you represent []?

I have come to the conclusion that the Dremel encoding has some limitations: `[]` can only happen on `REPEATED` properties, and are encoded as `null` at the given definition level.  For example, there is no way to dremel-encode the following dataset:

         a
    0  {"a": None}
    1  {"a": 1}
    2  {"a": []}
    3  {"a": [None]}
    4  {"a": [1]}
    5  {"a": [1, 2]}

You can encode `0` and `1` as `OPTIONAL` and you can encode `2`, `3`, `4`, `5` as `REPEATED`, but there is no way to encode all of them.

But that may not have answered your question; plus I noticed a very curious line:

https://github.com/dask/fastparquet/blob/ddea5b7ebbfab044c4235164162dea85314d9d15/fastparquet/encoding.py#L247

This seems to indicate that I do not understand the dremel encoding: I had assumed the array of values contains nulls, and has the same length as the repetition and definition level arrays! That would explain why I think definition levels is a bit redundant. It also makes your question harder to answer.

Okay, to answer you question: To encode the complicated cases we must be able to encode arrays of arrays (to arbitrary depth); this forces us to say more about a single property: Like, "`a` is of type `REPEATED`, `REPEATED`" - meaning two dimensional. This necessarily impacts the definition and repetition levels. Once we can encode multidimensional arrays, we can see how to encode other cases:  In the case of allowing a property to have both empty arrays and allow `nulls` in an array:  "`REPEATED`, `OPTIONAL`".  Allowing a property to be `null` or `[]` can be of type "`OPTIONAL`, `REPEATED`".  For implementation I would not attach multiple types to a single property; rather, insert "anonymous" properties into the schema to handle these complicated cases.  

> You have already put a decent amount of work into this

This has not been much work yet; I consider it verbose exploration of what **NOT** to do.  Do not be too hopeful about my success here.  :) 

As always; thank you for your time on this.

**Comment by martindurant** [comment]
```
     a
0  {"a": None}
1  {"a": 1}
2  {"a": []}
3  {"a": [None]}
4  {"a": [1]}
5  {"a": [1, 2]}
```
I think there may be a misunderstanding here: a single schema is used for the whole column, and the maximum repetition and definition levels are set beforehand. Indeed, I recommend reading about Dremel and particularly how the `_assemble_objects` function works (for the moderately shallow case). The data above can certainly be encoded - try it with spark or some other parquet writer.
As I said before, fastparquet can read a column of lists of simple type, or a column of dicts of simple types values, including all the levels of None, so I would aim to be able to write such data first. See the schema and output from the file `test-data/map_array.parq` - and the columns of definition/repetition/value, if you are brave. You would probably default to always optional (columns `'map_op_op'`, `'arr_op_op`').

**Comment by martindurant** [comment]
I will close this issue now.
If you make headway on implementing this, please start a PR for review.

**Comment by klahnakoski** [comment]
FYI, [Work is progressing](https://github.com/klahnakoski/fastparquet/blob/7875c06ce3b725e7de8580c741a4527bb1d95638/fastparquet/test/test_nested_json.py#L16).  Like you foresaw, this is a lot of work.  I have recently been busy with my day job, but I'll be back.

My next steps are to:

1. Enhance the re-assembly from parquet to deeply nested documents; this will help testing by having a encoder/decoder pair to verify correctness of both
2. The re-assembly will help read existing parquet files in the event I have confusion about encoding details.
3. Add many more tests. There are [more interesting tests](https://github.com/klahnakoski/mo-parquet/tree/dev/tests) in a sibling project

**Comment by martindurant** [comment]
Oh, interesting. I'll try to find some time to look through what you have there and comment on it. Of course, the typical use case for parquet is very tabular data, so you may not have too much "ground truth" deeply nested structures to work with. The original Dremmel paper would be one such source.
