### ISSUE TITLE
test_time_millis() does not pass on windows

### ISSUE THREAD

**Issue by klahnakoski** [dask/fastparquet#273]
```
F
fastparquet\test\test_converted_types.py:42 (test_time_millis)
def test_time_millis():
        """Test int32 encoding a timedelta in millis."""
        schema = pt.SchemaElement(
            type=pt.Type.INT32,
            name="test",
            converted_type=pt.ConvertedType.TIME_MILLIS,
        )
>       assert (convert(np.array([731888], dtype='int32'), schema)[0] ==
                np.array([731888], dtype='timedelta64[ms]'))
E       AssertionError: assert numpy.timedelta64(1743559680,'ns') == array([731888], dtype='timedelta64[ms]')
E        +  where array([731888], dtype='timedelta64[ms]') = <built-in function array>([731888], dtype='timedelta64[ms]')
E        +    where <built-in function array> = np.array

fastparquet\test\test_converted_types.py:50: AssertionError
```

**Comment by martindurant** [comment]
I wonder, does it work if those literal ints have `L` appended, i.e., we mark them explicitly as big integers?

**Comment by klahnakoski** [comment]
Changing to use `L` makes no difference; since the `dtype` is set anyway.  Here is my debug session; it may help you more then it helps me.

![image](https://user-images.githubusercontent.com/2334429/34954120-40455568-f9ed-11e7-8916-09147e9db2f8.png)

**Comment by martindurant** [comment]
My thinking was, it should make a difference at the time the code itself is parsed, before the dtype parameter is even considered. I would also try 1000->1000L in converted_types.time_shift.

**Comment by klahnakoski** [comment]
It looks the same with `L`:

![image](https://user-images.githubusercontent.com/2334429/34957773-f730b556-f9fc-11e7-86a4-59cd828bf707.png)

**Comment by klahnakoski** [comment]
Which is the "correct" value?  The `test` or the `expected`?  Or are both not correct?

**Comment by martindurant** [comment]
The value of `test` should be 731888000000ns (731888 * 1000000), which is an overflow on win32/py2.
Would you mind trying adding a L ontot the value on line https://github.com/dask/fastparquet/blob/master/fastparquet/converted_types.py#L123 ?

**Comment by klahnakoski** [comment]
Changing the `dtype='int64'` fixes the test, but I am not sure if that breaks the intent of the test.

![image](https://user-images.githubusercontent.com/2334429/34958845-9ff99bd6-fa01-11e7-8835-fb702803668a.png)

**Comment by klahnakoski** [comment]
Adding the `L` does not change the test, and it still overflows:

![image](https://user-images.githubusercontent.com/2334429/34958869-c403388e-fa01-11e7-9e3a-9922ac112527.png)

![image](https://user-images.githubusercontent.com/2334429/34958889-d5bcd7d8-fa01-11e7-91a6-70ca776331ab.png)

**Comment by martindurant** [comment]
I'm afraid TIME_MILLIS is always expected to arrive as int32 https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#time_millis

**Comment by klahnakoski** [comment]
TIME_MILLIS as int32 is ok, it is just the encoding.  I believe the test is taking the encoded int32 value and turning it into a standard internal timestamp: Which appears to be 64bit nanosecond-based time delta.

See https://github.com/dask/fastparquet/pull/275 for fix
