### ISSUE TITLE
Support LZ4 compression?

### ISSUE THREAD

**Issue by jonathanunderwood** [dask/fastparquet#288]
Are you interested in supporting LZ4 frame compression? If you are, I can knock up a patch to add it. (I'm the python-lz4 maintainer).

**Comment by martindurant** [comment]
Sure, sounds good. LZ4 has apparently been in the [standard](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L466) for four months now.
(Feel free to add Zstd too!)

**Comment by jonathanunderwood** [comment]
PR #292 - I'll close this.
