### ISSUE TITLE
fastparquet.write() to s3 fails from a Windows operating system (with file_scheme='hive')

### ISSUE THREAD

**Issue by robertdavidwest** [dask/fastparquet#289]
The following code works for me on Unix but fails on Windows.
```
from fastparquet import write
import pandas as pd
import s3fs

s3 = s3fs.S3FileSystem()
bucket = "your-bucket-name"
filepath = "s3://{b}/testspace/example.parquet".format(b=bucket)
df = pd.DataFrame({'A': [1, 1, 2, 3], 'B': [4, 5, 6, 7]})

write(filepath,
    data=df,
    file_scheme='hive',
    object_encoding='bytes',
    partition_on=['A'],
    open_with=s3.open)
```
It gives this error on Windows:

```
Traceback (most recent call last):
  File "make_error_parquet.py", line 22, in <module>
    open_with=s3.open)
  File "C:\Anaconda\lib\site-packages\fastparquet\writer.py", line 817, in write
    mkdirs(filename)
  File "C:\Anaconda\lib\site-packages\fastparquet\util.py", line 37, in default_       mkdirs
    os.makedirs(f)
  File "C:\Anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 's3:'
```
Fails spec:
```
OS: Microsoft Windows Server 2008
Python: 2.7
fastparquet: 0.1.3
pandas: 0.18.0
s3fs: 0.1.2
```
Works with Centos, same python version and packages

**Comment by martindurant** [comment]
Unfortunately, you also need to provide the keyword `mkdirs=` to the `write()` function. This is because, in general, parquet files live within directories that need to exist. For s3, however, there are no directories, and keys can always be made, so you can provide a noop function

    write(..., mkdirs=lambda: True)

https://fastparquet.readthedocs.io/en/latest/filesystems.html

**Comment by robertdavidwest** [comment]
Thank you. I saw this page: `https://fastparquet.readthedocs.io/en/latest/filesystems.html` but i didn't understand what `noop` was

**Comment by martindurant** [comment]
Edit: the no-op function should take an argument: `mkdirs=lambda x: True`

**Comment by robertdavidwest** [comment]
Maybe we could update the example on `https://fastparquet.readthedocs.io/en/latest/filesystems.html`  to define `noop=lambda x: True`?
