### ISSUE TITLE
Error writing chunks

### ISSUE THREAD

**Issue by ericman93** [dask/fastparquet#291]
Hey

The error is at `fastparquet/parquet_thrift/parquet/ttypes.py` line 1029 in `write` 
and the message is
`TypeError: expecting list of size 2 for struct args`
Using python `3.6.0` and fastqparquet version `0.1.3`

Thanks!

**Comment by martindurant** [comment]
Fixed in https://github.com/dask/fastparquet/pull/281 , release coming soon.
