### ISSUE TITLE
about decimal type with redshift spectrum

### ISSUE THREAD

**Issue by thomaszdxsn** [dask/fastparquet#299]
hi, i need some help...

when i use fastparquet generate parquet file, and upload s3, use redshift spectrum query it, some problem happen.

such as my table has a column is DECIMAL type, it will raise:

```
S3 Query Exception (Fetch)
...has an incompatible Parquet schema for column...
```

and i alter table schema, change column type to FLOAT, can query with parquet, but only 2 point precision.

and i search related article, find[issue48](https://github.com/dask/fastparquet/issues/48), [fastparquet-doc](http://fastparquet.readthedocs.io/en/latest/details.html#spark-timestamps),i know fastparquet not support DECIMAL, but how to solve my problem, i need redshift query FLOAT full point precision, may be i can store it with VARCHAR type, is it a good idea?

**Comment by martindurant** [comment]
Have you tried redshift type DOUBLE PRECISION (float64)? That will not give you the precision of a real decimal, but should be good enough for all practical purposes. Most non-integer numbers in pandas are stored using float64, and this is probably what you are writing to the parquet files.

**Comment by thomaszdxsn** [comment]
I do with you tell(`DOUBLE PRECISION (float64)`), Redshift just tell me invalid syntax, when I type `DOUBLE PRECISION `, this column's value just have 2 point precision(actually 6)

**Comment by martindurant** [comment]
float64 if the pandas/numpy name for the data type known by redshift as DOUBLE PRECISION.
I'm afraid I don't understand "this column's value just have 2 point precision(actually 6)".
