### ISSUE TITLE
partition_on_columns breaking change in 0.1.4

### ISSUE THREAD

**Issue by gorlins** [dask/fastparquet#300]
The addition of the argument ```sep``` in ```fastparquet.writer. partition_on_columns``` breaks Dask compatibility since both are using positional arguments, and are now out of order.  I would suggest using keywords or only adding new positional args to the end to prevent future issues

**Comment by gorlins** [comment]
*whoops I mean ```sep``` was removed in 0.1.4

**Comment by martindurant** [comment]
Yes, you are quite right, this was my mistake to allow the change in the internal API that was nevertheless used directly by dask.
This is fixed in dask master ( https://github.com/dask/dask/pull/3114 ) so will be in the next release.
