### ISSUE TITLE
QUESTION : How to handle timeseries data with different and variable frequencies

### ISSUE THREAD

**Issue by guilhermecgs** [dask/fastparquet#301]
Hi Folks,

I am evaluating this library but, before any coding, I would like to ask some basic stuff...
It would be really nice if you took 2 min to help me....

My situation is:  

- I have a list of hundreds of timeseries parameters
- Each parameter is independent of each other
- Each parameter has a basic frequency (lets say, 10hz) but due to hardware limitations may be saved from 9 to 11 hz (variable frequency)
- Normally, I only need to read a few of there parameters at a time

My questions are:

1. Do you think parquet would be a suitable file format given this brief description?
2. Can parquet (and this library) deal with variable frequency? In other words, does it save a timestamp associated with each value?

**Comment by martindurant** [comment]
Parquet can store timestamps, yes. Fastparquet supports both the standard int64 representation (us resolution) and non-standard int96 representation (ns resolution).

I'm not sure whether that answers your question of whether it's the right choice for your data, that will likely depend on how you intend to process it. Parquet stores tabular data (set of columns, each with a particular data type), is fairly efficient in its binary packing, and is particularly useful when you need to access chunks of columns. That is why it has found favour in the big-data/hadoop world, where processing is frequently like that.
