### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by martindurant** [dask/fastparquet#31]
Some ideas to think about which should make things work faster. Some of these are readily implementable, others more tricky

- [x] storing strings as fixed-length; see #30. In the first instance, we should give this option to the user, where they know beforehand what string length they would like (or they are prepared to find out), so that we don't have to calculate it, which could be very costly in the dask case. (implemented)
- [ ] we don't have a fast way to encode or decode variable-length strings, hence the previous item; if we did, some issues may go away. The trouble is, there is no way to access the underlying strings pointed to by a numpy object array from within a numba-jitted function
- [x] datetime columns can be constructed using the pd.DatetimeIndex directly rather than to_datetime, but care will need to be taken for what happens with NaT encoded in the integers and NULL values (special case in read_col, not only checking for nan) (should be easy)
- [x] currently we read everything into numpy arrays and convert immediately into pandas Series, so that we can do things like conversions using map. In this, pandas creates a default index, which is compared when putting the series together into the final dataframe. The cost of this has not been measured, but given that dask wants knowledge of the index anyway, and we have some code to deal with that, we could create the index up front and apply it to series as they are made, or keep things as arrays further on (in fact, arrays may be simpler and faster in some cases).

**Comment by mrocklin** [comment]
@seibert any thoughts on fast string operations with Numba?

Regarding pandas series if we know that all of the rows line up then its best to delay creating the series for as long as possible.  The `map` method might not be a big help.  I suspect that a list comprehension is about as fast in many cases.  Delaying using series would also help with the eventual desire to support straight NumPy.

**Comment by seibert** [comment]
The problem with strings in the above case is that Numba is basically not equipped to deal with a container that holds Python objects when generating code in nopython mode.  I'm not sure what we would do here.

**Comment by seibert** [comment]
@sklam might have an idea for a hack that would allow us to jump back into Python mode to fetch the pointer to the string data for a given element.

**Comment by martindurant** [comment]
Presumably numpy does this internally when you do `astype("S")` on an object array?

**Comment by martindurant** [comment]
- [ ] For 8- and 16-bit ints (signed or not), may be faster, and certainly more compact, to use the bit-packing encoding (which will actually look just like `tostring()`) rather than expand to 32-bit. Similarly, dictionary codes are always stored in bit-packing, and storing more bits to round up to 8 or 16 may be much faster than using the minimum number of bits per value.

**Comment by martindurant** [comment]
- [ ] Writing or reading an optional column should not take significant additional time if there are no actual nulls.

**Comment by martindurant** [comment]
The variable string encoding will remain outstanding, but with good fixed string and categorical options, it is less pressing.
Everything else here is complete, so closing this.
