### ISSUE TITLE
Unnecessary print statement when reading file with CategoricalDtype index

### ISSUE THREAD

**Issue by kylebarron** [dask/fastparquet#310]
[This line](https://github.com/dask/fastparquet/blob/master/fastparquet/dataframe.py#L82) is causing an unnecessary line to be printed to console/output every time I read in a file written by pandas and which has a categorical index. Can this be removed?

```py
def empty(types, size, cats=None, cols=None, index_type=None, index_name=None,
          timezones=None):
    ...
    if index_type is not None and index_type is not False:
    ...
        if str(index_type) == 'category':
        ...
            print(cats, index_name, c)
```

**Comment by martindurant** [comment]
Closed by #311
