### ISSUE TITLE
Use LZ4 block compression

### ISSUE THREAD

**Issue by llchan** [dask/fastparquet#314]
From what I can tell from the [parquet-cpp implementation](https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/compression_lz4.cc), LZ4 compression should use the LZ4 block (i.e. un-framed) format.

At the moment, getting this to work with `parquet-cpp` is unfortunately a bit more tricky than simply changing the compression/decompression funcs in `fastparquet.compression` to the funcs in `lz4.block`, because it appears that the decompression func fails with corrupted lengths. I have a suspicion this may be a bug on the `parquet-cpp` side of things, maybe writing some padding/garbage bytes after the true payload, but I haven't dug through the code yet.

For anyone debugging, I've gotten it to work by passing `page_header.uncompressed_page_size` down, but this makes the code less clean, so hopefully it's not a permanent requirement.

**Comment by llchan** [comment]
Scratch that. `parquet-cpp` is doing the right thing, but the `python-lz4` module expects to see a `uint32_t` header if the uncompressed size is unspecified (see [source](https://github.com/python-lz4/python-lz4/blob/master/lz4/block/_block.c)).

We have a few options:
- Modify the (internal) API to pass the `page_header` down to the decompression funcs. This will mean we'll need to wrap the vanilla compressor/decompressor funcs we have now with something that discards the extra arg.
- Get the `python-lz4` implementation to add a streaming decompression method when it doesnt know the uncompressed size. This seems less optimal since it may over-allocate and it may have to retry.
- Change the parquet lz4 spec (or rather...the lack thereof) to use the framed lz4 format. This is less efficient but maybe doesnt matter.

My vote is for the first option because it involves the least coordination, but open to ideas.

**Comment by martindurant** [comment]
cc @jonathanunderwood

**Comment by llchan** [comment]
I agree with you, just wanted to discuss simpler (albeit hacky) solutions before going the route of proposing a spec change that involves other projects (though this is really more of a spec clarification).

I'll file a ticket over there and link back. Unfortunately the `parquet-format` repo doesnt have issues enabled, so it'll have to go to the cpp implementation that I am treating as one of the reference implementations.

**Comment by martindurant** [comment]
It would be appropriate to submit a PR to https://github.com/apache/parquet-format/pulls - it would amount to the same as an issue in this case (i.e., a pure text change).

**Comment by wesm** [comment]
Note that we expose lz4 compression and decompression through the `pyarrow.compress` and `pyarrow.decompress` APIs

@llchan can you create a JIRA on issues.apache.org/jira under the Parquet project?

**Comment by wesm** [comment]
> Really, parquet-cpp has taken a massively wrong turn by not using the framed format.

There's no need for this divisive language -- we were not aware that we were making a turn at all. How to properly use LZ4 is obviously underdocumented in the Parquet format, so we should remedy that as a community and make an appropriate change if necessary.

**Comment by wesm** [comment]
Awesome, thank you. Will be happy to help

**Comment by jonathanunderwood** [comment]
>There's no need for this divisive language -- we were not aware that we were making a turn at all. How to properly use LZ4 is obviously underdocumented in the Parquet format, so we should remedy that as a community and make an appropriate change if necessary.

Sorry, I wasn't meaning to be divisive - I think you're inferring a tone incorrectly here, or I was just careless with words. Either way, seems this is going in the right direction. Cc me if you need any thing else from my side, or raise an issue on the python-lz4 page if you need anything extra there.

**Comment by jonathanunderwood** [comment]
Incidentally, the Python lz4 block bindings could be expanded to cope with the current parquet-cpp block usage if that was considered helpful in the interim. It would be good to deprecate the block usage, even if we do that, though.

**Comment by martindurant** [comment]
If you can do that without preventing the preferred use, that's good with me.

**Comment by llchan** [comment]
@jonathanunderwood Yeah, that would be nice to have in the `lz4.block` module, independent of this ticket. Probably no need to change the existing behavior in fastparquet since it's so easy to override the compressor/decompressor functions. Just having a header-less decompress option would be enough.

@wesm Thanks for the tip about pyarrow's built-in parquet reader. Didnt realize my pyarrow package was built without it, but I reconfigured/rebuilt and got it working. Works nicely and also has the side effect of allow code re-use with some arrow stuff I'm working with.

**Comment by jonathanunderwood** [comment]
@martindurant looking into this a bit more, is there any reason why, currently, the uncompressed data size value isn't passed into `decompress_data`? It seems this would a good thing, and would enable us to add block (de)compression very easily (and also simplify the code for lz4frame and zstd cases as well).

@llchan turns out to be slightly more tricky than I thought to do a trial and error block decompression without the uncompressed size using only the public block API from the LZ4 library. I can see ways to do it with, but it would need a patch submitting upstream to LZ4. Will continue to investigate.

**Comment by martindurant** [comment]
@jonathanunderwood , the only reason is, that it was never needed before. In `core._read_page`, where decompress is called, the compressed and decompressed data size is available in the `page_header` object.

**Comment by jonathanunderwood** [comment]
Having considered the options, and the current situation, it seemed like the best course of action was to use LZ4 block compression for the LZ$ compression codec in fastparquet to ensure compatibility with parquet-cpp in the short term. PR #315 does that. This turned out to be much easier than the trial-and-error approach for an unknown size - the LZ4 API doesn't really accommodate that for block compression (though it does for Frame compression).

Moving forward, we should consider adding an LZ4_FRAME codec specifier to the standard though, I think.

**Comment by martindurant** [comment]
Does the new PR make it harder to accommodate the frame approach in the future?

**Comment by jonathanunderwood** [comment]
> Does the new PR make it harder to accommodate the frame approach in the future?

Nope, it would remain trivial. I almost left frame in, but figured it would be better to wait until the details are agreed in the JIRA ticket.

**Comment by llchan** [comment]
Thanks, everyone. I think it's great we're getting the two projects synced up, and things are in motion on the other side to clarify the spec and make a decision on the frame format.

**Comment by xhochy** [comment]
Would be nice to add this to the tests of `dask`. They are a good indicator if `fastparquet` and `parquet-cpp` are compatible with each other.

**Comment by martindurant** [comment]
Closed by #315
