### ISSUE TITLE
Slow initialization with large numbers of columns

### ISSUE THREAD

**Issue by timothydmorton** [dask/fastparquet#317]
I am finding that a particular type of file, containing about 10k columns and written by fastparquet, takes inordinately long to be read by fastparquet, but not so with pyarrow.  As I am unable to reproduce this with synthetic data, I have posted a demo file (only 5 rows, but with the same structure otherwise) [here](http://lsst-web.ncsa.illinois.edu/~tmorton/fastparquet_bug/test_head.parq).

```
import fastparquet
file = 'test_head.parq'
%time pf = fastparquet.ParquetFile(file)
CPU times: user 11.3 s, sys: 20.5 ms, total: 11.3 s
Wall time: 11.3 s
```
And then, after that, even worse to dump to pandas:
```
%time pf.to_pandas()
CPU times: user 26.5 s, sys: 0 ns, total: 26.5 s
Wall time: 26.5 s
```
Pyarrow has no problem:
```
import pyarrow.parquet as pq
%time table = pq.read_table('test_head.parq')
CPU times: user 245 ms, sys: 18.3 ms, total: 263 ms
Wall time: 284 ms
```
and
```
%time table.to_pandas()
CPU times: user 149 ms, sys: 26.2 ms, total: 175 ms
Wall time: 99.6 ms
```

It seems like some book-keeping is taking way too long:
```
%prun pf = fastparquet.ParquetFile(file)
         56934834 function calls (56924628 primitive calls) in 17.071 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     5556   12.852    0.002   16.648    0.003 api.py:460(<listcomp>)
 56735158    3.801    0.000    3.801    0.000 {method 'join' of 'str' objects}
  10207/1    0.142    0.000    0.168    0.168 schema.py:28(schema_to_text)
        1    0.097    0.097    0.158    0.158 {built-in method thrift.protocol.fastbinary.decode_compact}
        1    0.022    0.022   16.690   16.690 api.py:448(_dtypes)
    10207    0.015    0.000    0.015    0.000 ttypes.py:422(__init__)
        1    0.013    0.013   17.071   17.071 <string>:1(<module>)
    10206    0.013    0.000    0.013    0.000 ttypes.py:1357(__init__)
        1    0.013    0.013    0.013    0.013 decoder.py:345(raw_decode)
       28    0.012    0.000    0.012    0.000 {method 'read' of '_io.BufferedReader' objects}
    10211    0.012    0.000    0.012    0.000 {built-in method builtins.hasattr}
    10206    0.011    0.000    0.011    0.000 ttypes.py:293(__init__)
        1    0.009    0.009    0.021    0.021 schema.py:52(flatten)
    10206    0.007    0.000    0.007    0.000 {built-in method builtins.getattr}
        1    0.006    0.006    0.006    0.006 schema.py:13(schema_tree)
    40856    0.005    0.000    0.005    0.000 {built-in method builtins.len}
    10206    0.005    0.000    0.005    0.000 ttypes.py:1258(__init__)
    10206    0.005    0.000    0.005    0.000 ttypes.py:1591(__init__)
        1    0.005    0.005   16.897   16.897 api.py:126(_set_attrs)
        1    0.004    0.004    0.007    0.007 api.py:452(<dictcomp>)
    30622    0.004    0.000    0.004    0.000 {method 'append' of 'list' objects}
        1    0.004    0.004    0.004    0.004 schema.py:78(<listcomp>)
        1    0.003    0.003    0.003    0.003 {method 'copy' of 'collections.OrderedDict' objects}
etc
```

This is using fastparquet version `0.1.4` and pyarrow `0.8.0`.

**Comment by martindurant** [comment]
That is an interesting observation in a rather extreme situation - parquet is not really meant for the huge-number-of-columns case because of the metadata requirements.

The profile you post clearly shows that there is a lot of room for improvement here. The loop in question is testing whether any of the chunks for a given integer column contain NULLs, in which case the final dtype needs to be float (in pandas). The complication is in large part around the column names, which should be computed just once, not on every iteration.

Are you interested in improving the functioning of `fastparquet.ParquetFile._dtypes`?

**Comment by martindurant** [comment]
(answers like "no, I have no time" or "no, I wouldn't know how" are fine)

**Comment by timothydmorton** [comment]
I am in principle interested in helping out, but as it appears I can use pyarrow to do what I need to do, I don't think I can justify taking the time to look into this deeply (nor would I know how to start).  What is pyarrow sacrificing in order to not have a similar problem?  Parquet is actually a good solution for my current problem, where we're storing data in tables with many columns, but typically only need a few at any one time, so the column-store format makes this possible.

**Comment by timothydmorton** [comment]
Related question; is there a way to specify the schema when you initialize a `ParquetFile` (or call `dask.dataframe.read_parquet`) so that it doesn't have to go through this type inference step?

**Comment by timothydmorton** [comment]
Or, is there any way that this testing-for-bools step couldn't be done on write, and then store the information in metadata somehow, (e.g. a `has_nulls` container with a bool entry per column) so it wouldn't have to be inferred?

**Comment by timothydmorton** [comment]
OK, I'm interested.  No promises I'll get anywhere, but I'll play with it for a little bit.
