### ISSUE TITLE
Spark cannot read files with converted type TIMESTAMP_MICROS

### ISSUE THREAD

**Issue by bartek-u** [dask/fastparquet#321]
Hi,

Fastparquet produces files with converted type TIMESTAMP_MICROS. This cannot be read in Spark. Can we add support for writing TIMESTAMP_MILLIS, please?

Kind Regards,
Bartek

**Comment by martindurant** [comment]
This support already exists: use `times='int96'`, see the [docs](https://fastparquet.readthedocs.io/en/latest/details.html#spark-timestamps)

**Comment by bartek-u** [comment]
Thank you for such a fast response! :-)
I will use INT96 for now.

My understanding (based on https://issues.apache.org/jira/browse/PARQUET-323) is that INT96 is deprecated and TIMESTAMP_MILLIS and TIMESTAMP_MICROS are preferred types.

What are your thoughts?

**Comment by martindurant** [comment]
I *completely agree*, however, the big-data world does not (yet) :|

**Comment by martindurant** [comment]
Closing for now. This topic may come around again in the future.
