### ISSUE TITLE
pip install fails in python 3.6 virtual environment

### ISSUE THREAD

**Issue by hugomailhot** [dask/fastparquet#332]
Trying to install fastparquet using pipenv and Python 3.6.

**What I do**

```
$ pipenv install --python 3.6
$ pipenv shell
(test36-gubVLC04) $ pip install fastparquet
```

**What I get**

https://pastebin.com/QKvrp3Bp

**This seems specific to Python 3.6**

The following works without any problem

```
$ pipenv install --python 3.5
$ pipenv shell
(test35-8PQYERv4) $ pip install fastparquet
```

**Comment by hugomailhot** [comment]
Solved it. Just learned that `sudo apt-get install python3-dev` on Ubuntu does not cover Python 3.6, and that I needed to run `sudo apt-get install python3.6-dev`.

**Comment by eduedix** [comment]
are there any plans to make this package python 3.7 compliant?

**Comment by martindurant** [comment]
Yes, it should be available on py37 whenever conda-forge build is updated. I don't believe there is anything fundamental in the cython code that should have any problem with py37. Note that numba is available for py37 on the anaconda channel but not the conda-forge channel.
