### ISSUE TITLE
TIMESTAMP_MILLIS support

### ISSUE THREAD

**Issue by Spacerat** [dask/fastparquet#333]
Hi!

I'm considering adding support to fastparquet for the Parquet TIMESTAMP_MILLIS type. The motivation is to support Amazon Athena (i.e. Presto), which assumes that parquet int64 timestamps are milliseconds and thus reads fastparquet timestamps as being far in the future.

It is actually possible to get round the issue using int96, but given that int96 is supposed to be deprecated, it would be nice to support int64/millis.

Before I try it I just want to:
a) check with you that you would actually accept the diff, and that you haven't limited writes to MICROS for any specific reason
b) confirm that the approach I'm considering would be correct

If you would accept a diff adding MILLIS, then as far as I can tell, the following changes would be required:
- A new option for `times` [here](https://github.com/dask/fastparquet/blob/4b5b3e4e866c924e7f219f7b742215c3a78324a4/fastparquet/writer.py#L132 ) which accepts something like 'int64ms' and outputs a `TIMESTAMP_MILLIS`
- A new condition [here](https://github.com/dask/fastparquet/blob/4b5b3e4e866c924e7f219f7b742215c3a78324a4/fastparquet/writer.py#L198) which checks for `TIMESTAMP_MILLIS` and calls `time_shift` with `factor=1000000`
- Documentation updates & tests

What do you think?

**Comment by xhochy** [comment]
I'm not sure if Presto is able to understand `TIMESTAMP_MILLIS`. From my understanding it is not aware of `TIMESTAMP_MILLIS` or `TIMESTAMP_MICROS` and just implicitly assumes any int that is declared as timestamp in the schema is in milliseconds.

**Comment by martindurant** [comment]
@xhochy , it sounds like it amounts to the same thing in this case? i.e., the column would look like times for readers that handle times explicitly, but presto would be happy too.

@Spacerat , you are welcome to submit the PR as you propose. The reason for only having micros was to preserve as much of the time-resolution from pandas as possible, which always stores times as nanoseconds internally.k

**Comment by xhochy** [comment]
> @xhochy , it sounds like it amounts to the same thing in this case? i.e., the column would look like times for readers that handle times explicitly, but presto would be happy too.

Yes, it would. The information was only meant as an explanation why this is happening
