### ISSUE TITLE
writing partitioned parquet files to s3 via AWS lambda gives a FileNotFoundError

### ISSUE THREAD

**Issue by vipinchadha** [dask/fastparquet#334]
Hi,

I am getting an error when I am trying to write partitioned parquet files when the logic is enclosed in AWS Lambda. The same implmentation works fine on a local or an ec2 instance. Below are the error logs.  I am yet to look at writer.py. But my guess is that it is trying to create a local file structure before pushing the files to s3. For now I will leave it to experts . :)

Thanks

V

{
  "stackTrace": [
    [
      "/var/task/lambda.py",
      18,
      "lambda_handler",
      "write('s3://vipin-parquet/orders/', df, open_with=fh, partition_on=['year', 'month', 'day'], file_scheme='hive',append=True)"
    ],
    [
      "/tmp/pip-install-h1nhEU/fastparquet/fastparquet/writer.py",
      851,
      "write",
      null
    ],
    [
      "/tmp/pip-install-h1nhEU/fastparquet/fastparquet/api.py",
      99,
      "__init__",
      null
    ],
    [
      "/tmp/pip-install-ekrfd6/s3fs/s3fs/core.py",
      315,
      "open",
      null
    ],
    [
      "/tmp/pip-install-ekrfd6/s3fs/s3fs/core.py",
      1102,
      "__init__",
      null
    ],
    [
      "/tmp/pip-install-ekrfd6/s3fs/s3fs/core.py",
      1120,
      "info",
      null
    ],
    [
      "/tmp/pip-install-ekrfd6/s3fs/s3fs/core.py",
      455,
      "info",
      null
    ]
  ],
  "errorType": "FileNotFoundError",
  "errorMessage": "vipin-parquet/orders/"
}

**Comment by vipinchadha** [comment]
Apologies for the stack trace not being formated :(

**Comment by martindurant** [comment]
It is very hard to tell from what you have submitted, but my first guess would be that you do not have permission to write to the s3 location from within Lambda.

**Comment by vipinchadha** [comment]
Hi Martin,

Thanks for the quick reply. I have checked the permissions and they seem to be correct. What I observed was there was a local directory structure similar to the bucket structure created before the files were pushed to s3 bucket. 

The following log I additionally found
Traceback (most recent call last):
  File "/var/task/lambda.py", line 18, in lambda_handler
    write('s3://vipin-parquet/orders/data.parquet', df, open_with=fh, partition_on=['year', 'month', 'day'], file_scheme='hive',append=True)
  File "/tmp/pip-install-h1nhEU/fastparquet/fastparquet/writer.py", line 851, in write
  File "/tmp/pip-install-h1nhEU/fastparquet/fastparquet/api.py", line 99, in __init__
  File "/tmp/pip-install-ekrfd6/s3fs/s3fs/core.py", line 315, in open
  File "/tmp/pip-install-ekrfd6/s3fs/s3fs/core.py", line 1102, in __init__
  File "/tmp/pip-install-ekrfd6/s3fs/s3fs/core.py", line 1120, in info
  File "/tmp/pip-install-ekrfd6/s3fs/s3fs/core.py", line 455, in info
FileNotFoundError: vipin-parquet/orders/

END RequestId: a24ba657-5391-11e8-bf74-4bc4eb1a613c
REPORT RequestId: a24ba657-5391-11e8-bf74-4bc4eb1a613c	Duration: 1572.85 ms	Billed Duration: 1600 ms 	Memory Size: 128 MB	Max Memory Used: 75 MB

**Comment by martindurant** [comment]
Ah, the thing is this: you need to specify the function not only for writing but for creating directories, if using partitioning. In the case of s3, the directory-maker-function is a no-op, since s3 doesn't have real directories.

```
write(..., mkdirs=lambda x: True)
```

Sorry I didn't spot this in your initial description. 
https://fastparquet.readthedocs.io/en/latest/filesystems.html#backend-file-systems

**Comment by vipinchadha** [comment]
Cheers Martin. This was what I was missing.

Cheers

V
