### ISSUE TITLE
Hive-partitioned parquet files are broken

### ISSUE THREAD

**Issue by Spacerat** [dask/fastparquet#335]
Due to this line (I think!): https://github.com/dask/fastparquet/blob/master/fastparquet/core.py#L347

The following code:

```py
import fastparquet
import pandas as pd


fastparquet.write('test.parquet', pd.DataFrame({
    'literal': ['40+2', '1e-10', '"5"', "2018-10-09", "2018-10-10"],
    'idx': [1, 2, 3, 4, 5]
}), partition_on=['literal'], file_scheme='hive')

fastparquet.ParquetFile('test.parquet').to_pandas()
```

produces the following output

<img width="187" alt="screen shot 2018-05-15 at 9 56 13 pm" src="https://user-images.githubusercontent.com/141427/40097402-cdab11e4-588a-11e8-884e-3665d6c50b59.png">

I can see that this has been done so that the after the dataframe has been read back in, the underlying values of the categorical column generated for the partition key are (hopefully likely to be) the type you expect. 

Since the column ends up as a categorical anyway, does it really matter if it’s backed by strings or integers/dates/etc? Or: since the data doesn’t actually exist as typed columns in the parquet files themselves, does it make sense to try to simulate that?

My answers to the above two questions would be no, but if you disagree then I think the `val_to_num` function needs to be made a bit more robust; e.g. by parsing things as dates first and parsing literals in a more deliberate way (or at the very least, white or blacklisting certain characters before parsing)

**Comment by martindurant** [comment]
You are suggesting, essentially, that values should not be parsed at all?
The reason this exists, is so that the user can make meaningful comparisons when filtering (x > 5, etc) and also use the column accessor functions such as `.dt` and `.str`. 
Perhaps the right thing to do would be to warn if all the labels didn't end up having the same type? Can you suggest a way to make `val_to_num` more robust?

**Comment by Spacerat** [comment]
To make sure we're on the same page: by filtering are you referring to the `filters=[('x', '>', 5)]` type filtering, or filtering/processing of the dataframe after it's been loaded into pandas/dask, or both?

**Comment by martindurant** [comment]
Primarily the former, but if the partitioned/catagorical column were to be the index, then potentially the latter too.

**Comment by Spacerat** [comment]
Yeah I suppose I see why it can't be thrown away entirely... If I were being a purist, I think I'd argue for either: 
1.  https://github.com/dask/fastparquet/issues/260
2. and/or the introduction of a `partition_dtypes` argument to `to_pandas`, with a default of `str` for all partitions

However, since (1) would be quite a lot of work and doesn't solve the problem for parquet files not written by Fastparquet, and (2) introduces a breaking API change, then the most practical way forward right now is probably something like:

```
def val_to_num(x):
    if x in ['NOW', 'TODAY']:
        return x
    if set(x) == {'0'}:
        # special case for values like "000"
        return 0
    # Try dates first
    try:
        return pd.to_datetime(x)
    except:
        pass
    try:
        return pd.to_timedelta(x)
    except:
        pass
   # only try to parse as a literal as a last resort
     return _parse_literal(x)

def _parse_literal(x):
    # The contents of this function are up for debate. Another approach would be to just blacklist
    # a few characters then try `int(x)` and `float(x)`
    # '+boxje_' is the most restrictive set of numeric literal characters I could come up with
    # preventing scientific notation, imaginary numbers, binary/hex/octals, arithmetic and
    # the use of _ as a separator.

    if any(c in x for x in "+boxjeBOXJE_'\""): 
        return x
    if '-' in x[1:]: # We still want to allow '-' at the start of the string for negative numbers
        return x

    try:
        return ast.literal_eval(x.lstrip('0'))
    except:
        pass
```

Let me know if this seems reasonable to you or if you'd change any of the details, and I'll make a PR.

**Comment by Spacerat** [comment]
Yeah I think `partition_dtypes` would default to `infer`, but you could give it `str` or a dict of `{name: dtype}`. I think that should come in a separate commit though. 

I'll add the different-types warning but I'm still not sure what to do about timedeltas. If we don't know what the labels looked like then we could just keep them in for now. You'd still hit the cases above but at least we'd have fixed the most obvious usecase: `yyyy-mm-dd` dates.

**Comment by martindurant** [comment]
Yeah, I wouldn't change the timedelta behaviour for the default, some people may be using that.

**Comment by Spacerat** [comment]
There are other aspects to this `val_to_num()` business which will still be broken even after it's been made more robust. For example:

```
df = pd.DataFrame({
    'date': ["2015-05-09", "may-09-2015"],
    'x': [1, 2]
})
fastparquet.write(tempdir, df, file_scheme='hive', partition_on=['date'])
ParquetFile(tempdir).to_pandas() # ValueError: Categorical categories must be unique
```

The same thing happens for other literals, e.g. `['0.7', '.7']`, or (until timestamps are fixed) `['2018-10-15', '2020-10-16']`. 

Should I raise a separate issue for this? Or is this expected/acceptable behaviour? It's possible to fix this in `api.py._read_partitions()` by calling `val_to_num()` on the partition names, which results in the dates here being converted to the same value (despite living in separate folders), but you could argue that no one should partition their folders like that anyway.

**Comment by martindurant** [comment]
If we have the optional conversion you suggested, then it probably comes down to catching this error and providing a good message to the user. It is reasonable to assume that those values are datetimes, and we should attempt to parse them as such - but a conflict will need to be reported. I agree that no one should do that, but you never know.
