### ISSUE TITLE
Error while saving a big pandas dataframe

### ISSUE THREAD

**Issue by sbatururimi** [dask/fastparquet#348]
I'm trying to save a dataframe to disk
```
write(_filename_with_total_num_logs_sorted, df_sorted_by_logs_num, compression="gzip", 
         row_group_offsets=20000000 )
```

returns 
```
OverflowError: int out of range
```

**Comment by martindurant** [comment]
It is possible that you have too many columns in your data. Each row-group can only store a limited number of bytes, which is a combination of the number of rows and columns. Likewise, each column chunk is limited, which can be a problem for string data. Recommend you try reducing the `row_group_offsets` value.

**Comment by sbatururimi** [comment]
No, only 3 columns but the dataframe itself is quite big with many rows. But it helped. The following worked:

```
fastparquet..write(_filename_with_total_num_logs, df, row_group_offsets=100, compression="gzip")
```

Thank you!

**Comment by martindurant** [comment]
Perhaps you wanted something in-between - I assume you now have rather a high fraction of your file-size which is metadata, because it's having to write new headers every 100 rows ;)
