### ISSUE TITLE
MultiIndex.levels become duplicated and fail indexing when using fastparquet

### ISSUE THREAD

**Issue by 0x0L** [dask/fastparquet#349]
(from https://github.com/pandas-dev/pandas/issues/21949)

```python
df = pd.DataFrame(list(range(9)), pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2, 3]]), ['col'])
df.index
# MultiIndex(levels=[['a', 'b', 'c'], [1, 2, 3]],
#            labels=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]])
df.to_parquet('test.parquet', engine='fastparquet')
df1 = pd.read_parquet('test.parquet', engine='fastparquet')
df1.index
# MultiIndex(levels=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c'], [1, 2, 3, 1, 2, 3, 1, 2, 3]],
#            labels=[[0, 1, 2, 3, 4, 5, 6, 7, 8], [0, 1, 2, 3, 4, 5, 6, 7, 8]],
#            names=['level_0', 'level_1'])
# 
df.loc['a', 1]
# col    0
# Name: (a, 1), dtype: int64
df1.loc['a', 1]
# Traceback (most recent call last):
...
# TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>
```

The index can be fixed with
```
df1.reset_index().set_index(['level_0', 'level_1'])
```

@martindurant
Good thing you didn't release a new version last week :)

I can see two ways to fix this:

* simple one: remove all index logic form `empty` just treat indexes as regular columns and add a call to `set_index` in each and every single methods returning a dataframe

* less simple one: use a class for the view (instead of a plain numpy array) that would take care of updating the multi-index correctly. I have no idea how this would impact the performances

What do you think ?

**Comment by martindurant** [comment]
I'm sorry, "simple one" if a no-starter, the whole purpose of `empty()` is to make a DataFrame that can be filled in. Such pandas operations can be very expensive! If you can call `set_index()` within `empty` before extending the size...

**Comment by 0x0L** [comment]
We don't know the unique levels at that point

**Comment by 0x0L** [comment]
WIP
https://github.com/0x0L/fastparquet/commit/03a80b62a0c360388160446239d53c060e26ae6d

I haven't tested the performances yet but I suspect it'll be really bad :(

**Comment by martindurant** [comment]
@TomAugspurger , do you have any insight into the right way to do this?

**Comment by TomAugspurger** [comment]
Remind me what the goal is again? Allocate an empty multiindex of size `size`? Does it matter what the `labels` for each level are?

**Comment by martindurant** [comment]
To create a dataframe of given size, with a multi-index where we can get corresponding numpy arrays for each level, and fill them in from the data. We know the names of the "levels" (which are ordinary columns int he parquet data).

**Comment by TomAugspurger** [comment]
What versions of pandas / fastparquet reproduce the exception? The snippet runs for me without exception using fastparquet master and pandas 0.23.3.

**Comment by martindurant** [comment]
The whole point of this function is to produce an allocated dataframe and numpy views into its pieces for direct assignment of data. 

In the fastparquet context, anyone who want to load the data and set the index after the fact can already do with (with in `to_pandas(index=False)`).

**Comment by 0x0L** [comment]
Numpy pieces for the indexes would still be allocated for assignement. But a multi-index is not just a collection of two such columns you have to do so more work to get a multi-index.

**Comment by martindurant** [comment]
If the scenario I propose is not possible, I would revert the multi-index effort and only deal with the simple index case, allow the user to call set_index at their convenience.

**Comment by 0x0L** [comment]
I agree but i don't see why by default you don't want to call `.set_index` at the end. User can still use `index=False`

**Comment by martindurant** [comment]
Am I right in thinking that the internal storage model for multi-index is in fact a single numpy array, containing tuples of values? I don't suppose we can persuade anyone that this should be a 2D numpy array, but I do wonder why.

**Comment by 0x0L** [comment]
No it isn't, see the snippet:
```
# MultiIndex(levels=[['a', 'b', 'c'], [1, 2, 3]],
#            labels=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]])
```
A level is a pandas Index (apparently ordered when it can) with unique elements.
Labels have the same size as the dataframe and they hold the actual values of the multi index (kind like your pair of tuples) but they are encoded through the levels.

In the case of the snippet above:
```
(0, 0) -> 'a', 1
(0, 1) -> 'a', 2
...
(1, 0) -> 'b', 1
...
```

**Comment by martindurant** [comment]
Hm, looks suspiciously like dictionary encoding; in the case that the data was written by fastparquet (i.e., following reset_index), would the index columns become category-encoded? Can we use categorical columns for the index, are they used internally?

**Comment by 0x0L** [comment]
The data is written as plain columns (as pyarrow does)

but... for truly a categorical index in a multiindex eg:

```python
df = pd.DataFrame(list(range(9)), pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2, 3]]), ['col'])
df = df.reset_index()
df['level_0'] = df['level_0'].astype('category')
df = df.set_index(['level_0', 'level_1'])

df.index.levels[0]
# CategoricalIndex(['a', 'b', 'c'], categories=['a', 'b', 'c'], ordered=False, name='level_0', dtype='category')

df.index.labels[0]
# FrozenNDArray([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype='int8')
```

pyarrow looses the categorical nature of level_0

```python
df.to_parquet('test.parquet', engine='pyarrow')
df1 = pd.read_parquet('test.parquet', engine='pyarrow')

df1.index.levels[0]
# Index(['a', 'b', 'c'], dtype='object', name='level_0')
```

but fastparquet does not

```python
df.to_parquet('test.parquet', engine='fastparquet')
df1 = pd.read_parquet('test.parquet', engine='fastparquet')

df1.index.levels[0]
# CategoricalIndex(['a', 'b', 'c'], categories=['a', 'b', 'c'], ordered=False, name='level_0', dtype='category')
```

**Comment by 0x0L** [comment]
I did some timings. `df.index = ...` is only a matter of microseconds (for indexes and multi-indexes) so having a finalizer wouldn't impact performance at all.

For a multi-index, in the finalizer, prior to assigning df.index, we would need to call `pd.MultiIndex.from_arrays([...])` with the various pre-assigned indexes. This is the slow part. Looking at pandas code, this boils down to calling `pd.Categorical(...)` on each index. It's slow but I imagine this has already been optimized

**Comment by martindurant** [comment]
The time taken grown super-linearly:
```
In [4]: df, arrs = fastparquet.dataframe.empty('i4,u2,f4,f2,f4,M8,m8', size=1000000)

In [5]: %timeit df.set_index(['0', '1'])
49.7 ms ± 224 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: df, arrs = fastparquet.dataframe.empty('i4,u2,f4,f2,f4,M8,m8', size=10000000)

In [7]: %timeit df.set_index(['0', '1'])
693 ms ± 18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
**much** longer than the assignment of the empty dataframe.

**Comment by 0x0L** [comment]
You should not do it with `set_index` but with `.index = ` (and have the index already exist as pd.Index separately). We would still preallocate the pd.Index(es) in `empty`. Only for a multi-index we would need to actually build it before calling `set_index`.

**Comment by martindurant** [comment]
So like:

```
index = pd.MultiIndex(levels=[arrs['index0-catdef',] arrs['index1-catdef']],
    labels=[arrs['index0'], arrs['index1']]
df.index = index
```
which can be done within `empty`?
This only works for categorical columns, of course.

**Comment by 0x0L** [comment]
The way I see it `empty` returns a triple `idx, df, views` with `idx` being a list of (preallocated) `pd.Index` (views would still contain the views to the indexes too)

In `iter_row_groups` and `to_pandas` before returning `df` we have something along

```python
if len(idx) == 1:
    df.index = idx
elif len(idx) > 1:
    df.index = pd.MultiIndex.from_array(*idx)
```

**Comment by 0x0L** [comment]
@TomAugspurger This looks strange:

```python
i = pd.Index(np.linspace(-1, 1, 1000000))
%timeit pd.MultiIndex.from_arrays([i])
# 228 ms ± 2.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

j = i.astype('category')
%timeit pd.MultiIndex.from_arrays([j])
# 178 ms ± 431 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

I would expect the second call to be as fast as calling `pd.MultiIndex(levels=[j.categories], labels=[j.codes], verify_integrity=False)`. See https://github.com/pandas-dev/pandas/blob/edb71fda022c6a155717e7a25679040ee0476639/pandas/core/arrays/categorical.py#L2510

**Comment by TomAugspurger** [comment]
I'm not really familiar with that section of pandas. If you see any room
for improvement though, please open an issue / PR for pandas.

**Comment by 0x0L** [comment]
@TomAugspurger 
See https://github.com/pandas-dev/pandas/issues/22044

**Comment by martindurant** [comment]
Thanks for posting. I tried a few thing without getting anywhere, so lets hold off to see if the pandas people can say something useful.

**Comment by martindurant** [comment]
I guess it can be OK, but it still feels wrong, like we are having to do unnecessary work. If the logic can be kept entirely within `empty()`, I'd be far happier. You should be aware than a change like this will require reworking code in dask, so it's not as small an undertaking as you suggest.

**Comment by 0x0L** [comment]
Changes in `dask` look rather minimal: I could spot one call to `_pre_allocate` and it would only involve changing the return values of the call to `_pre_allocate` plus a one line addition along `df = _attach(df, idx)` just like in our own methods in fastparquet

**Comment by martindurant** [comment]
In order to not break backwards compatibility current dask, could the multi-index become an entry in the dict-of-arrays, rather than having an extra return value? That way, the new dask code could be `if 'multi-index' in arrs:`, and the entry is ignored in the current code.

Otherwise, I'm OK to go with your plan, because a slow multi-index is still better than a non-functional one.

**Comment by 0x0L** [comment]
The slowness comes from the fact we have to encode the index columns. That's a pandas requirement and there's no way around it. Either on the fly or at the end, it is slow process.

While it does not change the (non public) api, doing it on the fly like in https://github.com/0x0L/fastparquet/commit/03a80b62a0c360388160446239d53c060e26ae6d would certainly require highly customized cython code to be on-par performance with pandas. I honestly doubt that's even possible without any prior knowledge of the number of categories.

Regarding dask IMO it makes more sense to wait for their next release.

**Comment by martindurant** [comment]
Unfortunately, waiting for Dask isn't really an option: if people have newer dask and older fastparquet or vice-versa, they wouldn't be able to use read_parquet if we were to change the `empty()` function's return signature. I'd really like to avoid even temporary breakage, if possible (right now it's only broken for the multiple-index case, which will be rare).
