### ISSUE TITLE
Can't write DataFrame as parquet on S3

### ISSUE THREAD

**Issue by airanzad** [dask/fastparquet#350]
I have a simple code to create a DataFrame and save it as Parquet on S3. 

```
import pandas as pd
import s3fs
import fastparquet as fp
s3 = s3fs.S3FileSystem()
myopen = s3.open
nop = lambda *args, **kwargs: None

fileContents = """
{
"Results": [{
"Test": {
"Address": "[nil]",
"Type": "PowerON",
"TestStartTime": "02/02/2018 15:58:54",
"TestStopTime": "02/02/2018 15:59:20"
}]
}
"""

def writeDataForYear():
    year = 2018
    for x in range(1, 365):
        day = x 
        for y in range(1, 5):
            resId = str(year) + "_" + str(day) + "_" + str(y)
            data = {'SerialNumber': ['SN'], 'Year': [year], 'Day': [day], 'RawData': [fileContents]}
            data_frame = pd.DataFrame(data)        
            fp.write('bucket_name/fastparquet.parq', data_frame, partition_on = ['Day', 'Year'], open_with = myopen, mkdirs = nop, append = True)
    pf = fp.ParquetFile(outputFile)
    data_frame2 = pf.to_pandas(['Day', 'Year', 'SerialNumber'], filters=[('Day', 'in', [1, 100, 110,199])])
    print(data_frame2)
```

But it returns error:

> /var/task/fastparquet/writer.py:217: FutureWarning: Method .valid will be removed in a future version. Use .dropna instead.
  head = data[:10] if isinstance(data, pd.Index) else data.valid()[:10]
bucket_name/fastparquet.parq: FileNotFoundError
Traceback (most recent call last):
  File "/var/task/writeParquet.py", line 3429, in handler
    writeDataForYear(2018)
  File "/var/task/writeParquet.py", line 3420, in writeDataForYear
    fp.write('bucket_name/fastparquet.parq', data_frame, partition_on = ['Day', 'Year'], open_with = myopen, mkdirs = nop, append = True)
  File "/var/task/fastparquet/writer.py", line 848, in write
    compression, open_with, has_nulls, append)
  File "/var/task/fastparquet/writer.py", line 698, in write_simple
    pf = api.ParquetFile(fn, open_with=open_with)
  File "/var/task/fastparquet/api.py", line 99, in __init__
    with open_with(fn, 'rb') as f:
  File "/var/task/s3fs/core.py", line 315, in open
    s3_additional_kwargs=kw)
  File "/var/task/s3fs/core.py", line 1102, in __init__
    info = self.info()
  File "/var/task/s3fs/core.py", line 1120, in info
    refresh=refresh, **kwargs)
  File "/var/task/s3fs/core.py", line 455, in info
    raise FileNotFoundError(path)
FileNotFoundError: bucket_name/fastparquet.parq

I can't figure out what the problem is. Looks like it is a bug.

**Comment by martindurant** [comment]
Does `s3://bucket_name/fastparquet.parq` exist?

**Comment by airanzad** [comment]
Hi Martin,
To give you a bit of background, my ultimate goal is to create a parquet file and gradually append to it.

Now, if I set append to False, it succeeds no matter if  

> s3://bucket_name/fastparquet.parq 

exists or not. 

If append is set to True and s3://bucket_name/fastparquet.parq exists, it gives this error:

> 
> /var/task/fastparquet/writer.py:217: FutureWarning: Method .valid will be removed in a future version. Use .dropna instead.
>   head = data[:10] if isinstance(data, pd.Index) else data.valid()[:10]
> File mode must be {'rb', 'wb', 'ab'}, not rb+: NotImplementedError
> Traceback (most recent call last):
>   File "/var/task/writeParquet.py", line 3429, in handler
>     writeDataForYear(2018)
>   File "/var/task/writeParquet.py", line 3420, in writeDataForYear
>     fp.write(outputFile, df, partition_on = ['Day', 'Year'], open_with = myopen, mkdirs = nop, append = True)#,file_scheme = 'hive')
>   File "/var/task/fastparquet/writer.py", line 848, in write
>     compression, open_with, has_nulls, append)
>   File "/var/task/fastparquet/writer.py", line 706, in write_simple
>     with open_with(fn, mode) as f:
>   File "/var/task/s3fs/core.py", line 315, in open
>     s3_additional_kwargs=kw)
>   File "/var/task/s3fs/core.py", line 1048, in __init__
>     "not %s" % mode)
> NotImplementedError: File mode must be {'rb', 'wb', 'ab'}, not rb+
> 
> Exception ignored in: <object repr() failed>
> Traceback (most recent call last):
>   File "/var/task/s3fs/core.py", line 1411, in __del__
>     self.close()
>   File "/var/task/s3fs/core.py", line 1371, in close
>     if self.closed:
> AttributeError: 'S3File' object has no attribute 'closed'  

If append is set to True and s3://bucket_name/fastparquet.parq doesn't exist, it gives this error:

> bucket_name/fastparquet.parq: FileNotFoundError
> Traceback (most recent call last):
>   File "/var/task/writeParquet.py", line 3429, in handler
>     writeDataForYear(2018)
>   File "/var/task/writeParquet.py", line 3420, in writeDataForYear
>     fp.write(outputFile, df, partition_on = ['Day', 'Year'], open_with = myopen, mkdirs = nop, append = True)#,file_scheme = 'hive')
>   File "/var/task/fastparquet/writer.py", line 848, in write
>     compression, open_with, has_nulls, append)
>   File "/var/task/fastparquet/writer.py", line 698, in write_simple
>     pf = api.ParquetFile(fn, open_with=open_with)
>   File "/var/task/fastparquet/api.py", line 99, in __init__
>     with open_with(fn, 'rb') as f:
>   File "/var/task/s3fs/core.py", line 315, in open
>     s3_additional_kwargs=kw)
>   File "/var/task/s3fs/core.py", line 1102, in __init__
>     info = self.info()
>   File "/var/task/s3fs/core.py", line 1120, in info
>     refresh=refresh, **kwargs)
>   File "/var/task/s3fs/core.py", line 455, in info
>     raise FileNotFoundError(path)
> FileNotFoundError: bucket_name/fastparquet.parq

**Comment by martindurant** [comment]
The error message is correct: you cannot truncate a file on s3fs, which would be required to append to parquet in single-file mode (because the footer needs to be chopped off and moved to the end of the file). If using append=True, the data-set should exist, and for s3fs, it should be in hive or other multi-file format.

**Comment by danielhaviv** [comment]
In my use case I'm reading a parquet file row-group by row-group and would like to write it back row-group by row-group (so no need to chop off the footer as it is completely being overwritten)

How about supporting append for an explicit overwrite?

**Comment by martindurant** [comment]
I'm not sure quite how that would work - you need to keep in memory all the row-groups of a file, so that you can write the footer when done. The code basically does this internally, if you specify how many rows to include in each row-group, except of course it is iterating through a single in-memory dataframe. You are welcome to delve into the writer to make it read from an arbitrary generator of dataframe pieces, if you like.
