### ISSUE TITLE
allow_empty parameter has been deleted in python-zstandard 0.9

### ISSUE THREAD

**Issue by thrasibule** [dask/fastparquet#354]
See release note https://github.com/indygreg/python-zstandard/blob/d530bc7689c07bad67161d1d679dc57275f83e71/NEWS.rst. which causes this line to break: https://github.com/dask/fastparquet/blob/master/fastparquet/compression.py#L95

**Comment by martindurant** [comment]
Thanks for the note. Would you like to provide a PR? I assume the older version still requires the kwarg.

**Comment by thrasibule** [comment]
I can provide a PR. How should I do the fallback, should I just catch the exception? or explicitly test for the version?
