### ISSUE TITLE
Remaining differences with pyarrow

### ISSUE THREAD

**Issue by martindurant** [dask/fastparquet#374]
This is a list of functionality that I believe fastparquet implements but pyarrow does not. It should be considered for making a set of JIRAs in arrow, should there be will to implement any of them (@wesm). Please help by adding to this list anything I have missed or noting things that already do also exist in pyarrow.

The list is in no particular order.

- JSON and BSON encoding
- reading of array and map types
- directory-based partitioning in "drill" style
- direct reading and writing of categoricals
- use of metadata files to avoid pre-scan of all data files
- filtering on index or specific columns which have chunk-level max/min information
- column-level choice of object encoding and optional/required
- parameters passed to compression backends
- arbitrary row-group splitting
- fixed-length string and bytes types
- 8- and 12-bytes times
- (new) read datasets without scanning the files at all in the client

**Comment by mrocklin** [comment]
A few thoughts:

1.  These are all features, but are they important features?  Are these things that people have actively wanted from parquet in practice?  My guess is that for some yes, but for others they might be a very low priority
2.  I think that for those that are valuable, it would be polite to raise them on Arrow's Jira.  I don't think that we can reasonably expect Arrow developers to track fastparquet's issue tracker.  We also probably can't expect @wesm to handle all of this, so it's probably more important to raise these individually where the full Arrow community can see.
3.  I'm particularly interested in those issues that are necessary in order for dask.dataframe to change its default from fastparquet to pyarrow.  I know that some issues, like the use of metadata files and min/max chunk-level information are particularly valuable.  It might be useful to highlight these.

**Comment by martindurant** [comment]
@mrocklin , I do generally agree, but I wanted to gather things here first before making JIRAs, maybe give this a week or so to cover my ignorance of the present state of pyarrow's parquet, and perhaps remember some more differences.

I didn't want to make value judgements on importance here, but leave it to arrow to say whether they thought something should/would be implemented on their side, and for dask to separately decide how painful it would be to forego some feature.

**Comment by wesm** [comment]
I would suggest applying the YAGNI principle when exposing features in dask. For object encoding, for example, we have never had anyone request this functionality. Given how many other projects we have going on, it's hard to imagine prioritizing a feature based on hypothetical need.

**Comment by mrocklin** [comment]
> I didn't want to make value judgements on importance here, but leave it to arrow to say whether they thought something should/would be implemented on their side, and for dask to separately decide how painful it would be to forego some feature.

Perhaps then you can put on your dask dataframe maintainer hat and determine the features that you believe would be necessary for dask.dataframe to switch its default to pyarrow and make JIRAs for those if they don't exist, or chime in on a JIRA if they already exist.  By informing the Arrow community about our needs and our plans then maybe they can prioritize that work, or maybe we can help.  

This will probably require a bit of research on your part to read Arrow's existing JIRAs on this topic and to understand the state of parquet reading in Arrow today.  Can I ask you to take on this work?

**Comment by mrocklin** [comment]
I don't think we need to wait a week.  I think that we should engage the Arrow community now.

**Comment by martindurant** [comment]
JIRAS:

 -https://jira.apache.org/jira/browse/ARROW-3244
- https://jira.apache.org/jira/browse/ARROW-3245
- https://jira.apache.org/jira/browse/ARROW-3246
- https://jira.apache.org/jira/browse/ARROW-3247

**Comment by mrocklin** [comment]
Thanks for putting those together @martindurant !
