### ISSUE TITLE
ZSTD implemented wrong if `zstd` is installed

### ISSUE THREAD

**Issue by dargueta** [dask/fastparquet#381]
When calling `write()` with `compression='zstd'`, if you have [`zstd`](https://pypi.org/project/zstd/) installed instead of `zstandard` you get the following exception:

```
Traceback (most recent call last):
  File "./load_logs.py", line 80, in <module>
    load_files()
  File "./load_logs.py", line 77, in load_files
    compression='zstd', engine='fastparquet', has_nulls=False)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pandas/core/frame.py", line 1945, in to_parquet
    compression=compression, **kwargs)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pandas/io/parquet.py", line 257, in to_parquet
    return impl.write(df, path, compression=compression, **kwargs)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pandas/io/parquet.py", line 218, in write
    compression=compression, **kwargs)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/writer.py", line 848, in write
    compression, open_with, has_nulls, append)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/writer.py", line 717, in write_simple
    compression=compression)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/writer.py", line 614, in make_row_group
    compression=comp)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/writer.py", line 536, in write_column
    bdata = compress_data(bdata, compression)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/compression.py", line 133, in compress_data
    return compressions[algorithm.upper()](data)
  File "/Users/dargueta/.pyenv/versions/3.7.0/lib/python3.7/site-packages/fastparquet/compression.py", line 94, in zstd_compress
    cctx = zstd.ZstdCompressor(**kwargs)
AttributeError: module 'zstd' has no attribute 'ZstdCompressor'
```

Using `zstd` instead of `zstandard` *is* supported in theory, but the bug appears to be a copy-paste error. The compression and decompression functions can be simplified to something like the following:

```py
def zstd_compress(data, compression_level=None):
    if compression_level is not None:
        return zstd.compress(data, compression_level)
    return zstd.compress(data)
def zstd_decompress(data):
    return zstd.decompress(data)
```

Environment:
* Python 3.7.0
* MacOS High Sierra
* Packages:

```
fastparquet==0.1.6
zstd==1.3.5.1
```

**Comment by martindurant** [comment]
Would you mind turning this into a PR?
Can there be a test for zstd versus zstandard in Travis, or are they mutually exclusive?

**Comment by dargueta** [comment]
> Would you mind turning this into a PR?

Yep! I can do that later this week.

> Can there be a test for zstd versus zstandard in Travis, or are they mutually exclusive?

[Possibly?](https://stackoverflow.com/a/1350574)

**Comment by CarrierDiagnostics** [comment]
when pip install zstd and pip install zstandard getting:

`AttributeError: module 'zstd' has no attribute 'ZstdDecompressor'`
`AttributeError: module 'zstandard' has no attribute 'ZstdDecompressor'`

**Comment by martindurant** [comment]
I don't know...
I have the conda versions (py37 in this case):
```
In [1]: import zstandard

In [2]: zstandard.ZstdDecompressor
Out[2]: zstd.ZstdDecompressor

In [3]: import zstd

In [4]: zstd.ZstdDecompressor
Out[4]: zstd.ZstdDecompressor
```

**Comment by CarrierDiagnostics** [comment]
added that I use python 3.6.8

**Comment by martindurant** [comment]
Same on 36:
```
> conda create -n py36 python=3.6 zstandard -c conda-forge
> conda activate py36
> python
Python 3.6.10 | packaged by conda-forge | (default, Mar  5 2020, 09:56:10)
[GCC Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zstd
>>> zstd.ZstdDecompressor
<class 'zstd.ZstdDecompressor'>
```

**Comment by CarrierDiagnostics** [comment]
`Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import zstd
>>> zstd.ZstdDecompressor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'zstd' has no attribute 'ZstdDecompressor'`

**Comment by martindurant** [comment]
Perhaps a good idea at the this point to specify:
- how you installed python
- how you installed zstd/zstandard
- the repr of `zstd` after import

**Comment by martindurant** [comment]
Does the workaround at the top of this thread work for you? If so, you could submit it as a PR. I don't know anything about zstandard in particular... :)

**Comment by CarrierDiagnostics** [comment]
Perhaps a good idea at the this point to specify:

how you installed python - executable from python site, all other modules work
how you installed zstd/zstandard - as stated, used PIP
the repr of zstd after import - sorry not sure what you mean here.

Yes I have tried both zstandard and zstd

**Comment by martindurant** [comment]
> the repr of zstd after import

By doing
```
>>> zstd
```
at the python prompt and seeing what comes back. `dir(zstd)` would be a good thing to try too, in case the `decompress` function is indeed there, as suggested at the very top.

**Comment by CarrierDiagnostics** [comment]
`>>> import zstd
>>> zstd
<module 'zstd' from 'C:\\Python36\\lib\\site-packages\\zstd.cp36-win_amd64.pyd'>
>>> dir(zstd)
['Error', 'ZSTD_compress', 'ZSTD_uncompress', 'ZSTD_version', 'ZSTD_version_number', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'compress', 'decompress', 'dumps', 'loads', 'uncompress', 'version']`

**Comment by martindurant** [comment]
Hah, so a matter of capitalisation. Clearly the conda team patches zstd for us. However, there is a `decompress` function, so it would be fine to use the simpler method.

**Comment by CarrierDiagnostics** [comment]
But I'm trying to stream the decompression, I don't think I can use decompress to do that

**Comment by martindurant** [comment]
Sorry, I don't follow - the functions in fastparquet.compression only de/compress whole blocks, they do not stream.

**Comment by CarrierDiagnostics** [comment]
thanks for your help. If anyone else knows please chime in
