### ISSUE TITLE
ParquetFile.to_pandas changes global `cols` object

### ISSUE THREAD

**Issue by kylebarron** [dask/fastparquet#383]
I tend to name the list of columns that I want to import `cols`. To my surprise, after reading a file with `to_pandas`, the `cols` list is mutated. I assume this is a bug, that the reader shouldn't mutate an object in the global scope?

```py
>>> import pandas as pd
>>> import fastparquet as fp
>>> df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
>>> df.to_parquet('test.parquet')
>>> cols = ['a']
>>> pf = fp.ParquetFile('test.parquet')
>>> df = pf.to_pandas(columns=cols)
>>> cols
['a', '__index_level_0__']
```

**Comment by kylebarron** [comment]
It appears that the input list of columns is always mutated. Is this just an instance of a missing `list.copy()`, so that the changes that happen within `ParquetFile.to_parquet` don't propagate back to the original list?

**Comment by martindurant** [comment]
Would you like to make a PR, and include a test along the lines of your code above, showing that the cols input is no longer changed?
