### ISSUE TITLE
If you are interested I have some changes I made in a fork off of your repo a while back

### ISSUE THREAD

**Issue by bdrosen96** [dask/fastparquet#40]
This is in https://github.com/bdrosen96/parquet-python . I'm not sure if any of these changes might be useful, but if so feel free to take any of them. Some of the changes include:

Python 3 support

Switch from thrift to thriftpy

Boolean array

Filesystem class

Reader class with support for multiple files.

Proper support for dictionary

Optimization using cython for some operations for significant performance gain. (order of magnitude)

**Comment by martindurant** [comment]
I'm sorry I didn't know about your optimizations before starting this endeavour. As you can see, this codebase has now diverged significantly from the original parquet-python, and performance is many orders of magnitude better, using numpy and numba. 
I will read through your changes though, to see if there's anything useful there from our point of view.

**Comment by martindurant** [comment]
@bdrosen96 , if you have specific suggestions for improvements, I'd be happy to hear them. Closing this for now, as your changes are really for parquet-python than here.
