### ISSUE TITLE
FR: Accept a file-like object in addition to a path in `fastparquet.write`

### ISSUE THREAD

**Issue by tswast** [dask/fastparquet#408]
pyarrow accepts either a filename or a file-like object when writing a DataFrame. It would be very helpful if fastparquet also does this. I found https://github.com/dask/fastparquet/issues/215 which adds a special in-memory path name, but that seems specific to the dask-ecosystem.

Currently `google-cloud-bigquery` requires `pyarrow` rather than `fastparquet` to upload a DataFrame to BigQuery due to this issue.

**Comment by martindurant** [comment]
Is the `open_with` parameter to [`write`](https://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.write) not sufficient for this? Dask and other libraries successfully use this with fastparquet to write to S3, GCS, etc.

**Comment by martindurant** [comment]
Which API method are you trying to use? I see nothing about parquet files in https://googleapis.github.io/google-cloud-python/latest/bigquery/reference.html#client

**Comment by tswast** [comment]
`google-cloud-bigquery` calls `to_parquet` on a pandas DataFrame in the `Client. load_table_from_dataframe` method.

https://github.com/googleapis/google-cloud-python/blob/master/bigquery/google/cloud/bigquery/client.py#L1091-L1092

Currently we are passing in a file-like BytesIO object, which is consistent with what we were doing with `to_csv` before we switched to parquet in order to better handle array/struct columns. pyarrow accepts a file-like just fine, but fastparquet does not.

**Comment by tswast** [comment]
It sounds like `pandas` could potentially pass in `open_with=lambda x: x` when a file-like is passed if we bumped the path/file detection up to that layer?

**Comment by martindurant** [comment]
Yes, you could do this
```
i = io.ByesIO()
df.to_parquet('noname', engine='fastparquet', open_with=lambda x, y: i)
```
Unfortunately, the write closes the BytesIO object, discarding the contents (I wonder what arrow does about this??)
You would, therefore, have to use a custom one:
```
class newBytes(io.BytesIO):
     def close(self):
        pass
i = newBytes()
df.to_parquet('noname', engine='fastparquet', open_with=lambda x, y: i)
i.getvalue()  # binary contents
```

**Comment by martindurant** [comment]
Note that https://github.com/dask/fastparquet/pull/378 is actually the link you wanted - this could theoretically be put directly into the library.

**Comment by martindurant** [comment]
Basically, I think its better to deal with file-systems than file-like objects or path things.

**Comment by ospikovets** [comment]
@martindurant a code snippet in [this](https://stackoverflow.com/a/57838851) stackoverflow comment is a good example of the use case for supporting a file-like object when writing a DataFrame.

It is definitely possible to do what you suggest [here](https://github.com/dask/fastparquet/issues/408#issuecomment-467682064), it just doesn't look as "elegant" as simply passing the file-like.

Any chance `fastparquet` will support that in the future?
