### ISSUE TITLE
column index name(s) not persisted on save or load

### ISSUE THREAD

**Issue by timothydmorton** [dask/fastparquet#409]
fastparquet does not persist column index name information, and appears to not support multiindexing?
```python
import pandas as pd
import numpy as np
from fastparquet import write, ParquetFile
from pandas.util.testing import assert_frame_equal

column_index = pd.Index(['a', 'b'], name='column')
df = pd.DataFrame(np.random.random((4, 2)), columns=column_index)

def test_roundtrip_fastparquet(df):    
    print(df.columns)
    write('test.parq', df)
    pf = ParquetFile('test.parq')
    df2 = pf.to_pandas()
    print(df2.columns)
    assert_frame_equal(df, df2)
    
test_roundtrip_fastparquet(df)
```
running this gives:
```
Index(['a', 'b'], dtype='object', name='column')
Index(['a', 'b'], dtype='object')
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-57-3692bf07de0a> in <module>
     15     assert_frame_equal(df, df2)
     16 
---> 17 test_roundtrip_fastparquet(df)
...etc
```
In contrast, pyarrow works:
```python
import pyarrow as pa
import pyarrow.parquet as pq

def test_roundtrip_pyarrow(df):
    print(df.columns)
    table = pa.Table.from_pandas(df)
    pq.write_table(table, 'test2.parq')
    df2 = pq.ParquetFile('test2.parq').read(use_pandas_metadata=True).to_pandas()
    print(df2.columns)
    assert_frame_equal(df, df2)
    
test_roundtrip_pyarrow(df)
```
Gives 
```
Index(['a', 'b'], dtype='object', name='column')
Index(['a', 'b'], dtype='object', name='column')
```
A multi-level column index fails:
```python
column_index_multi = pd.MultiIndex.from_tuples([('a', 'b'), ('a', 'c')], names=['level1', 'level2'])
df_multi = pd.DataFrame(np.random.random((4,2)), columns=column_index_multi)
test_roundtrip_fastparquet(df_multi)
```
gives
```
MultiIndex(levels=[['a'], ['b', 'c']],
           labels=[[0, 0], [0, 1]],
           names=['level1', 'level2'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-63-66bcf22cf107> in <module>
      1 column_index_multi = pd.MultiIndex.from_tuples([('a', 'b'), ('a', 'c')], names=['level1', 'level2'])
      2 df_multi = pd.DataFrame(np.random.random((4,2)), columns=column_index_multi)
----> 3 test_roundtrip_fastparquet(df_multi)

<ipython-input-57-3692bf07de0a> in test_roundtrip_fastparquet(df)
      9 def test_roundtrip_fastparquet(df):
     10     print(df.columns)
---> 11     write('test.parq', df)
     12     pf = ParquetFile('test.parq')
     13     df2 = pf.to_pandas()

~/.local/lib/python3.6/site-packages/fastparquet/writer.py in write(filename, data, row_group_offsets, compression, file_scheme, open_with, mkdirs, has_nulls, write_index, partition_on, fixed_text, append, object_encoding, times)
    842     fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
    843                         fixed_text=fixed_text, object_encoding=object_encoding,
--> 844                         times=times, index_cols=index_cols)
    845 
    846     if file_scheme == 'simple':

~/.local/lib/python3.6/site-packages/fastparquet/writer.py in make_metadata(data, has_nulls, ignore_columns, fixed_text, object_encoding, times, index_cols)
    666             continue
    667         pandas_metadata['columns'].append(
--> 668             get_column_metadata(data[column], column))
    669         oencoding = (object_encoding if isinstance(object_encoding, STR_TYPE)
    670                      else object_encoding.get(column, None))

~/.local/lib/python3.6/site-packages/fastparquet/util.py in get_column_metadata(column, name)
    221         raise TypeError(
    222             'Column name must be a string. Got column {} of type {}'.format(
--> 223                 name, type(name).__name__
    224             )
    225         )

TypeError: Column name must be a string. Got column ('a', 'b') of type tuple
```
Whereas it works for pyarrow.  

I had switched to pyarrow for my current purposes I think mostly because of the lack of multi-level column index support, but then pyarrow is having problems loading large files that fastparquet *does* load, except for this issue with the column index name.

**Comment by martindurant** [comment]
Note that you *can* specify multiple columns as the index when loading, like `df2 = pf.to_pandas(index=('a', 'b'))`.

It seems that the pandas metadata description created and implemented by pyarrow is ahead of fastparquet. It would be good to see what is in the metadata for the arrow-made file, and change fastparquet's creation and parsing of that to match. Would you like to take this on? I don't imagine it taking too much effort.

**Comment by timothydmorton** [comment]
Sure, happy to look into it.

**Comment by timothydmorton** [comment]
Hi @martindurant; I'm making progress on this ('issue-409' branch on my fork), in that I have gotten my above test to work.  However, it has now broken some of the other fastparquet unit tests.  In particular, one of the tests seems to fail because the demo dataframe has a categorical column, which gets duplicated in `cols` within `_pre_allocate()`, and then one of the functions borrowed from pyarrow fails because of this duplication.  I will keep poking around, but thought I'd just ping you at this stage in case you have any guidance.

**Comment by martindurant** [comment]
> one of the functions borrowed from pyarrow

You pandas mean metadata handling? That is changing anyway in pandas/arrow, so now would be a good time to try to be rigorous about it.

**Comment by timothydmorton** [comment]
Oh it is?  I don't really know anything about those details.  I was just trying to reproduce in fastparquet the pandas_compat stuff from pyarrow, but if a bunch of that stuff is changing, then someone else with more knowledge about that had better work on this...

**Comment by martindurant** [comment]
Please don't be discouraged! The [PR](https://github.com/pandas-dev/pandas/pull/25709) has not yet been merged, and from fastparquet's point of view, what we really need is to be able to cope with parts of the metadata that are not as we expected. After all, we can already read datasets with no pandas metadata at all.

**Comment by timothydmorton** [comment]
OK-- Then should I continue based on current pandas?  And then we'll have to add some logic to deal with new pandas versions when they hit?

**Comment by martindurant** [comment]
Yes, perfect - and ideally generally robust to parsing errors, so that unexpected metadata does not prevent data loading.
