### ISSUE TITLE
Non-string column names

### ISSUE THREAD

**Issue by martindurant** [dask/fastparquet#41]
We currently assume that column names are strings when writing, because within parquet they must be. If columns are integers or something else, this causes an exception.

Thanks, @teh for pointing this out

**Comment by martindurant** [comment]
Recommendations on what to do about this? If I enforce str(col_name) upon writing, there had better be a check for repeated values, as a set of columns like [0, '0'] is allowed in pandas. 
Also, the loaded column labels will always be strings - should they be passed to util.val_to_num? In that case, in column selectors like to_pandas(columns=...), should users refer to the string version or the derived version?

The easy option: require string column names.

**Comment by teh** [comment]
I can't remember a single case where I was happy with silent coercion but many where I wasn't, so IMHO raising an informative exception ("parquet column names must be strings, but 0, 1, NaN are not strings").

**Comment by mrocklin** [comment]
Raising on non-strings seems like a fine way to start to me.  We can always relax that in the future if we find better solutions.

**Comment by poleguy** [comment]
I'm leaving this workaround for the next guy:
Try: df.columns = df.columns.astype(str)
https://stackoverflow.com/questions/38577126/convert-column-name-from-int-to-string-in-pandas
