### ISSUE TITLE
tz is undefined in one code path in api.py

### ISSUE THREAD

**Issue by cottrell** [dask/fastparquet#412]
I think the recent refactor broke the one part of the code path where 'tz' is undefined:

https://github.com/dask/fastparquet/blob/master/fastparquet/api.py#L525

I suspect it should be self.tz but probably @martindurant chimes in.

**Comment by martindurant** [comment]
I think you are quite right...
Would you like to make a PR of this? I suppose the correct test would be to save a dataset with a time column and then check the resultant ParquetFile's `dtypes` attribute.

**Comment by martindurant** [comment]
Actually, there's no way to check this with fastparquet alone, since then there always is pandas metadata and the code-path is never triggered. Pushing a fix...
