### ISSUE TITLE
pd.read_parquet engine='fastparquet' corrupting FIXED_LEN_BYTE_ARRAY, DECIMAL inputs

### ISSUE THREAD

**Issue by telferm57** [dask/fastparquet#417]
When reading a file  generated by parquet-dotnet that contains decimals, using pandas read_parquet engine='fastparquet', the numeric values change to seemingly unrelated numbers, e.g.
 44.4520 -> 0.000678

When reading the same file using pyarrow, there is no problem. 

input file and 

script attached
[parquet_test_1.zip](https://github.com/dask/fastparquet/files/3053442/parquet_test_1.zip)

**Comment by telferm57** [comment]
Pandas 0.24.1
fastparquet 0.3.0
python 3.6.4

**Comment by telferm57** [comment]
Hi Martin, the parquet file in the zip contains the correct values ..... pandas df created fine by pyarrow, not so by fastparquet

**Comment by martindurant** [comment]
It would be extremely useful to be able to do
```
assert fp.ParquetFile(test).to_pandas().equals(known_data)
```
i.e., to have those numbers independently of what is in the file, and without having to depend on pyarrow (or anything else) for the purposes of testing.

**Comment by telferm57** [comment]
I'll put it that format - give me a mo' !

**Comment by telferm57** [comment]
`expected_weights = pd.Series([93, 155, 102, 80, 85.5, 109, 105, 139, 91, 105], name='weight measure:WEIGHT(KG, 0)')
pd.to_numeric(fastparquet.ParquetFile(ifn).to_pandas()['weight measure:WEIGHT(KG, 0)']).equals(expected_weights)`

This is about as close as I can get (with a smaller file of 10 records ) as I do not have direct control over the parquet file creation on the dot-net side 

[pq_test_small.zip](https://github.com/dask/fastparquet/files/3060163/pq_test_small.zip)

**Comment by martindurant** [comment]
The values seem to differ by exactly a factor of 2**16

**Comment by telferm57** [comment]
ah yes, you're right - is the exponet being mis-read or miscalculated do you think?

**Comment by martindurant** [comment]
See the linked PR :)

**Comment by telferm57** [comment]
👍 Nice one!

**Comment by telferm57** [comment]
Any plans for a release this week? If not, I'll take a fork from here ...

many thanks !

**Comment by martindurant** [comment]
> Any plans for a release this week? 

Probably? It doesn't take that much time, I just have to remember to do it.
