### ISSUE TITLE
Reading array of string does not work as expected

### ISSUE THREAD

**Issue by victornoel** [dask/fastparquet#419]
Hi,

According to the documentation, fastparquet should be able to read arrays of string (https://fastparquet.readthedocs.io/en/latest/details.html#reading-nested-schema).

Actually, I have been reading map of string without any problem. But for a reason I don't understand, reading an array of string always give me a `None` value.

I am using pandas 0.24.2 and fastparquet 0.3.0.

I use the following code to read it:
```py
meta = pd.read_parquet('/home/jovyan/work/meta.parquet')
```

The parquet files are written using parquet-avro 1.10.1 in Java.

The avro schema is as follows:
```json
{"namespace": "ns",
 "type": "record",
 "name": "Log",
 "fields": [
     {"name": "id", "type": "string"},
     {"name": "step", "type": "int"},
     {"name": "product_ids", "type": {"type": "array", "items": "string"}},
     {"name": "histo_val", "type": "double"},
     {"name": "impacted_histo_ca", "type": ["null", "double"]},
     {"name": "impacted_nb_clients", "type": ["null", "int"]},
     {"name": "impacted_volume", "type": ["null", "double"]}
 ]
}
```

And the problematic one is `product_ids`.

For the record, here is a schema with a map that can be read without problems by fastparquet:
```json
{"namespace": "ns",
 "type": "record",
 "name": "Log",
 "fields": [
     {"name": "id", "type": "string"},
     {"name": "step", "type": "int", "unsigned": true},
     {"name": "criticality", "type":
     	["null", {"name": "CriticalityLog", "type": "record", "fields": [
     		{"name": "dissatisfaction", "type": "double"},
     		{"name": "importance", "type": "double"}
     	]}]
     },
     {"name": "variable", "type":
     	{"name": "DomainEntityLog", "type": "record", "fields": [
     		{"name": "value", "type": "double"},
     		{"name": "min", "type": "double"},
     		{"name": "max", "type": "double"}
     	]}
     },
     {"name": "meta", "type": {"type": "map", "values": "string"}}
 ]
}
```

**Comment by martindurant** [comment]
fastparquet's map and array capability was designed specifically for the schemas produced by spark, which has a particular structure. It would be good to display fastparquet's view of the schema for your problematic file (which might not be the same as the input avro schema).
Note that `uavro` may produce reasonable results in reading the original avro directly - but it doesn't handle nested fields at all.

**Comment by victornoel** [comment]
> It would be good to display fastparquet's view of the schema for your problematic file (which might not be the same as the input avro schema).

Good idea, how would I do that?

**Comment by martindurant** [comment]
```
pf = fastparquet.ParquetFile(...)
print(pf.schema)
```

**Comment by victornoel** [comment]
@martindurant this is the schema:
```
| - product_ids: LIST, REQUIRED
|   - array: BYTE_ARRAY, UTF8, REPEATED
```

**Comment by martindurant** [comment]
So a list of strings coming from Spark would look something like 
```
  - arr_req_req: LIST, REQUIRED
    - list: REPEATED
      - element: BYTE_ARRAY, UTF8, REQUIRED
```
(where either REQUIRED could be OPTIONAL)

You are having the problem because these are not the same. Reading from your version could be implemented, because the spark version allows for more levels of OPTIONAL (i.e., values like `None`, `[]`, `None`, `["stuff"]`). I think the spark version is a superset including yours, so maybe a small code change would read it - see `fastparquet.schema._is_list_like`.

**Comment by victornoel** [comment]
@martindurant I see!

For the record, it seems that the array type is maybe something deprecated and has been replaced by the list type as the one you are talking about. In parquet-avro, there is a setting (a bit hidden) so that the new format is used, it is `AvroWriteSupport.WRITE_OLD_LIST_STRUCTURE` that must be set to false in the configuration.

It gives this kind of schema:
```
| - product_ids: LIST, REQUIRED
|   - list: REPEATED
|     - element: BYTE_ARRAY, UTF8, REQUIRED
```

and fastparquet parses it without any problem!

So I think it is maybe not worth the energy to implement support for array (especially because I'm not very good with python ;)

Thanks for your help, I propose to close this issue since a acceptable solution was found.

**Comment by martindurant** [comment]
OK, suits me, and glad it worked!
