### ISSUE TITLE
schema.SchemaHelper.__eq__ is object default method

### ISSUE THREAD

**Issue by thomasbkahn** [dask/fastparquet#420]
The `schema.SchemaHelper.__eq__` method is not explicitly implemented, and therefore inherits the default `__eq__` method from `object`. This evaluation is whether two instances are the same, but not (necessarily, and in this case) whether the _contents_ are identical. This means that comparing separate files written with the same schema may not return expected results when using `==` (how I found this issue).

A quick fix for this could just be adding:
```python
def __eq__(self, other):
    return self.schema_elements == other.schema_elements
```

I can submit a PR if there's interest.

**Comment by martindurant** [comment]
Sure, that would be a fine change - with an appropriate test.
Can I ask what brought you across this?

**Comment by thomasbkahn** [comment]
I was looking to verify that two Parquet files I wrote (from different versions of a script) had the same schemata. They did, but `x.schema == y.schema` returned `False`.

**Comment by martindurant** [comment]
Fair enough - yes, this would be a totally good PR to have
