### ISSUE TITLE
Handling of dateutil timezones

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/fastparquet#424]
From https://github.com/pandas-dev/pandas/issues/25423

fastparquet converts the `tz` to a string and writes that into the metadata:

https://github.com/dask/fastparquet/blob/c0c8a442a0476ee809e3c70f2488fce8d0e6798c/fastparquet/util.py#L236-L237

However, this "fails" (gives you a result that cannot be read back), if there is a `dateutil.tz.tzutc` timezone, since this converts to `'tzutc()'`, which will fail parsing:

```
In [78]: from dateutil.tz import tzutc

In [79]: tz = tzutc()

In [80]: str(tz)
Out[80]: 'tzutc()'
```

For that reason, you get the error "UnknownTimeZoneError: 'tzutc()'" when reading the parquet file, as reported in https://github.com/pandas-dev/pandas/issues/25423

**Comment by martindurant** [comment]
... because there had to be a special case! The default would be utc anyway, which is why this didn't come up. Would the string "utc" be the right thing to write?
Would you be interested in fixing this?

**Comment by jorisvandenbossche** [comment]
BTW, I don't necessarily think you should support it (eg I don't directly know how to get a proper string from those timezones), but, in such a case an error should be raised instead of writing "invalid" metadata.

**Comment by jorisvandenbossche** [comment]
To add to my previous comment: similar problem will occur with any dateutil timezone in general:

```
In [86]: idx = pd.date_range('2012-01-01', periods=3, tz='dateutil/Europe/London')

In [87]: idx
Out[87]: 
DatetimeIndex(['2012-01-01 00:00:00+00:00', '2012-01-02 00:00:00+00:00',
               '2012-01-03 00:00:00+00:00'],
              dtype='datetime64[ns, tzfile('/usr/share/zoneinfo/Europe/London')]', freq='D')

In [88]: idx.tz
Out[88]: tzfile('/usr/share/zoneinfo/Europe/London')

In [89]: str(idx.tz)
Out[89]: "tzfile('/usr/share/zoneinfo/Europe/London')"
```

But I don't directly find how to get a proper string (like 'Europe/London' in the above) from a dateutil timezone

**Comment by jorisvandenbossche** [comment]
> Would the string "utc" be the right thing to write?

For `pytz.UTC` it is the string "UTC", so I would use that.

**Comment by martindurant** [comment]
Maybe interpreting the string produced can be tried right there in the function - if the roundtrip doesn't succeed, raise an exception immediately, telling the user not to use dateutil for this...

**Comment by martindurant** [comment]
I can implement what I said above, but I can't seem to find a way to get a string like 'dateutil/Europe/London' out of the `tz` object to actually get the roundtripping right.

**Comment by jorisvandenbossche** [comment]
> I can't seem to find a way to get a string like 'dateutil/Europe/London' out of the tz object to actually get the roundtripping right.

I also don't directly see a way to get this. Might be something to bring up with dateutil.

Another option is also to raise an informative error message when writing (or at least for now), to avoid writing an invalid file that gives an error on reading.

**Comment by martindurant** [comment]
That sounds like a reasonable strategy. If you happen to get to it before me, I would appreciate it...

**Comment by jorisvandenbossche** [comment]
I probably won't get to it in the short term ..

Regarding gettings the time zone name of dateutil, that's indeed not yet possible: https://github.com/dateutil/dateutil/issues/76. Once that issue is fixed (and it seems to be a priority for the next release), it should be rather easy to support dateutil timezones, as then we can just store the Olsen name in the metadata.

**Comment by jorisvandenbossche** [comment]
Thanks for the fix!
