### ISSUE TITLE
Fast parquet strips `_metadata` from anywhere in path during S3 read

### ISSUE THREAD

**Issue by jperkelens** [dask/fastparquet#429]
Not sure if an S3 only bug or not but the following code: 
```python
path = f"dataeng-data-test/testing/data/products/sku_metadata/*.parquet"
s3 = s3fs.S3FileSystem()
fs = s3fs.core.S3FileSystem()
all_paths_from_s3 = fs.glob(path=path)
 	 
custom_open = s3.open
fp_obj = fp.ParquetFile(all_paths_from_s3, open_with=custom_open)
actual = fp_obj.to_pandas()
```
results in the following error:
```sh
FileNotFoundError: dataeng-data-test/testing/data/products/sku/<partitions>/<filename>.parquet
```

Note the path descrepancy in the directory called `sku_metadata`

**Comment by martindurant** [comment]
hah! Yes, that's probably something done right in the ParquetFile init.
To be sure - do you have any `_metadata` files, or is this just a coincidence?

**Comment by jperkelens** [comment]
we do not have `_metadata` files but one of our data sets is a type of metadata, hence the naming conflict.
