### ISSUE TITLE
Use times=int96 when writing parquet for Redshift Spectrum

### ISSUE THREAD

**Issue by sburns** [dask/fastparquet#432]
👋 thanks for a wonderful library.

I'm opening this issue mostly for the Google juice to help people in the future and will instantly close this.

When you're using dask+fastparquet to write parquet files for use in Redshift Spectrum, you should use the `times='int96'` argument. I can't say for sure but it seems like Spectrum is using Spark underneath the hood. If you use the default `int64` argument, all of your timestamps will read by Spectrum as `2262-04-09 23:47:16.854776`.

**Comment by max-toepfer** [comment]
Make this post famous please! I spend hours on figuring out, why Redshift hates particularly fastparquet's date type...

**Comment by yohplala** [comment]
Hi,
Maybe this ticket should be left open till a corresponding note is added in [Usage note](https://fastparquet.readthedocs.io/en/latest/details.html)?
(adding a new chapter #Timestamps# ?)

**Comment by martindurant** [comment]
Sounds like a reasonable suggestion to add some language in that section.
