### ISSUE TITLE
Pandas Period and including period frequency in pandas metadata

### ISSUE THREAD

**Issue by alexifm** [dask/fastparquet#441]
Would it make sense to optionally include a key `period_freq` in the pandas metadata?  This would only get used to call `.to_period(pd_metadata[col]['period_freq'])` if `period_freq` is there.

Relatedly, what is the reason for not including the partition columns in the pandas metadata?  If I have a Period column that I partition on, it would be nice to convert back to Period using the metadata.

**Comment by martindurant** [comment]
Yes, it should be included in the metadata. There is a slight wrinkle that the metadata in the `_metadata` file will be different than for the individual data files, but that seems something we can live with.

**Comment by martindurant** [comment]
(I guess possible changes to the metadata spec should be proposed to the pandas repo)

**Comment by alexifm** [comment]
Ah, okay.  Didn't know this was an established spec.  That makes sense.

So there's a bit of an issue then: pandas has PeriodDtype but that doesn't show up here:
https://pandas.pydata.org/pandas-docs/stable/development/developer.html

On top of that, it looks like the PeriodDtype isn't really fully operational anyhow in that it can't be converted to numpy.
```
>> pd.api.types.infer_dtype(df.c)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
pandas/_libs/lib.pyx in pandas._libs.lib.infer_dtype()

TypeError: Cannot convert PeriodArray to numpy.ndarray
```
I guess we'll have to figure out how to handle this on our own.

**Comment by martindurant** [comment]
@TomAugspurger , who is the right person to talk to here?

**Comment by TomAugspurger** [comment]
Period is documented at http://pandas-docs.github.io/pandas-docs-travis/reference/arrays.html

Is an extension type, not a regular numpy dtype. It’s an array of integer ordinals and a freq.

Is this issue for adding support for period IO in fastparquet?
