### ISSUE TITLE
Missing data when parsing Parquet files containing maps with complex elements

### ISSUE THREAD

**Issue by cmenguy** [dask/fastparquet#443]
For example I have some Parquet files where one of the column has the following schema (in Spark):

```
 |-- myNestedMap: map (nullable = true)
 |    |-- key: string
 |    |-- value: map (valueContainsNull = true)
 |    |    |-- key: string
 |    |    |-- value: struct (valueContainsNull = true)
 |    |    |    |-- field1: timestamp (nullable = true)
 |    |    |    |-- payload: struct (nullable = true)
 |    |    |    |    |-- payloadField1: double (nullable = true)
 |    |    |    |    |-- payloadField2: string (nullable = true)
```

Although this is parsing without errors with `fastparquet`, it seems like this column is missing some data and shows as simply an array containing just the keys. The entire values are gone.

File attached which exhibits this behavior: 

[nestedMapClean.zip](https://github.com/dask/fastparquet/files/3308059/nestedMapClean.zip)

**Comment by martindurant** [comment]
This is not surprising, fastparquet only supports simple types only in maps, I'm afraid. A full nested record interface would be too hard to implement.

**Comment by cmenguy** [comment]
Got it, thanks for clarifying - do you have a sense of what changes in the code base this would require? I wouldn't mind taking a stab at it as nested structures is something I have to deal with on a daily basis, if you can give some pointers on where to start; or do you think it would require a complete rewrite of the codebase to support that @martindurant ?

**Comment by martindurant** [comment]
The basic algorithm is in https://github.com/dask/fastparquet/blob/master/fastparquet/encoding.py#L227 ; however, the initial setup of the arrays would have to account for all of the definition and repetition arrays of each of the sub-columns, so it gets complicated. 

In general, deep for-loops creating python objects like this would expect to be very slow indeed; this is why arrow aims to (as oamap did, maybe awkward-arrays can) keep the data in the original columns and walk the values without converting to python nested dicts.

**Comment by cmenguy** [comment]
Makes sense, it sounds like this would be quite a big work. One thing I'm wondering is if we could just fix to just keep the nested structures in a single column instead of doing the right thing about splitting that into multiple columns as per the schema - do you think that would still require this big refactoring @martindurant ? So in the example above we would have a single column which contains the entire map instead of having it split into 5 different columns, and we can still manipulate it.

**Comment by martindurant** [comment]
Having the data in a single column is actually the only possible representation of data like yours - each value would be a complicated dict containing more dicts; I'm not even sure what the "record" part would be, perhaps a named tuple.
