### ISSUE TITLE
Fastparquet crashes in official Python 3.7.4 docker image

### ISSUE THREAD

**Issue by philipp-block** [dask/fastparquet#450]
When using fastparquet in the official Python 3.7.4 docker image, the Python process exits with a segmentation fault and non-zero exit code (but after successfully executing the code).

A reproducible example can be found in https://github.com/philipp-block/fastparquet-py374-crash . The example uses pandas, but the same behavior happens when using Dask.

The segfault doesn't happen when using python3.6 or python3.7.3 docker images.

**Comment by martindurant** [comment]
Honestly, I don't know. You may want to install cython first to re-make the C-code included in fastparquet. Probably the pip build logs have some useful information, although they can be extremely verbose. Of course, many people install via conda to (usually) avoid this kind of thing.

**Comment by philipp-block** [comment]
Thank you for your suggestions @martindurant.

I've tried install cython before fastparquet, it didn't make a difference.

The [relevant parts of the pip build logs](https://github.com/philipp-block/fastparquet-py374-crash/blob/master/pip.log) also look normal to me.

We're pinning python <=3.7.4 for now as a workaround. Thanks again for looking at it.
