### ISSUE TITLE
Read _metadata file

### ISSUE THREAD

**Issue by marchinidavide** [dask/fastparquet#456]
Hi everyone!

As title, how can I read the `_metadata` file created when running a `dd.to_parquet()`?
Also, how can I modify it?
Maybe a a dumb question, please point me to the right docs in that case!

Best, Davide

**Comment by martindurant** [comment]
I'm afraid I don't know what you mean. The _metadata file is always read when you re-read the created directory of data. It contains no data itself, but points to the other files in the dataset. You could use fastparquet for more low-level operations, but I don't see why you would ever want to.

**Comment by marchinidavide** [comment]
Thanks for reading :)
I'm trying to understand how "append" works in to_parquet().
I would like to avoid crating a new file for each append call so my idea was to read in pandas the last numbered file, append there the new data and then save with pandas to_parquet() and modify the "parameters" in the metadata files to make Dask aware of the appended new data.
It's related to #114 
Is my understanding fundamentally wrong? I would do it to avoid rebuild the _metadata from scratch through the merge function...

**Comment by martindurant** [comment]
Yes you could in theory rewrite the metadata file from a set of data files using the tools in fastparquet with a little research. However loading it and adding just the part you know you appended is fiddly logic, I'd say too hard to get right - please just write extra data files! Append creates new "row groups" in any case, so there is no real benefit from having it in a file with other row groups. If you find you are making many very small appends, then probably the best thing to do is redesign your workflow, sorry.

**Comment by marchinidavide** [comment]
Ok, thanks for your inputs!
