### ISSUE TITLE
AttributeError When Read certain columns from ParquetFile

### ISSUE THREAD

**Issue by yushizhao** [dask/fastparquet#457]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-2124c416cd8c> in <module>
----> 1 first = next(iter(pf.iter_row_groups(columns=["BidUpdate"])))

~/.local/lib/python3.6/site-packages/fastparquet/api.py in iter_row_groups(self, columns, categories, filters, index)
    359                                                   categories, index)
    360                     self.read_row_group(rg, columns, categories, infile=f,
--> 361                                         index=index, assign=views)
    362                     yield df
    363         else:

~/.local/lib/python3.6/site-packages/fastparquet/api.py in read_row_group(self, rg, columns, categories, infile, index, assign)
    257                 infile, rg, columns, categories, self.schema, self.cats,
    258                 self.selfmade, index=index, assign=assign,
--> 259                 scheme=self.file_scheme)
    260         if ret:
    261             return df

~/.local/lib/python3.6/site-packages/fastparquet/core.py in read_row_group(file, rg, columns, categories, schema_helper, cats, selfmade, index, assign, scheme)
    352         raise RuntimeError('Going with pre-allocation!')
    353     read_row_group_arrays(file, rg, columns, categories, schema_helper,
--> 354                           cats, selfmade, assign=assign)
    355 
    356     for cat in cats:

~/.local/lib/python3.6/site-packages/fastparquet/core.py in read_row_group_arrays(file, rg, columns, categories, schema_helper, cats, selfmade, assign)
    329         read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
    330                  selfmade=selfmade, assign=out[name],
--> 331                  catdef=out.get(name+'-catdef', None))
    332 
    333         if _is_map_like(schema_helper, column):

~/.local/lib/python3.6/site-packages/fastparquet/core.py in read_col(column, schema_helper, infile, use_cat, grab_dict, selfmade, assign, catdef)
    261                         parquet_thrift.FieldRepetitionType.REQUIRED)
    262             row_idx = 1 + encoding._assemble_objects(assign, defi, rep, val, dic, d,
--> 263                                              null, null_val, max_defi, row_idx)
    264         elif defi is not None:
    265             max_defi = schema_helper.max_definition_level(cmd.path_in_schema)

~/.local/lib/python3.6/site-packages/fastparquet/encoding.py in _assemble_objects(assign, defi, rep, val, dic, d, null, null_val, max_defi, prev_i)
    286         assign[i] = None if have_null else part
    287     else: # can only happen if the only elements in this page are the continuation of the last row from previous page
--> 288         assign[i - 1].extend(part)
    289     return i
    290 

AttributeError: 'NoneType' object has no attribute 'extend'

**Comment by yushizhao** [comment]
Actually, what does that comment mean?
# can only happen if the only elements in this page are the continuation of the last row from previous page

**Comment by martindurant** [comment]
I'm sorry, I don't understand the issue. Please can you post what you were doing, as a reproducible verifier?

**Comment by yushizhao** [comment]
Okay. There was a parquet file produced by https://github.com/xitongsys/parquet-go which can be read via the go package. However, when I try to read it using next(iter(pf.iter_row_groups(columns=["BidUpdate"]))), I got above error. 
It is a large file, I will try to get a minimize example.

**Comment by yushizhao** [comment]
By the way, when I read other columns, it was fine.

**Comment by martindurant** [comment]
Likely the column contains nested types, which fastparquet cannot cope with. The support for nested types is [limited](https://fastparquet.readthedocs.io/en/latest/details.html#reading-nested-schema).

**Comment by yushizhao** [comment]
Yes. After flatten the column, it works.
