### ISSUE TITLE
Use "field_name" in pandas metadata for consistency with pyarrow

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/fastparquet#462]
From the original report in pandas (https://github.com/pandas-dev/pandas/issues/28252) about a file written with fastparquet that cannot be read with pyarrow, I fixed this in the pyarrow metadata compatibility handling (https://issues.apache.org/jira/browse/ARROW-6492, https://github.com/apache/arrow/pull/5331).

Although this particular issues will thus be fixed in the next pyarrow release, it would still be good that both libraries write consistent pandas metadata. 

The main difference that caused the above bug was the `"field_name"` key in the columns descriptions (which fastparquet does not write, but pyarrow does). 
Would you be open to write the `"field_name"` key as well (which would be identical to `"name"` in all cases supported by fastparquet I think)? This would also follow was is currently written in the spec (https://dev.pandas.io/development/developer.html#storing-pandas-dataframe-objects-in-apache-parquet-format)

An example where pyarrow uses the fact of having both is non-default index without name: fastparquet gives this a default generated "index" name, so the written parquet file comes back with this name. In pyarrow the `"field_name"` is set to the generated name used in the parquet file, but `"name"` is still `None`, so on roundtripping pyarrow can "preserve" the fact that the index has no name.

**Comment by jorisvandenbossche** [comment]
For the `"column_indexes"`, both are already included:

https://github.com/dask/fastparquet/blob/55675a42def19b8ec72724de2ef87c131a7fd6d5/fastparquet/writer.py#L660-L661

**Comment by martindurant** [comment]
Sure, fine with me, but I suspect that some tests in Dask may rely on the current behaviour.

**Comment by jorisvandenbossche** [comment]
Do you mean that you think adding a field will break some things in dask, or just that some tests hardcode the full expected dictionary?

**Comment by martindurant** [comment]
I think the latter. In fact, it may be that this change will simplify some tests which explicitly ignore this discrepancy - but I just wanted to warn that this kind of change often requires corresponding changes in the tests (but the functionality should be fine)
