### ISSUE TITLE
fastparquet ValueError: Can't infer object conversion type: 0    2019-11-02

### ISSUE THREAD

**Issue by gimpor33** [dask/fastparquet#469]
I am pulling 1 date field from Teradata to parquet and I receive this error every time.

select Run_Dt,  Ver_Wk from Table TeraX

Run_Dt  Ver_Wk########
0         2019-11-02                        -9
1         2019-11-27                        -2
2         2019-12-04                         0
3         2019-12-04                         0
4         2019-12-04                         0
Starting Parquet......
Traceback (most recent call last):
  File "Cap_v_test.py", line 176, in <module>
    td_results.to_parquet('x.parquet')
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 1945, in to_parquet
    compression=compression, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\io\parquet.py", line 257, in to_parquet
    return impl.write(df, path, compression=compression, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\io\parquet.py", line 218, in write
    compression=compression, **kwargs)
  File "C:\Python27\lib\site-packages\fastparquet\writer.py", line 862, in write
    times=times, index_cols=index_cols)
  File "C:\Python27\lib\site-packages\fastparquet\writer.py", line 692, in make_metadata
    object_encoding=oencoding, times=times)
  File "C:\Python27\lib\site-packages\fastparquet\writer.py", line 95, in find_type
    object_encoding = infer_object_encoding(data)
  File "C:\Python27\lib\site-packages\fastparquet\writer.py", line 238, in infer_object_encoding
    raise ValueError("Can't infer object conversion type: %s" % head)
ValueError: Can't infer object conversion type: 0    2019-11-02
1    2019-11-27
2    2019-12-04
3    2019-12-04

Name: Run_Dt, dtype: object

**Comment by martindurant** [comment]
You seem to have times in the column, but the column type is object. You need to convert it to a datetime column.

**Comment by gimpor33** [comment]
Covert to datetime in teradata before I  push to parquet select Run_Dt, Ver_Wk from Table TeraX

or while I am pushing it to Parquet 
td_results.to_parquet('x.parquet')

**Comment by martindurant** [comment]
`td_results` should have the column already as datetime type. I have no idea how to get teradata to do that for you (`select Run_Dt AS ...`?).

**Comment by francois-baptiste** [comment]
```
import pandas as pd
df = pd.DataFrame({"receipt_date": [pd.datetime(2021, 10, 11), ] * 1000})
df.receipt_date = df.receipt_date.dt.date
df.to_parquet('dummy')
Traceback (most recent call last):
  File "line 1, in <module>
    df.to_parquet('dummy')
  File "\site-packages\pandas\core\frame.py", line 2222, in to_parquet
    **kwargs
  File "\site-packages\pandas\io\parquet.py", line 254, in to_parquet
    **kwargs
  File "\site-packages\pandas\io\parquet.py", line 182, in write
    **kwargs
  File "\site-packages\fastparquet\writer.py", line 876, in write
    times=times, index_cols=index_cols)
  File "\site-packages\fastparquet\writer.py", line 706, in make_metadata
    object_encoding=oencoding, times=times)
  File "\site-packages\fastparquet\writer.py", line 95, in find_type
    object_encoding = infer_object_encoding(data)
  File "\site-packages\fastparquet\writer.py", line 238, in infer_object_encoding
    raise ValueError("Can't infer object conversion type: %s" % head)
ValueError: Can't infer object conversion type: 0    2021-10-11
1    2021-10-11
2    2021-10-11
3    2021-10-11
4    2021-10-11
5    2021-10-11
6    2021-10-11
7    2021-10-11
8    2021-10-11
9    2021-10-11
Name: receipt_date, dtype: object
```

It seems that this code reproduce the bug.
The column type is indeed reported as object by pandas however pyarrow is dealing with it as a datetime...
My version of fastparquet is 0.3.3.

**Comment by martindurant** [comment]
Yeah, timestamp-objects are not among those expected, because pandas already has a time type, which work well (and is much more efficient). You should convent your column with `pd.to_datetime`. Adding it to the inferred objects types would not be hard, but would amount to doing the exact same conversion within the code.

**Comment by y-da-zhuang** [comment]
> 是的，时间戳对象不在预期之列，因为 pandas 已经有一个时间类型，它运行良好（并且效率更高）。您应该使用`pd.to_datetime`. 将其添加到推断的对象类型并不难，但相当于在代码中进行完全相同的转换。
But like there are multiple data types in the same field in mongodb, how should I solve it？

**Comment by martindurant** [comment]
@y-da-zhuang , I'm afraid I cannot understand what you have written.

**Comment by y-da-zhuang** [comment]
> @y-da-zhuang，恐怕我看不懂你写的东西。

That is, I now query the data from mongodb and save it as a parquet file through pandas.to_parquet(), but there can be multiple data types in the same field in mongodb, which will cause an error

 for item in query_set:
            for row in list(item):
                if isinstance(item.get(row), (datetime.datetime, ObjectId, Regex, Timestamp, list, dict,float)):
                        result_dump = json.dumps(item.get(row), default=self.special_characters)
                        try:
                            if isinstance(json.loads(result_dump), (list, dict)):
                                item[row] = result_dump
                            else:
                                item[row] = json.loads(result_dump)
                        except:
                            pass 
        return query_set

    def special_characters(self, value):
        if isinstance(value, (ObjectId, Regex, Timestamp)):
            return str(value)

        if isinstance(value, (datetime.datetime,)):
            return value.strftime('%Y-%m-%d-%H-%M-%S')

**Comment by schistyakov** [comment]
Just get the same error and it was solved by manually changing parquet engine to pyarrow. data.to_parquet('....', engine='pyarrow')
