### ISSUE TITLE
Importing from pandas.core.index is deprecated

### ISSUE THREAD

**Issue by jorisvandenbossche** [dask/fastparquet#470]
The imports here (and maybe in other places as well):

https://github.com/dask/fastparquet/blob/8767c2f94975aed8d052a9d0ad6f5e4e630a6f12/fastparquet/dataframe.py#L5

is deprecated now in pandas master (and it has also been private before). Those imports are simply available from the top-level namespace, so no need to import them from there.

**Comment by martindurant** [comment]
@TomAugspurger , to what extent do you think it's useful to keep fastparquet up to date with the changing face of pandas? I don't just mean imports, but the range index attributes and various extension column types.

**Comment by TomAugspurger** [comment]
The imports are relatively easy to handle.

The new extension types are another matter though. I don’t think fastparquet has the bandwidth for that.
