### ISSUE TITLE
ParquetFile(file) NotADirectoryError: error[20] Not a directory: '/xxx/xxx/xx.parquet/ _metadata'

### ISSUE THREAD

**Issue by Wercurial** [dask/fastparquet#472]
Hello, let me ask you a question. 
system: centos 6.6, fastparquet 0.1.5, anaconda python 3.6.3
I use pandas.to_parquet() to split a small parquet file from a large parquet file. Reading the small parquet file with fastparquet.ParquetFile (file) will report the error as the topic.
 but I will merge 3600 such small parquet files into a large parquet file, and then read it with fastparquet.ParquetFile (file). Excuse me ,Do you know why?

**Comment by quasiben** [comment]
I am not really sure what the question being asked is.  Can you provide a reproducible example which demonstrates the error ?

**Comment by quasiben** [comment]
If possible, can you upgrade from 0.1.5 to 0.3.2 ?

**Comment by Wercurial** [comment]
> I am not really sure what the question being asked is. Can you provide a reproducible example which demonstrates the error ?
Of course, the details are as follows:
Traceback(most recent call last):
      File "xx/xx/fastparquet/api.py", line 98, in __init__
             with open_with(fn2,'rb') as f:
      File "xx/xx/fastparquet/util.py", line 37, in default_open
             return open(f, mode)
NotADirectoryError: error[20] Not a directory: '/xxx/xxx/xx.parquet/ _metadata' 
 
During handling of the above exception, another exception occurred:

Traceback(most recent call last):
      File "xx/xx/fastparquet/api.py", line 104, in  __init__
            self.__parse_header(f,verify)
       File "xx/xx/fastparquet/api.py", line 128, in  __parse_header
             self._set_attrs()
       File "xx/xx/fastparquet/api.py", line 142, in  _set_attrs
              self.schema = schema.SchemaHelper(sel._schema)
       File "xx/xx/fastparquet/schema.py", line 80, in  __init__
               self.text = schema_to_text(self.schema_elements[0])
       File "xx/xx/fastparquet/schema.py", line 47, in  schema_to_text
               text += '\n' + schema_to_text(child,indent)
       File "xx/xx/fastparquet/schema.py", line 36, in  schema_to_text
               root.converted_type])
KeyError: 24

**Comment by Wercurial** [comment]
> If possible, can you upgrade from 0.1.5 to 0.3.2 ?

Ok, i will to try,thx

**Comment by Wercurial** [comment]
oh,i used pandas.to_parquet(file,engine='auto') has error before.
And now i used pandas.to_parquet(file,engine='fastparquet') is OK.
i think engine='auto' maybe was 'pyarrow' and i use fastparquet to read it  was error.
thank you everyone,good luck for u.
