### ISSUE TITLE
decimal type conversion

### ISSUE THREAD

**Issue by ephes** [dask/fastparquet#48]
Hi,

the decimal to float type conversion fails for decimals with high precision. Here's the schema for the failing column:
<pre>
<class 'parquet_thrift.SchemaElement'>
converted_type: 5
field_id: None
name: foobar
num_children: None
precision: 38
repetition_type: 1
scale: 1
type: 7
type_length: 16
</pre>

Calling pf.to_pandas() raises:
<pre>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-67-3295021a90fc> in <module>()
----> 1 ba_cast = t.foobar.cast(np.float32)

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/api.py in cast(arg, target_type)
    384 def cast(arg, target_type):
    385     # validate
--> 386     op = _ops.Cast(arg, target_type)
    387 
    388     if op.args[1] == arg.type():

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/types.py in __init__(self, *args)
    302 
    303     def __init__(self, *args):
--> 304         args = self._validate_args(args)
    305         Node.__init__(self, args)
    306 

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/types.py in _validate_args(self, args)
    309             return args
    310 
--> 311         return self.input_type.validate(args)
    312 
    313     def root_tables(self):

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/rules.py in validate(self, args)
    345             args = list(args) + [t.default for t in self.types[n:]]
    346 
--> 347         return self._validate(args, self.types)
    348 
    349     def _validate(self, args, types):

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/rules.py in _validate(self, args, types)
    351         for i, validator in enumerate(types):
    352             try:
--> 353                 clean_args[i] = validator.validate(clean_args, i)
    354             except IbisTypeError as e:
    355                 exc = e.args[0]

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/rules.py in validate(self, args, i)
    302                 return arg
    303 
--> 304         return self._validate(args, i)
    305 
    306     def _validate(self, args, i):

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/rules.py in _validate(self, args, i)
    712             arg = arg.lower()
    713 
--> 714         arg = args[i] = dt.validate_type(arg)
    715         return arg
    716 

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/datatypes.py in validate_type(t)
    449         return t
    450 
--> 451     parsed_type = _parse_type(t)
    452     if parsed_type is not None:
    453         return parsed_type

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/datatypes.py in _parse_type(t)
    480 def _parse_type(t):
    481     for parse_fn in _type_parsers:
--> 482         parsed = parse_fn(t)
    483         if parsed is not None:
    484             return parsed

/home/jwersdoerfer/miniconda3/envs/bidding/lib/python3.5/site-packages/ibis/expr/datatypes.py in _parse_decimal(t)
    463 
    464 def _parse_decimal(t):
--> 465     m = _DECIMAL_RE.match(t)
    466     if m:
    467         precision, scale = m.groups()

TypeError: expected string or bytes-like object
</pre>

It's possible to fix this with this change to converted_types.py:
<pre>
    if ctype == parquet_thrift.ConvertedType.DECIMAL:
        scale_factor = 10**-se.scale
        if se.precision > 18:
            data = np.array(
                [int.from_bytes(d, byteorder='big', signed=False)
                 for d in data])
</pre>

But I don't know if this is  the right way to do it. I've played around with np.fromstring, but couldn't get it to work.

regards,
jochen

**Comment by martindurant** [comment]
Do you know if float128 would be sufficient? The biggest int type in numpy (and therefore pandas, the target of fastparquet) is 64-bit. It seems to me like a bad idea to construct an object array of big-ints, although if that's your only option...
I can't follow your traceback, above, which only seems to be executing within `ibis` - perhaps it cannot understand numbers of such size either?

**Comment by mrocklin** [comment]
It is surprising and unfortunate that NumPy doesn't implement a Decimal DType.  How does Parquet encode decimals?  Perhaps we can encode and decode these specially to and from something?

@jreback, I take it that Pandas uses `float` for decimals?

**Comment by jreback** [comment]
we don't handle Decimal type very well either

**Comment by mrocklin** [comment]
In practice do people use floats or Python Decimal objects?

I guess this is one problem for which we probably wait for the underlying stack to improve (pandas 2.0 or some numpy evolution thing)

**Comment by ephes** [comment]
For me np.float32 would be sufficient, I won't be able to use bigger types anyway, since I want to create a huge feature matrix from the numbers. My problem is that I can't read the parquet files of my table. The int.frombytes call kind of works, but I wondered if there's a better way to convert an numpy array of dtype |S16 into a float array.  The parquet files are created by an ibis table expression, but then I download the files directly via hdfs.get.

**Comment by mrocklin** [comment]
Is this helpful?

```python
In [1]: import numpy as np

In [2]: x = np.array(['1.1', '2.2', '3.3'], dtype='S3')

In [3]: x.astype(np.float32)
Out[3]: array([ 1.10000002,  2.20000005,  3.29999995], dtype=float32)
```

**Comment by ephes** [comment]
Throws a value error. I don't know exactly how decimals are encoded in parquet, but the array of bytes looks like this:
<pre>
[b'' b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1e\\'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1d\\' ...,
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x18\x80'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0bm'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0e\t']
</pre>

**Comment by mrocklin** [comment]
@martindurant would know more, but this might be helpful: https://github.com/Parquet/parquet-format/blob/master/LogicalTypes.md#decimal

The primitive type stores an unscaled integer value. For byte arrays, binary and fixed, the unscaled number must be encoded as two's complement using big-endian byte order (the most significant byte is the zeroth element). The scale stores the number of digits of that value that are to the right of the decimal point, and the precision stores the maximum number of digits supported in the unscaled value.

**Comment by martindurant** [comment]
OK, now I follow you - what's missing is a conversion where the basic data is byte arrays rather than int or float. I can certainly add that.

**Comment by martindurant** [comment]
Is there any chance you can send me an extract of your data, or something similar to it, so it can be included in a test? The correct values of the bytes array would do.

**Comment by ephes** [comment]
@martindurant  Oh, that would be cool :) - the correct result is array([   0. ,  777.2,  751.6,  345.1,  644.1])

**Comment by martindurant** [comment]
@ephes , I am using your solution, because it works generally. However, it will be very slow for a large number of values. There are faster numpy alternatives that would work when the int size is <=8bytes. However, I would expect those to be stored as actual integers rather than byte-strings, so I am not implementing it until necessary. Note that in your case, the values are 32-byte strings (although it says 16 in the schema element), but 2-byte integers would have done. Perhaps there are options in the software that generated them (ibis?) that can produce the more useful int type representation.
