### ISSUE TITLE
my_nan in core.read_col

### ISSUE THREAD

**Issue by jbrockmendel** [dask/fastparquet#489]
In experimenting with a refactor in pandas internals (using DatetimeArray/TimedeltaArray in a couple of places instead of ndarray) I stumbled on this in `fp.core.readcol`:

```
        elif assign.dtype.kind in ["M", 'm']:
            my_nan = -9223372036854775808  # int64 version of NaT
```

Setting `my_nan` into an `np.ndarray` is allowed, but setting it into a pandas `DatetimeArray` is not, so one of our downstream tests failed here.

Instead of the integer value, would it be viable to use `my_nan = assign.dtype.type("NaT")` here?  That fixes the issue for me locally.

If this is acceptable, I'll open a PR.

**Comment by martindurant** [comment]
Sounds OK to me.
In practice, all Null values may be put into the new extension types in the near future (#483 )
