### ISSUE TITLE
Update numba jitclass imports

### ISSUE THREAD

**Issue by luk-f-a** [dask/fastparquet#495]
Hi! Thanks a lot for this package.

I'd like to raise the issue that Numba has changed the location of `jitclass`. In the current version (0.49) we are getting a bunch of DeprecationWarnings, and from 0.50 this imports will fail. The new location is numba.experimental.jitclass.

```
C:\Users\\miniconda3\envs\litt-conda\lib\site-packages\fastparquet\encoding.py:222: NumbaDeprecationWarning: The 'numba.jitclass' decorator has moved to 'numba.experimental.jitclass' to better reflect the experimental nature of the functionality. Please update your imports to accommodate this change and see http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#change-of-jitclass-location for the time frame.
  Numpy8 = numba.jitclass(spec8)(NumpyIO)
C:\Users\\miniconda3\envs\litt-conda\lib\site-packages\fastparquet\encoding.py:224: NumbaDeprecationWarning: The 'numba.jitclass' decorator has moved to 'numba.experimental.jitclass' to better reflect the experimental nature of the functionality. Please update your imports to accommodate this change and see http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#change-of-jitclass-location for the time frame.
  Numpy32 = numba.jitclass(spec32)(NumpyIO)
```

**Comment by martindurant** [comment]
Sure, updating these would be appreciated. Do you have the time?

**Comment by luk-f-a** [comment]
@martindurant would it be ok if I update all the imports, thus making the next release dependent on numba 0.49+?

**Comment by martindurant** [comment]
If it's clearly in the requirements, then yes.

**Comment by luk-f-a** [comment]
thanks for the review @martindurant . Is there a release in the horizon?

**Comment by martindurant** [comment]
Maybe? Not top of my list really. There are many improvements that could be made to fastarquet as the world has gone on, but I don't think there's too much apatite.

**Comment by luk-f-a** [comment]
I was thinking on whether this PR would be part of a release I can get from conda or pip. Otherwise it won't be possible to use numba 0.50 together with fastparquet in the same conda environment.
Even if it's a point release with a few small fixes like this one.

**Comment by aleyan** [comment]
Thank you for fastparquet and for this update. Also interested in a point release as we are getting a lot of deprecation warnings in our logs. I suspect a 0.50 release of numba could be breaking for projects that are using it transitively through other packages (and get swept up in other package updates).

**Comment by martindurant** [comment]
Done.

**Comment by luk-f-a** [comment]
thanks a lot!

**Comment by ybagdasa** [comment]
@martindurant Is the fix only available by pulling from the repo? Is it available through any conda install?

**Comment by martindurant** [comment]
The version on conda-forge includes this fix
```
conda install -c conda-forge fastparquet
```

**Comment by ybagdasa** [comment]
@martindurant  Hmm, I did the reinstall, but it didn't seem to work. I get the following warnings when loading a parquet file:
```
.../miniconda3/lib/python3.7/site-packages/fastparquet/encoding.py:222: NumbaDeprecationWarning: The 'numba.jitclass' decorator has moved to 'numba.experimental.jitclass' to better reflect the experimental nature of the functionality. Please update your imports to accommodate this change and see http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#change-of-jitclass-location for the time frame.
  Numpy8 = numba.jitclass(spec8)(NumpyIO)
.../miniconda3/lib/python3.7/site-packages/fastparquet/encoding.py:224: NumbaDeprecationWarning: The 'numba.jitclass' decorator has moved to 'numba.experimental.jitclass' to better reflect the experimental nature of the functionality. Please update your imports to accommodate this change and see http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#change-of-jitclass-location for the time frame.
  Numpy32 = numba.jitclass(spec32)(NumpyIO)
.../miniconda3/lib/python3.7/site-packages/fastparquet/dataframe.py:5: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import CategoricalIndex, RangeIndex, Index, MultiIndex
```

**Comment by martindurant** [comment]
@ybagdasa , which version did you end up with?

**Comment by ybagdasa** [comment]
@martindurant Actually I tried again, by first removing the package and then installing again, and this time it worked :)

**Comment by martindurant** [comment]
OK, I guess "install" maybe should have been "update" in your case, or could have specified the version you wanted. Glad it works.
