### ISSUE TITLE
handle indexes

### ISSUE THREAD

**Issue by martindurant** [dask/fastparquet#5]
A pandas dataframe has an index, which we simply ignore for now. Suggest a "with index" option on write, which puts the index into a column. Also should check `is_monotonic_[in/de]creasing` on each column, including the index, and note this sorting in the metadata.

On load enable choice of index: a specific column, a numeric index, or any sorted index, if present. Whether a column is sorted should show up in the ParquetFile instance, to enable the user's choice.
For loading with dask, if the index is a sorted column or numeric index, can fill in the partition divisions. (also, we don't set the numeric index offsets in each partition, they all start at 0, which is not an important problem, but still inconsistent)

**Comment by martindurant** [comment]
On a separate but connected issue, loading partitioned datasets currently just adds categorical columns for each partition key, but it could be a hierarchical index; conversely, writing to partitions could be done via groupby or by requiring a hierarchical index (or both).

**Comment by mrocklin** [comment]
So on the Pandas-only side we might establish a convention like the following:

1.  If the index has a name, use that name, otherwise, use 'index'
2.  While this name conflicts with any other column, prefix it with 'index-'

In the common case this convention is not particularly opinionated.  However, it also appears that we can add sorted column metadata, both on the file level and the rowgroup level.  In the case of a sorted index (common) this might help to serve as another cue.

On the dask.dataframe side I'm curious where we can set metadata for a column being sorted.  There appears to be a `SortingColumn` struct in the thrift file.  Where can we set this?

**Comment by martindurant** [comment]
I agree on the naming when making an index into a column for saving, although we should also have the option to just drop the index. *If* saving an index, we can check if it is sorted, or ask the user to specify if it is (checking for sorting might be slow for dask-dataframes, and the information should already be known). 

Sorting is done per row_group, but we also have the min/max in the column stats per row_group. So on load you would require a column that is the first sorting column in every row_group, and whose min/max form a progression, in order to consider it as a sorted index.

**Comment by mrocklin** [comment]
Where in this codebase should we set that information?

**Comment by martindurant** [comment]
In writer.make_row_group, we create the RowGroup structure that would hold sorting information. You would need 
```
rg.sorting_columns = parquet_thrift.SortingStructure(index=<int>, descending=<True/False>, nulls_first=<True/False>)
```
and make sure that write_column in the block below gets called with the index (which maybe would need to be viewed as a Series to work).

**Comment by mrocklin** [comment]
OK, thanks for the pointer.  Are there good ways to test that what I'm doing is correct or do we just round trip things and check that the metadata is there?

**Comment by martindurant** [comment]
Pretty much all my tests are roundtrip - the thrift library is strict about what sorts of information you can put where - but you can also check by loading through spark, where, maybe, the column will show up as sorted in the spark-dataframe schema. On the other hand, there are lots of things spark simply ignores...

**Comment by mrocklin** [comment]
OK, diving through the thrift definition file a bit:

*  FileMetaData contains
*  many RowGroups
*  each of which contain a list of SortingColumns and a list of ColumnChunks
*  each ColumnChunk contains a ColumnMetaData
*  each ColumnMetaData contains a Statistics
*  a Statistics contains a min/max/count/ndistinct 
*  each SortingColumn contains an index of the column name and whether or not it is increasing or decreasing

**Comment by martindurant** [comment]
Yes, quite right
https://github.com/Parquet/parquet-format has a diagram

**Comment by martindurant** [comment]
@mrocklin , does #14 close this?

**Comment by mrocklin** [comment]
I wouldn't be surprised if we needed to revisit the issue in the future, but yes, lets close for now.
