### ISSUE TITLE
fastparquet silently strips NULL bytes off the end of binary arrays

### ISSUE THREAD

**Issue by adq** [dask/fastparquet#504]
### Environment
fastparquet              0.3.2      
numpy                    1.18.2     
python37 3.7.7-2
On arch linux.

### Issue
I was trying to read a parquet file with binary encoded data in it. Some of the binary encoded data would be "randomly" corrupt. Investigation and comparison with pyarrow showed that fastparquet is silently stripping NUL (\0) bytes from the end of dictionary encoded binary data arrays.

ie the value should be b'abcde\0'. But fastparquet returns b'abcde'.

digging into the library code shows that this is caused in core.py/read_col() where it decodes dictionary pages (two places in the code). Specifically, you do:

```
    if ph.type == parquet_thrift.PageType.DICTIONARY_PAGE:
        dic = np.array(read_dictionary_page(infile, schema_helper, ph, cmd))
```

that call to np.array causes the stripping. It appears to be a "feature" of np.array.

Confirming this with a simple example in a python shell:

```
>>> import numpy
>>> a = [b'abcd\0']
>>> numpy.array(a)
array([b'abcd'], dtype='|S5')
```

### Possible fix
I can obviously simply drop the np.array() calls, but I don't know what consequences this would have on performance etc.

**Comment by martindurant** [comment]
Huh, fascinating.
What happens if you do remove np.array from this? For the bytes input, perhaps the dtype needs to be "object", in the first branch of the `if` in `read_dictionary_page`; for the other branch, the return is already an array and will be unchanged.
```diff
--- a/fastparquet/core.py
+++ b/fastparquet/core.py
@@ -156,8 +156,8 @@ def read_dictionary_page(file_obj, schema_helper, page_header, column_metadata):
     """
     raw_bytes = _read_page(file_obj, page_header, column_metadata)
     if column_metadata.type == parquet_thrift.Type.BYTE_ARRAY:
-        values = unpack_byte_array(raw_bytes,
-                                   page_header.dictionary_page_header.num_values)
+        values = np.array(unpack_byte_array(raw_bytes,
+                                   page_header.dictionary_page_header.num_values), dtype='object')
     else:
         width = schema_helper.schema_element(
             column_metadata.path_in_schema).type_length
@@ -196,7 +196,7 @@ def read_col(column, schema_helper, infile, use_cat=False,

     dic = None
     if ph.type == parquet_thrift.PageType.DICTIONARY_PAGE:
-        dic = np.array(read_dictionary_page(infile, schema_helper, ph, cmd))
+        dic = read_dictionary_page(infile, schema_helper, ph, cmd)
         ph = read_thrift(infile, parquet_thrift.PageHeader)
         dic = convert(dic, se)
```

**Comment by martindurant** [comment]
(the second change might be unnecessary)
