### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 0; dimension is 50 but corresponding boolean dimension is 10770

### ISSUE THREAD

**Issue by Ritesh-pandey-crypto** [dask/fastparquet#512]
train_idx = np.arange(metadata.shape[0]) % 9 != 0
test_idx = np.arange(metadata.shape[0]) % 9 == 0
print(metadata.shape)
print(train_idx.shape)
print(test_idx.shape)
Output: (10770,)
             (10770,)
             (10770,)

embeddings = np.asarray(embeddings)

 X_train = embeddings[train_idx]
X_test = embeddings[test_idx]

**Comment by Ritesh-pandey-crypto** [comment]
print(X_train.shape)
print(X_train.shape)

**Comment by Ritesh-pandey-crypto** [comment]
Please help me in getting outta this error.

**Comment by martindurant** [comment]
Could you please include the code that produces this problem, ideally in a completely self-contained example. The two lines you supply do not seem to involve fastparquet at all.

**Comment by Ritesh-pandey-crypto** [comment]
Here are the codes i have edited the above codes please help

**Comment by martindurant** [comment]
What is `metadata`, what is `embeddings`, and what does this have to do with fastparquet?

**Comment by Ritesh-pandey-crypto** [comment]
I have given above the output which i am getting and so is the error

**Comment by martindurant** [comment]
> what is embeddings, and what does this have to do with fastparquet?

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Ritesh-pandey-crypto** [comment]
But the error remains the same bro
