### ISSUE TITLE
Segmentation fault (core dumped) when run to_pandas

### ISSUE THREAD

**Issue by ajing** [dask/fastparquet#513]
**What happened**:

Segmentation fault

**What you expected to happen**:

return a pandas dataframe

**Minimal Complete Verifiable Example**:

```python
import fastparquet
pf = fastparquet.ParquetFile('/tmp/tmpu3ivvojp/part-00009-4c3b4a78-98b6-4bca-8591-ed5bd82a1f25-c000.snappy.parquet')
pf.to_pandas()
```

**Anything else we need to know?**:

The file size is 85M

**Environment**:

- Dask version:0.19.1
- Python version:3.7
- Operating System:Ubuntu
- Install method (conda, pip, source):conda

**Comment by ajing** [comment]
It failed when run `read_row_group_arrays`.

**Comment by martindurant** [comment]
I'm afraid it's very hard for me to guess what happened there. You might want to investigate the schema of the data file in question, and perhaps try with different versions of fastparquet. This library is not being very actively maintained, so it's possible that your data contains a new encoding type that we don't handle.

**Comment by ajing** [comment]
Thanks for your suggestion!
