### ISSUE TITLE
`_metadata` file doesn't support incremental updates

### ISSUE THREAD

**Issue by fanshi118** [dask/fastparquet#521]
Currently, the `_metadata` will get overwritten by the most recent incremental update, if we write data to the same output directory iteratively. Ideally, would like the `_metadata` file to be consistent with all the data that are in the output directory; however, now it would ignore the previously written partitions/subsets and update itself with the most recently written data. Even in `append` mode, the `_metadata` file doesn't update incrementally, which would be a super helpful feature to have!

**Comment by martindurant** [comment]
> Even in append mode, the _metadata file doesn't update incrementally, which would be a super helpful feature to have!

Can you clarify?

Note that the code has a merge-many function which can be called with a set of parquet files, to construct the _metadata once all the writing is done.

**Comment by fanshi118** [comment]
> Can you clarify?

Let's say I write to a directory one partition at a time and set `write_metadata_file` to `True`. After the 2nd iteration, the `_metadata` will be overwritten by the 2nd partition that was processed and, as a result, exclude the 1st one.

> Note that the code has a merge-many function which can be called with a set of parquet files, to construct the _metadata once all the writing is done.

This sounds like a cool feature. How do we do this in code?

**Comment by martindurant** [comment]
https://github.com/dask/fastparquet/blob/master/fastparquet/writer.py#L1033

**Comment by yohplala** [comment]
> Let's say I write to a directory one partition at a time and set `write_metadata_file` to `True`. After the 2nd iteration, the `_metadata` will be overwritten by the 2nd partition that was processed and, as a result, exclude the 1st one.
 

Hi @fanshi118,
I have recently delved into the code of `write` function for another purpose (PR #546), and I think to know the code enough to tell you that:
- yes `_metadata` is fully rewritten
- but past data are not erased

So your feedback is for me surprising.
Please, can you post your line of code that calls the `write` function?
Thanks for your help understanding this unexpected behavior your are witnessing.
Bests,

**Comment by yohplala** [comment]
PS: to go straight to the point, are you using `append=True` ?

**Comment by fanshi118** [comment]
> PS: to go straight to the point, are you using `append=True` ?

It does work with `append=True`. Thanks for looking into this!
