### ISSUE TITLE
smaller package size

### ISSUE THREAD

**Issue by dazza-codes** [dask/fastparquet#523]
The fastparquet at `0.3.3` installation includes a `test` package; is it necessary?  When trying to squeeze a bunch of python packages into an AWS Lambda layer, it would help if the `test` package could be deleted; can it be deleted?  Could the test package be an optional extra instead of bundled in the default installation?

```
        0  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/
     2408  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_compression.py
    27732  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_api.py
      624  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_thrift_structures.py
     3443  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_speedups.py
     4283  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_encoding.py
     4914  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_partition_filters_specialstrings.py
    33252  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_output.py
     3549  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_with_n.py
     2873  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_dataframe.py
     2735  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_schema.py
     1328  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/util.py
     4641  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_converted_types.py
     4191  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_util.py
    19554  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_read.py
     5027  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/test_aroundtrips.py
        0  2020-10-30 10:26   python/lib/python3.6/site-packages/fastparquet/test/__init__.py
```

**Comment by dazza-codes** [comment]
Thanks for confirmation that the `test` package is not required (it could be an optional extra).  If I was clear about how to modify the `setup.py` for the project, I would gladly submit a PR for it, but I'm not yet so familiar with providing an optional package in the setup.py (vs. an optional extra dependency).  
- https://stackoverflow.com/questions/11240285/can-i-define-optional-packages-in-setuptools
  - note that this applies to optional dependencies (not optional "project packages" within the project)
- https://github.com/dask/dask/blob/master/setup.py
  - the dask setup specifies multiple packages, with associated package-extras for their dependencies
  - it's not entirely clear how to specify _the_ default package vs. optional packages

For my immediate purposes to squeeze a lambda layer, I'm using a work-around to delete the test package and run a project pytest suite on the resulting installation to see that the project is working OK (given adequate test coverage for the footprint used in fastparquet).

```
clean_fastparquet () {
  site=$1
  # removing test package
  if [ -d "${site}/fastparquet" ]; then
    echo "Cleaning fastparquet in $site ..."
    find "${site}/fastparquet" -type f -name '*/test/*' -exec rm {} \;
  fi
}

package_dst=$(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')
clean_fastparquet "$package_dst"
```

For setuptools, maybe there is a way to add an 'optional package' within the project.  When that option is not requested, the default package build could exclude or delete the `test` package.

**Comment by dazza-codes** [comment]
One more thought - I'm more familiar with a project structure that extracts the tests code into a separate directory from the package code, e.g.

- docs
- fastparquet
- tests
  - benchmarks
  - test-data

But that could be a more substantial refactoring with various CI changes required.  I don't understand the full-ecosystem that might require the `test` package to be bundled with the fastparquet distribution.

**Comment by dazza-codes** [comment]
Is fastparquet fully-functional without `numba`?  Could `numba` be an optional dependency?  Using `pipdeptree`:

```
fastparquet==0.3.3
  - numba [required: >=0.28, installed: 0.51.2]
    - llvmlite [required: >=0.34.0.dev0,<0.35, installed: 0.34.0]
    - numpy [required: >=1.15, installed: 1.19.2]
    - setuptools [required: Any, installed: 49.6.0.post20201009]
  - numpy [required: >=1.11, installed: 1.19.2]
  - pandas [required: >=0.19, installed: 1.1.3]
    - numpy [required: >=1.15.4, installed: 1.19.2]
    - python-dateutil [required: >=2.7.3, installed: 2.8.1]
      - six [required: >=1.5, installed: 1.14.0]
    - pytz [required: >=2017.2, installed: 2020.1]
  - six [required: Any, installed: 1.14.0]
  - thrift [required: >=0.11.0, installed: 0.13.0]
    - six [required: >=1.7.2, installed: 1.14.0]
```

Note that `llvmlite` is not "not so lite" - it's a large package in the context of python pip packages, e.g.:

```text
$ du -sh /opt/python/lib/python3.6/site-packages/* | grep -E '^[0-9]*M' | sort
11M	/opt/python/lib/python3.6/site-packages/numba
14M	/opt/python/lib/python3.6/site-packages/numpy
24M	/opt/python/lib/python3.6/site-packages/pandas
24M	/opt/python/lib/python3.6/site-packages/pyproj
32M	/opt/python/lib/python3.6/site-packages/numpy.libs
44M	/opt/python/lib/python3.6/site-packages/fiona
55M	/opt/python/lib/python3.6/site-packages/rasterio
57M	/opt/python/lib/python3.6/site-packages/llvmlite
```

When trying to bundle a parquet library along with other useful science packages for AWS lambda, anything to reduce the package size by using optional extras is useful.  This could be at the cost of performance, but functionality trumps performance when the AWS Lambda limits prevent installation within the lambda limits.

**Comment by martindurant** [comment]
numba is required, sorry. I think any dataset that has any optional fields (i.e., all of them) needs the numba code, or maybe actually every every dataset. Still smaller than arrow :)

I believe @stuartarchibald may be looking into the possibility of cutting out the cython code in favour of numba too.

**Comment by dazza-codes** [comment]
I get that this may not be desired due to the difficulty of the work and/or a preference for using numba, but I'm offering a few comments about a possible set of changes to allow an optional numba....

```
$ git grep 'import numba'
fastparquet/converted_types.py:import numba
fastparquet/encoding.py:import numba
fastparquet/test/test_api.py:import numba
fastparquet/writer.py:import numba
```
Those modules would have to use conditional imports and a custom decorator that could substitute a null-decorator when numba is not available.  It could be refactored into maybe something like `fastparquet/numba_wrapper.py` to consolidate all the dependencies and null-decorator behavior.  

When numba is available, the numba-wrapper decorator would return the function wrapper from numba (`@numba.njit(nogil=True)` mostly).  When numba is not available, the the numba-wrapper decorator would return a null-decorator.

Replace all the numba datatypes in encoding.py with numpy data types?
- `numba.uint8` -> np.uint8 ?

BTW, in my size-estimations, `pyarrow` is coming out smaller than `fastparquet` when bundled with other sci-libs and it _almost_ fits in AWS Lambda limits.  (I'm using various optimizations to enable this, including some binary `strip` changes on libs that can be stripped without breaking ELF - https://github.com/pypa/manylinux/issues/119)

**Comment by martindurant** [comment]
You are welcome to try, but I am fairly certain that the code to walk the encoded definition levels won't run without numba and would need more of a refactor than a null decorator replacing @numba.njit - mostly around the jitclass file-like objects.

**Comment by martindurant** [comment]
Latest master builds 122kB (source) 149kb (wheel) on my machine. Closing this now - release to come soon.
