### ISSUE TITLE
uninitialized array leads to failure in tz_localize ("UserWarning: Inferring time-zone from CET in column __null_dask_index__ failed, using time-zone-agnostic")

### ISSUE THREAD

**Issue by sdementen** [dask/fastparquet#532]
**What happened**:

Cannot get proper tz while reading a dataframe written with tz="CET" (get naive datetimeindex instead).

Issue probably due to use of `np.empty` instead of `np.zeros` in https://github.com/dask/fastparquet/blob/master/fastparquet/dataframe.py#L100 which leads to an exception in https://github.com/dask/fastparquet/blob/master/fastparquet/dataframe.py#L103 as pandas cannot infer the right timezone as the input is garbage (not initalised to zero).

**Minimal Complete Verifiable Example**:

Difficult to come with as depends on the content of `np.empty` .
issue fixed when replacing  `np.empty` by `np.zeros`

**Comment by martindurant** [comment]
Can you show what you did, please?

It may be worthwhile inserting more debugging into that block to see what the problem actually is. In this case, we are not *converting* any times, only attaching a timezone.

**Comment by sdementen** [comment]
Sorry, I am referring to line https://github.com/dask/fastparquet/blob/master/fastparquet/dataframe.py#L128 and https://github.com/dask/fastparquet/blob/master/fastparquet/dataframe.py#L131 (the code there is almost a copy paste of the code in lines 100-103.

I have printed indeed the value of `d` before the line 131 and its content was random dates (e.g.
```
['1970-01-01T00:38:05.738044368' '1970-01-01T00:38:05.736480848'
 '1970-01-01T00:00:00.000007618' ... '2116-06-30T07:23:37.495814144'
 '2116-06-30T07:23:37.495814144' '2116-06-30T07:23:37.495814144']
```)
The line 103 then triggers an `{AmbiguousTimeError} Cannot infer dst time from 2019-10-27 02:00:00, try using the 'ambiguous' argument` with `timezones[six.text_type(col)]="CET"`. This is due to the fact that some random dates is falling on the time of DST (when 2 hours have the same naive representation) and pandas cannot infer.

Would there be some simpler code to just attach a tz ?

**Comment by martindurant** [comment]
cc @jsignell - I forget the dask issue, but it seems we do do timezones, but probably this isn't applied to the max/min statistics values.

**Comment by sdementen** [comment]
can we just create the Index as a DatetimeIndex with the right tz directly (`if d.dtype.kind == "M" and six.text_type(col) in timezones`) ?

**Comment by martindurant** [comment]
I don't know - worth trying. By the way, does everything work despite the warning? We could just catch and ignore the warning (the values get overwritten later anyway).

**Comment by sdementen** [comment]
something like
```python
            d = np.empty(size, dtype=t)
            if d.dtype.kind == "M" and six.text_type(col) in timezones:
                index = DatetimeIndex(d,tz=timezones[six.text_type(col)])
            else:
                index = Index(d)
            views[col] = index.values
```

**Comment by martindurant** [comment]
I don't know, feel free to try. I expect it hits the same ambiguity. There may have been a reason for the two-line version.

(note that we don't actually support py2 anymore, so six.text_type -> str)

**Comment by sdementen** [comment]
you are right, same behavior.
```python
                index = DatetimeIndex(d).tz_localize("UTC").tz_convert(tz=timezones[col]))
```
works but probably slower than
```python
                d.fill(0)
                index = DatetimeIndex(d, tz=timezones[col])
```

**Comment by martindurant** [comment]
Want to make a PR and test? pytest has a hook to ensure no warning is raised by some piece of code.

If you have time, it would be nice to look into the min/max values, in the column-chunk stats, getting the correct timezone too.

**Comment by sdementen** [comment]
@martindurant could you review/comment the PR ?

**Comment by sdementen** [comment]
is fixing this bug solving the issue https://github.com/dask/dask/issues/6925 ? or is it unrelated ?

**Comment by martindurant** [comment]
I don't think it will fix that - the timezone needs to be applied to the "statistics" values, not to the data values as here.
