### ISSUE TITLE
0.4.2 requires pandas >= 1.1.0

### ISSUE THREAD

**Issue by clowtown** [dask/fastparquet#537]
https://github.com/dask/fastparquet/blob/8df22dba86a3cf84f32131a34d7c75e8895997e3/fastparquet/writer.py#L12

This patch change now requires pandas [1.1.0 ](https://github.com/pandas-dev/pandas/pull/33064/files?file-filters%5B%5D=.py) despite having support in this same module for pandas < 1.0.

Was this intentional on a patch? I understand the project documentation says it uses all the latest libraries, but showing support for conflicting versions of pandas is misleading and requires patching by consumers.

**Comment by martindurant** [comment]
Thanks for noticing. 
Yanked, and doing #538 , leading to a 0.5.0.

**Comment by yohplala** [comment]
Hi,
I think this ticket should be marked as solved, right?
