### ISSUE TITLE
`jitclass` dependency failed with latest numba ( 0.52.0 )

### ISSUE THREAD

**Issue by mitochon** [dask/fastparquet#539]
```
AttributeError: module 'numba' has no attribute 'jitclass'
```

**What happened**:
jitclass is moved to experimental starting numba==0.52.0
Currently [requirements.txt](https://github.com/dask/fastparquet/blob/master/requirements.txt#L2) show only numba>=0.28
Possibly this need to be restricted to <=0.51.0
Stack trace points to this line -> https://github.com/dask/fastparquet/blob/master/fastparquet/encoding.py#L231

**What you expected to happen**:
Should not see run time error due to missing dependency

**Anything else we need to know?**:

See also latest Numba release notes -> https://numba.readthedocs.io/en/stable/release-notes.html#version-0-52-0-30-november-2020 in which it is noted

```
PR #6281: Remove numba.jitclass shim as per deprecation schedule. (Stuart Archibald)
```

**Environment**:

- Python version: 3.7
- Operating System: linux
- Install method (conda, pip, source): python:3.7 docker container

**Comment by martindurant** [comment]
See https://github.com/dask/fastparquet/pull/538/files?file-filters%5B%5D=.py&file-filters%5B%5D=.pyx&file-filters%5B%5D=.txt#diff-811f75148ee2687611bb423a83066e82fff00831384cabbe743d226f94f0c8e6 - this will be fixed in the upcoming release.

**Comment by mitochon** [comment]
Thanks for the response!
I'll close this issue.
Do you plan to patch earlier versions?
I imagine something like ` numba>=0.28,<0.52.0` in requirements.txt should suffice as band-aid solution.

**Comment by martindurant** [comment]
> Do you plan to patch earlier versions?

It's not actually possible to do this on pypi - you have to delete and upload new versions, so pip would probably still get confused. I would not attempt this.
