### ISSUE TITLE
is the UserWarning "Coercing datetimes to UTC" still meaningul ? 

### ISSUE THREAD

**Issue by sdementen** [dask/fastparquet#540]
I see the userwarning "Coercing datetimes to UTC" triggered in https://github.com/dask/fastparquet/blob/master/fastparquet/writer.py#L162.
Is it useful ? How is this impacting the user ? 
Should it be removed?

**Comment by martindurant** [comment]
It is maybe useful: paruqet only stored datetimes in UTC, so if you supply timezone aware pandas data, this coercion happens, and you should know about it. The timezone information is stored in the global metadata pandas-specific tag, so if you were to reload the data using fastparquet or pyarrow, you would get the original timezone information back, but if you load with spark or something else, you would loose that information.

**Comment by sdementen** [comment]
ok, that is what i suspected. Maybe the warning should be more explicit/longer to mention what you pinpoint

**Comment by martindurant** [comment]
Feel free to submit a PR with the extended clarification :)

**Comment by sdementen** [comment]
would this be clear ? if so I do a PR

            warnings.warn('Coercing datetimes to UTC before writing the parquet file, the timezone is stored in the metadata. Reading back with fastparquet will restore the timezone properly.')

**Comment by martindurant** [comment]
I think that's fine, yes. Note that pyarrow also supports reading the timezone metadata, because we agreed on how to describe the pandas dtypes.
