### ISSUE TITLE
Future is past? Code cleaning to operate?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#547]
Hi,
I am reading here and there in the sources several `from __future__ import ...`.
From [python doc](https://docs.python.org/3/library/__future__.html), end of page, a lot of these modules (if not all) have made their way into the official python package 3.7, which is, according to my understanding the minimal python version to use with fastparquet. 
That is, except `annotations`.

Hence, I would suggest to remove these imports that have now become useless.
(please, correct me if I am wrong)
Bests,

**Comment by martindurant** [comment]
Yes, there are definitely py2-related lines that can be removed, and I assume this includes all `__future__` imports.

**Comment by yohplala** [comment]
Had a look, don't see them any more.
