### ISSUE TITLE
Reduced number of categories while loading categorical data 

### ISSUE THREAD

**Issue by MayankKr8** [dask/fastparquet#548]
I am trying to load a snappy compressed parquet file from, and then convert the data to a pandas data frame.

I use the fastparquet API for my purpose. I load the parquet files and use the to_pandas method with the categories parameter. This helps me load the data with the desired columns as type 'category', but significantly reduces the number of unique categories. 

The function I use is:
```python
import fastparquet
pqobj = fastparquet.ParquetFile(BytesIO(d['part-00001-e31f9a97-6431-49dc-8bc0-76d9ed4e364c.c000.snappy.parquet']))
e = fastparquet.ParquetFile('myfile.parquet').to_pandas(categories=['canonical_hash'])
e.canonical_hash
```

for which I get the following output 
```
0          0003192ec41337a4a3cd0777193e0719.d2s
1          00075d3c2567d4a6f0527ad08a406aa5.d2s
2          0007e58854e51b38f16921fec04cddc3.d2s
3          000ef2d88ac1bdb583c402024e922f6b.d2s
4          000efa9fa39f852f43a990745a61add6.d2s
                           ...                 
8204744                                    misc
8204745    a85bf0db67ca9a6d1f303eef97ea70dd.d2s
8204746    4f74892b4d5671ef25b125f7485bde4b.d2s
8204747    4936f8d36d3b0062523a30732c128b45.d2s
8204748    d85d25dab7228874c1d262c04f3bb5bf.d2s
Name: canonical_hash, Length: 8204749, dtype: category
Categories (20435, object): ['0003192ec41337a4a3cd0777193e0719.d2s', '00075d3c2567d4a6f0527ad08a406aa5.d2s', '0007e58854e51b38f16921fec04cddc3.d2s', '000ef2d88ac1bdb583c402024e922f6b.d2s', ..., 'ffeb7689588432b574a1cb7de96028fe.d2s', 'ffed262ad72123fdaf1408cb21f70c24.d2s', 'fffffbe413e2341e6d6f125d421243db.d2s', 'misc']
```

However when I do it the long way 
```python
import fastparquet
pqobj = fastparquet.ParquetFile(BytesIO(d['part-00001-e31f9a97-6431-49dc-8bc0-76d9ed4e364c.c000.snappy.parquet']))
e = fastparquet.ParquetFile('myfile.parquet').to_pandas()
e["canonical_hash"]= e["canonical_hash"].astype("category")
e.canonical_hash
```
I get the following output:

```
0          0003192ec41337a4a3cd0777193e0719.d2s
1          00075d3c2567d4a6f0527ad08a406aa5.d2s
2          0007e58854e51b38f16921fec04cddc3.d2s
3          000ef2d88ac1bdb583c402024e922f6b.d2s
4          000efa9fa39f852f43a990745a61add6.d2s
                           ...                 
8204744                                    misc
8204745    a85bf0db67ca9a6d1f303eef97ea70dd.d2s
8204746    4f74892b4d5671ef25b125f7485bde4b.d2s
8204747    4936f8d36d3b0062523a30732c128b45.d2s
8204748    d85d25dab7228874c1d262c04f3bb5bf.d2s
Name: canonical_hash, Length: 8204749, dtype: category
Categories (1308228, object): ['3d9406de839fe730d4014abe99503d18.d2s', '971117ee007eadbc70fa1cc2939bd432.d2s', '96d38697a7487cdb9ebe04003c6ddfc7.d2s', '2eb9ffeaf26ccd9e4036b3824823c24c.d2s', ..., '342d2f6d5f3e01fce8b65439fd390528.d2s', 'd018049ad35fb34dfe03c70e38eba288.d2s', 'f119750a9ec996f0d02f508448d8a7e2.d2s', '29504034e7075b924cda327eb8c188cb.d2s']
```
which is the correct number of categorical classes 
I have also tried using passing a dictionary with the maximum possible number for the labels in the column, but that doesn't sort the problem 
```python
e = fastparquet.ParquetFile('myfile.parquet').to_pandas(categories={"canonical_hash": 8204749})
```

**Environment**:
- fastparquet version : '0.4.2'
- Python version: 3.8.5
- Operating System: Linux, 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
- Install method (conda, pip, source): conda

**Comment by martindurant** [comment]
First a comment: if you have 1.3m categories and 8.2m rows, I would rate this as "high cardinality" and not a great fit for categorical representation.

The categorical loading feature of fastparquet only applies if you can guarantee the same categorisation throughout your dataset - which normally means that it must have been written from pandas in the first place.

**Comment by MayankKr8** [comment]
Hey @martindurant, thanks for clearing this up.
 
I am using this data for training a Gradient Boosted Model, so I require this feature in categorical representation. 

The second comment would explain things, I am using pyspark dataframes to write the data in parquet files, and then try loading them again.
Converting them using .astype() takes a significant amount of time in the pipeline, hence I was looking for a faster way around.

**Comment by yohplala** [comment]
Hi @MayankKr8 @martindurant 
Visiting some tickets. Maybe this one could be closed?
