### ISSUE TITLE
Doc for Spark compatibility

### ISSUE THREAD

**Issue by mrocklin** [dask/fastparquet#55]
I'm trying to make a dataset with fastparquet that can be easily read by both dask.dataframe and spark.  I'm running into some issues because fastparquet appears to support parts of the Parquet spec that Spark does not.  (fixed-len-bytes, run length encoding?)  I anticipate getting questions about this set of landmines in the future.  It would be useful to have a document describing the general situation around the uneven coverage of Parquet readers and a list of features to avoid if cross-system compatibility is desired.

**Comment by martindurant** [comment]
These things are mentioned in "usage", updated in #58 - can you suggest better/more prominent places?

**Comment by martindurant** [comment]
@jangorecki , you may wish to open a new issue with the specifics of how you made your data and the errors you are seeing.
