### ISSUE TITLE
Refactoring way 'partition_on' parameter is handled in 'write'?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#554]
Hi,
This more a general question before being a enhancement request.

Working lately on `write` function to make 'overwrite' possible when using `partition_on` parameter and a 0 `row_group_offsets`, I have been 'surprised' by the way `partition_on` parameter is handled vs row groups.

These 2 parameters result in a split of the data in several files.
Currently, their processing is ordered this way:
* loop over row groups: [line 955](https://github.com/dask/fastparquet/blob/d9cb86d33cedb7cdda1893e569c48ced75e419d0/fastparquet/writer.py#L955)
    - let say I am processing a first group of 100 rows
* then if `partition_on` 'loop' (so to say) over partitions [line 960](https://github.com/dask/fastparquet/blob/d9cb86d33cedb7cdda1893e569c48ced75e419d0/fastparquet/writer.py#L960)
    - if I have 2 partitions into which is equally distributed the data, I will only have 50 rows in each final row group that will be created
* then write files, generate rg metadata and add them to dataset metadata.

This way of doing has the consequence that it does not maintain in a group (a file) the number of rows as requested by the user through the parameter `row_group_offsets`.
According to my understanding, specifying a number of rows in a row group is most notably to 'ensure' size of the data in a row group, to process the right amount of data vs CPU/mem capabilities.
Not having the right number of rows could thus bring degraded performances (somewhat I guess).

As I see it / understand it, the inverse logic would guarantee an approximately constant number of rows in files located in partition folders. Thus it would maintain read/write performances.
* loop over partitions (if any)
     - selection of all rows for a given partition
* then loop over row groups
     - then writing as many row groups, maintaining the number or rows

 So I raise the question of the current logic. Is there something I am missing?
Thanks in advance for your feedback,
Bests,

**Comment by martindurant** [comment]
Yes, you are quite right, it would make more sense for the partition_on and row offsets to be the other way around, and result in fewer files of the requested size. I doubt in practice that both get used together. You should contrast with the Dask case, where many files from a large dataset is acceptable, the current pattern is much easier to implement, because you don't need to do a global groupby and shuffle all of the data before starting to write.

**Comment by yohplala** [comment]
Thanks for the feedback. Some more questions / comments then:

> You should contrast with the Dask case, where many files from a large dataset is acceptable, the current pattern is much easier to implement, because you don't need to do a global groupby and shuffle all of the data before starting to write.

I understand. But is this to be taken into account in the case of fastparquet? To what extent dask use case apply to fastparquet use case? (I am not familiar with dask, nor the interactions between fastparquet ecosystem and dask ecosystem)

> it would make more sense for the partition_on and row offsets to be the other way around, and result in fewer files of the requested size. I doubt in practice that both get used together.

Could we clarify what is the idea / motivation for `row_group_offsets`? In my understanding (to be challenged of course):
- if `row_group_offsets` is an `int`, it means the user really wants that number of rows in his file. So the way it is currently implemented does not fulfill this request.

- if `row_group_offsets` is a list of `int`, the user has so much control over his DataFrame that he is able to say which part of his DataFrame he wants in a separate file, and indeed, in this case, `partition_on` parameter does not make much sense.

So, do you think that the following logic may be applied:

```python
def write_row_grp(file, data, row_group_offsets: List[int]):
    for rg in row_group_offsets:
        metadata = write_file(file, data[rg:rg-1])
    return metadata

def write(file, data, row_group_offsets, partition_on):
    if is_instance(row_group_offsets, list) and partition_on:
        raise Exception
    if partition_on: # in this case, row_group_offsets is an int
       row_group_offsets = # code to turn row_group_offsets into a list
       intersections = # dataset split into sub datasets according intersection of all partitions
       for intersect in intersections:
           metadata = write_row_grp(file, intersect, row_group_offsets: List[int])
    else:
           metadata = write_row_grp(file, data, row_group_offsets: List[int])               
    # update metadata
    ...

**Comment by yohplala** [comment]
Hi @martindurant 
I am not planning to work on this ticket in the short term, but I have been continuing to think about it (my last ticket about grouping row group per partition #658 is actually in connection to this one)
I would just like adding few 'new' thoughts.

> the current pattern is much easier to implement, because you don't need to do a global groupby and shuffle all of the data before starting to write.

Yes, i see a definitive advantage of current pattern: if data for different partitions are spread over the full DataFrame, in the worst case, before reaching `row_group_offsets` for even a 1st partition, loading the full DataFrame might be needed, which would defeat the 'work-by-chunk' logic to save RAM.

Hence, I am thinking that a possibly more relevant approach to try having row groups of target size in each partition (as opposed to the approach I 1st mentionned when opening the ticket) would be to do it in a 2-step approach.
- the 1st step is the one already implemented: chunk by chunk, it sorts the data by partition and write it to files,
- then, if the user requests it through a parameter when calling `write`, like `fill_row_groups=True`, in a 2nd step, data would be read back partition per partition (this time sorted), so that row groups can be merged to reach target row group size.

This 2nd step would be a function on its own:
- that could be called alone on an existing Parquet dataset to 'optimize' data storage,
- or called by `write` if requested by the user.

When called by `write`, the 1st writing step would observe some specificities to speed things up:
- 1st writing would be made on local drive (not target directory, in case it is a remote storage) in a cache directory
- also, no compression (SNAPPY or other) would be used, as these files are not kept
- if target row group size is reached before writing in cache, writing would directly be made to target directory with appropriate settings (compression...)

The core of the new function to develop would:
- conducts an analysis of temporary `pf.row_groups` to sort them by partition (here is the link with #658)
- compares number of rows per row group vs target `row_group_offsets`
- decides which row groups should be merged together
- proceeds to the read/write step
- and recreates/adjust row group description in `pf.row_groups` accordingly

**Comment by yohplala** [comment]
The type of behavior presented above (data compaction) as just been discussed in #733 and is now easier to manage with the `overwrite` feature.
Closing this ticket.
