### ISSUE TITLE
Issue while installing fastparquet . Python 3.8.7 

### ISSUE THREAD

**Issue by connectsachit** [dask/fastparquet#557]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9ncqd0ol/fastparquet/setup.py", line 52, in <module>
        setup(
      File "/opt/pyenv/lib/python3.8/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/opt/pyenv/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/pyenv/lib/python3.8/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/opt/pyenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/opt/pyenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/opt/pyenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/opt/pyenv/lib/python3.8/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/opt/pyenv/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/opt/pyenv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpltrq7lmx', '--quiet', 'numpy>=1.11']' returned non-zero exit status 1.
    ----------------------------------------

**Comment by martindurant** [comment]
I have no idea what that means :|
You might try using an older version of pip, which seems like it is more stable, or you install the dependencies beforehand and then try installing fastparquet.

**Comment by connectsachit** [comment]
I tried older version of pip (19.3.1). 
Also I installed the dependencies of fastparquet first. Still it is not working. Could you please suggest something else?

**Comment by martindurant** [comment]
Not really. I can't even tell from the traceback whether this was a wheel or source install - if the latter, you will need cython and a compiler installed. What is your OS?

In practice, I usually deal with installations on conda, where things tend to work better, particularly for complex dependencies like numba.

**Comment by connectsachit** [comment]
Its a wheel based install. I have python venv, python version 3.8.7

**Comment by martindurant** [comment]
As far as I can tell, we *only* have a wheel for macos, py37 (i.e., my system) https://pypi.org/project/fastparquet/#files . You could try a source install explicitly (`--no-binary fastparquet`).

**Comment by connectsachit** [comment]
Could you please tell what is the use of --no-binary here? 
Should I put all installs first for fastparquet? or directly --no-binary will work ?

**Comment by martindurant** [comment]
`pip install --no-binary fastparquet fastparquet` would make sure that you install the source distribution. You will need compilers and cython, in addition to the normal dependencies.

**Comment by connectsachit** [comment]
pip install --no-binary fastparquet is not working
I installed cpython through pip too

ERROR: You must give at least one requirement to install (see "pip help install")
This is the error while doing pip installl --no-binary fastparquet

**Comment by martindurant** [comment]
> pip install --no-binary fastparquet is not working

That's not the line I wrote, please see above.

Also, I specified "cython", not "cpython"

**Comment by connectsachit** [comment]
@martindurant -> Thanks a lot for help.
pip install from requirements.txt was not taking in the specified order. Hence I specified the fastparquet outside requirements.txt as a separate pip install command and it worked.

**Comment by connectsachit** [comment]
@martindurant - Is pytest-runner mandatory for fastparquet?

**Comment by martindurant** [comment]
...sort of.
It is required to allow `python setup.py test` (or equivalent with pip), but it is not used during normal invocation.
