### ISSUE TITLE
'partition_on' defeats 'statistics'

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#560]
```python
from os import path as os_path
import pandas as pd
import fastparquet as fp
file_path = os_path.expanduser('~/Documents/code/data/test_data')
df=pd.DataFrame({'a':[1,2,3], 'b':['aha', 'oho', 'aha']})
df['b']=df['b'].astype('category')
fp.write(file_path, df, partition_on=['b'], file_scheme='hive')

# Check statistics
print(fp.ParquetFile(file_path).statistics)
```
Results.
```python
{'min': {'a': [1, 2]},
 'max': {'a': [3, 2]},
 'null_count': {'a': [0, 0]},
 'distinct_count': {'a': [None, None]}}
```

If a column is written as a `partition`, it does not appear in the `statistics` dict.
I think it ought to stay considered as a 'normal' column (albeit a `partition`) and be listed in `statistics`.
What is your thought?

**Comment by martindurant** [comment]
No, i disagree with this one - those stats have a specific parquet standard meaning. This is why filter-by-cats and filter-by-stats are different, whee the former needs to worry about types.

On February 7, 2021 7:04:58 AM EST, yohplala <notifications@github.com> wrote:
>```python
>from os import path as os_path
>import pandas as pd
>import fastparquet as fp
>file_path = os_path.expanduser('~/Documents/code/data/test_data')
>df=pd.DataFrame({'a':[1,2,3], 'b':['aha', 'oho', 'aha']})
>df['b']=df['b'].astype('category')
>fp.write(file_path, df, partition_on=['b'], file_scheme='hive')
>
># Check statistics
>print(fp.ParquetFile(file_path).statistics)
>```
>Results.
>```python
>{'min': {'a': [1, 2]},
> 'max': {'a': [3, 2]},
> 'null_count': {'a': [0, 0]},
> 'distinct_count': {'a': [None, None]}}
>```
>
>If a column is written as a `partition`, it does not appear in the
>`statistics` dict.
>I think it ought to stay considered as a 'normal' column (albeit a
>`partition`) and be listed in `statistics`.
>What is your thought?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/fastparquet/issues/560

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yohplala** [comment]
Ok, let's close this ticket then.
A side question. Is there any way to retrieve all `partition` values?

**Comment by martindurant** [comment]
Yes: pf.cats should be it

On February 7, 2021 2:33:33 PM EST, yohplala <notifications@github.com> wrote:
>Ok, let's close this ticket then.
>A side question. Is there any way to retrieve all `partition` values?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/fastparquet/issues/560#issuecomment-774743511

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
