### ISSUE TITLE
unable to install fastparquet using pip in py 2.7

### ISSUE THREAD

**Issue by frustatedprogrammer** [dask/fastparquet#566]
pip install fastparquet was working in py 2.7 till Thursday ( 11/2/2021), after that since Friday it isn't working. 
i havent changed any configurations, it remains the same.
I had just re-ran the same code the next day, and it didnt work. It kept throwing error.

I tried installing the lower version 0.3.3 which is actually compatible with py 2.7, but even there it says require py 3.7 .
ERROR : "RuntimeError: Python version >= 3.7 required." 

command used : 
pip install fastparquet
pip install fastparquet==0.3.3

**Comment by martindurant** [comment]
Sorry, I have no idea why things would have suddenly stopped working for you. I can only suppose that something else on your system was updated.
Perhaps you can clone the repo and run `setup.py` manually? Obviously, I haven't touched py27 myself in quite some time - but I would still recommend conda over pip for installation.

**Comment by frustatedprogrammer** [comment]
![image](https://user-images.githubusercontent.com/79202630/108226100-94ac8500-7162-11eb-917d-c90b01683e02.png)

I am unable to install in py 2.7. I tried almost all the possible ways, there is a constrain. The only way i can install is using pip.

**Comment by frustatedprogrammer** [comment]
it is not installing anywhere, neither in cloud or in local. Please try to install using pip, check if you are also facing similar issues and please let me know how to resolve it.

**Comment by martindurant** [comment]
This works
```
$ conda create -n old -y python=2 fastparquet
...
$ conda activate old
$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:58:04)
[GCC Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastparquet
>>>
```
and this also worked, installing with pip (but I am *not* going to build numba locally)
```
$ conda create -n old python=2 cython pip numba thrift
...
$ conda activate old
$ pip install fastparquet
$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:58:04)
[GCC Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastparquet
>>>
```
