### ISSUE TITLE
Snappy doesn't release the GIL

### ISSUE THREAD

**Issue by mrocklin** [dask/fastparquet#57]
I believe that python-snappy does not release the GIL.  This can be a significant performance blocker for multi-threaded workers.  The direct fix to this would be to improve the upstream library, but there might be  another workaround.  For example, blosc might have direct access.

@esc I know this isn't your focus these days, but can we get GIL-free access to raw compression libraries through Blosc?  Other people without blosc are (de)compressing the data, so we can't use blosc headers and such.

**Comment by esc** [comment]
No, last I checked this was not the case, unfortunately. Might be worth asking @FrancescAlted though.

**Comment by FrancescAlted** [comment]
Yes, [Robert McLeod recently contributed](https://github.com/Blosc/python-blosc/commit/5be587cd6c02c9fceed873fe5e98e4e93841ddb2) a way to release the GIL during Blosc operation.  We still need to do a new public release though.

**Comment by mrocklin** [comment]
To be clear the question is also asking "Can I use python-blosc to snappy-compress data, such that other people with only snappy (not blosc) can decompress it?"

**Comment by martindurant** [comment]
Another useful feature not provided by python-snappy is a counterpart to GzipFile, so that larger data-blocks could be decompressed in a streaming fashion, without materializing the before and after bytestrings.

**Comment by FrancescAlted** [comment]
@mrocklin The answer for the question about Snappy being able to decompress a Blosc frame with Snappy codec is *no*.  The reason is that Blosc adds some meta-information at the beginning of every frame, and hence the pure codecs will not be able to interpret that.

**Comment by mrocklin** [comment]
Yeah, my question isn't whether or not Snappy can decompress Blosc, but rather if the Blosc Python library provides hooks to call Snappy directly, without invoking the Blosc machinery.

**Comment by FrancescAlted** [comment]
That could be possible, but not implemented yet.

Sent from my phone

El 24 des 2016, a les 16:01, Matthew Rocklin <notifications@github.com> va escriure:

**Comment by martindurant** [comment]
There seems to be an open PR to release the GIL: https://github.com/andrix/python-snappy/pull/38

**Comment by makmanalp** [comment]
This can perhaps be closed now that the above PR is merged.

**Comment by martindurant** [comment]
I agree, although at some point, snappy should be released and new conda packages built.
