### ISSUE TITLE
metadata not found error when reading a partition folder on S3

### ISSUE THREAD

**Issue by pembeci** [dask/fastparquet#570]
**What happened**:
I am trying to read a partition from a S3 parquet file which is generated by fastparquet and couldn't do it. My setup is as follows.
* Parquet file is generated by using partitions and appended from time to time. So I have:
`<Root>/file.parquet/YEAR=2021/MONTH=03/DAY=12/` folders where _metadata is in file.parquet directory and under `DAY=XX` I have several `part.X.parquet` files. Generated by:
```
partitions = ["YEAR", "MONTH", "DAY"]
write_parquet(fpath, df, open_with=s3_open, write_index=False, file_scheme="hive", append=True, partition_on=partitions)
```
To read partition `DAY=12` for instance I tried:
```
fpath = f"<Root>/file.parquet/YEAR=2021/MONTH=03/DAY=12"  # tried with trailing /  too
pf = ParquetFile(fpath, open_with=s3_open, root='<Root>/file.parquet')
```
gives error:
`FileNotFoundError: <Root>/file.parquet/YEAR=2021/MONTH=03/DAY=12/_metadata`
Although I specified `root`, _metadata is still looked in the partition folder.

I tried various things by specifiying the root parquet file and adding filters, categories or using iter_row_groups but nothing worked to read the data in chunks. Only thing I got working was putting `part.X.parquet` paths in a list and then reading but this is too manual since I wouldn't know how many part files would be in DAY folders. This becomes much harder if I want to read a whole MONTH partition.

**What you expected to happen**:
To be able to read all data in a partition directory into a dataframe.

**Anything else we need to know?**:
This parquet file is a result of some external streaming data. I can't be sure of the schema, other party may add fileds. So what I am doing is creating a parquet file and then whenever I need to append and schema's didn't match (new chunk of external data may have a new field), reading the parquet file as it is, merge it with new chunk, removing old parquet file and then writing a fresh new parquet. I wonder if this related.
 
**Environment**:

- Python version: 3.8
- Install method (conda, pip, source): pip (version 0.5)

**Comment by martindurant** [comment]
Fastparquet was written before fsspec, and doesn't know how to descend into directories to look for files. However, you can past a *list* of paths, if you've already listed the directly yourself.

```
    fn: path/URL string or list of paths
        Location of the data. If a directory, will attempt to read a file
        "_metadata" within that directory. If a list of paths, will assume
        that they make up a single parquet data set. This parameter can also
        be any file-like object, in which case this must be a single-file
        dataset.
```

**Comment by pembeci** [comment]
OK. Thanks. May be we can use the new append="overwrite" option to mitigate number of part files or try to read it by some other library. Will dask be useful for this purpose or is it using fastparquet underneath?

**Comment by martindurant** [comment]
Dask can use fastparquet or pyarrow, and in both cases gets the list of files in a path for you I think.
