### ISSUE TITLE
RLE_DICTIONARY encoding not supported

### ISSUE THREAD

**Issue by pitrou** [dask/fastparquet#583]
The RLE_DICTIONARY encoding has been added to the Parquet format in November 2013, and is often used to encode dictionary indices in dictionary-encoded columns. It doesn't seem supported in fastparquet 0.5.0.

**Comment by pitrou** [comment]
Snipped traceback:
```python
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fastparquet/api.py", line 402, in to_pandas
    index=index, assign=parts)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fastparquet/api.py", line 231, in read_row_group
    scheme=self.file_scheme)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fastparquet/core.py", line 355, in read_row_group
    cats, selfmade, assign=assign)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fastparquet/core.py", line 331, in read_row_group_arrays
    catdef=out.get(name+'-catdef', None))
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fastparquet/core.py", line 246, in read_col
    skip_nulls, selfmade=selfmade)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/fastparquet/core.py", line 140, in read_data_page
    raise NotImplementedError('Encoding %s' % daph.encoding)
NotImplementedError: Encoding 8
```

**Comment by martindurant** [comment]
Is there a list of encodings that are supported for reading or writing in pyarrow? There are many that had been in the parquet definition for some time, but not actually used by any frameworks.

**Comment by pitrou** [comment]
Yes, you can find it here: https://arrow.apache.org/docs/cpp/parquet.html#encodings
It's up-to-date AFAICT.

**Comment by martindurant** [comment]
No delta ints or delta-byte-array :(. Those are the ones I was really waiting for. DATA_PAGE_V2 has useful extras in, though.

It would be nice to add these to fastparquet, but I'm not sure when I'll get to it. Should have been a GSOC project!

**Comment by pitrou** [comment]
Feel free to open an Arrow JIRA for those encodings, explaining what the savings would be :-)

**Comment by pitrou** [comment]
Also, for reference, this came in the context of https://issues.apache.org/jira/browse/ARROW-12203 . We're considering emitting more types and encodings by default.

**Comment by martindurant** [comment]
It would be worthwhile surveying the other parquet systems (especially spark) to see which of them implements what. These days, arrow can go it alone, however.

I might get around to raising a JIRA as you suggest, except that I'll be making more work for myself eventually.

**Comment by pitrou** [comment]
AFAICT, Spark uses the reference Java Parquet implementation [parquet-mr](https://github.com/apache/parquet-mr/), which supports all encodings.

**Comment by martindurant** [comment]
What I mean to say is: does it actually produce data that makes use of those encodings? Does it, for instance, produce "v2" data page headers when writing?

**Comment by pitrou** [comment]
There seem to be two presets: "v1" (the default) and "v2". If "v2" is chosen, then it can emit the various DELTA encodings and the RLE_DICTIONARY encoding.

I have no idea how it chooses to emit v2 rather than v1 data pages (but note v2 data pages are not much different from v1).

**Comment by martindurant** [comment]
Thanks for looking into it, @pitrou . Good to know that fastparquet is probably still compatible with their default.

So I'll have to decide whether to implement all of these. It may not be worth just doing RLE_DICTIONARY when there are others out there that we can't handle.

**Comment by martindurant** [comment]
@pitrou , do you happen to have a nice simple example of a dataset with RLE_DICTIONARY for testing? Seems like a trivial fix, something we already support but hadn't added the name.

**Comment by pitrou** [comment]
You can take a look at https://github.com/apache/parquet-testing/blob/master/data/datapage_v2.snappy.parquet and https://github.com/apache/parquet-testing/blob/master/data/repeated_no_annotation.parquet

**Comment by martindurant** [comment]
Perfect, thank you.
