### ISSUE TITLE
Reading a row group from its position in 'row_groups'?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#591]
Hi,

As far as I understand, `statistics` attribute of `ParquetFile` object is generated from the `row_groups` attribute.
I am thus assuming that the position of the values in the lists ('min', 'max'...) is the same as the position  in `row_groups` of the row group the values belong to.

I am selecting row groups based on the number of rows they have.
(attribute `pf.row_groups[row_group_idx].num_rows`)

I first identify a row group given a timestamp. I retrieve its index from the min/max timestamps as contained in `statistics`.
Then, as I want to be sure to have at least N previous rows, I add row groups that precedes the one with the timestamp of interest until I am certain I have enough rows.
(data is sorted according timestamps)

For example,
 * timestamp of interest is in row group wich index is 10 (10th position in `row_groups` attribute).
 *  I want to be sure to have at least 20 previous rows (preceding this timestamp),
 * I check row group which index is 9. It contains 13 rows: there might be up to 6 missing rows,
 * I check row group which index is 8. It contains 18 rows. Ok, if I load row groups 8, 9 & 10, I am sure to have 20 rows preceding the timestamp of interest.

Please, what is the most convenient way to load row groups knowing their index (position) in `row_groups` attribute?
Should a convenience function be implemented?
Thanks for your help!
Bests

**Comment by martindurant** [comment]
There is API for exactly this:
- `ParquetFile.read_rw_group_file` (and `.read_row_group`) will read only the supplied row-group into a pandas dataframe. The "row group" is exactly one of the objects from the `ParquetFile.row_groups` list . The variant without `_file` is for the case that you created the `ParquetFile` from an open file (not a pathstring) and the dataset is not partitioned into files.

Alternatively, you you operate on the `row_groups` list directly:
```python
import fastparquet
import copy
pf = fastparquet.ParquetFile(...)
pf2 = copy.copy(pf)  # only necessary to copy if you still want to use the original or its stats
pf2.row_groups = pf.row_groups[8:11]
df = pf2.to_pandas()
```

**Comment by yohplala** [comment]
Thanks a lot Martin, it works great! Thanks again!
