### ISSUE TITLE
fastparquet v 0.6.1 crashes on read

### ISSUE THREAD

**Issue by jonathanbranam** [dask/fastparquet#604]
**What happened**:

Loading a 32Mb parquet file crashes with a core dump. It takes up 3Gb of memory before crashing.

**What you expected to happen**:

Prior to this version (unsure if 0.5.0 or 0.6.0) loading the same file worked with no problem. Tested on 0.5.0 without issues. Will test on 0.6.0 also.

**Minimal Complete Verifiable Example**:

Sorry I can't provide the file as it is private data. 

```python
pd.read_parquet(filename)
```

**Anything else we need to know?**:

This issue appeared today (2021-05-12) so we assume it is related to release 0.6.1. Switching to `pyarrow` fixed the problem immediately. Previously, `pyarrow` was not installed and `fastparquet` was always used. Our Jupyter environments are ephemeral and torn down every day, so we reinstall new versions daily for work. Thus we assume 0.6.1 introduced the bug.

**Environment**:

- Dask version: ? 0.6.1 fastparquet
- Python version: 3.8.5
- Operating System: Ubuntu 20.04.1 LTS (Focal Fossa) on AWS
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Can you please give any extra information you can, for example:
- if you can select from the columns, maybe you can isolate which data type is causing this
- it would be useful to know the total number of rows, or rows per row-group/file
- if you happen to know the encoding and compression

**Comment by jonathanbranam** [comment]
Sorry, updated above. I am working with a colleague and I do not have direct access to the data file. It is only 32Mb! I will try to get more information about the data types.

**Comment by martindurant** [comment]
Thank you. Obviously I would have a better chance to fix if you could create a sharable version of the file which also shows the crash.

**Comment by jonathanbranam** [comment]
Of course, I understand. I will see if I can get a minimum reproducible set of data and de-identify it. Might take me a few days to get it though.

**Comment by jonathanbranam** [comment]
Here is the output of calling DataFrame.info(). This file was loaded successfully using `fastparquet` `0.5.0`. This file was written using a previous version of `fastparquet` but we aren't sure exactly which version. Thanks! I'll try to provide more information when I have it. Please feel free to ask for anything. We appreciate the library and the great work!

<img width="728" alt="dataframe_info_obsc" src="https://user-images.githubusercontent.com/21876/118009534-1fdd8700-b31c-11eb-9a80-87b60605267b.png">

**Comment by martindurant** [comment]
I would appreciate if you would try reading one column of each type: object, float, datetime, category. Do you happen to know how many category labels per category column you have?

**Comment by tobiasraabe** [comment]
Hi, happy to open another issue if I am mixing two separate problems.

I also experience problems with the new release. For me, it is related to reading timestamps on Windows. Other platforms seem fine. You can find the failing tests here : https://github.com/covid-19-impact-lab/sid/pull/125/checks?check_run_id=2568579248. I can provide more information if you tell me what you need.

**Comment by martindurant** [comment]
I am already working on this. It turns out that Windows has a different idea of what `long` means, even on 64-bit.

**Comment by jonathanbranam** [comment]
Update: I have the problematic file now. The error occurs on an object column with six distinct values. It has 370k non-null values. If I read the file using pyarrow then write it out using pyarrow, then fastparquet can read it without error. However, if I read with pyarrow, then write it out with fastparquet, then fastparquet will fail on read. Tested on 0.6.2.

**Comment by martindurant** [comment]
```
In [5]: import pandas as pd

In [6]: import numpy as np

In [7]: x = np.random.choice(["six", "different", "but", "interesting", "strings", "here"], size=792692)

In [8]: df = pd.DataFrame({'x': x})

In [9]: df['x2'] = df.x.astype("categorical")

In [10]: df['x2'] = df.x.astype("category")

In [11]: df.to_parquet("out", engine="fastparquet")

In [12]: pd.read_parquet("out", engine="fastparquet")
Out[12]:
                  x           x2
0           strings      strings
1              here         here
2           strings      strings
3               but          but
```

**Comment by jonathanbranam** [comment]
The data are encoded as objects. Sorry, just finishing a minimal reproducible example. This gives a core dump for me:

```
import pandas as pd
import numpy as np

values = [
    "nan",
    "Hello",
    "How is this",
    "Another String",
    "These arent categories",
    "Heres another",
    "This is fine",
]

p = [0.52, 0.28, 0.08, 0.05, 0.04, 0.028, 0.002]

test_df = pd.DataFrame({
    'test': [np.nan if v=='nan' else v for v in np.random.choice(values, size=500_000, p=p)]
})

test_filename = 'test_issue_604.parquet'

test_df.to_parquet(test_filename, engine='fastparquet')
pd.read_parquet(test_filename, engine='fastparquet')
```

**Comment by jonathanbranam** [comment]
If I reduce the size of the column to 4,000 elements, I get an actual error instead of a core dump:

```
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-1-35f125a80d81> in <module>
     22 
     23 test_df.to_parquet(test_filename, engine='fastparquet')
---> 24 pd.read_parquet(test_filename, engine='fastparquet')

/opt/conda/lib/python3.8/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, **kwargs)
    315     """
    316     impl = get_engine(engine)
--> 317     return impl.read(path, columns=columns, **kwargs)

/opt/conda/lib/python3.8/site-packages/pandas/io/parquet.py in read(self, path, columns, **kwargs)
    210             parquet_file = self.api.ParquetFile(path)
    211 
--> 212         return parquet_file.to_pandas(columns=columns, **kwargs)
    213 
    214 

/opt/conda/lib/python3.8/site-packages/fastparquet/api.py in to_pandas(self, columns, categories, filters, index)
    389                                     else v[start:start + rg.num_rows])
    390                              for (name, v) in views.items()}
--> 391                     self.read_row_group(rg, columns, categories, infile=f,
    392                                         index=index, assign=parts)
    393                     start += rg.num_rows

/opt/conda/lib/python3.8/site-packages/fastparquet/api.py in read_row_group(self, rg, columns, categories, infile, index, assign)
    254                                            categories, index)
    255             ret = True
--> 256         core.read_row_group(
    257                 infile, rg, columns, categories, self.schema, self.cats,
    258                 self.selfmade, index=index, assign=assign,

/opt/conda/lib/python3.8/site-packages/fastparquet/core.py in read_row_group(file, rg, columns, categories, schema_helper, cats, selfmade, index, assign, scheme, partition_meta)
    533     if assign is None:
    534         raise RuntimeError('Going with pre-allocation!')
--> 535     read_row_group_arrays(file, rg, columns, categories, schema_helper,
    536                           cats, selfmade, assign=assign)
    537 

/opt/conda/lib/python3.8/site-packages/fastparquet/core.py in read_row_group_arrays(file, rg, columns, categories, schema_helper, cats, selfmade, assign)
    506             continue
    507 
--> 508         read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
    509                  selfmade=selfmade, assign=out[name],
    510                  catdef=out.get(name+'-catdef', None))

/opt/conda/lib/python3.8/site-packages/fastparquet/core.py in read_col(column, schema_helper, infile, use_cat, selfmade, assign, catdef)
    419         else:
    420             skip_nulls = False
--> 421         defi, rep, val = read_data_page(infile, schema_helper, ph, cmd,
    422                                         skip_nulls, selfmade=selfmade)
    423         if rep is not None and assign.dtype.kind != 'O':  # pragma: no cover

/opt/conda/lib/python3.8/site-packages/fastparquet/core.py in read_data_page(f, helper, header, metadata, skip_nulls, selfmade)
    125 
    126         width = helper.schema_element(metadata.path_in_schema).type_length
--> 127         values = read_plain(io_obj.read(),
    128                             metadata.type,
    129                             int(daph.num_values - num_nulls),

/opt/conda/lib/python3.8/site-packages/fastparquet/encoding.py in read_plain(raw_bytes, type_, count, width, utf, stat)
     39             else:
     40                 return np.array([bytes(raw_bytes)], dtype='O')
---> 41         return np.array(unpack_byte_array(raw_bytes, count, utf=utf))

/opt/conda/lib/python3.8/site-packages/fastparquet/speedups.pyx in fastparquet.speedups.unpack_byte_array()

SystemError: Negative size passed to PyUnicode_New
```

**Comment by martindurant** [comment]
OK thank you - I should be able to work with that

**Comment by jonathanbranam** [comment]
Great. Thanks! I'm happy to provide more if needed and/or test any builds. Again, very appreciative of the great library and work!

**Comment by martindurant** [comment]
Note that you helped me to identify a speedup of ~15% for UTF8 string reading, so I'm almost glad this bug was there.
