### ISSUE TITLE
Documentation not updated yet regarding custom metadata

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#611]
Hi,

Reading through the website, I can see that `custom_metadata` is not documented in [`write` API documentation](https://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.write).

**Comment by martindurant** [comment]
There have been a lot of changes in fastparquet recently, and the docs have yet to catch up! Help appreciated.

On May 15, 2021 2:55:50 PM EDT, yohplala ***@***.***> wrote:
>Hi,
>
>Reading through the website, I can see that `custom_metadata` is not
>documented in [`write` API
>documentation](https://fastparquet.readthedocs.io/en/latest/api.html#fastparquet.write).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/fastparquet/issues/611

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yohplala** [comment]
`custom_metadata` parameter is now in the documentation.
Closing ticket.
