### ISSUE TITLE
Filtering not working ?anylonger? on timestamp

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#612]
**What happened**:
I updated fastparquet from 0.5.0 to 0.6.3 to benefit from being able to add custom key/value metadata.
On the lib I am working on, heavily relying on fastparquet :), I ran my set of unit tests, and all of sudden, several tests (previously running ok) were failing. Damn!
Checking more thoroughly what could be the cause of failure, it appears that when loading dataset with fastparquet while using filters, expected data would not be loaded.
Making some examples of dataset, it seems that filtering on timestamp fails.
I am however unable at the moment to say that the root cause really is the type of the data or if it is someting else.
(I say this because I feel that there has been some work between 0.5.0 and 0.6.3 on data encoding, but then, I have clearly not deep dived in this).
It may also be something else because the 1st example and the 2nd example are the same, only the ordering of the filter is different. But because it is an 'OR' filtering, order should not matter.
So maybe there are several bugs.
Here are some examples that work and some that fail.

```python
import os
import pandas as pd
import fastparquet as fp

file = os.path.expanduser('~/Documents/code/data/fp_test')
# Dataset
ts = [pd.Timestamp('2021/01/01 08:00:00'),
      pd.Timestamp('2021/01/05 10:00:00')]
val = [10, 34]
df = pd.DataFrame({'val': val, 'ts': ts})
fp.write(file, df, row_group_offsets=1, file_scheme='hive')      # the 2 rows are written in 2 different files
```
```bash
In [46]: df
Out[46]: 
   val                  ts
0   10 2021-01-01 08:00:00
1   34 2021-01-05 10:00:00
```
```python
ts_filter = pd.Timestamp('2021/01/03 00:00:00')

# OR filtering on timestamps: work
filt = [[('ts','<',ts_filter)],[('ts','>=',ts_filter)]]
pf = fp.ParquetFile(file)
df_filtered = pf.to_pandas(filters=filt)

# OR filtering on timestamps: does not work (same as previous one, but different order)
filt = [[('ts','>=',ts_filter)],[('ts','<',ts_filter)]]
pf = fp.ParquetFile(file)
df_filtered = pf.to_pandas(filters=filt)
```
Result:
```bash
In [48]: df_filtered
Out[48]: 
   val                  ts
0   34 2021-01-05 10:00:00
```
Expect:
```bash
   val                  ts
0   10 2021-01-01 08:00:00
1   34 2021-01-05 10:00:00
```
```python
# AND filtering on timestamps: does not work (I could check that applied independently, result is ok for each of them)
ts_filter_down = pd.Timestamp('2021/01/03 00:00:00')
ts_filter_up = pd.Timestamp('2021/01/06 00:00:00')
filt = [('ts','>=',ts_filter_down),('ts','<',ts_filter_up)]
pf = fp.ParquetFile(file)
df_filtered = pf.to_pandas(filters=filt)
```
Result:
```bash
In [52]: df_filtered
Out[52]: 
Empty DataFrame
Columns: [val, ts]
Index: []
```
Expected:
```bash
   val                  ts
0   34 2021-01-05 10:00:00
```
```python
# AND filtering on int: work
val_filter_down = 16
val_filter_up = 36
filt = [('val','>=',val_filter_down),('val','<',val_filter_up)]
pf = fp.ParquetFile(file)
df_filtered = pf.to_pandas(filters=filt)
```

**Anything else we need to know?**:
Not that I can see.

**Environment**:

- Fastparquet version: 0.6.3
- Python version: 3.8.5.final.0
- Operating System: #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
- Install method (conda, pip, source): first conda, then to run fastparquet test cases, from source

**Comment by martindurant** [comment]
Sorry, i'm unlikely to have time to look into this next week due to Dask Distributed. You may wish to check what happens in val_to_num.

On May 15, 2021 4:08:12 PM EDT, yohplala ***@***.***> wrote:
>**What happened**:
>I updated fastparquet from 0.5.0 to 0.6.3 to benefit from being able to
>add custom key/value metadata.
>On the lib I am working on, heavily relying on fastparquet :), I ran my
>set of unit tests, and all of sudden, several tests (previously running
>ok) were failing. Damn!
>Checking more thoroughly what could be the cause of failure, it appears
>that when loading dataset with fastparquet while using filters,
>expected data would not be loaded.
>Making some examples of dataset, it seems that filtering on timestamp
>fails.
>I am however unable at the moment to say that the root cause really is
>the type of the data or if it is someting else.
>(I say this because I feel that there has been some work between 0.5.0
>and 0.6.3 on data encoding, but then, I have clearly not deep dived in
>this).
>It may also be something else because the 1st example and the 2nd
>example are the same, only the ordering of the filter is difference.
>But because it is an 'OR' filtering, order should not matter.
>So maybe there are several bugs.
>Here are some examples that work and some that fail.
>
>```python
>import os
>import pandas as pd
>import fastparquet as fp
>
>file = os.path.expanduser('~/Documents/code/data/fp_test')
># Dataset
>ts = [pd.Timestamp('2021/01/01 08:00:00'),
>      pd.Timestamp('2021/01/05 10:00:00')]
>val = [10, 34]
>df = pd.DataFrame({'val': val, 'ts': ts})
>fp.write(file, df, row_group_offsets=1, file_scheme='hive')      # the
>2 rows are written in 2 different files
>```
>```bash
>In [46]: df
>Out[46]: 
>   val                  ts
>0   10 2021-01-01 08:00:00
>1   34 2021-01-05 10:00:00
>```
>```python
>ts_filter = pd.Timestamp('2021/01/03 00:00:00')
>
># OR filtering on timestamps: work
>filt = [[('ts','<',ts_filter)],[('ts','>=',ts_filter)]]
>pf = fp.ParquetFile(file)
>df_filtered = pf.to_pandas(filters=filt)
>
># OR filtering on timestamps: does not work (same as previous one, but
>different order)
>filt = [[('ts','>=',ts_filter)],[('ts','<',ts_filter)]]
>pf = fp.ParquetFile(file)
>df_filtered = pf.to_pandas(filters=filt)
>```
>Result:
>```bash
>In [48]: df_filtered
>Out[48]: 
>   val                  ts
>0   34 2021-01-05 10:00:00
>```
>Expect:
>```bash
>   val                  ts
>0   10 2021-01-01 08:00:00
>1   34 2021-01-05 10:00:00
>```
>```python
># AND filtering on timestamps: does not work (I could check that
>applied independently, result is ok for each of them)
>ts_filter_down = pd.Timestamp('2021/01/03 00:00:00')
>ts_filter_up = pd.Timestamp('2021/01/06 00:00:00')
>filt = [('ts','>=',ts_filter_down),('ts','<',ts_filter_up)]
>pf = fp.ParquetFile(file)
>df_filtered = pf.to_pandas(filters=filt)
>```
>Result:
>```bash
>In [52]: df_filtered
>Out[52]: 
>Empty DataFrame
>Columns: [val, ts]
>Index: []
>```
>Expected:
>```bash
>   val                  ts
>0   34 2021-01-05 10:00:00
>```
>```python
># AND filtering on int: work
>val_filter_down = 16
>val_filter_up = 36
>filt = [('val','>=',val_filter_down),('val','<',val_filter_up)]
>pf = fp.ParquetFile(file)
>df_filtered = pf.to_pandas(filters=filt)
>```
>
>**Anything else we need to know?**:
>Not that I can see.
>
>**Environment**:
>
>- Fastparquet version: 0.6.3
>- Python version: 3.8.5.final.0
>- Operating System: #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
>- Install method (conda, pip, source): first conda, then to run
>fastparquet test cases, from source
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/fastparquet/issues/612

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yohplala** [comment]
> Sorry, i'm unlikely to have time to look into this next week due to Dask Distributed. You may wish to check what happens in val_to_num.

Hi Martin,
Thanks for letting me know.
Ok, I re-played the commits and I have at least found when the 'regression' has been introduced.
I can confirm that on above tests, everything is working fine (at least, I have the expected results) till [commit f1b80b1](https://github.com/dask/fastparquet/commit/f1b80b13c1813c92b5b601d30c32ba176c440d54).

Starting at this commit, results are not ok any longer.

Here is the set of tests I am running. I can confirm it seems related to `pd.Timestamp`, as I am running 'same' filtering logic with `int` as well and they continue to work ok on later commits.

```python
# commit  fp    status date
# 3372735 0.5.0 ok
# fdef884 0.5.0 ok     26/04
# d9e0598 0.6.0 nook   11/05
# b0185b5 0.6.0 ok     07/05
# d6eb55c 0.6.0 nook   09/05
# 508cb47 0.6.0 ok     08/05
# f1b80b1 0.6.0 nook   09/05 <- regression introduced

import os
import pandas as pd
import fastparquet as fp

file = os.path.expanduser('~/Documents/code/data/fp_test')

ts = [pd.Timestamp('2021/01/01 08:00:00'),
      pd.Timestamp('2021/01/05 10:00:00')]
val = [10, 34]
df = pd.DataFrame({'val': val, 'ts': ts})
fp.write(file, df, row_group_offsets=1, file_scheme='hive')
pf = fp.ParquetFile(file)

ts_filter = pd.Timestamp('2021/01/03 00:00:00')

# OR filtering on timestamps: work
filt = [[('ts','<',ts_filter)],[('ts','>=',ts_filter)]]
df_filtered = pf.to_pandas(filters=filt)
assert df.equals(df_filtered)


# OR filtering on int: work
val_filter = 16
filt = [[('val','>=',val_filter)],[('val','<',val_filter)]]
df_filtered = pf.to_pandas(filters=filt)
assert df.equals(df_filtered)

# OR filtering on timestamps: does not work
filt = [[('ts','>=',ts_filter)],[('ts','<',ts_filter)]]
df_filtered = pf.to_pandas(filters=filt)
assert df.equals(df_filtered)


# AND filtering on int: work
val_filter_down = 16
val_filter_up = 36
filt = [('val','>=',val_filter_down),('val','<',val_filter_up)]
df_filtered = pf.to_pandas(filters=filt)
assert df.iloc[1:].reset_index(drop=True).equals(df_filtered)

# AND filtering on timestamps: does not work
ts_filter_down = pd.Timestamp('2021/01/03 00:00:00')
ts_filter_up = pd.Timestamp('2021/01/06 00:00:00')
filt = [('ts','>=',ts_filter_down),('ts','<',ts_filter_up)]
df_filtered = pf.to_pandas(filters=filt)
assert df.iloc[1:].reset_index(drop=True).equals(df_filtered)
```

I will take a look at modified file.
I am sharing these inputs so that maybe it can give you some hints what may have turn wrong without that you have to delve deep into the topic.

Have a good evening,
Bests,

**Comment by yohplala** [comment]
Hmmm,
I can see that `val_to_num` is not modified in this commit, nor are `filter_out_stats` nor `filter_out_cats`, I am clueless...
The commit is ...huge...
If you have any pointer, I would gladly take it. I am sorry, it does not appear that easy.
Thanks for any help,
Bests
