### ISSUE TITLE
Modifiable custom metadata in case of append True or 'overwrite'

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#613]
Custom metadata cannot be modified when 'append' is True or 'overwrite'.
Request is that they are modifiable.
There might be 2 ways, I am not sure if one is simpler than the other. Both seem fine to me.
 - case 1: either new custom metadata replaces previous ones, whatever the keys
 - case 2: or only by using the same keys, the previous value gets replaced (and all previous keys are kept)

Currently:
```python
import os
import pandas as pd
from fastparquet import write, ParquetFile
import pickle
import codecs

file = os.path.expanduser('~/Documents/code/data/test_fp')
# Dataset
df = pd.DataFrame({'a': [15, 16], 'b':[0.3, 0.8]})
write(file, df, file_scheme='hive', custom_metadata={'cache':'tralala'})
#ParquetFile(file).key_value_metadata['cache']

df = pd.DataFrame({'a': [17], 'b':[0.9]})
write(file, df, file_scheme='hive', custom_metadata={'truc':'tralalaloulou'},
      append=True)
ParquetFile(file).key_value_metadata['truc']
```
Result
```bash
Traceback (most recent call last):

  File "<ipython-input-62-439d27e24215>", line 16, in <module>
    ParquetFile(file).key_value_metadata['truc']

KeyError: 'truc'
```
With request,
 - either case 1: key 'cache' would be erased, overwritten by the new key 'truc'
 - or case 2: key 'truc' is added to key 'cache', and (I think this case is more complex) if key 'cache' is used again in a call to 'write', then its value is updated
 
Do you think this is possible?

**Comment by martindurant** [comment]
Yes, sounds very possible, just not a case that's been tried before. I favour Case 2, which matches my understanding of what "append" means. It would be a pity to add yet more optional arguments to write.

**Comment by yohplala** [comment]
Implementation of specific functions for updating metadata in PR #768
 - `util.update_custom_metadata`
 - `writer.update_file_custom_metadata`
