### ISSUE TITLE
Sensitivity to order of row group filters causes empty dataframes to be returned from ParquetFile.to_pandas

### ISSUE THREAD

**Issue by Iguanotron** [dask/fastparquet#624]
**What happened**:

Reading a parquet file with relational comparison filters on a date column (using filters which should have included all rows in the file, which had a single row group) returned an empty dataframe, depending on the order of the filters.

**What you expected to happen**:

I expected all rows in the file to be present in the output.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import fastparquet

dates = pd.date_range('20200101', '20200201', freq='1H')
filename = 'foo.parquet'
df = pd.DataFrame(dates, columns=['a'])

fastparquet.write(filename, df)

# Old-style filters
filters = [
    ('a', '>=', dates.min()),
    ('a', '<=', dates.max()),
]

# Works correctly
assert fastparquet.ParquetFile(filename).to_pandas(filters=filters).shape[0] == len(dates)

# Fails; dataframe is empty (bug)
assert fastparquet.ParquetFile(filename).to_pandas(filters=list(reversed(filters))).shape[0] == len(dates)
```

**Anything else we need to know?**:

Which order the filters need to be in seems to vary per-file--some files written with an older version of fastparquet failed with the filters in the opposite order.

**Environment**:

- Fastparquet version: 0.6.3
- Pandas version: 1.2.4
- Python version: 3.8.10
- Operating System: Ubuntu 20.04.1 LTS
- Install method (conda, pip, source): conda

**Comment by martindurant** [comment]
Please try with the main branch version, I believe this was fixed.

**Comment by Iguanotron** [comment]
Ah, looks like it's working with the main branch. Thanks!
