### ISSUE TITLE
Support for timestamp in nanosecond with Parquet format v2?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#625]
Hi,
This is a general newbie question.
I could read in pyarrow documentation [here](https://arrow.apache.org/docs/python/parquet.html#storing-timestamps) the following:
_Timestamps with nanoseconds can be stored without casting when using the more recent Parquet format version 2.0_

I have understood that you are working on datapage v2 @martindurant 
Is 'datapage v2' and 'parquet format v2' the same thing or are these different topics?

Thanks in advance for the clarification.
Have a good day,
Bests

**Comment by martindurant** [comment]
There isn't really a parquet version 2, but certain new things have percolated in over time - more of an evolution.

#586 lists "new time types" as a bullet not yet started. I am aware of it!

**Comment by yohplala** [comment]
Thanks for your quick feedback @martindurant. Ok, closing then.
