### ISSUE TITLE
parquet.gz file corrupted after failed append write

### ISSUE THREAD

**Issue by ipl31** [dask/fastparquet#626]
**What happened**:
Wrote data frame to parquet file using fastparquet. Attempted to append to the file with another data frame which was missing a column. Write failed (expected). But now parquet file appears to be corrupted and can't be read by fastparquet.

**What you expected to happen**:
I expected the append to fail. But I expected to be able to read the parquet file after the failed append.

**Minimal Complete Verifiable Example**:

```
from pandas import DataFrame
from fastparquet import ParquetFile,write

data1 = {'col1': [1,2], 'col2': [1,2]}
data2 = {'col1': [3,4] }

filename = "./bug-report-repro.parquet.gz"

write(filename,DataFrame(data=data1),append=False,compression="GZIP",file_scheme="simple")

try:
    write(filename, DataFrame(data=data2),append=True,compression="GZIP",file_scheme="simple")
except KeyError as e:
    print("Column not found")
    print(e)

# This will raise TypeError on schema.py", line 71, in __init__self.root = schema_elements[0]
ParquetFile(filename)
```
**Anything else we need to know?**:
I don't believe so.

**Environment**:

- Dask version: N/A
- Parquet version: 0.6.3 
- Python version: 3.7.10
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Agreed, checks of compatibility should be done before the file is touched. This would be a relatively simple change in `fastparquet.writer.write`.

**Comment by ipl31** [comment]
@martindurant not very familiar with the code base, but might be able to provide a patch if you can give me more details on how to perform the compatibility check.

**Comment by martindurant** [comment]
The existing file is opened [here](https://github.com/dask/fastparquet/blob/main/fastparquet/writer.py#L921) and [here](https://github.com/dask/fastparquet/blob/main/fastparquet/writer.py#L736) (you were probably hitting the latter). The existing dataset's dtypes can be compared with the incoming ones: either identical, or, better, accounting for possible casting. As a first pass, you could compare just that the same set of columns are in both.

**Comment by ipl31** [comment]
@martindurant thanks for merging the fix. When do you intend to cut a new a release tag? Should I close this ticket now?

**Comment by martindurant** [comment]
I have a lot going on right now, including development in this library (see the PRs), but it should not be more than a couple of weeks or so.
