### ISSUE TITLE
UserWarning: Non-categorical multi-index is likely brittle

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#629]
I am encountering following warning as I am loading data initially written with fastparquet.
```python
/home/pierre/anaconda3/lib/python3.8/site-packages/fastparquet-0.6.3-py3.8-linux-x86_64.egg/fastparquet/core.py:466: UserWarning: Non-categorical multi-index is likely brittle
  warnings.warn("Non-categorical multi-index is likely brittle")
```
Despite having the initial dataset, I have been unable to pinpoint when / what is the action before writing that causes at reading this warning, nor have I been able to reproduce the error on a DataFrame created specifically to illustrate this trouble.

Within this DataFrame, I am encoding a column as categorical (column 'trend').
I noticed that if I do not order the categories before writing, I don't have the warning at reading.
```python
from pandas.api.types import CategoricalDtype
trends = CategoricalDtype(['down', 'unconfirmed', 'up'])
df['trend'] = df['trend'].astype(trends)
```
If I order the categories before writing, I have the warning at reading.
```python
from pandas.api.types import CategoricalDtype
trends = CategoricalDtype(['down', 'unconfirmed', 'up'], ordered=True)
df['trend'] = df['trend'].astype(trends)
```

I am joining the parquet file that at reading causes this warning.
I am also joing the very same one without categories being ordered, and that does not raise the warning.
Comparing them with  `pd.testing.assert_frame_equal`, they appear equal, so fastparquet is able to rebuild files the same way.

To read the files, and see the warrning for the 1st one, nothing crazy.
```python
import os
import fastparquet as fp

file = os.path.expanduser('~/Documents/code/data/fp_brittle')
df1 = fp.ParquetFile(file).to_pandas()

file = os.path.expanduser('~/Documents/code/data/fp_not_brittle')
df2 = fp.ParquetFile(file).to_pandas()
```

**Environment**:

- fastparquet version: 0.6.3
- Python version: 3.8.5.final.0
- Operating System: 20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021
- Install method (conda, pip, source): source

[fp_brittle.zip](https://github.com/dask/fastparquet/files/6757158/fp_brittle.zip)
[fp_not_brittle.zip](https://github.com/dask/fastparquet/files/6757173/fp_not_brittle.zip)

**Comment by yohplala** [comment]
PS:
This is more a 'feature request'. I also noticed that fastparquet is not able to keep category ordering.
On this example, ('unfortunately', no warning is raised at reading), category ordering is not kept.

```python
import os
import pandas as pd
import fastparquet as fp
from pandas.api.types import CategoricalDtype

file = os.path.expanduser('~/Documents/code/data/fp_cat')

ts = [pd.Timestamp('2021/01/01 08:00:00'),
      pd.Timestamp('2021/01/05 10:00:00'),
      pd.Timestamp('2021/01/05 11:00:00')]
cat = ['hot', 'moderate', 'cold']
catdtype = CategoricalDtype(cat, ordered=True)
val = [30, -10, 10]
cities = ['Lisbonne', 'Paris', 'Paris']
df = pd.DataFrame({'val': val, 'cat': cat, 'city': cities, 'ts': ts})
df['cat'] = df['cat'].astype(catdtype)
```
Before writing, categories are ordered.
```python
df['cat']
Out[229]: 
0         hot
1    moderate
2        cold
Name: cat, dtype: category
Categories (3, object): ['hot' < 'moderate' < 'cold']
```
```python
fp.write(file, df, file_scheme='hive', partition_on=['city'])
df = fp.ParquetFile(file).to_pandas()
```
After reading, they are not ordered any longer (alas, no warning here... I am at a loss on that one...).
```python
df['cat']
Out[231]: 
0         hot
1    moderate
2        cold
Name: cat, dtype: category
Categories (3, object): ['hot', 'moderate', 'cold']
```

**Comment by martindurant** [comment]
Agree that the warning can be dropped, it serves no purpose any more. 

On ordering, that should be very doable, with the pandas section of the dataset metadata. As usual, keep prodding me until I get around to it (unless you would like to try) :)

**Comment by yohplala** [comment]
Hi @martindurant 
As usual, you are amazing! ;) Thanks a lot!
Bests!
