### ISSUE TITLE
ValueError: output array is read-only when converting <M8[ns] to Pandas

### ISSUE THREAD

**Issue by gargantr** [dask/fastparquet#634]
Tried to convert a parquet file written in Spark to Pandas but keep hitting this error. The data type in Spark was DateType and according to the dtypes attribute on ParquetFile object, it's <M8[ns]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-114-ef898162962c> in <module>
----> 1 pf.to_pandas(['addedat_date'])

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/api.py in to_pandas(self, columns, categories, filters, index)
    398                          for (name, v) in views.items()}
    399                 self.read_row_group_file(rg, columns, categories, index,
--> 400                                          assign=parts, partition_meta=self.partition_meta)
    401                 start += rg.num_rows
    402         return df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/api.py in read_row_group_file(self, rg, columns, categories, index, assign, partition_meta)
    239                 fn, rg, columns, categories, self.schema, self.cats,
    240                 open=self.open, selfmade=self.selfmade, index=index,
--> 241                 assign=assign, scheme=self.file_scheme, partition_meta=partition_meta)
    242         if ret:
    243             return df

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/core.py in read_row_group_file(fn, rg, columns, categories, schema_helper, cats, open, selfmade, index, assign, scheme, partition_meta)
    488         return read_row_group(f, rg, columns, categories, schema_helper, cats,
    489                               selfmade=selfmade, index=index, assign=assign,
--> 490                               scheme=scheme, partition_meta=partition_meta)
    491 
    492 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/core.py in read_row_group(file, rg, columns, categories, schema_helper, cats, selfmade, index, assign, scheme, partition_meta)
    540         raise RuntimeError('Going with pre-allocation!')
    541     read_row_group_arrays(file, rg, columns, categories, schema_helper,
--> 542                           cats, selfmade, assign=assign)
    543 
    544     for cat in cats:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/core.py in read_row_group_arrays(file, rg, columns, categories, schema_helper, cats, selfmade, assign)
    514         read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
    515                  selfmade=selfmade, assign=out[name],
--> 516                  catdef=out.get(name+'-catdef', None))
    517 
    518         if _is_map_like(schema_helper, column):

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/core.py in read_col(column, schema_helper, infile, use_cat, selfmade, assign, catdef)
    401         if ph.type == parquet_thrift.PageType.DICTIONARY_PAGE:
    402             dic2 = read_dictionary_page(infile, schema_helper, ph, cmd, utf=se.converted_type == 0)
--> 403             dic2 = convert(dic2, se)
    404             if use_cat and dic is not None and (dic2 != dic).any():
    405                 raise RuntimeError("Attempt to read as categorical a column"

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/converted_types.py in convert(data, se, timestamp96)
    132             ])
    133     elif ctype == parquet_thrift.ConvertedType.DATE:
--> 134         data *= DAYS_TO_MILLIS
    135         return data.view('datetime64[ns]')
    136     elif ctype == parquet_thrift.ConvertedType.TIME_MILLIS:

ValueError: output array is read-only

**Comment by martindurant** [comment]
Can you share a small example file or dataset exhibiting this problem?

On July 14, 2021 3:07:20 PM EDT, gargantr ***@***.***> wrote:
>Tried to convert a parquet file written in Spark to Pandas but keep
>hitting this error. The data type in Spark was DateType and according
>to the dtypes attribute on ParquetFile object, it's <M8[ns]
>
>
>---------------------------------------------------------------------------
>ValueError                                Traceback (most recent call
>last)
><ipython-input-114-ef898162962c> in <module>
>----> 1 pf.to_pandas(['addedat_date'])
>
>/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/api.py
>in to_pandas(self, columns, categories, filters, index)
>    398                          for (name, v) in views.items()}
>399                 self.read_row_group_file(rg, columns, categories,
>index,
>--> 400                                          assign=parts,
>partition_meta=self.partition_meta)
>    401                 start += rg.num_rows
>    402         return df
>
>/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/api.py
>in read_row_group_file(self, rg, columns, categories, index, assign,
>partition_meta)
>239                 fn, rg, columns, categories, self.schema,
>self.cats,
>240                 open=self.open, selfmade=self.selfmade,
>index=index,
>--> 241                 assign=assign, scheme=self.file_scheme,
>partition_meta=partition_meta)
>    242         if ret:
>    243             return df
>
>/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/core.py
>in read_row_group_file(fn, rg, columns, categories, schema_helper,
>cats, open, selfmade, index, assign, scheme, partition_meta)
>488         return read_row_group(f, rg, columns, categories,
>schema_helper, cats,
>489                               selfmade=selfmade, index=index,
>assign=assign,
>--> 490                               scheme=scheme,
>partition_meta=partition_meta)
>    491 
>    492 
>
>/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/core.py
>in read_row_group(file, rg, columns, categories, schema_helper, cats,
>selfmade, index, assign, scheme, partition_meta)
>    540         raise RuntimeError('Going with pre-allocation!')
>541     read_row_group_arrays(file, rg, columns, categories,
>schema_helper,
>--> 542                           cats, selfmade, assign=assign)
>    543 
>    544     for cat in cats:
>
>/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/core.py
>in read_row_group_arrays(file, rg, columns, categories, schema_helper,
>cats, selfmade, assign)
>514         read_col(column, schema_helper, file,
>use_cat=name+'-catdef' in out,
>    515                  selfmade=selfmade, assign=out[name],
>--> 516                  catdef=out.get(name+'-catdef', None))
>    517 
>    518         if _is_map_like(schema_helper, column):
>
>/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/core.py
>in read_col(column, schema_helper, infile, use_cat, selfmade, assign,
>catdef)
>    401         if ph.type == parquet_thrift.PageType.DICTIONARY_PAGE:
>402             dic2 = read_dictionary_page(infile, schema_helper, ph,
>cmd, utf=se.converted_type == 0)
>--> 403             dic2 = convert(dic2, se)
>404             if use_cat and dic is not None and (dic2 != dic).any():
>405                 raise RuntimeError("Attempt to read as categorical
>a column"
>
>/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fastparquet/converted_types.py
>in convert(data, se, timestamp96)
>    132             ])
>    133     elif ctype == parquet_thrift.ConvertedType.DATE:
>--> 134         data *= DAYS_TO_MILLIS
>    135         return data.view('datetime64[ns]')
>    136     elif ctype == parquet_thrift.ConvertedType.TIME_MILLIS:
>
>ValueError: output array is read-only
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/fastparquet/issues/634

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gargantr** [comment]
```
from pyspark import SparkSession 
import pandas as pd
import fastparquet as fp
from pyspark.sql.types import DateType

spark = (
        SparkSession
            .builder
            .getOrCreate()
)
test_df = spark.createDataFrame(
    [
        (1, "2020-1-1"),
        (2, "2020-1-2"),
    ],
    ["id", "Date"] 
)

test_df = test_df.withColumn('Date', f.col("Date").cast(DateType()))

test_df.write.parquet('test')

fp.ParquetFile('test').to_pandas()
```

This will reproduce the ValueError for me

**Comment by martindurant** [comment]
What is your version of pyspark, and what is `f` in the code, above?

**Comment by martindurant** [comment]
OK, I found the pieces. I do not see your issue with the current `main` branch (perhaps releasing this tomorrow). There are a couple of issues, though, when some of the produced files are empty - which is the case with the toy dataset you provided, but unlikely to be the case in reality.
