### ISSUE TITLE
Taking dependency on FastParquet in production

### ISSUE THREAD

**Issue by rcmadhu** [dask/fastparquet#64]
Hello:

This is awesome that you folks have added native read/write between Pandas dataframe and Parquet.  As I read this, I understand that this is still in Alpha and interfaces are expected to change.

What is the plan on package version upgrade if such breaking changes happen? Hopefully, I am hoping that they should not affect existing ones.

Thanks,
MC

**Comment by martindurant** [comment]
Personally, as you can see form #1, I have implemented the majority of the functionality I originally planned for. I do not expect the structure to change much in the medium term.
Having said that, the package is very new, and has not been subjected to too much real-world testing (to my knowledge), so further bugs are certainly expected, and should be fixed as they come along.
