### ISSUE TITLE
any way to write `date` objects?

### ISSUE THREAD

**Issue by ExpandingMan** [dask/fastparquet#641]
Is there any way to use this package to write [date](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#date) objects as referred to in the parquet format spec?

I'm in the somewhat awkward position of trying to work on a parquet reader for another language and I can't get anything to write `date` for me, only full timestamps.

**Comment by martindurant** [comment]
Unfortunately, pandas does not support a "date" time column, it only has datetime64 (i.e., "timestamp"). It *is* possible to create an object column filled with date objects, but this is not something we've ever come across - it would be very inefficient - so we have no code to deal with it.

**Comment by martindurant** [comment]
(and fastparquet only writes data from a pandas dataframe, if that wasn't obvious)
