### ISSUE TITLE
Python 2 compatibility?

### ISSUE THREAD

**Issue by yalwan-scee** [dask/fastparquet#65]
I haven't audited the codebase thouroughly, but I was wondering if this project has the aim to support python 2.7?

I know that this module relies on gzip.compress, which is not present in 2.7, and if this is the only thing, would it be too burdensome to allow the user to forgo the option for gzip compression in order to run on 2.7? I gather gzip compression for parquest files is a fairly rare choice anyway, with performance stats showing that gzipped files can be slower to work with.

The primary motitvation for the request is some issues with using pyodbc on python 3 (encoding, surprise), which would be used as the primary mechanism for reading the data to be written to parquet.

**Comment by mrocklin** [comment]
Keeping this issue or https://github.com/dask/fastparquet/issues/21 open would be good.  

I think that @martindurant , the maintainer of this library is off-grid for the holidays.  Until then I'll put in my thoughts.

Generally I think that yes, it would be great to maintain support for Python 2, however I don't personally plan to spend much time on this.  Instead it would be good to get either development support from the community or financial support from some company before putting in a lot of hours here.  Instead I'd personally rather see dedicated fastparquet devs like @martindurant spend their time establishing functionality and performance for Python 3.  That's just my preference though.

**Comment by yalwan-scee** [comment]
Thanks for the input.

The reason why I closed it because I spent a fair amount of time going through the code (mostly to troubleshoot some issues) and it struck me that it would probably require an extensive rewrite in order to support python 2. If you feel it is valuable I have no issue keeping it open however.

**Comment by mrocklin** [comment]
Can you list the issues that arose?  It would be helpful for others that come later.

See also #66

**Comment by yalwan-scee** [comment]
I was auditing the codebase to understand what was going on with "date" types, because my pandas dataframes contains some of these -- theres a bug in type inference which I annotated, and I am still trying to figure out if I can use this with "date" types or if the data needs to be cast.

**Comment by RadhaSwathi** [comment]
Is it 2.7 compatible yet?

**Comment by martindurant** [comment]
fastparquet no longer supports py2, but you should be able to find an old version which does. No backporting is planned.
