### ISSUE TITLE
Doc looks broken

### ISSUE THREAD

**Issue by aymondebroglie** [dask/fastparquet#651]
**What happened**:
I went to the following page : 
https://fastparquet.readthedocs.io/en/latest/api.html
**What you expected to happen**:
I want to look at the API of the parquet file but I only see a blank page ! 
**Minimal Complete Verifiable Example**:

`
**Environment**:
- Brave browser
- Mac OS X

**Comment by martindurant** [comment]
Oh no! It builds fine locally - let me fix this.

**Comment by martindurant** [comment]
Done
