### ISSUE TITLE
MISC. Comparing fastparquet writing speed to vaex writing speed.

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#656]
Hi there,
I don't mean to troll. I am testing out vaex, and am at a point of how damn writing a parquet file while benefiting fastparquet features (like a certain `append=overwrite`) with data coming from vaex DataFrame?

I enclose here a comparison of writing times, either using parquet writing ensured by vaex (arrow under hood), or by fastparquet.
Comparison is not millimetrically exactly the same, but fastparquet appears to present in this case a slight speedup.
(I have used in the functions the same logic for directory creation and removal to have equal time spent in these tasks when using `%timeit`)

I thought this comparison could be of interest for other people maybe?
Will close the ticket in some days.

```python
import vaex as vx
import pandas as pd
import fastparquet as fp
from os import path as os_path
import os
import shutil

# Writing data.
file_v=os_path.expanduser('~/Documents/code/data/vaex/test_v')
file_f=os_path.expanduser('~/Documents/code/data/vaex/test_f')

# test data
n_val=600000
ts = pd.date_range(start='2021/01/01 08:00', periods=n_val, freq='1T')
df = pd.DataFrame({'val': range(n_val), 'vol': range(n_val, 2*n_val),
                   'timestamp': ts})
vdf = vx.from_pandas(df)

# vaex
def write_v(vdf):
    try:
        shutil.rmtree(file_v)
    except:
        pass
    try:
        vdf.export_many(os_path.join(file_v, 'output_chunk-{i:06}.parquet'),
                        chunk_size=100_000)
    except FileNotFoundError:
        os.mkdir(file_v)
        vdf.export_many(os_path.join(file_v, 'output_chunk-{i:06}.parquet'),
                        chunk_size=100_000)


# fastparquet
def write_f(vdf):
    try:
        shutil.rmtree(file_f)
    except:
        pass
    gen_df = vdf.to_pandas_df(chunk_size=100_000)    
    for _, _, chunk in gen_df:
        try:
            fp.write(file_f, chunk, file_scheme='hive', append=True)
        except FileNotFoundError:
            fp.write(file_f, chunk, file_scheme='hive', append=False)

# test
# 118 ms ± 3.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit write_v(vdf)
# 91.6 ms ± 5.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit write_f(vdf)

# read with fastparquet & compare
df_v = fp.ParquetFile(file_v).to_pandas()
df_f = fp.ParquetFile(file_f).to_pandas()
assert df_v.equals(df)
assert df_f.equals(df)
```
Bests

**Comment by martindurant** [comment]
Note that all the recent work has been for optimising **read** speed, not write. Frankly, I am surprised that it performs fairly well. 
There's probably too much pandas-specific stuff in the codebase to be able to deal with data from any other origin.

**Comment by yohplala** [comment]
Thanks for the feedback Martin.

> There's probably too much pandas-specific stuff in the codebase to be able to deal with data from any other origin.

Yes, and vaex is probably not yet accepted widely enough to justify any development.
But maybe later on, if I see I am sticking with vaex, I can take a closer look and make some proposals. Will see.
These are only preliminary tests.

**Comment by martindurant** [comment]
(did you happen to time reading? Did you try with datapage v2?)

**Comment by yohplala** [comment]
> (did you happen to time reading? Did you try with datapage v2?)

I am sorry Martin, I don't know about Datapage v2. Does it need to be activated in fastparquet by some parameter?

I did not compare reading time, nor do I see how to easily do it.

I don't know if you know about vaex.
Similarly to dask, it will not load the data, only keep in memory where the data come from.
Then you write the dataflow in python with vaex functions,
In the end you record, and it is the recording step (or other command to output in-memory objects like numpy array or pandas DataFrame) that triggers the actual computations (well this is my understanding - they tend to use also the description `out-of core` which I don't know about - the terrific advantage is that it basically does not need RAM).

In the example above, it uses a generator to output pandas Dataframe as chunks that I record then with fastparquet,
but the data source is already in-memory so benefits are hidden.
As I am working with my personal computer, which has 'only' 16GB RAM, such an approach is for me very appealing, although I could check that it presents some limitations in some computations involving rolling windows.

I tested that vaex can read data from parquet files written by fastparquet with 'hive' format, this works OK.
So the dataflow I will try to implement is:
- vaex will read from parquet files ('hive' format) on its own
- then as I need to record the information in parquet files using `append=overwrite` feature, it will output the data as pandas DataFrame in chunks and I will record them using fastparquet (like the example above).

This comparison is very likely inaccurate but I see vaex as being to dask what numba is to cython, a somewhat more user friendly lib / less constraining.
cython and dask are 2 libs I could not succeed to have working during a 30-minute test.
In comparison to cython, I tried numba, and it was just transparent, only a decorator to add.
Vaex gives me the same result so far.

**Comment by martindurant** [comment]
Since I also am on the dask team, it is disappointing that you found it a less than friendly experience. We could very likely solve that, and you already know that fastparquet and dask are very well integrated.

If you did want to speed test reading versus vaex, I suppose you'd have to do some trivial aggregation to force all chunks to be read. Of course, fastparquet does not support any parallelism by itself.

**Comment by yohplala** [comment]
@martindurant  I am sorry, my previous post was inappropriate here and I removed it.
I appreciate your proposal to help Martin. It is possible I am doing mistake, but I wish to assess further the track I am currently visiting.

**Comment by martindurant** [comment]
It is totally fine to make comparisons, but [benchmarks are hard](https://matthewrocklin.com/blog/work/2017/03/09/biased-benchmarks), which may be why I consistently see fastparquet outperform everything else :)
