### ISSUE TITLE
Fastparquet not deduplicating string values for parquets written by fastparquet

### ISSUE THREAD

**Issue by davidhao3300** [dask/fastparquet#657]
**What happened**:

When using fastparquet engine to read a pandas DF written by fastparquet engine, the strings are not deduplicated (see code) - this causes unnecessary memory usage for dataframes with large number of duplicate values.

**What you expected to happen**:

Strings to be deduplicated, like they are in other engines (or even pyarrow reading a fastparquet-written file)

**Minimal Complete Verifiable Example**:

```python
import pandas as pd

df = pd.DataFrame({'a': ["asjfiasjfiasjfiojasiofjaios"]*1000})
df.to_parquet('pyarrow.parquet', engine="pyarrow")
df.to_parquet('fastparquet.parquet', engine="fastparquet")

for write in ["pyarrow", "fastparquet"]:
    for read in ["pyarrow", "fastparquet"]:
        print(f"Write: {write}, Read: {read}")
        ids = pd.read_parquet(f"{write}.parquet", engine=read).a.map(id).values
        print(len(set(ids))) # This should print 1, not 1000
```

**Anything else we need to know?**:

Note that every combination except fastparquet write, fastparquet read deduplicates values

**Environment**:

- Dask version: N/A
- Python version: 3.7.6
- Operating System: Ubunutu 20.04
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
For high-cardinality data like this, you would be best off using categorical encoding
```
df['a'] = df.a.astype("category")
df.to_parquet('fastparquet.parquet', engine="fastparquet")
pd.read_parquet("fastparquet.parquet", engine="fastparquet").a.values
set(pd.read_parquet("fastparquet.parquet", engine="fastparquet").a.map(id).values)
```
shows you only store the string once.

For loading non fastparquet data, I have a small bugfix in https://github.com/dask/fastparquet/pull/660

**Comment by davidhao3300** [comment]
Thanks for the tip, we may do categorical or switch to pyarrow for reading depending on experiments.
What is going on with the fastparquet write, fastparquet read case? Do the other combinations involve some auto-conversion to categorical?

**Comment by martindurant** [comment]
I'm not sure how fastparquet-write/pyarrow-read is working. It is possible to "intern" strings on read, but this is an extra call and not normally done for an arbitrary stream of strings (which is what the data will look like).

For writing, pyarrow always attempts to "dictionary encode" data first, falling back to simple encoding when that fails. This works nicely for the example given, but will be wasted effort in more random data. Which is "right" is a matter of opinion. Fastparquet prefers to make the choice explicit for the user by providing the categorical route.

**Comment by davidhao3300** [comment]
Got it, thank you for the explanation. Closing the issue
