### ISSUE TITLE
ENH: retrieving n preceding rows when applying filters

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#665]
**I. Context**
I am achieving rolling computations on data stored beforehand in parquet format with fastparquet.
Rolling computations are made with a constant-size window.

To avoid loading the full data, I am using `filters` parameter on a column used as index (`DatetimeIndex`).
The time span between 2 timestamps is not necessarily constant.

In this context, the timestamp of the 1st result from this rolling window computation is known, this is my input for filters.
But to achieve this rolling window computation, I need the n preceding rows (n being then the size of my window).

**II. Request**
Can a parameter be added in `to_pandas()`, meaningful when existing parameters ` filters` and `row_filter` are both used and for instance called `prev_rows` (int, 0). Through this parameter the user indicates that the n preceding rows from the 1st valid row (valid according `filters`) have to be retrieved as well.

If there are no row enough, then, the maximum number of rows are retrieved.

**III. Example**
```python
from os import path as os_path
import pandas as pd
import fastparquet as fp

path = os_path.expanduser('~/Documents/code/data/nth_val')
# Test data.
val = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
df = pd.DataFrame({'value' : val})
fp.write(path, df, row_group_offsets=[0,2,5], file_scheme='hive')
pf = fp.ParquetFile(path)

df
Out[8]: 
    value
0     0.1
1     0.2
2     0.3
3     0.4
4     0.5
5     0.6
6     0.7
7     0.8
```
```python
# Reading data with '>=' in 'filters'.
pf.to_pandas(filters=[['value','>=', 0.6]], row_filter=True, prev_rows=4,)
Out[12]: 
    value
0     0.2
1     0.3
2     0.4
3     0.5
4     0.6
5     0.7
6     0.8
```
```python
# Reading data with '>' in 'filters'.
pf.to_pandas(filters=[['value','>', 0.6]], row_filter=True, prev_rows=4)
Out[13]:
   value
0    0.3
1    0.4
2    0.5
3    0.6
4    0.7
5    0.8
```

**Comment by martindurant** [comment]
This seems like it would be rather difficult to achieve in this codebase. I would advise you to load more data than you need into pandas dataframes and do the filtering-with-precedents afterwards.

**Comment by yohplala** [comment]
> This seems like it would be rather difficult to achieve in this codebase. I would advise you to load more data than you need into pandas dataframes and do the filtering-with-precedents afterwards.

I had a look in `api.py`.
It seems like this would impact the 1st read step in `to_pandas`.
```python
        if filters and row_filter:
            # TODO: special case when filter columns are also in output
            cs = self._columns_from_filters(filters)
            df = self.to_pandas(columns=cs, filters=filters, row_filter=False,
                                index=False)
            sel = self._column_filter(df, filters=filters)
            size = sel.sum()
            selected = []
            start = 0
            for rg in rgs[:]:
                selected.append(sel[start:start+rg.num_rows])
                start += rg.num_rows
```
- adding `prev_rows` to 'size'.
- checking there are rows enough in the 1st row group,
   - if yes, adjusting its `start` ?
   - if no, adding previous row group in `selected` with appropriate number of rows.
 
I clearly don't understand fully this part of the code, but it seems to me that this is where are defined the list of row groups and related slices of data to be read.
Then in a 2nd step, definitive df is pre-allocated and slices are 'printed' in pre-allocated df.

**Comment by yohplala** [comment]
Answered by PR #670

**Comment by yohplala** [comment]
Application of this feature available in [this comment](https://github.com/dask/fastparquet/pull/681#issuecomment-925134814).
