### ISSUE TITLE
Filters fail for columns with run length encoded NULLs

### ISSUE THREAD

**Issue by ig248** [dask/fastparquet#674]
**What happened**:
Using filters in `ParquetFile.to_pandas` (or, equivalently, `pd.read_parquet(enging="fastparquet")`) fails with exceptions for some parquet files written with nulls (the default).

**What you expected to happen**:
A subset of rows to be returned according to filter.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import pandas as pd
import fastparquet
print(f"{sys.version=}"). # 3.8.6, Clang 12.0.0
print(f"{pd.__version__=}")  # 1.3.2
print(f"{fastparquet.__version__=}")  # 0.7.1

df = pd.DataFrame(
    {"col": [0, 1, np.nan, np.nan]},
    index=pd.Index(np.arange(4), name="index")
)

fastparquet.write("temp.pq", df, has_nulls=True)

filters = [("index", ">=", 1)]
fastparquet.ParquetFile("temp.pq").to_pandas(row_filter=True, filters=filters)
```

fails with
<details>
<summary>ValueError: The truth value of an array with more than one element is ambiguous.</summary>

```
~/.pyenv/versions/3.8.6/envs/kvasir38/lib/python3.8/site-packages/fastparquet/core.py in read_col(column, schema_helper, infile, use_cat, selfmade, assign, catdef, row_filter)

    492                                         skip_nulls, selfmade=selfmade)
    493         if isinstance(row_filter, np.ndarray):
--> 494             defi = defi[row_filter] if defi else defi
    495             rep = rep[row_filter] if rep else rep
    496             val = val[row_filter]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

</details>

The immediate error is easy to fix by replacing with `if defi is None`/`if rep is None`, however the arrays are still different length and the error becomes

<details>
<summary>IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 4</summary>

```
.../fastparquet/core.py in read_col(column, schema_helper, infile, use_cat, selfmade, assign, catdef, row_filter)

    494             defi = defi[row_filter] if defi is not None else defi
    495             rep = rep[row_filter] if rep is not None else rep
--> 496             val = val[row_filter]
    497         if rep is not None and assign.dtype.kind != 'O':  # pragma: no cover
    498             # this should never get called

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 4
```

</details>

**Anything else we need to know?**:

**Environment**:

- Dask version: N/A
- Python version: 3.8.6
- Operating System: macOS Big Sur 11.4
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Confirmed
