### ISSUE TITLE
Error when writing a Pandas dataframe with a column of empty bytes

### ISSUE THREAD

**Issue by SKolodynski** [dask/fastparquet#677]
**What happened**:
The fastparquet `write` function signals an error when writing a Pandas dataframe that has a column in which each cell is a empty `bytes` string. The error is `Error converting column "col" to bytes using encoding UTF8. Original error: bad argument type for built-in operation`. 

**What you expected to happen**:
I expected the file to be written without an error.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import fastparquet as fp

df = pd.DataFrame()
df['col'] = pd.Series([b'',b''])
fp.write('testBytes.parq',df)
```

**Anything else we need to know?**:
I do not have dask installed, only fastparquet. The error does not happen when at least one of the elements of the bytes column is nonempty, e.g. when in the example above one has 
```python
df['col'] = pd.Series([b'abc',b''])
```
 instead of 
```python
df['col'] = pd.Series([b'',b''])
```
**Environment**:
- fastparquet version:  0.7.1
- Python version: 3.8.1
- Operating System: Windows 10 Pro
- Install method (conda, pip, source): `pip install fastparquet --user`

**Comment by martindurant** [comment]
That's a new one! Do you also get this issue when one of the items is `None`. I can put this on my list, but I can't promise when I'll get to it. If you have the time, you would be welcome to try to investigate the problem yourself.

**Comment by martindurant** [comment]
Please test with #684
