### ISSUE TITLE
why do we omit lz4_raw here

### ISSUE THREAD

**Issue by framlog** [dask/fastparquet#679]
We don't add `LZ4_RAW` in `rev_map` currently, but it seems that compression type could work well if it's added to that map.

See: https://github.com/dask/fastparquet/blob/cad6698ff3df6ff26be2c350cd23d29a4f481790/fastparquet/compression.py#L70

**Comment by martindurant** [comment]
Good point, please feel free to add it. In practice, LZ4 is identical to LZ4_RAW, but this was ambiguous in the parquet spec, hence the (relatively) new name.
