### ISSUE TITLE
TypeError in writing a column of nullables/strings

### ISSUE THREAD

**Issue by orenmazor** [dask/fastparquet#682]
**What happened**:

I recently updated my fastparquet to 0.7.x from 0.5.x and a few changes came along. I noticed a weird issue is happening in my ETL occasionally, and eventually narrowed it down to cases where my entire single column of strings is nones. 

When this happened before, I simply wrote out a column of nones. But now this is raising.

There's a few things I can do to fix my source data, but I'm wondering if I'm just holding it wrong?

**What you expected to happen**:

success. happiness. good snacks. sleeping in.

**Minimal Complete Verifiable Example**:

```python
Python 3.9.7 (default, Sep  3 2021, 02:02:37) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> df = pandas.DataFrame()
>>> df['foo'] = [None, None, None]
>>> df = df.astype({'foo': 'string'})
>>> df.foo
0    <NA>
1    <NA>
2    <NA>
Name: foo, dtype: string
>>> df.to_parquet("foo")
Traceback (most recent call last):
  [ TRUNCATED ] 
  File "/venvs/foo/lib/python3.9/site-packages/fastparquet/writer.py", line 795, in write_simple
    foot_size = write_thrift(f, fmd)
  File "/venvs/foo/lib/python3.9/site-packages/fastparquet/thrift_structures.py", line 52, in write_thrift
    thrift.write(pout)
  File "/venvs/foo/lib/python3.9/site-packages/fastparquet/parquet_thrift/parquet/ttypes.py", line 4530, in write
    oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
TypeError: expected bytes, NAType found
```

**Anything else we need to know?**:

I think this might be a variation of #677 

**Environment**:

debian bullseye docker. python:3.9.7-slim-bullseye

- Dask version: NA
- Python version: 3.9.7
- Operating System: Docker Debian Bullseye
- Install method (conda, pip, source): poetry/pip

**Comment by orenmazor** [comment]
additionally: 

```
> df = df.astype({'foo': 'float'})
>>> df.to_parquet("foo")
>>> df
   foo
0  NaN
1  NaN
2  NaN
>>> df = df.astype({'foo': 'string'})
>>> df
    foo
0  <NA>
1  <NA>
2  <NA>
>>> df.to_parquet("foo")
TypeError: expected bytes, NAType found
```

so its just the nullable string?

**Comment by orenmazor** [comment]
hammered out a temporary workaround, as my other alternative seems to be to downgrade fastparquet:

```
        string_columns = dataframe.select_dtypes(include=["string"]).columns
        if len(string_columns) > 0:
            for col in string_columns:
                # if the whole column is empty, lets recast it
                if dataframe[col].isna().all():
                    dataframe[col] = dataframe[col].astype("object")
```

I could also do a `fillna()` call here, but I want to write out nulls so that my parquet consuming code (athena) still gets a null

**Comment by martindurant** [comment]
have you tried 
```
df.to_parquet(..., object_encoding="utf8")
```
?

fastparquet tries to guess the types of object-like columns, and it may that is fails for your case since the values are NULL (even though it's definitely a string-type column).

**Comment by orenmazor** [comment]
@martindurant thanks for commenting! thats actually how my pipeline outputs things! full snippet:

```
        return dataframe.to_parquet(
            path=filename,
            compression="SNAPPY",
            index=print_index,
            times="int96",
            object_encoding="utf8",
        )
```

**Comment by martindurant** [comment]
OK, thanks - so we have a concrete issue to fix. I'm not sure when I'll have a chance to look into it.

**Comment by ilCatania** [comment]
I also have this issue.

**Comment by martindurant** [comment]
Part of the problem seems to be that pandas have renames the ~string~ repr form of pd.StringDType from "string" to "string[python]".

**Comment by martindurant** [comment]
Please test with #684

**Comment by orenmazor** [comment]
awesome. thanks Martin! haven't had the chance to check this yet but this looks good!
