### ISSUE TITLE
Raise exception when hitting max number of row groups?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#683]
Hi @martindurant,
I remember a ticket in which someone was reporting an error, and you highlighted that too many row groups were written, and then the ticket has been closed.
I don't succeed to find it again, and I did not react at this time.
I open this ticket to propose:
- to add a check on row group number when writing so as to raised an exception informing it will not be possible to write if the limit is hit (the error encountered by the user was probably not clear on this)
- to add a not in Usage notes maybe in [__Partitions and row groups__](https://fastparquet.readthedocs.io/en/latest/details.html#partitions-and-row-groups) to inform about the max number of row groups that can be written?

Please, what is the limit in number of row group that can be written? (you indicated it in this ticket I can't find anylonger)
thanks for your help,
Have a good day,
Bests,

**Comment by martindurant** [comment]
The the thrift metadata, the size of the row_groups list is stored as a var_int, so can have a large number (~int64) of entries. However, the total size of the file metadata is limited to be stored in a 4-byte value. There are probably other limits that would be hit first, I'm not sure what.

**Comment by martindurant** [comment]
...but I generally agree that there should be a note about metadata size and when one should expect it to matter,
