### ISSUE TITLE
What is the purpose of 'ParquetFile.sep' attribute?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#687]
Hi,
Currently investigating fastparquet source code, I could notice the undocumented `sep` attribute in `ParquetFile` class.

It appears in `__init__` function signature, [line 96](https://github.com/dask/fastparquet/blob/93e7e2cdaaf27e01437e7b78dd760ac2a1f123c7/fastparquet/api.py#L96).
```python
    def __init__(self, fn, verify=False, open_with=default_open,
                 root=False, sep=None, fs=None, pandas_nulls=True):
```

It is recorded [line 161](https://github.com/dask/fastparquet/blob/93e7e2cdaaf27e01437e7b78dd760ac2a1f123c7/fastparquet/api.py#L161)
`self.sep = sep`

It can be displayed through `__getstate__` [line 162](https://github.com/dask/fastparquet/blob/93e7e2cdaaf27e01437e7b78dd760ac2a1f123c7/fastparquet/api.py#L662).
```python
    def __getstate__(self):
        return {"fn": self.fn, "open": self.open, "sep": self.sep, "fmd": self.fmd,
                "pandas_nulls": self.pandas_nulls}
```

But then i don't see it being used elsewhere.
Please, what is its purpose?

Thanks for your feedback,
Have a good day,
Bests

**Comment by martindurant** [comment]
Probably for creating path names from the relative paths contained in the metadata. However, even Windows works with a separator of "/", and fsspec filesystems all use that, so it probably went defunct. The signature predates fsspec (and you can now explicitly pass a filesystem object).

**Comment by yohplala** [comment]
Ok, I propose to solve this ticket when [corresponding dask ticket](https://github.com/dask/dask/issues/8201) is solved.

**Comment by martindurant** [comment]
The linked issue is closed, but this thread is now very old.

**Comment by yohplala** [comment]
> The linked issue is closed, but this thread is now very old.

Yes, sorry, there has been no follow-up so far.
I propose to close with PR #799: all dask tests are now running.

**Comment by martindurant** [comment]
Actually, let's just close this. We probably should leave the unused parameter in place for at least another release cycle.
