### ISSUE TITLE
Naive question regarding code

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#690]
Hi,
I am sorry for the probably very naïve question.
What means / what makes the `if "/"` at the right most location of [line 730](https://github.com/dask/fastparquet/blob/88cc7653a428c07e732b75621d619b8b78ed8b6f/fastparquet/api.py#L730) in `api.py`?

```python
    paths = set(path.rsplit("/", 1)[0] if "/" in path else "" for path in paths if "/")
```
Thanks in advance for the feedback.
Bests,

**Comment by martindurant** [comment]
It appears to do... nothing. Perhaps look back int he git history to see how it came to be there.

**Comment by yohplala** [comment]
> It appears to do... nothing. Perhaps look back int he git history to see how it came to be there.

It has been added in this commit, but nothing clear to me as what it changes.
https://github.com/dask/fastparquet/commit/fdef884500e249b6f15ea1d94c786cdf619ab0e1#diff-7b92d23f427a36a5f1c24bd40d75b13516c1eb406f148fbd89576db3f5505444

**Comment by yohplala** [comment]
I have removed it in my last commits for PR #689 . (on my machine, there was no error in test case while removing it, I will see if it leads to error in my PR - I extracted this part in a separate function to re-use it, hence my question about this code)

**Comment by martindurant** [comment]
OK, so we can close this issue, thanks for catching.
