### ISSUE TITLE
New file 'test_issue_604.parquet' created each time when running pytest in fastparquet folder.

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#692]
When running
`python -m pytest` in fastparquet folder (pulled from source with `git`), a file is systematically created (from a test as I understand) `test_issue_604.parquet`

Could it be possible to create it in a `tempdir` as provided by `pytest`?

(when doing a `git add .` this file gets then added)

**Comment by martindurant** [comment]
Should be in a tempdir, yes, like all the rest of the tests.

**Comment by martindurant** [comment]
Would you like to find the test that's doing this and fix it to use a temporary location?

**Comment by yohplala** [comment]
> Would you like to find the test that's doing this and fix it to use a temporary location?

Sorry, I was on something else.
Sure, please find resolution in #694.
