### ISSUE TITLE
Provide an API to change the default row groups N-row value

### ISSUE THREAD

**Issue by MacHu-GWU** [dask/fastparquet#702]
Hi fastparquet team, `iter_row_groups` is awesome, I read from the doc that the default n_rows is 50million rows.
Is there a way I can change the value and yield the desired number of row per pandas.Dataframe?

I do searched the issue and document, but found no answer. Thank you

Thank you

**Comment by MacHu-GWU** [comment]
... I just realize that the row_group_size is handled by parquet writer, not reader ....

Ignore this issue please...

**Comment by martindurant** [comment]
Exactly: on read, the row group size is fixed by the files on disk.
