### ISSUE TITLE
Project management / general discussion: app for managing continuous integration?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#716]
Hi, sorry for this very general question.
Please, which Github app is used by fastparquet project to run test cases when a PR is made?
Sorry for the question quite far from fastparquet code internals.
Thanks for your answer, bests,

**Comment by martindurant** [comment]
See the .github/workflows directory. The [main](https://github.com/dask/fastparquet/blob/main/.github/workflows/main.yaml) workflow runs the CI against conda packages, the [test_wheel](https://github.com/dask/fastparquet/blob/main/.github/workflows/test_wheel.yaml) one runs against a freshly made wheel of this repo, and the `wheels` workflow build wheel for upload whenever a tag is made.

**Comment by yohplala** [comment]
thanks a lot @martindurant !
