### ISSUE TITLE
Passing a list of relative paths to ParquetFile does not work in fastparquet >= 0.7.1

### ISSUE THREAD

**Issue by latvanii** [dask/fastparquet#717]
**What happened**:
Passing a list of relative paths to ParquetFile stopped working in fastparquet 0.7.1.

**What you expected to happen**:
Reading the data to work correctly with a list of relative paths

**Minimal Complete Verifiable Example**:

```python
paths = ['./metaflow.s3.ii48agnk/60e98b02f6f5a52825cf999e863342c7dae9ef1b-part_0000_snappy_parquet', './metaflow.s3.ii48agnk/fb015cacf085aa4befc081cd4d8660665c4afa4e-part_0001_snappy_parquet', './metaflow.s3.ii48agnk/9ed1c451087e7ab5506908488fb7cb1c4a5c2191-part_0002_snappy_parquet']
data = ParquetFile(paths)
```
Results in:
```
KeyError: './metaflow.s3.ii48agnk/fb015cacf085aa4befc081cd4d8660665c4afa4e-part_0001_snappy_parquet''
```
in L174 in util.py https://github.com/dask/fastparquet/blob/effea701553ab709ebb57d98e85867f0b266acda/fastparquet/util.py#L174

It looks like the paths in `pieces` are misformed:
```
>>>pieces.keys()
dict_keys(['/Users/my-home/project-root/./metaflow.s3.ii48agnk/60e98b02f6f5a52825cf999e863342c7dae9ef1b-part_0000_snappy_parquet', '/Users/my-home/project-root/./metaflow.s3.ii48agnk/fb015cacf085aa4befc081cd4d8660665c4afa4e-part_0001_snappy_parquet', '/Users/my-home/project-root/./metaflow.s3.ii48agnk/9ed1c451087e7ab5506908488fb7cb1c4a5c2191-part_0002_snappy_parquet',])
```

**Anything else we need to know?**:

**Environment**:
- fastparquet: 0.7.1 and 0.7.2
- Python version: 3.8.9
- Operating System: Mac OS 11.6.1
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
This appears to be a fault in fsspec's `find`/`walk` for local filesystem, ultimately in `fsspec.implementations.local.make_path_posix`. That implementation works hard to reconcile many styles of path without resorting to `os.path.abspath`, which is rather slow.

However, the obvious workaround is *not* to use "./" in your path
