### ISSUE TITLE
Perf. improvement in 'write()': Numpy slices are memoryless while pandas ones are not.

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#718]
Hi,
Just realized that this evening:
```python
import sys
import pandas as pd
import numpy as np

# Numpy
#ar = np.arange(200_000_000)
ar = np.arange(1_000_000)

sys.getsizeof(ar)
#Out[5]: 8000104
sys.getsizeof(ar[:])
#Out[6]: 104

# Pandas
df = pd.DataFrame({'a':[ar]})

sys.getsizeof(df)
#Out[8]: 8000256
sys.getsizeof(df[:])
#Out[9]: 8000256
```
We are doing such slices when we are splitting new data in row groups for writing in `write()`.
After reading some SO answers, it would seems that numpy 'simple' slices are direct pointers to area in the original table.
I could not find information about pandas case, but it seems a 'deep copy' is made, meaning, it creates a new `DataFrame`.
This takes some more memory, and some time for filling new memory slots I guess (well, the time to make a copy).

A perf. improvement would be to switch current pandas slices to numpy slices.

I will not manage this in current PR ` write_row_groups()` (its scope is already big enough I think), but can have a look in a next PR.
Bests,

**Comment by martindurant** [comment]
I guess the thing to do is run a time/memory line profiler to see if slicing is costly. Indeed I would indeed have thought that slicing is a no-copy operation.

**Comment by martindurant** [comment]
(but maybe don't trust what sys.getsizeof tells you!)

**Comment by yohplala** [comment]
Yes, sure! I will have a deeper look somewhat later.

**Comment by yohplala** [comment]
```python
%load_ext memory_profiler

n_chunks = 10
chunk_size = int(len(df)/n_chunks)
def split(ar, n_chunks, chunk_size):
    for i in range(n_chunks):
        br = ar[i*chunk_size:(i+1)*chunk_size]

%timeit split(df,n_chunks, chunk_size)
# 164 µs ± 525 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit split(ar,n_chunks, chunk_size)
# 2.31 µs ± 32.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

%memit split(df,n_chunks, chunk_size)
# peak memory: 156.95 MiB, increment: 0.24 MiB

%memit split(ar,n_chunks, chunk_size)
# peak memory: 156.96 MiB, increment: 0.01 MiB
```

That is a surprise. There does be a difference in execution time where numpy slices are faster. But in memory both are equal.
Not sure where to go from here.
In execution time, I am not so sure there is so much to save, as in 'real world', if the dataframe fit into RAM, depending of the chunking strategy, you will have between 2 to 20 at most row groups? (meaning, we are not doing huge loops here)

**Comment by martindurant** [comment]
Pandas definitely does some extra checking and extra work (making index instances and block managers) compared to numpy, but if the memory is not copied, then it shouldn't be significant. In many cases, perhaps the most common, a single dataframe becomes a single row-group.

**Comment by yohplala** [comment]
I am aligned with this.
Closing the ticket.
