### ISSUE TITLE
How to retrieve statistics from a row group object?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#719]
Hi,
I am sorry, I asked this question among others in a ticket, then closed the ticket as part of the questions I raised were answered. But I am coming back to this one as I am still interested to know if it is feasible to access the stats of a row group from its own metadata?

So basically, we have access to following row group metadata thanks to the `pf.row_groups` list.
I can see that statistics are kept by column in a row group, doing so on a test file:
```python
pf.row_groups[0].columns[0].meta_data.statistics
Out[18]: 
<class 'fastparquet.parquet_thrift.parquet.ttypes.Statistics'>
distinct_count: None
max: b'\x00(t\x15\xd5\xf5\xe5\x15'
max_value: None
min: b'\x00\xe8\x02\xb4H\xef\xe5\x15'
min_value: None
null_count: 0
```
Trying to access max:
```python
pf.row_groups[0].columns[0].meta_data.statistics.max
Out[20]: b'\x00(t\x15\xd5\xf5\xe5\x15'
```
How the value should be decoded to be able to process it?
Thanks for your help,
Bests

**Comment by yohplala** [comment]
Well, I thought, this would do the trick, from looking at the source in `api.py`, but it does not.

```python
import os
import pandas as pd

from fastparquet import ParquetFile, write, converted_types

df1 = pd.DataFrame({'humidity': [0.3, 0.8, 0.9, 0.7, 0.6],
                    'pressure': [1e5, 1.1e5, 0.95e5, 0.98e5, 1e5],
                    'city': ['Paris', 'Paris', 'Milan', 'Milan', 'Marseille'],
                    'country': ['France', 'France', 'Italy', 'Italy', 'France']},
                    index = [pd.Timestamp('2020/01/02 01:59:00'),
                             pd.Timestamp('2020/01/02 03:59:00'),
                             pd.Timestamp('2020/01/02 02:59:00'),
                             pd.Timestamp('2020/01/02 02:57:00'),
                             pd.Timestamp('2020/01/02 02:58:00')])

path = os.path.expanduser('~/Documents/code/data/')
file = path + 'weather_data'
write(file, df1, file_scheme='hive', row_group_offsets=2)
pf = ParquetFile(file)

col_metadata = pf.row_groups[0].columns[1].meta_data
vmax = col_metadata.statistics.max
name = ".".join(col_metadata.path_in_schema)
se = pf.schema.schema_element(name)
converted_types.convert(vmax, se, False)

**Comment by martindurant** [comment]
Those are PLAIN encoded bytes, so the meaning depends on the data type of the corresponding schema element. You can decode them manually with `fastparquet.encoding.read_plain(..., stat=True)`, but you probably want to run
```python
chunk = pf.row_groups[0].columns[0]
fastparquet.api.statistics(chunk)
```

Note that the `.statistics` attribute of a `ParquetFile` will walk all the columns of all of the row-groups, and return the values for those that can be sorted.

**Comment by yohplala** [comment]
> you probably want to run
> 
> ```python
> chunk = pf.row_groups[0].columns[0]
> fastparquet.api.statistics(chunk)
> ```

Awesome! Thanks!
