### ISSUE TITLE
Writing massive files

### ISSUE THREAD

**Issue by aloneguid** [dask/fastparquet#72]
I'm using fastparquet and it's great so far. My only problem is I need to write massive files to disk. Due to how fastparquet.write method works I need to prepare the whole dataframe in memory which doesn't fit even in the really expensive Azure VM. For me writing to separate files is not an option (customer requirements). Is there something you can recommend when it can be written in chunks i.e. one Series at a time? Much appreciated.

**Comment by martindurant** [comment]
If you need to write one massive data collection, as opposed to a single massive file, then the function `writer.merge` will help you: you create the individual files from chunks of data-frame (which must have the same columns and types) and then create the single data collection at the end.

If you must write to a single file, you could try `write` with `append=True` repeatedly for each chunk. This is probably not as efficient as it could be, but maybe is good enough for you. Appending does not, however, work for backend file-systems such as s3fs, which don't allow update (`'rb+'`) mode.

**Comment by aloneguid** [comment]
Thanks @martindurant  I ended up using the `append=True` option, works brilliant.

**Comment by QuantScientist** [comment]
Can you please share your a sample? I have the same scenario, 
Thanks.
