### ISSUE TITLE
Different `file_path` values for columns of a same row group? (`find_max_part` implementation)

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#722]
Hi,
[The 1st line in `find_max_part`](https://github.com/dask/fastparquet/blob/effea701553ab709ebb57d98e85867f0b266acda/fastparquet/writer.py#L1079) reads:
```python
    paths = [c.file_path or "" for rg in row_groups for c in rg.columns]
```
Isn't it overkill?
My understanding is that we cannot have columns in different files, meaning the same path will be present for all the columns of a row group.
Wouldn't the following be enough?
```python
    paths = [rg.columns[0].file_path or "" for rg in row_groups]
```
Thanks in advance for your feedback,
Bests,

**Comment by martindurant** [comment]
In theory, each column could be in its own file, but I've never in practice seen any file containing less than a whole row-group together. Agreed that the simplification here is worthwhile - and there may be other instances of the same. 

I don't think we can go as far as to omit the path on non-first columns on write, that would likely confuse readers even when they are reading all the columns.

**Comment by yohplala** [comment]
> In theory, each column could be in its own file, but I've never in practice seen any file containing less than a whole row-group together. Agreed that the simplification here is worthwhile - and there may be other instances of the same.

Yes, even more so that the remaining of the code assumes a pattern in file name that probably only fastparquet is using.
If this pattern is not followed, `find_max_part` returns 0.
This means that the logic of this 1st line of code has to follow `fastparquet` writing logic.

> I don't think we can go as far as to omit the path on non-first columns on write, that would likely confuse readers even when they are reading all the columns.

Understood.
Thanks @martindurant for your quick feedback!

**Comment by martindurant** [comment]
> Yes, even more so that the remaining of the code assumes a pattern in file name that probably only fastparquet is using.
If this pattern is not followed, find_max_part returns 0.

That's OK though, because we won't accidentally overwrite them!

**Comment by yohplala** [comment]
Taken into account in #712
