### ISSUE TITLE
Unable to run a dask test case: unexpected keyword argument 'name_function'

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#725]
**What happened**:
Trying to run a dask test case, in my environment, I get an error message while the same dask test case runs without this eror, (but with another one occuring after).

**Minimal Complete Verifiable Example**:
From dask tests: [test_custom_filename_with_partition](https://github.com/dask/dask/blob/a86ff77a08809d7b5ab3712b468acea29b16f443/dask/dataframe/io/tests/test_parquet.py#L3886)
```python
import pandas as pd
import dask.dataframe as dd

tmpdir = '/home/yoh/Documents/code/data/fastparquet/'
fn = str(tmpdir)
pdf = pd.DataFrame(
        {
            "first_name": ["frank", "li", "marcela", "luis"],
            "country": ["canada", "china", "venezuela", "venezuela"],
        },
    )
df = dd.from_pandas(pdf, npartitions=4)
df.to_parquet(
        fn,
        partition_on=["country"],
        name_function=lambda x: f"{x}-cool.parquet",
        write_index=False,
    )
```
Error message:
```python
Traceback (most recent call last):

  File "/tmp/ipykernel_385501/3135864392.py", line 13, in <module>
    df.to_parquet(

  File "/home/yoh/anaconda3/lib/python3.9/site-packages/dask/dataframe/core.py", line 4560, in to_parquet
    return to_parquet(self, path, *args, **kwargs)

  File "/home/yoh/anaconda3/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 652, in to_parquet
    meta, schema, i_offset = engine.initialize_write(

  File "/home/yoh/anaconda3/lib/python3.9/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 1107, in initialize_write
    fmd = fastparquet.writer.make_metadata(

TypeError: make_metadata() got an unexpected keyword argument 'name_function'
```
And it is completely accurate that [`make_metadata()`](https://github.com/dask/fastparquet/blob/9bd2a57a627f08629e4b97d22df4f4ccc4c3e0ce/fastparquet/writer.py#L735) in fastparquet does not accept `name_function`.
```python
def make_metadata(data, has_nulls=True, ignore_columns=None, fixed_text=None,
                  object_encoding=None, times='int64', index_cols=None, partition_cols=None):
```
Any idea what could be wrong in my environment?

**Environment**:

- fastparquet version: from PR #712 
- Python version: 3.8
- Operating System: Ubuntu 20.04

**Comment by martindurant** [comment]
Please make sure you have a release of dask later than https://github.com/dask/dask/pull/7682 . I don't think that dask is pushing the argument through to make_metadata, but that it is not being picked up with the earlier write function, and so gets swallowed in the general **kwargs.

**Comment by yohplala** [comment]
> Please make sure you have a release of dask later than [dask/dask#7682](https://github.com/dask/dask/pull/7682) . I don't think that dask is pushing the argument through to make_metadata, but that it is not being picked up with the earlier write function, and so gets swallowed in the general **kwargs.

Thanks, I confirm it works with dask installed straight from github!
Closing.
