### ISSUE TITLE
Cannot write with append=True to s3

### ISSUE THREAD

**Issue by erinov1** [dask/fastparquet#743]
I'm unable to append to an existing partitioned parquet dataset using s3 protocol (in this case my data is stored in Wasabi Cloud rather than AWS, but the protocol should be identical; I don't have an AWS account so it's not clear to me if this is where the issue lies). The error is
```
ValueError: Opening directories without a _metadata requiresa filesystem compatible with fsspec
```
(Contrary to the error, a _metadata file does exist.)

#### Reproduction:

 I have two pandas DataFrames, `df_1` and `df_2` with identical schema. The following works fine:
```
df_1.to_parquet('s3://my_bucket/my_dir/my_dataset', 
    engine='fastparquet', 
    index=False,
    partition_on=['id', 'year'],
    compression='snappy',
    storage_options=my_config,
)
```
Immediately after, I try appending the second DataFrame:
```
df_2.to_parquet('s3://my_bucket/my_dir/my_dataset', 
    engine='fastparquet', 
    index=False,
    partition_on=['id', 'year'],
    compression='snappy',
    storage_options=my_config,
    append=True # <------ Appending this time!
)
```
Tail of the traceback:
```
File ~/Library/Caches/pypoetry/virtualenvs/project-GfuZs_x0-py3.8/lib/python3.8/site-packages/fastparquet/api.py:132, in ParquetFile.__init__(self, fn, verify, open_with, root, sep, fs, pandas_nulls)
    130     fn = fs._strip_protocol(fn)
    131 if not isinstance(fs, fsspec.AbstractFileSystem):
--> 132     raise ValueError("Opening directories without a _metadata requires"
    133                      "a filesystem compatible with fsspec")
    134 if fs.isfile(fn):
    135     self.fn = join_path(fn)

ValueError: Opening directories without a _metadata requiresa filesystem compatible with fsspec
```
Environment:
`fastparquet==0.8.0`

**Comment by erinov1** [comment]
I tested this out on an actual AWS bucket and can confirm the same error.

**Comment by yohplala** [comment]
Hi @erinov1 
Does it work in local?
A 'simple workaround' maybe, is to specify the additional parameter `file_scheme='hive'` : this will create a `_metadata` file along with the parquet file, and maybe this is enough to get rid of the error message.
BUT
It should work without this workaround. Appending is also possible with `file_scheme=simple` (default config)

Having your feedback about whether it works in local or not (not AWS) would be interesting to know.

Also, specifying a fsspec filesystem, as the message requests, should solve the trouble.
BUT
I can see that `write` function does not accept such a parameter, you have to specify `open_with` parameter.

**Comment by erinov1** [comment]
It seems like there are some bugs with fastparquet, pandas, and dask. I am using the following versions:

```
dask==2021.12.0
fastparquet==0.8.0
pandas==1.3.5
```

----
#### `fastparquet` issue:
The issue appending to s3 occurs when using `fastparquet.write`. In summary:
1. I can use `append=True` just fine when writing my dataset to a local filesystem. It is only on s3 that I am experiencing issues.
2.  Explicitly setting `file_scheme='hive'` does not help with the s3 issue.

-----
#### `pandas` issue:

When writing to s3 using `engine=fastparquet` with `pd.to_parquet` (with `append=False` of course) it actually creates an additional local copy of my dataset directory structure (!!). For example, if I try to write to 
```
s3://my_bucket/my_dir/my_dataset
``` 
it will write to both the desired s3 bucket *and* create the directory structure 
```
$(pwd)/s3:/my_bucket/my_dir/my_dataset
``` 
However, no actual data is copied to the local directories. This occurs regardless of whether or not I pass `open_with=fs.open` to `pd.to_parquet`.

----
#### `dask` issue:
I also tried using `dask.dataframe.to_parquet` to append to the dataset. Oddly, this seems to work in the following case:
1. First I write the dataset to s3 directly using `fastparquet.write` using `file_scheme=hive`.
2. Next, I append the second dataset by calling `dask.dataframe.to_parquet` with `append=True`.

However, if in the first step I create the dataset in s3 using dask instead of fastparquet and then attempt to append using dask in the second step, there is mismatch involving the partitioning columns:

```
File ~/Library/Caches/pypoetry/virtualenvs/project-GfuZs_x0-py3.8/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py:1089, in FastParquetEngine.initialize_write(cls, df, fs, path, append, partition_on, ignore_divisions, division_info, schema, object_encoding, index_cols, **kwargs)
   1083     raise ValueError(
   1084         "Requested file scheme is hive, but existing file scheme is not."
   1085     )
   1086 elif (set(pf.columns) != set(df.columns) - set(partition_on)) or (
   1087     set(partition_on) != set(pf.cats)
   1088 ):
-> 1089     raise ValueError(
   1090         "Appended columns not the same.\n"
   1091         "Previous: {} | New: {}".format(pf.columns, list(df.columns))
   1092     )
   1093 elif (pd.Series(pf.dtypes).loc[pf.columns] != df[pf.columns].dtypes).any():
   1094     raise ValueError(
   1095         "Appended dtypes differ.\n{}".format(
   1096             set(pf.dtypes.items()) ^ set(df.dtypes.iteritems())
   1097         )
   1098     )

ValueError: Appended columns not the same.
Previous: ['ts', 'value'] | New: ['id', 'ts', 'value', 'year']
```
Here `['id', 'year']` are the columns I'm attempting to partition on.

It's not clear to me to what extent the pandas and dask issues are independent of fastparquet itself — any advice would be appreciated!

**Comment by yohplala** [comment]
Hi @martindurant ,
I think we need your insight here.

Looking at [the code](https://github.com/dask/fastparquet/blob/d7a0e57abe759828e20f2aee5979600ea2bc3ad9/fastparquet/api.py#L131), it seems to me the error message is inadequate:

```python
# api.py, L131
            if not isinstance(fs, fsspec.AbstractFileSystem):
                raise ValueError("Opening directories without a _metadata requires"
                                 "a filesystem compatible with fsspec")
```
How can we guess from the fact that `fs` is not an instance of `fsspec.AbstractFileSystem` that there is no `_metadata` file? (and @erinov1 indicates there is one)

Also, has there been any change in `fsspec` lately that may raise such an error? (I am not a used of remote file storage myself, but I can guess this use case is common?)

**Comment by martindurant** [comment]
This is a genuine issue. Actually, there are two issues:
- pandas seems to have reorganised itself for some reason, such that using df.to_pandas no longer passes an open_with argument which is a method of the filesystem, but creates a lambda function on the fly. It is correct that we don't have an AbstractFileSystem, but maybe we can track it down
- since almost all calls are assumed to be passing fsspec things, we seem not to have handled the case for open_with being something else and not directly given the filename of the _metadata (or a list of files, which also seems to work).

I can fix both these things.

**Comment by erinov1** [comment]
Thanks @martindurant

I'm guessing the dask issue I mentioned above unrelated to this? Even with a local filesystem I am unable to use dask to append to a partitioned dataset that was originally written with dask (there is a mismatch involving the columns used for partitioning). I can an open an issue there.

**Comment by martindurant** [comment]
Yes, please open that issue.
