### ISSUE TITLE
fastparquet does not support StringDtype column with NA values

### ISSUE THREAD

**Issue by EdGaere** [dask/fastparquet#747]
**What happened**:
Segmentation fault: 11

**What you expected to happen**:
DataFrame to be written to parquet file.

**Minimal Complete Verifiable Example**:

```
import pandas as pd

# create basic dataframe with some strings 
# Pandas will default to dtype='object'
df = pd.DataFrame( {"A" : ["2", "3", "4"]} )

# cast to Pandas nullable StringDtype
df["A"] = df["A"].astype(pd.StringDtype())

# set *all* values to NA
df["A"].iloc[0] = pd.NA
df["A"].iloc[1] = pd.NA
df["A"].iloc[2] = pd.NA

```

**Anything else we need to know?**:
The error is caused by the following combination:
1. Explicitly casting to pd.StringDtype
2. All values in the column are pd.NA; if any single value is not NA, there is no error

**Environment**:

- Dask version: None
- fastparquet==0.8.0
- Pandas version: pandas==1.3.5
- Python version: 3.8.3
- Operating System: macOS (Catalina)
- Install method (conda, pip, source): pip

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by martindurant** [comment]
Interestingly, it's the column statistics that cause the issue. The following works:
```
df.to_parquet("out", engine="fastparquet", stats=False)
```
Given that the max/min is undefined anyway, you loose nothing like this; but obviously the crash should not happen.

**Comment by EdGaere** [comment]
Thanks Marin! :-)
