### ISSUE TITLE
Questions: How to read parq file into dask data frame?

### ISSUE THREAD

**Issue by ranranking** [dask/fastparquet#75]
Hello, I have a question on the usage. I want to read the parq file into dask data frame. For now it seems I can only use `df = pf.to_pandas()` then `df = dd.from_pandas(df)`. Is it possible to read parq file directly into dask data frames? Besides, is the `to_pandas()` function the only way to use the data? In that way, the data are read into the memory, right? Or I am not doing it right, there are ways to use the data directly from the disk? Thank you very much!

**Comment by mrocklin** [comment]
See the read_parquet function listed here: http://dask.pydata.org/en/latest/dataframe-create.html

**Comment by ranranking** [comment]
Oh! so the dask `read_parq()` uses `fastparquet`. Thank you very much!
