### ISSUE TITLE
C issue when writing dataframe with >498 columns to parquet

### ISSUE THREAD

**Issue by hcarlens** [dask/fastparquet#750]
**What happened**:

When writing certain dask dataframes to parquet, it fails and I get this error which I believe is triggered at the C level:

`free(): invalid next size (normal)`

**What you expected to happen**:

I would expect the file to just get written without any errors.

**Minimal Complete Verifiable Example**:

Here's a simple recreation of the issue. The `print(result)` line is never reached. The error occurs when I set the dataframe to have 499 columns, but not when it has 498 or fewer columns!

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

a = np.zeros((2, 499), dtype='float64')
df = pd.DataFrame(a)
df.columns = df.columns.astype(str)

combined_df = dd.from_pandas(df, npartitions=1)
result = combined_df.to_parquet('test.parq', engine='fastparquet', compression='lz4')
print(result)

...

free(): invalid next size (normal)
```

**Anything else we need to know?**:

When I turn off compression I get a different error:

`double free or corruption (!prev)`

Also worth noting that pyarrow doesn't exhibit this bug, although I would prefer to keep using fastparquet if possible. 

**Environment**:

- Dask version: `2022.1.0`
- Python version: `3.8.10`
- Operating System: `Ubuntu 20.04.3 LTS` (my colleague has the same issue on Windows)
- Install method (conda, pip, source): `pip`

Freeze of other potentially relevant packages:
```
dask==2022.1.0
distributed==2022.1.0
fastparquet==0.8.0
fsspec==2022.1.0
gcsfs==2022.1.0
lz4==2.1.10
numba==0.53.1
numcodecs==0.9.1
numpy==1.21.0
pandas==1.3.0
xarray==0.19.0
```

Thanks in advance!

**Comment by hcarlens** [comment]
Yeah it's a weird one! We've switched to using pyarrow for now, which seems fine when writing via dask :shrug:

**Comment by yohplala** [comment]
Hi, in some test cases of my data wrangling framework, using fastparquet, i can write datasets with several thousands of columns, and with names significantly longer than 10 characters.
Did you try to get a letter within column names (like starting them with a letter)?
Maybe, somewhere in the code, the fact that it can be easily converted to an int leads to this trouble you are seeing?

**Comment by martindurant** [comment]
It definitely seems possible to cause overflow somewhere with enough columns and long enough names (and extremely long pandas metadata). Sometimes you can write a lot of columns, sometimes you can write but crash on read, sometimes you cannot even get that far. It will be tricky to find out where the overflow is.

**Comment by yohplala** [comment]
Hi again,
For the the test, I have been using iPython through spyder IDE.
I was about to close the session, when I noticed the error message displayed in the terminal. Maybe this can be of some help?

```python
  File "/home/yoh/Documents/code/dask/dask/delayed.py", line 597, in __bool__
    raise TypeError("Truth of Delayed objects is not supported")
TypeError: Truth of Delayed objects is not supported
```

**Comment by martindurant** [comment]
@yohplala , have you checked that you can also read your many-column output?

**Comment by yohplala** [comment]
> @yohplala , have you checked that you can also read your many-column output?

I do confirm, this dataframe is a reference result: i wrote it a while ago with fastparquet and to check the number of columns, i loaded it back this morning.
But this raises something: i have used 'file_scheme' = 'simple' .
With file_scheme=hive, i only tried a write with example from @hcarlens , but i did not try to read it back.
I will check this evening.
Bests

**Comment by yohplala** [comment]
@martindurant 
I confirm both write & read work using only fastparquet, with example provided by @hcarlens , and `file_scheme='hive'` (and `'simple'` as well).
