### ISSUE TITLE
Question: key encoding of custom_metadata in ParquetFile.key_value_metadata

### ISSUE THREAD

**Issue by ap--** [dask/fastparquet#751]
Hello dask team,

**What happened**:

When providing `custom_metadata={"my_version": 1}` to `fastparquet.write`, I noticed that all keys get encoded.

**What you expected to happen**:

I expected `"my_version"` to be accessible in `.key_value_metadata`.

**Minimal Complete Verifiable Example**:

```python

import fastparquet
import pandas as pd

df = pd.DataFrame({"A": [1, 2, 3]})

fastparquet.write(
    "out.parquet",
    df,
    custom_metadata={
        "my_version": 1,
    },
)

pf = fastparquet.ParquetFile("out.parquet")

"my_version" in pf.key_value_metadata  # False
b"my_version" in pf.key_value_metadata  # True
assert pf.key_value_metadata[b"my_version"] == 1

pf.key_value_metadata["my_version"]  # raises KeyError
```

I was wondering if `key_value_metadata` could be a subclassed dict that tries to encode a provided key if `__getitem__` initially raises a KeyError. If there's interest in this, I could work on a PR.

Cheers,
Andreas 😃

**Comment by martindurant** [comment]
The parquet spec actually says that the keys should be strings (i.e., assume UTF8 encoding), so it would be reasonable to either build the fallback mechanism you suggest, or to convert all key-values on first access. I'm sure that latter method would have some knock-on failures in this codebase.

**Comment by ap--** [comment]
Great! I'll start work on a PR soon.

Given your explanation, I think it might be worth making `str` keys the default and allow `bytes` keys to fallback with emitting a `DeprecationWarning`. Then it shouldn't break any workflows and users can gradually switch. Does that sound reasonable?

**Comment by martindurant** [comment]
I don't think I would warn at all for this, as the distinction between what's in the file and the in-memory str is fluid.

**Comment by martindurant** [comment]
This one seems to have got lost along the way. What is the status here?

**Comment by ap--** [comment]
Hi @martindurant,

Sorry for the long delay. This dropped off my todo list back then when I saw that work on #762 started. Seeing now that this PR was closed and #764 was merged, I noticed that some functionality I assumed in my code is now broken in `0.8.1+`.

In `0.8.0`, where string keys and values were not decoded the following test passes:
```python
def test_custom_metadata_types(tempdir):
    df = pd.DataFrame({'a': [15]})
    fn = os.path.join(tempdir, "temp.parquet")
    write(fn, df, custom_metadata={"myint": 1, "mystr": "abc", "mybool": True})
    pf = ParquetFile(fn)
    assert pf.key_value_metadata[b'myint'] == 1
    assert pf.key_value_metadata[b'mystr'] == b"abc"
    assert pf.key_value_metadata[b'mybool'] is True
```

Starting with `0.8.1` the values are assumed to be byte strings, which makes `pf = ParquetFile(fn)` crash on read with
```python
>   self._kvm = {k.key.decode(): k.value.decode()
        for k in self.fmd.key_value_metadata or []}
E   AttributeError: 'int' object has no attribute 'decode'
```

If you could clarify if only `str`-type values for custom metadata should be allowed, I would work on a PR that would add a set of tests to document expected behavior for custom metadata, and would raise an exception on write if the type of a value is incorrect.

Cheers,
Andreas

**Comment by yohplala** [comment]
Hi @martindurant , hi @ap-- ,

As pointed out by @ap-- ; merged changes are those from #764, and they are rather minor.

fastparquet initial logic is that when metadata are loaded in memory, it is decoded.
But would you write the data back to disk, then some writing functions would encode the metadata, and the encoded version would also remain in memory.

Because most of the PRs I could contribute to fastparquet make the `ParquetFile` an object you can mutate / play with, this was not very convenient.
I pushed changes so that metadata in memory are not altered / remain decoded, even if they are written to disk.

Hope this helps.
Bests,

**Comment by ap--** [comment]
So, this is definitely interesting.
In version `0.8.0` I can run the following:

```python
# store.py

from fastparquet import write
import pandas as pd

df = pd.DataFrame(data={'a': [1]})

md = {
    "str_key_str_val": "abc",
    "str_key_int_val": 1,
    "str_key_bool_val": True,
    "str_key_float_val": 1.0,
    "str_key_none_val": None,
}

write("out.parquet", df, custom_metadata=md)
```

And then after writing, run in another python process
```python
# load.py

from fastparquet import ParquetFile

pf = ParquetFile("out.parquet")
print(pf.key_value_metadata)

for key in [
    "str_key_str_val",
    "str_key_int_val",
    "str_key_bool_val",
    "str_key_float_val",
    "str_key_none_val",
    ]:
    b_key = key.encode()
    print(key, pf.key_value_metadata[b_key], type(pf.key_value_metadata[b_key]))

```

And I get the following output:
```
{b'pandas': b'{"column_indexes": [{"field_name": null, "metadata": null, "name": null, "numpy_type": "object", "pandas_type": "mixed-integer"}], "columns": [{"field_name": "a", "metadata": null, "name": "a", "numpy_type": "int64", "pandas_type": "int64"}], "creator": {"library": "fastparquet", "version": "0.8.0"}, "index_columns": [{"kind": "range", "name": null, "start": 0, "step": 1, "stop": 1}], "pandas_version": "1.4.3", "partition_columns": []}', b'str_key_str_val': b'abc', b'str_key_int_val': 1, b'str_key_bool_val': True, b'str_key_float_val': 0.0, b'str_key_none_val': None}

str_key_str_val b'abc' <class 'bytes'>
str_key_int_val 1 <class 'int'>
str_key_bool_val True <class 'bool'>
str_key_float_val 0.0 <class 'float'>
str_key_none_val None <class 'NoneType'>


```

which means the KeyValue metadata actually seem to return the correct python types for `non-str` types.

I guess KeyValue just supports serializing to more python types than the spec suggests:

```python
# serialize `int` KeyValue and deserialize

>>> from fastparquet.parquet_thrift import KeyValue
>>> from fastparquet.cencoding import ThriftObject
>>> x = KeyValue(key="abc", value=1)
>>> type(x.value)
<class 'int'>
>>> serialized = bytes(x.to_bytes())
>>> y = ThriftObject.from_buffer(serialized)
>>> y
{1: b'abc', 2: 1}
>>> type(y[2])
<class 'int'>
>>> 
```

I guess the question now is, should that be allowed or not :shrug: ? 

I'm happy to put all that into a bunch of tests and make a draft PR to make it easier to discuss intended behavior for keyvalue metadata.

Cheers,
Andreas :smiley:

**Comment by martindurant** [comment]
Ah, I see, so this was a consequence of our custom thrift code, which does not do type checking against the official schema. I would say it should *not* be allowed, and I suspect that the file you made might at least show warnings if read with other parquet frameworks that are stricter. Probably what you should do, is have a single metadata value containing s JSON encoded version of the objects you currently have, as with the "pandas" key.
