### ISSUE TITLE
fastparquet mis-encodes some thrift enums

### ISSUE THREAD

**Issue by ExpandingMan** [dask/fastparquet#757]
**What happened**:
I am in the process of finishing up [my parquet reader in Julia](https://gitlab.com/ExpandingMan/Parquet2.jl) and have been testing mostly against `fastparquet` and pyarrow.

I believe that `fastparquet` attempts to write the `encodings` field of the `ColumnMetaData` thrift struct as a 64-bit integer while the [thrift specification](https://erikvanoosten.github.io/thrift-missing-specification/) (got to love how it's not that easy to find and they call it the "missing specification" as if that's very amusing to them) indicates that all enums should be encoded as 32-bit integers.

For me, this is resulting in the Julia thrift reader Thrift.jl panicking over an invalid struct, snippet below
```
┌ Debug: setting into container field
│   jtyp = Vector{Int32} (alias for Array{Int32, 1})
│   fldname = :encodings
└ @ Thrift ~/.julia/dev/Thrift/src/base.jl:189
┌ Debug: read TLIST
│   T = Vector{Int32} (alias for Array{Int32, 1})
└ @ Thrift ~/.julia/dev/Thrift/src/base.jl:368
┌ Debug: readCollectionBegin
└ @ Thrift ~/.julia/dev/Thrift/src/protocols.jl:436
┌ Debug: wtf
│   typ = 10
└ @ Thrift ~/.julia/dev/Thrift/src/base.jl:47
┌ Error: error encountered reading Thrift metadata for parquet. May indicate a corrupt file
└ @ Parquet2 ~/.julia/dev/Parquet2/src/utils.jl:139
ERROR: Can not resolve type. Int32 is not a subtype of Int64
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] julia_type(typ::Int32, narrow_typ::Type)
    @ Thrift ~/.julia/dev/Thrift/src/base.jl:48
  [3] read_container(p::Thrift.TCompactProtocol, val::Vector{Int32})
    @ Thrift ~/.julia/dev/Thrift/src/base.jl:372
  [4] read_container(p::Thrift.TCompactProtocol, #unused#::Type{Vector{Int32}})
    @ Thrift ~/.julia/dev/Thrift/src/base.jl:169
  [5] read_container(p::Thrift.TCompactProtocol, val::Parquet2.Metadata.ColumnMetaData)
    @ Thrift ~/.julia/dev/Thrift/src/base.jl:191
  [6] read_container(p::Thrift.TCompactProtocol, #unused#::Type{Parquet2.Metadata.ColumnMetaData})
    @ Thrift ~/.julia/dev/Thrift/src/base.jl:169
  [7] read_container(p::Thrift.TCompactProtocol, val::Parquet2.Metadata.Column)
```

That is, type code 10 (`Int64`) is given (not sure what the actual encoded values wind up being, but I assume `Int64`) when it should be 8 according to the spec.

I'm not quite sure I understand why this is even possible, I would have thought that in a fully described format such as thrift there wouldn't be any type metadata.  Arguably Thrift.jl should handle this case and convert to `Int32` after reading, but as far as I can tell it is following the spec as is.

**What you expected to happen**:
Again, the thrift type code for all enums should be 8 and the following serialized values should be `Int32`'s.

**Minimal Complete Verifiable Example**:
This seems to be a problem with all metadata in 0.8.  I have some older files from fastparquet that don't have this issue, so maybe something changed at some point?  If I had to guess it would be that it was introduced by [this](https://github.com/dask/fastparquet/commit/9bd2a57a627f08629e4b97d22df4f4ccc4c3e0ce).

**Comment by martindurant** [comment]
Bahh, thrift is super-annoying - the actual encoding of int32 and int64 is identical because of var-int. Thanks for finding and describing this. I'll get to you shortly.

**Comment by ExpandingMan** [comment]
> Bahh, thrift is super-annoying

Yeah, it's awful.
