### ISSUE TITLE
Incorrect values being read from parquet file

### ISSUE THREAD

**Issue by Pablete1234** [dask/fastparquet#766]
**What happened**:
I'm trying to read parquet files written from a separate java application, fastparquet returns wrong values for several of the columns in this particular file. The column values decoded also are different every time fastparquet reads the file.

**What you expected to happen**:
Proper values to come out of the file

**Minimal Complete Verifiable Example**:
```python
import pandas as pd
df = pd.read_parquet("foo.parquet", engine="fastparquet")

display(df)
```

**Anything else we need to know?**:
This is the result of calling read parquet multiple times, exact same file, notice the values of the columns are not the same
![image](https://user-images.githubusercontent.com/11789291/161154860-6371b810-a2ec-4b9b-b7a1-e4a539c8e77f.png)

When opening the file with [Bigdata File Viewer](https://github.com/Eugene-Mark/bigdata-file-viewer) it gives the correct values for all fields:
![image](https://user-images.githubusercontent.com/11789291/161154506-7c657fc3-24d3-4131-bd8c-b1fde0d3d41f.png)

The file in question can be found in the zip: [foo.zip](https://github.com/dask/fastparquet/files/8393244/foo.zip)

**Environment(s)**:
Windows x64:
- Pandas version: 1.4.1
- Fastparquet version: 0.8.0
- Python version: 3.8.3
- Install method (conda, pip, source): pip
(the above results)

Linux x64:
- Pandas version: 1.3.4
- Fastparquet version: 0.8.0
- Python version: 3.9.7
- Install method (conda, pip, source): pip

The first column (timeframe_seconds) is correct (value of 73), however the kit_* columns are still wrong. The values at least are consistent and do not change every time the file is read.

**Comment by martindurant** [comment]
You interestingly have data encoded using the DELTA scheme, but there is only one value per page. This has never happened before! I will fix...
