### ISSUE TITLE
Error using append=True on v0.8.1

### ISSUE THREAD

**Issue by JamieAllen1** [dask/fastparquet#769]
**What happened**:
Error received "return "/".join([p.replace("\\", "/").rstrip("/") for p in path if p])" when trying to append to existing Parquet file

Traceback (most recent call last):
  File "/Users/xxx/PyCharmProjects/fastparquet_defect/main.py", line 42, in <module>
    fastparquet.write(
  File "/Users/xxx/PyCharmProjects/fastparquet_defect/venv/lib/python3.10/site-packages/fastparquet/writer.py", line 1171, in write
    pf = ParquetFile(filename, open_with=open_with)
  File "/Users/xxx/PyCharmProjects/fastparquet_defect/venv/lib/python3.10/site-packages/fastparquet/api.py", line 137, in __init__
    self.fn = join_path(fn)
  File "/Users/xxx/PyCharmProjects/fastparquet_defect/venv/lib/python3.10/site-packages/fastparquet/util.py", line 435, in join_path
    return "/".join([p.replace("\\", "/").rstrip("/") for p in path if p])
  File "/Users/xxx/PyCharmProjects/fastparquet_defect/venv/lib/python3.10/site-packages/fastparquet/util.py", line 435, in <listcomp>
    return "/".join([p.replace("\\", "/").rstrip("/") for p in path if p])
TypeError: Path.replace() takes 2 positional arguments but 3 were given

**What you expected to happen**:
Data would append to file correctly

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
from pathlib import PosixPath
import fastparquet
import pandas as pd

# Setup two dataframes to load to file
d1 = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Test1", "Test2", "Test3", "Test4", "Test5"],
}
df1 = pd.DataFrame(data=d1)

d2 = {
    "ID": [6, 7, 8, 9, 10],
    "Name": ["Test6", "Test7", "Test8", "Test9", "Test10"],
}
df2 = pd.DataFrame(data=d2)

# Set posix file path
local_path = PosixPath('test_schema_test_table.parquet')

# Write first dataframe using Append=False
fastparquet.write(
    local_path,
    df1,
    write_index=True,
    compression=None,
    append=False,
)

# Attempt to write second dataframe using Append=False
# Fails here
fastparquet.write(
    local_path,
    df2,
    write_index=True,
    compression=None,
    append=True,
)

```

**Anything else we need to know?**:

**Environment**:

- Dask version: n/a
- Python version: Python 3.10.4
- Operating System: ProductName:    macOS ProductVersion: 12.3 BuildVersion:   21E230
- Install method (conda, pip, source): pip

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by martindurant** [comment]
The docstring says:
```
filename: string
    Parquet collection to write to, either a single file (if file_scheme
    is simple) or a directory containing the metadata and data-files.
```
so using a pathlib.Path is not supposed to work. We could explicitly make it work, cast to string, or raise a better exception. The workaround, though, is to make sure you pass a string.
