### ISSUE TITLE
fastparquet 0.8.1 Linux aarch64 builds are missing

### ISSUE THREAD

**Issue by michael-sanders** [dask/fastparquet#770]
**What happened**:
On a Linux aarch64 system, does not install 0.8.1 via pip. (This works fine on MacOS arm64.)

**What you expected to happen**:
fastparquet 0.8.1 to be installed

**Minimal Complete Verifiable Example**:

```
$ pip install fastparquet==0.8.1
ERROR: Could not find a version that satisfies the requirement fastparquet==0.8.1 (from versions: 0.0.1, 0.0.1.post1, 0.0.1.post2, 0.0.2, 0.0.3, 0.0.4, 0.0.4.post1, 0.0.5, 0.0.6, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.6.0.post1, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.7.1, 0.7.2, 0.8.0)
ERROR: No matching distribution found for fastparquet==0.8.1
```

**Anything else we need to know?**:
.whl file is missing on pypi: https://pypi.org/project/fastparquet/0.8.1/#files

**Environment**:
Python 3.9.11
Linux 4e20d812a0b1 5.10.104-linuxkit #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022 aarch64 GNU/Linux
fastparquet 0.8.1

**Comment by martindurant** [comment]
Do the packages exist on conda-forge, is that an option for you?

Do you know how to change https://github.com/dask/fastparquet/blob/main/.github/workflows/wheel.yml#L6 to get aarch builds? I'd be happy to run it and upload.

**Comment by michael-sanders** [comment]
Thanks Martin. The packages do not exist on conda-forge for 0.8.1. I have created #771 to add support for building on aarch64.
