### ISSUE TITLE
distutils Version classes DeprecationWarning

### ISSUE THREAD

**Issue by vascosmota** [dask/fastparquet#773]
**What happened**:
I got a DeprecationWarning when reading a parquet file through pandas.

**What you expected to happen**:
No Warnings to be raised.

**Minimal Complete Verifiable Example**:

```
dataset_file = "my_file.parquet"
df = pd.read_parquet(dataset_file)
```

**Anything else we need to know?**:
Output: 

> .venv/lib/python3.8/site-packages/fastparquet/util.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

**Environment**:

- Dask version: not installed. Fastparquet version = '0.8.1'
- Python version: 3.8
- Operating System: MacOS Monterey 12.2.1
- Install method (conda, pip, source): pip

**Comment by vascosmota** [comment]
Already mentioned on #772.

**Comment by martindurant** [comment]
@suryajayaraman ,
0.5.0 is over two years old, but you installing with more recent versions of other things, so the warnings are not surprising.

**Comment by suryajayaraman** [comment]
@martindurant, 

Thanks for pointing out. It was a silly mistake from my side. I was using `conda install fastparquet` command to install the required packages and throught it'd be a recent release. But it seems the conda manager still refers to old version. After I updated the package using `pip3 install --upgrade fastparquet` command, the warnings disappeared.

Thanks once again for pointing out.
