### ISSUE TITLE
0.8.1 Causes error when writing a nested list with json datatype

### ISSUE THREAD

**Issue by hydriniumh2** [dask/fastparquet#775]
Version affected: 0.8.1 

Expected Behavior:
Support for writing nested lists with the json encoding

Actual Behavior
When writing nested list of objects encoded as json type fastparquet throws an error `TypeError: Expected dict, got tuple`

I'm not sure if this was unintended behavior previous to 0.8.1, but the write function previously could encode these nested lists fine.

Fastparquet 0.8.1
```
>>> import pandas as pd
>>> import fastparquet as fp
>>>
>>> fp.__version__
'0.8.1'
>>> df = pd.DataFrame(
...         [{'a': [(1,2,4), ('x', 'y', 'z')]}]
...     )
>>> df
                        a
0  [(1, 2, 4), (x, y, z)]
>>> fp.write(
...         filename='test.pq',
...         data=df,
...         compression='SNAPPY',
...         write_index=False,
...         object_encoding={'a': 'json'}
...     )
TypeError: Expected dict, got tuple
Exception ignored in: 'fastparquet.cencoding.write_list'
Traceback (most recent call last):
  File "/Users/.../python3.8/site-packages/fastparquet/writer.py", line 894, in write_simple
    foot_size = f.write(fmd.to_bytes())
TypeError: Expected dict, got tuple
TypeError: Expected dict, got tuple
Exception ignored in: 'fastparquet.cencoding.write_list'
Traceback (most recent call last):
  File "/Users/.../python3.8/site-packages/fastparquet/writer.py", line 894, in write_simple
    foot_size = f.write(fmd.to_bytes())
TypeError: Expected dict, got tuple
```

Fastparquet 0.8.0
```
>>> import pandas as pd
>>> import fastparquet as fp
>>>
>>> fp.__version__
'0.8.0'
>>> df = pd.DataFrame(
...         [{'a': [(1,2,4), ('x', 'y', 'z')]}]
...     )
>>> df
                        a
0  [(1, 2, 4), (x, y, z)]
>>> fp.write(
...         filename='test.pq',
...         data=df,
...         compression='SNAPPY',
...         write_index=False,
...         object_encoding={'a': 'json'}
...     )
>>>
```

```
parquet-tools schema test.pq
message schema {
  optional binary a (JSON);
}
```

**Comment by martindurant** [comment]
The problem seems to be with the stats of the column - probably because the values are tuples (lists), but the underlying dtype after encoding is bytes. You can workaround by passing `stats=False` in `write()`.

**Comment by hydriniumh2** [comment]
That fixed the issue, thanks!

**Comment by martindurant** [comment]
I'll keep this open, since it *ought* to work :)

**Comment by hydriniumh2** [comment]
I wasn't sure if I should create another ticket as well but it seems that setting `stats=False` also changes the datatype read back into Parquetfile.to_pandas() for int64. 

Expected behavior:
When going from dataframe to parquet file back to dataframe the datatypes should be identical

Actual behavior:
When reading back a parquetfile generated with `stats=False` the `int64` (`numpy.int64`) type gets converted to `Int64`, the pandas nullable type `pd.Int64Dtype`.  When reading back with `stats=True` the type is correctly read back.

`stats=False` converts `numpy.int64` to `pd.Int64Dtype`
```
>>> df = pd.DataFrame(
...         [{'b': 65}]
...     )
>>> fp.write(
...         filename='test.pq',
...         data=df,
...         compression='SNAPPY',
...         write_index=False,
...         object_encoding={'b':'int64'},
...         stats=False
...     )
>>>
>>> pq_pf = fp.ParquetFile('test.pq')
>>> pq_df = pq_pf.to_pandas()
>>>
>>> pq_df['b'].dtype
Int64Dtype()
```

`stats=True` keeps correct `numpy.int64`
```
>>> fp.write(
...         filename='test.pq',
...         data=df,
...         compression='SNAPPY',
...         write_index=False,
...         object_encoding={'b':'int64'},
...         stats=True
...     )
>>>
>>> pq_pf = fp.ParquetFile('test.pq')
>>> pq_df = pq_pf.to_pandas()
>>>
>>> pq_df['b'].dtype
dtype('int64')
```

**Comment by martindurant** [comment]
Fascinating! Indeed, without stats in the metadata we cannot guarantee that the column contains no NULLs, but even without the stats, the metadata keeps hold of the fact that the original input was int64. I'll look into the two issues when I can.

**Comment by martindurant** [comment]
Fix for JSON: https://github.com/dask/fastparquet/pull/776

**Comment by GianlucaFicarelli** [comment]
I'm not sure if it's the same error, but with `fastparquet 0.8.1` I have this issue:
```
In [1]: import pandas as pd
In [2]: import fastparquet as fp
In [3]: df = pd.DataFrame({"k": [[1.1, 1.2], [2], [3, 4]]})
In [4]: fp.write(filename='test.pq', data=df, compression='SNAPPY')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: Expected dict, got float
Exception ignored in: 'fastparquet.cencoding.write_list'
Traceback (most recent call last):
  File "/.../venv/lib/python3.9/site-packages/fastparquet/writer.py", line 894, in write_simple
    foot_size = f.write(fmd.to_bytes())
TypeError: Expected dict, got float
```

The error is fixed for me with the commit 060d235d2e3118df844a754fb2b6b256506aa3cb or ad8c130c1244d813a4179df39afb04c12963b875, but I'm reporting it in case of any additional checks or tests are needed.

Note that I didn't specify `object_encoding` (but the code works using the current main branch).

I also wonder if there is any plan to make a release with the fix?

**Comment by martindurant** [comment]
Yes, a release is planned when I have the time. fastparquet takes more effort than most because of all the platforms it needs to be compiled against. Thanks for diagnosing your issue.

**Comment by GianlucaFicarelli** [comment]
Thanks for the confirmation and for your efforts 👍
