### ISSUE TITLE
latest version (0.8.1) not found by pip

### ISSUE THREAD

**Issue by danWexlerRidewithvia** [dask/fastparquet#779]
**What happened**:
installing fastparquet using pip yields version 0.8.0,
and errors out when forcing version 0.8.1 

**What you expected to happen**:
pip installing latest fastparquet

**Minimal Complete Verifiable Example**:

```bash
pip install fastparquet==0.8.1
```

**Environment**:

- Python version: 3.7.12
- Operating System: macOS 12.3.1
- Install method (conda, pip, source): pip 22.0.4

**Comment by martindurant** [comment]
What error does pip give?

Do you know what exact build pip is searching for? https://pypi.org/project/fastparquet/#files shows that there are a good number of wheels for various python versions and OSs.

**Comment by danWexlerRidewithvia** [comment]
the error is:
`ERROR: Could not find a version that satisfies the requirement fastparquet==0.8.1 (from versions: 0.0.1, 0.0.1.post1, 0.0.1.post2, 0.0.2, 0.0.3, 0.0.4, 0.0.4.post1, 0.0.5, 0.0.6, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.6.0.post1, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.7.1, 0.7.2, 0.8.0)
ERROR: No matching distribution found for fastparquet==0.8.1
`

the wheel count looks good, but the list is missing a python3.7 macOS wheel.
I'm assuming it's something like
_fastparquet-0.8.1-cp37-cp37m-macosx_10_9_universal2.whl_
(and another one for apple-silicon users)

**Comment by martindurant** [comment]
I made [fastparquet-0.8.1-cp37-cp37m-macosx_10_9_x86_64.whl](https://files.pythonhosted.org/packages/9b/26/686b6799bda306c5764975658f03c19924def974cfec40017ec74a9f0047/fastparquet-0.8.1-cp37-cp37m-macosx_10_9_x86_64.whl) - can you check now, please? With the release of apple silicon, I suppose the builder is making "universal" binaries only for python versions that support both intel and M1. This wheel, for py37, is intel-only; I can support this so long as I have an old(er) mac myself!

**Comment by danWexlerRidewithvia** [comment]
Works great, thank you so much!
Sad to hear about the coming end of python 3.7 prebuilts...

P.S.: thanks for the package in general!
