### ISSUE TITLE
Pandas MultiIndex loses dtypes when empty

### ISSUE THREAD

**Issue by phubaba** [dask/fastparquet#780]
If build an empty df with an empty multi index, write it and then read it using fastparquet, the dtypes on the index are lost.

```
idx = pandas.MultiIndex.from_arrays([pandas.Series([], dtype='timedelta64[ns]', name='td'), pandas.Series([], dtype=int, name='i')])
df = pandas.DataFrame([pandas.Series([], name='a', dtype=float)], index=idx)
```
Can see that they are there after creating the series:
```
>>> df.index.dtypes
td    timedelta64[ns]
i               int64
dtype: object
```
If I write it and then read it back 
```
f_single = 'f_single.parq'  
fastparquet.write(f_single, df)
df2 = fastparquet.ParquetFile(f_single).to_pandas()
```
the dtypes are empty:
```
>>> df2.index.dtypes
td    object
i     object
dtype: object
```

Note the column dtypes are not lost.

**Environment**:
I checked fastparquet 0.8.0 and 0.8.1. Python is 3.8.12. OS is linux. conda for 0.8.0 and pip for 0.8.1

**Comment by martindurant** [comment]
I wonder, do you experience the same if you first explicitly reset the index, so that they become ordinary columns?

**Comment by phubaba** [comment]
no normal columns do not have this issue.

**Comment by phubaba** [comment]
looks like dtypes are there properly

```
In [8]: df.reset_index().dtypes
Out[8]:
td    timedelta64[ns]
i               int64
a             float64
b     timedelta64[ns]
dtype: object
`
```

**Comment by phubaba** [comment]
the problem is on this line:
https://github.com/dask/fastparquet/blob/ad8c130c1244d813a4179df39afb04c12963b875/fastparquet/api.py#L790
```

                    df.columns = pd.MultiIndex.from_tuples(
                        [ast.literal_eval(c) for c in df.columns if c not in df.index.names],
                        names=names
                    )
```

This infers the dtypes from the columns. it should be using pd.MultiIndex.from_arrays if possible.. it seems like c is a column not a tuple, so bit hard to understand how this code is working.

**Comment by martindurant** [comment]
I wonder, is it possible to simply supply the dtypes on that line? Would you like to implement a fix in a PR?

**Comment by martindurant** [comment]
Closing as wontfix, sorry :|
