### ISSUE TITLE
invalid python_requires

### ISSUE THREAD

**Issue by henryliou-kklab** [dask/fastparquet#784]
**What happened**:
Poetry complains: "Could not parse version constraint: >=3.7,"

**What you expected to happen**:

**Minimal Complete Verifiable Example**:
```sh
poetry add fastparquet # successfully install and generate poetry.lock
poetry env remove python3.9 # remove environment
poetry install # install from poetry.lock and fail
```

**Anything else we need to know?**:
https://github.com/dask/fastparquet/blob/main/setup.py#L85
It says
`python_requires=">=3.7,"`
(with a trailing comma)
instead of
`python_requires=">=3.7"`

**Environment**:

- Python version: 3.9 (rosetta)
- Operating System: MacOS on M1 Max
- Install method (conda, pip, source): poetry add fastparquet

**Comment by martindurant** [comment]
Oh, so pip is alright with this, but poetry isn't - which is why it hadn't been spotted before. Since you know the fix already, would you like to make the PR?

**Comment by henryliou-kklab** [comment]
https://github.com/dask/fastparquet/pull/785
