### ISSUE TITLE
Maintainer email domain expired and has recently been re-registered

### ISSUE THREAD

**Issue by vesche** [dask/fastparquet#786]
Hello @martindurant -

PyPi is currently being hit with attacks similar to what we've seen happen to NPM recently - https://twitter.com/lrvick/status/1523774962909298690

I scanned many of the top packages on PyPi and looked for unregistered / recently registered domains. I noticed your listed maintainer email domain `canaconda.com` had expired and was recently (`2022-05-23T16:30:23Z`) re-registered on Gandi. This could potentially be used to take over your account / packages on PyPi: https://pypi.org/project/fastparquet/

I believe this could be a typo and perhaps can't be abused `anaconda.com` vs `canaconda.com`?
* https://github.com/dask/fastparquet/blob/main/setup.py#L52

Wanted to bring this to your attention and hopefully we can resolve this to avoid any possible abuse. Thanks.

**Comment by martindurant** [comment]
Thanks for bringing this to my attention. Indeed it should be "anaconda" (without the c). I can update this for the next release. If it can be changes in the old metadata, that would be good - but in practice, I have never had anyone try to contact me this way for any other package I have published with a correct address.

What other remediation actions do you suggest?
________________________________
From: Austin Jackson ***@***.***>
Sent: 25 May 2022 01:33
To: dask/fastparquet ***@***.***>
Cc: Martin Durant ***@***.***>; Mention ***@***.***>
Subject: [dask/fastparquet] Maintainer email domain expired and has recently been re-registered (Issue #786)


Hello @martindurant<https://github.com/martindurant> -

PyPi is currently being hit with attacks similar to what we've seen happen to NPM recently - https://twitter.com/lrvick/status/1523774962909298690

I scanned many of the top packages on PyPi and looked for unregistered / recently registered domains. I noticed your listed maintainer email domain canaconda.com had expired and was recently (2022-05-23T16:30:23Z) re-registered on Gandi. This could potentially be used to take over your account / packages on PyPi: https://pypi.org/project/fastparquet/

I believe this could be a typo and perhaps can't be abused anaconda.com vs canaconda.com?

Wanted to bring this to your attention and hopefully we can resolve this to avoid any possible abuse. Thanks.

**Comment by vesche** [comment]
Thanks for the response. I'm glad to hear this was a typo. As long as `mdurant@canaconda.com` is not a valid email- it appears there is limited or no concern for a PyPi ATO attack. I agree with updating the email. Closing this one, thanks again.
