### ISSUE TITLE
How about a fastfeather? Feather needs a fastparquet version, light and concise.

### ISSUE THREAD

**Issue by arturdaraujo** [dask/fastparquet#788]
The great thing about fastparquet is because it is concise, unlike pyarrow. It would be great to see another way to read and write feather format in a package like fastparquet. 

I encountered some incompatibility between packages in conda-forge while using pyarrow for feather, so I changed to parquet files and I installed fastparquet instead of pyarrow and there was no problems with compatibility with the package that I was using (tsfresh=0.19.0). 

Parquet is great but feather has some advantages and its gaining popularity these days. My focus is on speed for I/O (and for the files that I was using the compression is even better than parquet, which is not generally the case). 

Anyway, just giving some thoughts. f you planning to do so, I would love to help.

**Comment by martindurant** [comment]
Interesting idea!

Firstly: I presume you mean Feather 2 format, which is the same as arrow IPC in a file?

As I imply in that question, feather was specifically designed as encapsulation for arrow. Actually, to write a fast feather<->pandas interface without pyarrow would, I think, be pretty easy to do, so long as the schema of the dataset is actually compatible with tabular (no deep nested/variable length things). You would need to replicate or reverse engineer the code in arrow which constructs the dtypes from the feather schema. All this is doable.

To answer the specific question, I don't really have plans to take this on, and any implementation would be sufficiently different from parquet, that it would probably not make sense to include it in this same repo.

**Comment by martindurant** [comment]
I suppose this is it: https://github.com/apache/arrow/blob/master/docs/source/format/Columnar.rst#serialization-and-interprocess-communication-ipc

**Comment by arturdaraujo** [comment]
Thanks for the answer!

**Comment by martindurant** [comment]
Just for fun, I wrote a flatbuffer parser with a view to enabling what you propose. 

```python
import fastfeather.arrow_meta.parse
with open("fastfeather/arrow_meta/flatbuf/test.feather", "rb") as of:
    out = fastfeather.arrow_meta.parse.parse_feather(of)
```

**Comment by martindurant** [comment]
https://github.com/martindurant/fastfeather

**Comment by arturdaraujo** [comment]
That's incredible! You really meant it when you said it was easy. I'm using .parquet at the project but definitly will keep an eye on it.
