### ISSUE TITLE
Optional Ints can cause parser errors

### ISSUE THREAD

**Issue by peter-iron** [dask/fastparquet#808]
**What happened**:
Attempted to read a parquet file that has an entirely null`INT64, OPTIONAL` column.

**What you expected to happen**:
Reads with `pd.NA()` for every element of the DataFrame.

**Minimal Complete Verifiable Example**:
I cannot provide one of these. I cannot share the problematic file and cannot seem to replicate it using write().

The problem seems to be this, though
1. If your column is an int32 or int64, the converted python dtype is set to [np.int32 or np.int64](https://github.com/dask/fastparquet/blob/45de0d920d990572fea2fa6efed1a4de8c5e4228/fastparquet/converted_types.py#L39).
2. If your column is some kind of int (or bool), the `my_nan` [value is set](https://github.com/dask/fastparquet/blob/45de0d920d990572fea2fa6efed1a4de8c5e4228/fastparquet/core.py#L447) to `pd.NA`
3. If you attempt to assign `pd.NA` [to a numpy array with an integer dtype](https://github.com/dask/fastparquet/blob/45de0d920d990572fea2fa6efed1a4de8c5e4228/fastparquet/core.py#L528), it throws an error because it cannot coerce pd.NA using `int()`.

This results in the error:
```
...
File /opt/conda/lib/python3.10/site-packages/fastparquet/core.py:580, in read_row_group_arrays(file, rg, columns, categories, schema_helper, cats, selfmade, assign, row_filter)
    577 if name not in columns:
    578     continue
--> 580 read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
    581          selfmade=selfmade, assign=out[name],
    582          catdef=out.get(name+'-catdef', None),
    583          row_filter=row_filter)
    585 if _is_map_like(schema_helper, column):
    586     # TODO: could be done in fast loop in _assemble_objects?
    587     if name not in maps:

File /opt/conda/lib/python3.10/site-packages/fastparquet/core.py:528, in read_col(column, schema_helper, infile, use_cat, selfmade, assign, catdef, row_filter)
    526     part = part._data
    527 elif part.dtype.kind != "O":
--> 528     part[defi != max_defi] = my_nan
    529 if d and not use_cat:
    530     part[defi == max_defi] = dic[val]

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NAType'
```

Which is the same error you get from:
```python
import numpy as np
import pandas as pd
v = np.empty(5, dtype=np.int32)
v[0] = pd.NA
```

This commit eliminates the error for int32 and int64, but probably not for bools:
https://github.com/dask/fastparquet/commit/a3bcb25dea043e9fa42d3b9957dbdf0bcfaad8e4

**Anything else we need to know?**:
fastparquet 0.8.3
numpy 1.22.4
pandas 1.4.3

**Environment**:

- Dask version: N/A
- Python version: 3.10
- Operating System: Ubuntu 20.04.4 LTS
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
I did the following and encountered no error:
```
In [4]: import pandas as pd

In [5]: pd = pd.DataFrame({'a': pd.Series([None, None, None], dtype="Int32")})

In [6]: fastparquet.write?

In [7]: fastparquet.write("null.parq", pd)

In [8]: fastparquet.ParquetFile("null.parq")
Out[8]: <Parquet File: {'name': 'null.parq', 'columns': ['a'], 'partitions': [], 'rows': 3, 'row_groups': 1}>

In [9]: _.to_pandas()
Out[9]:
      a
0  <NA>
1  <NA>
2  <NA>
```

**Comment by peter-iron** [comment]
I don't think you can test that way because I believe that .write(path, DataFrame) stores pandas metadata and uses it to [reconstitute the dtypes](https://github.com/dask/fastparquet/blob/45de0d920d990572fea2fa6efed1a4de8c5e4228/fastparquet/api.py#L917).

**Comment by peter-iron** [comment]
Yep! I actually have no idea what framework my data was written by (external collaboration, which is why I cannot share the file).

**Comment by peter-iron** [comment]
Sorry for not getting back sooner. I will try to trace the problem more carefully through the code tomorrow night to see where it occurs.

Do you have an idea where in the code np.array changes from a numpy dtype to one that can support nullable ints?

**Comment by martindurant** [comment]
There are two stages: a dataframe with a set of empty arras is created in fastparquet.dataframe.empty (conditions `isinstance(t, BaseMaskedDtype)` and `str(bvalues.dtype)[0] in {"I", "U"}`), and filled in in fastparquet.core.read_col (condition `isinstance(piece, pd.core.arrays.masked.BaseMaskedDtype)`).

**Comment by peter-iron** [comment]
Ok, walking through the code for the bad column:
* `_dtypes()` calls `converted_types.typemap(se, None)` to get `np.int64` because the schema codes as int64 and satisfies the conditions to reach [here](https://github.com/dask/fastparquet/blob/main/fastparquet/converted_types.py#L115) (no arrow or pandas metadata so `md` is None, no `logicalType`, `se.type` == 2)
* after this it enters the enumeration and the `elif dt in converted_types.nullable` branch
* no self.pandas_metadata, so it goes into the `for rg in self.row_groups:` iteration.
* `st.get(3)` does exist for the bad column, but the value is 0 so the conditional still evaluates to false and `num_nulls` stays as `0` instead of being set to `True`, which means the column is not considered nullable in practice even though `null` is the only value it ever takes.

That last step looks the most suspicious to me. I'm not sure exactly what the parquet format is supposed to be, but I assume `st.get(3)` is supposed to return the number of nulls in the column?

**Comment by martindurant** [comment]
>  So it's 0/0 nulls, which the logic is interpreting as "no nulls" but could also be interpreted as "all nulls" because there's no provided value.

It would make a lot of sense if this was the unique thing about your data.

**Comment by martindurant** [comment]
Yes, I believe it always should

**Comment by peter-iron** [comment]
OK, closing it then!

**Comment by Byrth** [comment]
> Yes, I believe it always should

https://github.com/apache/parquet-format/blob/54e53e5d7794d383529dd30746378f19a12afd58/src/main/thrift/parquet.thrift#L819

You are correct
