### ISSUE TITLE
Error message unclear in case of an inconsistent `append`

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#811]
**Describe the issue**:

**Minimal Complete Verifiable Example**:

```python
import os
import pandas as pd
import fastparquet as fp

path = os.path.expanduser('~/Documents/code/data/fastparquet/')
df1 = pd.DataFrame({'val': [0,1]})
df2 = pd.DataFrame({'val': [-1,0]})
path2 = f"{path}file.2.parquet"

fp.write(path, df1, file_scheme="hive")
fp.write(path2, df2, file_scheme="hive", append=True)
```
This code snippet (inconsistent because `path2` in 2nd `write` is different than `path` in 1st `write`) results in this error message:
```python
AttributeError: 'ParquetFile' object has no attribute 'fmd'
```
I have not investigated where does come from the error message, but it does not really help to spot the error (that the paths provided between 1st and 2nd calls are inconsistent)

**Environment**:

- fastparquet version: from source
- Python version: 3.9
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): source

**Comment by martindurant** [comment]
I have seen that, and I think it means that metadata parsing failed in general, and should be raised as an explicit exception earlier than this.

**Comment by martindurant** [comment]
In your snippet, path2 doesn't exist yet - you can only append to an existing path. Agree that this should be stated clearly in the error. We seem to be able to build a ParquetFile from nowhere
```
p = fp.ParquetFile("none")
```
should fail, but instead makes an instance lacking useful attributes.

**Comment by martindurant** [comment]
I *think* this is probably fixed in the latest release? For me it now gives FileNotFound .

**Comment by yohplala** [comment]
> I _think_ this is probably fixed in the latest release? For me it now gives FileNotFound .

Yes, you are right! I just checked.
I am sorry, I have not followed closely lately, I have very little spare time currently, sorry again.
Ok, closing then! Thanks!
