### ISSUE TITLE
Partition paths not parsed correctly with leading `.` and filters

### ISSUE THREAD

**Issue by phobson** [dask/fastparquet#814]
**Describe the issue**:

xref: https://github.com/dask/dask/issues/9591

Reading a parquet file (via dask, at least) whose path contains a leading `./` raises an AssertionError when the basepath is compared to the roots of each partition

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client
import dask.dataframe as dd
import pandas as pd


def main():
    df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
    ddf = dd.from_pandas(df, npartitions=2)
    ddf.to_parquet("./result/", engine="fastparquet", partition_on=["a"])

    # works
    dd.read_parquet("result/", engine="fastparquet").head()
    dd.read_parquet("result/", engine="fastparquet", filters=[("a", ">", 1)]).head()

    # fails
    dd.read_parquet("./result/", engine="fastparquet").head()


if __name__ == "__main__":
    main()

```

**Anything else we need to know?**:

Output from my ipython/debug session:

```
> /Users/paul/mambaforge/envs/dask-dev/lib/python3.10/site-packages/fastparquet/util.py(366)analyse_paths()
    364         basepath = join_path(root).split('/')
    365         l = len(basepath)
--> 366         assert all(p[:l] == basepath for p in path_parts_list
    367                    ), "All paths must begin with the given root"
    368     out_list = []

ipdb> print(l)
7
ipdb> path_parts_list
[['', 'Users', 'paul', 'work', 'sources', 'dask', '.', 'result', 'a=1', 'part.0.parquet']]
ipdb> basepath
['', 'Users', 'paul', 'work', 'sources', 'dask', 'result']
```

**Environment**:

- Dask version: 2022.10.0+12.g97c22be7.dirty'
- fastparquet version: 0.8.3
- Python version: 3.10.6
- Operating System: Mac OS 13 (Ventura, M1 architecture)
- Install method (conda, pip, source): Conda for deps + fastparquet, source for dask

**Comment by martindurant** [comment]
Note that this works via pandas or directly with the fastparquet API with or without the leading "." .

**Comment by phobson** [comment]
Ahh yes -- I'd lost sight of that detail @martindurant. Thanks for the reminder. If that's the case, it seem like the fix is dask then. Is that right?

**Comment by martindurant** [comment]
Yes, I believe so
