### ISSUE TITLE
Parquet files can't exceed 2.14GB? Write throws overflow errors when filesize in bytes exceeds int32 limit...

### ISSUE THREAD

**Issue by sikanrong** [dask/fastparquet#825]
I'm having an issue storing a large dataset (around 40GB) in a *single* parquet file. I'm using `fastparquet` to append `pandas.DataFrames` to this parquet dataset file. 

The following is a minimal example program that appends chunks to a parquet file until it crashes as the file size in bytes exceeds the `int32` threshold of `2147483647` (2.1GB): 

[Link to minimum reproducible example code](https://gist.github.com/sikanrong/d4b2f62bfb17f19bca4946ce8cce37a3)

Everything goes fine until the dataset hits 2.1GB, at which point I get the following errors:

```
OverflowError: value too large to convert to int
Exception ignored in: 'fastparquet.cencoding.write_thrift'
```

Because the exception is ignored internally, it's very hard to figure out which specific thrift it's upset about on write and get a stack trace to provide here. However, it's very clear that the failure is directly linked to the file size in bytes exceeding the `int32` range. 

Also these thrift definitions come from the `parquet-format` repo *itself*, so I wonder if this is a limitation built into the design of the parquet format, or if it's an error in `fastparquet`...

I opened [a related issue](https://github.com/dask/fastparquet/issues/823) about this yesterday, but now I've been able to condense it into a very concise program that reproduces the issue. I feel like everyone keeps assuring me that this program shouldn't crash when the file hits 2.14GB, and that parquet format has no inherent size limitations, and yet it _does_ crash in such a way that suggests those exact limitations. Someone on the `fastparquet` team should run this code and ensure that it doesn't represent an issue with the library. 

I'm on Python `3.9.0` and `fastparquet==2022.11.0`

**Comment by sikanrong** [comment]
@martindurant Hi again! we talked about this yesterday. I've provided some dead-simple code so that you can reproduce this issue yourself; I really feel like the code I've provided ought to work without issue.

**Comment by martindurant** [comment]
Thanks for the reproducer, that's very helpful. You may want to try with #824 before I get around to trying with your code.

**Comment by sikanrong** [comment]
@martindurant so in the example (but is also the case in my real code) all that's being written are float32 values. In the example code, they're all set to `1`, for simplicity

**Comment by martindurant** [comment]
Perfect - fixed in https://github.com/dask/fastparquet/pull/824/commits/7961b11fefdf2f7107cfec10c4df124208514b85 (not the one-liner!)
