### ISSUE TITLE
OverflowError with a 3GB, 11M-line JSONL file

### ISSUE THREAD

**Issue by marklit** [dask/fastparquet#839]
The following was run on Ubuntu 20 on a `e2-highcpu-32` GCP VM with 32 GB of RAM and 32 vCPUs.

I downloaded the California dataset from https://github.com/microsoft/USBuildingFootprints and converted it from JSONL into Parquet with pyarrow and I attempted to do the same with fastparquet.

```bash
$ ogr2ogr -f GeoJSONSeq /vsistdout/ California.geojson \
    | jq -c '.properties * {geom: .geometry|tostring}' \
    > California.jsonl
$ head -n1 California.jsonl | jq .
```

```json
{
  "release": 1,
  "capture_dates_range": "",
  "geom": "{\"type\":\"Polygon\",\"coordinates\":[[[-114.127454,34.265674],[-114.127476,34.265839],[-114.127588,34.265829],[-114.127565,34.265663],[-114.127454,34.265674]]]}"
}
```

PyArrow is able to produce a 792 MB Parquet file without issue.

```bash
$ python3 -c "import pandas as pd; pd.read_json('California.jsonl', lines=True).to_parquet('pandas.pyarrow.snappy.pq', engine='pyarrow')"
```

The resulting Parquet file is 792 MB with a single row group.

```
<pyarrow._parquet.FileMetaData object at 0x7f18566254a0>
  created_by: parquet-cpp-arrow version 10.0.1
  num_columns: 3
  num_rows: 11542912
  num_row_groups: 1
  format_version: 2.6
  serialized_size: 3064
```

When I attempt the same with fastparquet I'm hit with an `OverflowError`.

```bash
$ python3 -c "import pandas as pd; pd.read_json('California.jsonl', lines=True).to_parquet('pandas.fastparquet.snappy.pq', engine='fastparquet')"
```

These are the versions of software involved:

* pandas-1.5.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
* fastparquet-2022.12.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
* pyarrow-10.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

Are there any flags I could pass to fastparquet to get this workload to run on a system with 32 GB of RAM?

**Comment by martindurant** [comment]
pyarrow splits row-group column chunks into "pages" on write, but fastparquet does not. Out of interest, what exactly overflowed? The exception traceback should give some information. To workaround, you can use the kwargs `row_group_offsets=5_000_000`, for example (I'm not sure what the right number would be). This will be happening because your string columns contain many bytes per record.

**Comment by martindurant** [comment]
I have had a quick look and actually adding subpage support would not be too hard, but I don't have the time in the immediate future. I am asking around to see if there is already a public version of this dataset in parquet format (not strings, but variable-length lists for the polygons), which would work nicely with the awkward-array library.

**Comment by martindurant** [comment]
Here is a parquet version, I'm not sure if this is with string geometries or lists of int: https://planetarycomputer.microsoft.com/dataset/ms-buildings#Example-Notebook

**Comment by marklit** [comment]
I picked the Microsoft Buildings dataset as an example dataset that others could download. My aim to understand the performance differences between the various Parquet writers available in the open source world.

This is the entire traceback.

```bash
$ python3 -c "import pandas as pd; pd.read_json('California.jsonl', lines=True).to_parquet('pandas.fastparquet.snappy.pq', engine='fastparquet')"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mark/.pq/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/mark/.pq/lib/python3.8/site-packages/pandas/core/frame.py", line 2975, in to_parquet
    return to_parquet(
  File "/home/mark/.pq/lib/python3.8/site-packages/pandas/io/parquet.py", line 430, in to_parquet
    impl.write(
  File "/home/mark/.pq/lib/python3.8/site-packages/pandas/io/parquet.py", line 312, in write
    self.api.write(
  File "/home/mark/.pq/lib/python3.8/site-packages/fastparquet/writer.py", line 1272, in write
    write_simple(filename, data, fmd,
  File "/home/mark/.pq/lib/python3.8/site-packages/fastparquet/writer.py", line 927, in write_simple
    rg = make_row_group(f, row_group, fmd.schema,
  File "/home/mark/.pq/lib/python3.8/site-packages/fastparquet/writer.py", line 742, in make_row_group
    chunk = write_column(f, coldata, column,
  File "/home/mark/.pq/lib/python3.8/site-packages/fastparquet/writer.py", line 583, in write_column
    uncompressed_page_size=check_32(l0),
  File "/home/mark/.pq/lib/python3.8/site-packages/fastparquet/writer.py", line 1599, in check_32
    raise OverflowError
OverflowError
```

The `row_group_offsets` setting does the trick. Thanks for the tip.

```bash
$ python3 -c "import pandas as pd; pd.read_json('California.jsonl', lines=True).to_parquet('pandas.fastparquet.snappy.pq', engine='fastparquet', row_group_offsets=30_000)"
```

**Comment by Quetzalcohuatl** [comment]
Have the same problem on fastparquet 2023.8.0 with very large dataframe with lots of columns being lists of strings. Editing row_group_offsets (to a smaller number, i used 30_000) fixed it for me

**Comment by martindurant** [comment]
>  lots of columns being lists of strings

It is hard for fastpaquet to guess the typical size-per-row of such data, since the size of each row may vary radically from one to the next.

As well as passing an explicit value for offsets, you can also set the `fastparquet.writer.MAX_PAGE_SIZE` to a smaller value (default 500MB), which would create more pages per row group rather than more row groups. It probably makes little difference to the performance.

Finally, if you are doing a lot of processing of nested/structured JSON and parquet data (as opposed to pure tabular), you may be interested to try [`awkward`](https://awkward-array.org/doc/main/) instead of fastparquet.
