### ISSUE TITLE
ValueError: Don't know how to convert data type: uint64

### ISSUE THREAD

**Issue by ginseil** [dask/fastparquet#85]
fastparquet refuses to write parquet file if data frame has columns with dtype uint64.

I am getting the following error:

File "..\fastparquet\writer.py", line 114, in find_type
    raise ValueError("Don't know how to convert data type: %s" % dtype)
ValueError: Don't know how to convert data type: uint64

**Comment by martindurant** [comment]
My apologies. Fix will be merged as soon as tests complete.

**Comment by ginseil** [comment]
Thanks for your quick reply, but shouldn't the changed line in writer.py be 
`'uint64': (parquet_thrift.Type.INT64, parquet_thrift.ConvertedType.UINT_64, 64),`

instead of 
`'uint64': (parquet_thrift.Type.INT32, parquet_thrift.ConvertedType.UINT_64, 32),`

since this type is 64 bits long?

**Comment by martindurant** [comment]
So sorry, you are right of course. fixed in master.
