### ISSUE TITLE
BUG single list of filters does not appear to AND properly

### ISSUE THREAD

**Issue by beckermr** [dask/fastparquet#851]
**Describe the issue**:

The documentation states

```
    filters: list of list of tuples
        To filter out some of the row-groups.
        Filter syntax: [[(column, op, val), ...],...] where op is
        [==, >, >=, <, <=, !=, in, not in]
        The innermost tuples are transposed into a set of filters applied
        through an `AND` operation.
        The outer list combines these sets of filters through an `OR`
        operation.
        A single list of tuples can also be used, meaning that no `OR`
        operation between set of filters is to be conducted.
```

but this does not appear to be working for me.

**Minimal Complete Verifiable Example**:

I think I found the offending code here: https://github.com/dask/fastparquet/blob/main/fastparquet/api.py#LL1337-L1341C90

```python
    # If 2nd level is already a column name, then transform
    # `filters` into a list (OR condition) of list (AND condition)
    # of filters (tuple or list with 1st component being a column
    # name).
    filters = [[filt] if filt and isinstance(filt[0], str) else filt for filt in filters]
```

For single list of tuples (which should be an AND) this snippet gives

```
In [29]: filters = [("blah", "in", ["blarg"]), ("foo", "==", "bar")]

In [30]: [[filt] if filt and isinstance(filt[0], str) else filt for filt in filters]
Out[30]: [[('blah', 'in', ['blarg'])], [('foo', '==', 'bar')]]
```

According to the doc string above this is now an OR since the two predicates are in separate lists.

**Anything else we need to know?**:

**Environment**:

- Dask version: n/a
- Python version: python 3.10.8
- Operating System: linux
- Install method (conda, pip, source): conda

**Comment by beckermr** [comment]
cc @jakirkham @martindurant

**Comment by martindurant** [comment]
I believe it is the documentation which is wrong rather than the code. Test `fastparquet/test/test_read.py::test_cat_filters` seems to depend on the current behaviour or a single-level set of filters being OR. I have not looked back through history to see what the behaviour used to be before adopting the two-level filter semantics from arrow. Actually, it would be worth checking what you get with a single-level filter set with them too.

**Comment by beckermr** [comment]
pyarrow does an AND, not OR.

The key bit here is

```
Predicates may also be passed as List[Tuple]. This form is interpreted as a single conjunction. To express OR in predicates, one must use the (preferred) List[List[Tuple]] notation.
```

see here: https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html

**Comment by yohplala** [comment]
Hi there,
I contributed the `OR` feature, but it has then been changed in a next PR [here](https://github.com/dask/fastparquet/commit/fe8dc1b05044f0608fd4fd87c60606b49a0c0e5f)

Before it was reading:
```python
    if isinstance(filters[0][0], str):
        # If 2nd level is already a column name, then transform
        # `filters` into a list (OR condition) of list (AND condition)
        # of filters (tuple or list with 1st component being a column
        # name).
        filters = [filters]
```
After change, it is now rading:
```python
    filters = filters or [[]]
    # If 2nd level is already a column name, then transform
    # `filters` into a list (OR condition) of list (AND condition)
    # of filters (tuple or list with 1st component being a column
    # name).
    filters = [[filt] if filt and isinstance(filt[0], str) else filt for filt in filters]
```
It seems to me that indeed the end result is not the same in the "new" version.
The 1st version was taking the all filters and putting it in a single list, resulting in an AND condition (all filters remain at same level).
The 2nd version take each of the filter and put it in a separate list, resulting in a OR condition (all filters now separated in individual list).

@martindurant , I don't know the reason of this 2nd version. Please, do you remember?

**Comment by beckermr** [comment]
Thank you @yohplala! I agree the first version looks correct.

**Comment by martindurant** [comment]
@beckermr , would you like to submit a PR reverting this and changing the test that will fail, as well as maybe adding a case of your own showing intended functionality?

**Comment by beckermr** [comment]
I am happy to do so, but I won't get to it for a bit.
