### ISSUE TITLE
API Documentation Page Is Empty

### ISSUE THREAD

**Issue by rawrgulmuffins** [dask/fastparquet#878]
Going to https://fastparquet.readthedocs.io/en/latest/api.html it looks (at least on my computer) like the API page has lot it's contents.
<img width="1301" alt="Screenshot 2023-08-17 at 1 36 01 PM" src="https://github.com/dask/fastparquet/assets/1521575/d78e0ada-ba7f-4646-9208-0b660ce289a2">

There was a release 15 minutes ago that modified this page so that may be related.

**Comment by martindurant** [comment]
Fixed, thanks :)
