### ISSUE TITLE
unable to merge parquet files located in the working directory

### ISSUE THREAD

**Issue by ginseil** [dask/fastparquet#88]
fastparquet fails with the following error:
  File "...\fastparquet\writer.py", line 854, in write_common_metadata
    with open_with(fn, 'wb') as f:
  File "...\fastparquet\util.py", line 39, in default_open
    return open(f, mode)
PermissionError: [Errno 13] Permission denied: '\\\\_metadata'

The paths for '_metadata' and '_common_metadata' are generated in writer.py on lines 920 and 924 by joining an empty basepath with the listed file names.

This issue is fixed, if the join is only done for a non empty basepath.

Thanks for fixing.

**Comment by martindurant** [comment]
I assume this problem goes away if you use the absolute path to the files?
I would prefer not to put special code around relative paths (i.e., those including `.`) because fastparquet was designed to be able to use non-local file-systems without the concept of a current directory.

**Comment by ginseil** [comment]
I replaced the file names with absolute paths as you suggested and it works.
Thanks!
