### ISSUE TITLE
fastparquet encoding issue.

### ISSUE THREAD

**Issue by venkatsura** [dask/fastparquet#882]
**Describe the issue**:

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

Azure blob, Blob trigger, python

exception 
System.Private.CoreLib: Result: Failure
Exception: NotImplementedError: Encoding 5
Stack:   File "Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.8/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 407, in _handle__invocation_request
    call_result = await self._loop.run_in_executor(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.8/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 649, in _run_sync_func
    return ExtensionManager.get_sync_invocation_wrapper(context,
  File "\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.8/WINDOWS/X64\azure_functions_worker\extension.py", line 215, in _raw_invocation_wrapper
    result = function(**args)
  
    data = fastparquet.ParquetFile(BytesIO(Blob_Data)).to_pandas() #read the data from parquet file
  "\.venv\lib\site-packages\fastparquet\api.py", line 782, in to_pandas
    self.read_row_group_file(rg, columns, categories, index,
  File "\.venv\lib\site-packages\fastparquet\api.py", line 384, in read_row_group_file
    core.read_row_group(
  File "\.venv\lib\site-packages\fastparquet\core.py", line 631, in read_row_group
    read_row_group_arrays(file, rg, columns, categories, schema_helper,
  File "\.venv\lib\site-packages\fastparquet\core.py", line 601, in read_row_group_arrays
    read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
  File "\.venv\lib\site-packages\fastparquet\core.py", line 505, in read_col
    defi, rep, val = read_data_page(infile, schema_helper, ph, cmd,
  File "\.venv\lib\site-packages\fastparquet\core.py", line 163, in read_data_page
    raise NotImplementedError('Encoding %s' % daph.encoding)
- Dask version:
- Python version: 3.8.10
- Operating System: in azure deployed in Linux app. in local: windows with visual studio code
- Install method (conda, pip, source):
pip

**Comment by martindurant** [comment]
What is the data you are working with, please, how was it made?

**Comment by venkatsura** [comment]
we received it from other vendor. not sure how they are generating.

**Comment by martindurant** [comment]
The indicated line in the code is reading a Parquet V1 data page, but encoding 5, DELTA_BINARY_PACKED, is a feature of Parquet V2. There's no technical reason V1 pages couldn't be decoded, but the code path does not exist.

**Comment by venkatsura** [comment]
I appologies for that. I didn't get you. you mean my code is refering v1. current i am using 0.8.3 fastparquet version.

**Comment by martindurant** [comment]
No, V1 of the parquet spec, which (roughly) corresponds to V1 type data pages, which is what your file has

**Comment by venkatsura** [comment]
Ok. As per my understanding, some of the files has been generated with V1 type and some of them are genereated with V2 type? Could you please suggest how can i verfiy? if that is the case which is the better approch to load V1 and V2 type files with fastparquet lib.

**Comment by venkatsura** [comment]
The NotImplementedError you're encountering indicates that fastparquet encountered an encoding that it does not support. The error message specifically mentions "Encoding 5," which is likely a Parquet encoding method or type that fastparquet does not currently handle.

**Comment by martindurant** [comment]
>  some of the files has been generated with V1 type and some of them are genereated with V2 type

I suppose so? fastparquet does not expose this information, although I can see it would be useful.

To be sure, it is the _combination_ of v1 and encoding 5 that is the problem. encoding 5 works with v2, and other encodings work with v1.

**Comment by martindurant** [comment]
Given that the decoding algorithm already exists, I'll see if I can carve out a little time to implement it for v1 data pages - but I would need a file to test against.

**Comment by venkatsura** [comment]
I didn't find the file attachment. can you share me your email id?

**Comment by martindurant** [comment]
You can put binary files directly into a comment box here, but maybe it needs to be inside a .zip . Alternatively, you can start a private Gist and invite me if the file is sensitive.

I can't promise when I might get a chance to look into the matter.

**Comment by venkatsura** [comment]
[TestFile_Failure.zip](https://github.com/dask/fastparquet/files/12690465/TestFile_Failure.zip)

**Comment by martindurant** [comment]
I am seeing BookingTypeIDs incrementing from 1 to 12. Is this right?

Can this test file be included in the repo?

**Comment by venkatsura** [comment]
yes. Thats the file only. please do not include in repo.

**Comment by martindurant** [comment]
@venkatsura , can you build and test this on your data, please?

**Comment by venkatsura** [comment]
I am using astparquet-2023.8.0. build my code and tested. it's giving the same error.

**Comment by venkatsura** [comment]
Thank you. It's working. May i know when it can be released to public. we are going to be deploy it to Azure. for azure lib's will be installed by pip online.

**Comment by venkatsura** [comment]
FYI.. we doing some testing. we identified integer values are loading with negative (-) sign. I will post the details.
