### ISSUE TITLE
BUG: dataframe.empty with non-nano pd.DatetimeTZDtype

### ISSUE THREAD

**Issue by jbrockmendel** [dask/fastparquet#891]
```
        elif getattr(bvalues.dtype, 'tz', None):
            values = np.zeros(shape=shape, dtype='M8[ns]')
            values = type(bvalues)(values, dtype=bvalues.dtype)
```

This handles pd.DatetimeTZDtype. Starting in pandas 2.0, these dtypes can support non-nanosecond resolutions ["s", "ms", "us"].     The "ns" hardcoded into the np.zeros call can cause a mismatch between values and dtype here.  This doesn't raise in the constructor (yet), but can raise later on if you try to do e.g. `.tz_convert` on these values.

I suggest using _from_sequence instead of `__init__`, using the same pattern you use a few lines down.  You can get the appropriate unit using `dtype.unit`.

cc @phofl

**Comment by martindurant** [comment]
Thank you for bringing this to my attention.

> I suggest using _from_sequence

Does that not iterate of copy the values?

**Comment by jbrockmendel** [comment]
_from_sequence has a copy keyword
