### ISSUE TITLE
attrs persistance for Pandas

### ISSUE THREAD

**Issue by davetapley** [dask/fastparquet#900]
Pandas 2.10 has ⬇️, but it only works with `pyarrow`.
If `pyarrow` isn't installed then if falls back to `fastparquet` ([per docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_parquet.html)), and `attrs` is always loaded as `{}`.

- https://github.com/pandas-dev/pandas/pull/54346

I _assume_ this need a fix here?

**Comment by martindurant** [comment]
Yes, this can be fixed here. fastparquet does support storing metadata using `write(fn, df, ..., custom_metadata=)`, so if `df` has there attrs, we can extract them. The whole of this metadata appears in `.key_value_metadata` when opening the file, so we can restore them.

I am disappointed in pandas that they have once again ignored fastparquet.

Would you like to implement the functionality, @davetapley ?
