### ISSUE TITLE
Bug loading parquet files with timezone information

### ISSUE THREAD

**Issue by barbuz** [dask/fastparquet#908]
**Describe the issue**:
Trying to load parquet files that have some timezone-aware column gives `TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize`. This happens only if `pandas>=2.0` is installed.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import fastparquet

# Generating a parquet file with a UTC time column
dates = pd.to_datetime(['2023-12-04 13:20:00Z', '2023-12-04 13:25:00Z'])
df = pd.DataFrame(dates, columns=['date'])
df.to_parquet('test-tz.parquet')

# Loading that file, will throw an exception
fastparquet.ParquetFile('test-tz.parquet')

```

**Anything else we need to know?**:
I believe the source of the error is at https://github.com/dask/fastparquet/blob/296d7baed31f0d0d63ecbd9d73caf57eb9feb81b/fastparquet/api.py#L964-L966
When reading a file with pandas metadata, fastparquet will use `numpy_type` as the type of datetime columns, but that value does not include timezone information, so it ends up having to manage tz-naive timestamps.

**Environment**:

- fastparquet version: 2023.10.1
- pandas version: 2.1.3
- Dask version: 2023.3.2
- Python version: 3.10.12
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
The `tz` variable is supposed to hold timezone information and get applied to the dtype in the few lines following the one you indicate. Does `tz` not contain useful information in this case?

**Comment by barbuz** [comment]
> Does tz not contain useful information in this case?

It does, but see the following lines here:

https://github.com/dask/fastparquet/blob/296d7baed31f0d0d63ecbd9d73caf57eb9feb81b/fastparquet/api.py#L967-L972

In line 970 we have `pd.Series([], dtype=dt).dt.tz_convert(z)`. 
`pd.Series([], dtype=dt)` will create an empty series with a datetime without any timezone specified; trying to call `dt.tz_convert()` on it results in an exception independently of what argument is passed to it, because this function can only convert between two specified timezones.

**Comment by martindurant** [comment]
Would you like to propose a fix for this in a PR? It should be easily testable, you already have the code.

**Comment by barbuz** [comment]
I'm working on a PR. Meanwhile I've found out that this issue only happens with files generated by pyarrow. Pyarrow will store for example `datetime64[ns]` as `numpy_type`, while fastparquet will store `datetime64[ns, UTC]`. 

Is this a bug on pyarrow's side?

**Comment by martindurant** [comment]
> Pyarrow will store for example datetime64[ns] as numpy_type, while fastparquet will store datetime64[ns, UTC]

Hm, I'm not sure. I don't think numpy allows timezones, but I seem to recall that pyarrow used to store pandas-like dtypes in the numpy field. Maybe it should be datetime64[ns] for fastparquet too, so long as we do indeed process the timezone.

**Comment by barbuz** [comment]
Here is the PR! https://github.com/dask/fastparquet/pull/909

I am not sure whether fastparquet should omit the timezone from `numpy_type` or not, but at least this fix will allow it to read datasets written in either way.
