### ISSUE TITLE
SNAPPY Compression does not work on Windows

### ISSUE THREAD

**Issue by rsheftel** [dask/fastparquet#91]
I am using fastparquet 0.0.5 installed today from conda-forge with Python 3.6 from the Anaconda distribution.

When I attempt to use SNAPPY compression on a Windows machine using:

`fastparquet.write('c:/temp/test.pqt', df_in, file_scheme='simple', `compression='SNAPPY')`

I get the following:

`RuntimeError: Compression 'SNAPPY' not available.  Options: ['GZIP', 'UNCOMPRESSED']`

**Comment by mrocklin** [comment]
You will need to install the snappy compressor before using it.  The fastparquet library does not include snappy by default.  

I don't see any conda packages for snappy for Windows on Anaconda.org.  You may have to install the Snappy compresssor and the python-snappy library yourself if you want to use it.

**Comment by rsheftel** [comment]
The windows binary is available here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#python-snappy

I had that installed, but no success. I also tried on Linux after installing snappy using conda, again I got the same error message. Do I need to register snappy with fastparquet so that it knows about its existence on my machine?

**Comment by mrocklin** [comment]
It looks like if snappy is importable from python then it will be added.
See
https://github.com/dask/fastparquet/blob/master/fastparquet/compression.py#L41-L46

You might want to ensure that you are able to import snappy

You might need to install not just the snappy system library, but also the
python-snappy library.

**Comment by martindurant** [comment]
It seems that python-snappy is [not built](https://github.com/conda-forge/python-snappy-feedstock/blob/master/recipe/meta.yaml#L14) for windows, but maybe https://github.com/andrix/python-snappy/pull/30 allow it to work. 
The underlying library is listed for windows, but not built, see https://github.com/conda-forge/snappy-feedstock/issues/4 ; but it **is** available on other channels, such as the standard Anaconda one.
