### ISSUE TITLE
Numpy 2: OverflowError with int96

### ISSUE THREAD

**Issue by bnavigator** [dask/fastparquet#921]
**Describe the issue**:

Upgrading from numpy  1 to 2.0.0rc1, the fastparquet test suite starts to fail during the unit tests for the openSUSE rpm packaging builds.

```python
[   76s] _______________________________ test_int96_stats _______________________________
[   76s] [gw2] linux -- Python 3.10.14 /usr/bin/python3.10
[   76s] 
[   76s] tempdir = '/tmp/tmpmti7pznk'
[   76s] 
[   76s]     def test_int96_stats(tempdir):
[   76s]         df = makeMixedDataFrame()
[   76s]     
[   76s]         fn = os.path.join(tempdir, 'foo.parquet')
[   76s]         write(fn, df, row_group_offsets=[0, 2], times='int96')
[   76s]     
[   76s]         p = ParquetFile(fn)
[   76s]     
[   76s] >       s = statistics(p)
[   76s] 
[   76s] ../../BUILDROOT/python-fastparquet-2024.2.0-63.1.x86_64/usr/lib64/python3.10/site-packages/fastparquet/test/test_api.py:892: 
[   76s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   76s] ../../BUILDROOT/python-fastparquet-2024.2.0-63.1.x86_64/usr/lib64/python3.10/site-packages/fastparquet/api.py:1278: in statistics
[   76s]     else list(converted_types.convert(
[   76s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   76s] 
[   76s] data = array([b'\x00\x00\x00\x00\x00\x00\x00\x001u%',
[   76s]        b'\x00\x00\x00\x00\x00\x00\x00\x005u%'], dtype='|S12')
[   76s] se = {'type': 3, 'type_length': None, 'repetition_type': 1, 'name': 'D', 'num_children': None, 'converted_type': None, 'scale': None, 'precision': None, 'field_id': None, 'logicalType': None}
[   76s] timestamp96 = True, dtype = None
[   76s] 
[   76s]     def convert(data, se, timestamp96=True, dtype=None):
[   76s]         """Convert known types from primitive to rich.
[   76s]     
[   76s]         Parameters
[   76s]         ----------
[   76s]         data: pandas series of primitive type
[   76s]         se: a schema element.
[   76s]         timestamp96: convert int96 as if it were written by mr-parquet
[   76s]         """
[   76s]         ctype = se.converted_type
[   76s]         if se.type == parquet_thrift.Type.INT96 and timestamp96:
[   76s]             data2 = data.view([('ns', 'i8'), ('day', 'i4')])
[   76s]             # TODO: this should be ms unit, now that we can?
[   76s] >           return ((data2['day'] - 2440588) * 86400000000000 +
[   76s]                     data2['ns']).view('M8[ns]')
[   76s] E           OverflowError: Python integer 86400000000000 out of bounds for int32
[   76s] 
[   76s] ../../BUILDROOT/python-fastparquet-2024.2.0-63.1.x86_64/usr/lib64/python3.10/site-packages/fastparquet/converted_types.py:161: OverflowError
...
[   76s] =========================== short test summary info ============================
[   76s] FAILED test/test_api.py::test_int96_stats - OverflowError: Python integer 864...
[   76s] FAILED test/test_api.py::test_spark_date_empty_rg - OverflowError: Python int...
[   76s] FAILED test/test_read.py::test_timestamp96 - OverflowError: Python integer 86...
[   76s] FAILED test/test_read.py::test_truncated_decimal - OverflowError: Python inte...
[   76s] ===== 4 failed, 380 passed, 123 skipped, 1 xfailed, 26 warnings in 20.34s ======
[   76s] error: Bad exit status from /var/tmp/rpm-tmp.QIGekb (%check)
```

Full build log: 

[fastparquet-numpy2.txt](https://github.com/dask/fastparquet/files/15174794/fastparquet-numpy2.txt)

**Minimal Complete Verifiable Example**:

- get all dependencies compiled with numpy 2
- run test suite

**Environment**:

- Dask version: 2024.4.2
- Python version: All of them
- Operating System: openSUSE Tumbleweed
- Install method (conda, pip, source): source / rpm packages from source

**Comment by martindurant** [comment]
Thanks for letting me know, I'll look into it.

**Comment by martindurant** [comment]
As far as I can tell, no released version of pandas supports numpy 2 yet (I see 2.2.2, and https://github.com/pandas-dev/pandas/blob/main/environment.yml#L26 ) - should this issue wait until that is resolved? Dev versions of pandas do use numpy2, but rebuilding that seems too much.

**Comment by bnavigator** [comment]
`environment.yml` is not relevant here. The only relevant lines are in pyproject.toml:

https://github.com/pandas-dev/pandas/blob/v2.2.2/pyproject.toml#L11
https://github.com/pandas-dev/pandas/blob/d9cdd2ee5a58015ef6f4d15c7226110c9aab8140/pyproject.toml#L30-L32

and from the changelog: 
https://pandas.pydata.org/docs/whatsnew/v2.2.2.html#pandas-2-2-2-is-now-compatible-with-numpy-2-0
> Pandas 2.2.2 is the first version of pandas that is generally compatible with the upcoming numpy 2.0 release, and wheels for pandas 2.2.2 will work with both numpy 1.x and 2.x.

The pandas 2.2.2 wheels published on PyPI were compiled with numpy 2, so pandas itself works with numpy 2. A few optional extra dependencies are not compatible yet, but these should not be relevant for the test cases in question.

**Comment by bnavigator** [comment]
Besides, this is not a failure related to pandas, but rather to a change in numpy type promotion:
https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion

https://github.com/dask/fastparquet/blob/ec267332d6585dfdec513404c06c603c1726122a/fastparquet/converted_types.py#L159-L162
