### ISSUE TITLE
No wheel file for fastparquet 2024.5.0 for Python 3.12 and Windows

### ISSUE THREAD

**Issue by DrGFreeman** [dask/fastparquet#928]
**Describe the issue**:

There is currently no built distribution of fastparquet 2024.5.0 for Python 3.12 & Windows which causes installation with pip to fail while attempting to build the package from source.

**Minimal Complete Verifiable Example**:

```
py -3.12 -m venv .venv --upgrade-deps
.venv\Scripts\activate
python -m pip install fastparquet==2024.5.0
```

**Anything else we need to know?**:

There is a wheel file for 2024.5.0 / Python 3.11 / Windows:
![image](https://github.com/user-attachments/assets/aecc0f01-7cd4-4d39-8b95-0ae20a6efced)

and there is a wheel file for 2024.2.0 / Python 3.12 / Windows for :
![image](https://github.com/user-attachments/assets/d9f58f18-3013-44c0-aeb4-2a110b9fa058)

which makes me believe that the lack of wheel file for 2024.5.0 / Python 3.12 / Windows is not intended.

**Environment**:

- Dask version: N/A
- Python version: 3.12.4
- Operating System: Windows 10
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
It was not intended. I'll try to make some time to make the missing wheel.

**Comment by DrGFreeman** [comment]
> It was not intended. I'll try to make some time to make the missing wheel.

Great! Thanks for the fast response!

**Comment by martindurant** [comment]
You should have it now. Required a reinstall of Studio Tools 2022 :)

**Comment by DrGFreeman** [comment]
@martindurant, Wow! that was fast!

Installation from wheel works fine now. Thanks as lot for the support, it is much appreciated!
