### ISSUE TITLE
``statistics`` does not work on a ParquetFile subset?

### ISSUE THREAD

**Issue by yohplala** [dask/fastparquet#938]
**Describe the issue**:

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import fastparquet as fp

fp.write(filename="small_df", data=pd.DataFrame({'a':[1,2,3]}), row_group_offsets=[0,2], file_scheme="hive")
pf = fp.ParquetFile("small_df")

# Works
pf.statistics
{'min': {'a': [1, 3]},
 'max': {'a': [2, 3]},
 'null_count': {'a': [0, 0]},
 'distinct_count': {'a': [None, None]}}

# Does not work
pf[-1].statistics
AttributeError: 'ParquetFile' object has no attribute '_statistics'

```

Selecting row groups should still result in a ``ParquetFile`` and ``statistics`` should work?

**Environment**:

- Python version: 3.10
- Operating System: Ubutnu
- Install method (conda, pip, source): conda

**Comment by martindurant** [comment]
You're probably in as good a place as anyone to fix this?

**Comment by yohplala** [comment]
Hi @martindurant yes, I will have a look, probably by end of this week. Yesterday, the reason for this did not seem that straightforward to me, but I will investigate deeper.
