### ISSUE TITLE
No wheel file for fastparquet 2024.11.0 for Python 3.12 and Windows

### ISSUE THREAD

**Issue by DrGFreeman** [dask/fastparquet#946]
**Describe the issue**:

There is currently no built distribution of fastparquet 2024.11.0 for Python 3.12 & Windows on PyPI which causes installation with pip to fail while attempting to build the package from source (similar to #928).

**Minimal Complete Verifiable Example**:

```
py -3.12 -m venv .venv --upgrade-deps
.venv\Scripts\activate
python -m pip install fastparquet==2024.11.0
```

**Anything else we need to know?**:

There are wheel files for Windows + 3.9, 3.10, 3.11 & 3.13 but not 3.12. 

**Environment**:

- Dask version: N/A
- Python version: 3.12.4
- Operating System: Windows 10
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
huh, as you say, py 3.9, 3.10, 3.11 and 3.13 are listed at https://pypi.org/project/fastparquet/2024.11.0/#files . I don't know why one is missing, but I can fill it in this week.

In the meantime, you should be able to build this yourself so long as you have cython and a C build toolchain locally.

**Comment by DrGFreeman** [comment]
@martindurant No worries, I constrained the version to <=2024.5.0 in my projects for the time being.

Thanks for the support! ✨

**Comment by martindurant** [comment]
done

**Comment by DrGFreeman** [comment]
> done

@martindurant Thank you 🚀
