### ISSUE TITLE
With file_scheme='hive', appends slow down notably after around 200 times

### ISSUE THREAD

**Issue by yalwan-scee** [dask/fastparquet#96]
Is there any way to append without updating the metadata? I am using the append mode with hive file scheme, but after 1-200 appends the performance is degrading, and I am fairly sure it is to do with read/manipulate/writing of the metadata. Is there any scope for an "append and finalise later" kind of mode?

**Comment by martindurant** [comment]
Yes, you can write the files individually (file_scheme='simple'), supplying the full path of the file you want to write, and then call `merge(...)` later. If you want to also partition, I think you should still use 'hive' and manually move the directories together before calling merge.

**Comment by martindurant** [comment]
As of #95 , you no longer need the merge step, and you can supply a list of files to fastparquet.ParquetFile to treat them as a single logical dataset. The locations of these files should be in a directory structure expected for parquet, e.g., all in a single directory, if not using partitioning.

**Comment by yalwan-scee** [comment]
Thanks, I tested using the merge way and that was sufficiently fast.

Would it be possible to provide as a convenience an option for "no_write_metadata" as an option to write to encapsulate this idea? I'm happy with both of the above solutions anyway to have this closed, but I thought it would be good, and in keeping with the notion of having a simple interface rather than needing a user to roll their own.

**Comment by martindurant** [comment]
I disfavour not writing metadata for most cases, as it is very useful when loading. With the options available, it feels like cases are covered for now.
