### ISSUE TITLE
parallel write possibility

### ISSUE THREAD

**Issue by areshytko** [dask/fastparquet#98]
Since fastparquet provides file partitioning ability it should be possible theoretically to allow parallel write of multiple pandas dataframes (with common schema). Is it? And if it is are there any plans for this?

**Comment by martindurant** [comment]
This implemented as part of [dask](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.to_parquet) - you could do something similar without dask, using threads or whatever, if you wished.

**Comment by areshytko** [comment]
can you please provide some reference how it can be done manually (without dask). I couldn't find the relevant info in the project documentation

**Comment by martindurant** [comment]
The easiest would probably be to write each data-frame to a separate parquet file in the same directory, parallelized in whatever manner is suitable to you, and then call `merge()` when done. Looking at the code of `merge()`, you will see that it loads in some metadata from each file, which you could in theory be avoided with a little extra code.

**Comment by areshytko** [comment]
Many thanks!
